### ISSUE TITLE
cstool prints instruction bytes glued together, leading to confusion

### ISSUE THREAD

**Issue by 10110111** [aquynh/capstone#1005]
Consider the following use of `cstool`:
```
$ cstool arm '78 56 34 12 12 34 56 78'
0  78563412  eorsne     r5, r4, #120, #12
4  12345678  ldmdavc    r6, {r1, r4, sl, ip, sp} ^
```
The column of instruction bytes is very misleading, since it makes the user think that the first and second instructions are respectively encoded as `0x78563412` and `0x12345678`, while due to little-endian mode they are actually are respectively `0x12345678` and `0x78563412`.
This becomes even more confusing if we compare the output of `objdump` for these bytes:
```
   0:   12345678        eorsne  r5, r4, #120, 12        ; 0x7800000
   4:   78563412        ldmdavc r6, {r1, r4, sl, ip, sp}^
```
As you can see, `objdump` faithfully prints the instruction opcodes as words, so it's correct to avoid any spaces between digits, and the readers accustomed to such output will find `cstool` output even more confusing.

I suggest to insert spaces between bytes in `cstool` output to prevent confusion of readers of the output. Then the above example would look something like
```
0  78 56 34 12  eorsne     r5, r4, #120, #12
4  12 34 56 78  ldmdavc    r6, {r1, r4, sl, ip, sp} ^
```
If you don't mind this change in principle, I might make a patch to do this.

**Comment by aquynh** [comment]
yes, please do pull req, thanks.
