### ISSUE TITLE
x86 prefetch instruction cannot parsing

### ISSUE THREAD

**Issue by ParkHanbum** [aquynh/capstone#1012]
0F 0D 05 2E 10 00  00  ; prefetch large byte ptr ds:102Eh

>>> pre = ks.asm('prefetch [10000]')
>>> bytecode = bytearray(pre[0])
>>> inst = cs.disasm(bytecode, 0x1000)
>>> print_inst(inst)
>>> pre[0]
[15, 13, 5, 16, 39, 0, 0]

>>> pre = ks.asm('call 0x401000')
>>> bytecode = bytearray(pre[0])
>>> inst = cs.disasm(bytecode, 0x1000)
>>> print_inst(inst)
call    0x402000
>>> pre[0]
[232, 251, 15, 64, 0]

cstool x32 0F0D052E100000
ERROR: invalid assembly code

**Comment by ParkHanbum** [comment]
m@DEMACIA:~/git/capstone$ cstool x32 0F0D052E100000
>>> readOpcode() = 0
Found a two-byte escape prefix (0xf)Didn't find a three-byte escape prefixERROR: invalid assembly code

**Comment by aquynh** [comment]
which branch is this?
-- 
Thanks,
Quynh

http://www.keystone-engine.org
http://www.capstone-engine.org
http://www.unicorn-engine.org

**Comment by ParkHanbum** [comment]
@aquynh on next branch

**Comment by ParkHanbum** [comment]
I'm found why it couldn't parsing prefetch instruction. prefetch instructions are have not modRM, but have digits. however prefetch instruction located at 1 of table1852 in next branch. 

see follow, 
 63773 /* Table1852 */
 63774   0x0, /* */
 63775   0x8a2, /* PREFETCHW */
 63776   0x0, /*  */

I'm move that to zero of table1852. 
 63773 /* Table1852 */
 63774   0x8a2, /* PREFETCHW */
 63775   0x0, /*  */


it can parsing well, see result
m@DEMACIA:~/git/capstone$ cstool x32 0F0D052E100000
>>> readOpcode() = 0
firstByte : (0xf)
Found a two-byte escape prefix (0xf)
twoByteEscape : (0xd)
Didn't find a three-byte escape prefix
>>> getID()
OPCODE : d
INSTRUCTION CLASS : 0
insnContext : 0   index : 1
DECODE MODRM : 5
TYPE TWOBYTE
DECODE INSTRUCTION ID : 73c
MODRM_SPLITREG
REF dec->instructionID : 73c
ATTR MASK : 0
OPCODE : d
INSTRUCTION ID : 8a2
0  0f 0d 05 2e 10 00 00                    prefetchw    byte ptr [0x102e]


@aquynh  how do you think?

**Comment by PlasmaHH** [comment]
Just wanted to report basically the same issue, was playing with sandsifter and found that the whole family of 0f0d based prefetch instructions is not detected by capstone

**Comment by ParkHanbum** [comment]
@aquynh can you review this?

**Comment by aquynh** [comment]
Sorry for late reply. Yes i will do soon.
