### ISSUE TITLE
very weird issue with "cs_insn" on Linux i386

### ISSUE THREAD

**Issue by Coldzer0** [aquynh/capstone#1019]
i was working on Hook-Engine for FreePascal that support [Mac - Linux - windows] x86_x64 & i386

my main problem is that **cs_insn** struct acting very weird on i386 with ubuntu linux 64 

here's the **cs_insn** struct code in Pascal 

```
  cs_insn = record
    id: DWORD; // 4 bytes
    address: UInt64; // 8 bytes
    size: Word; // 2 bytes
    bytes: array[0..15] of Byte; // 16 byte
    mnemonic: array[0..31] of AnsiChar; // 32 byte as Char
    op_str: array[0..159] of AnsiChar; // 160 byte as Char
    detail: ^cs_detail; // pointer to cs_detail
  end; 
```

i'm using it with **cs_disasm_iter**

it works fine on Mac OS with i386 & x86_x64 apps
but in ubuntu linux 17
when i build my code as x86_x64 it works fine

but when i build it as i386 the structure of cs_insn acting weird 
it's not giving the values as expected 

but if i change the  **cs_insn** struct to 

```
  cs_insn = record
    id: DWORD; // 4 bytes 
    align : DWORD; // 4 bytes   <<<<<<<<<
    address: DWORD; // 4 bytes  <<<<<<<<<
    size: Word; // 2 bytes
    bytes: array[0..15] of Byte; // 16 byte
    mnemonic: array[0..31] of AnsiChar; // 32 byte as Char
    op_str: array[0..159] of AnsiChar; // 160 byte as Char
    detail: ^cs_detail; // pointer to cs_detail
  end; 
```
now if i rebuild the code it works for i386 but now x86_x64 will be broken 😅 O_O

it's really crazy :D

**Comment by Coldzer0** [comment]
i dump the Structure from the memory for both 32 & 64 bit apps


**64-Bit (x86_x64)** 
```
ID      = 44 02 00 00 
Address = 00 00 00 00 00 00 00 00
unknow  = 00 00 00 00 
Size 	= 01 00 
Bytes 	= 55 00 00 | 00 00 00 00 | 00 00 00 00 | 00 00 00 00 | 00 
```
but this works fine i don't know why 0_0

**32-bit (i386)** 
```
ID      = 44 02 00 00
Address = 00 00 00 00 00 00 00 00 
Size 	= 01 00
Bytes 	= 55
```

and this one not working 

this's really drive me crazy -_-

if anyone want me to upload the binary files to debug let me know ...
i hope i have an answer ..

**Comment by aquynh** [comment]
Perhaps this is due to alignment issue of Pascal struct? I you dump all the struct fields out, and some get wrong value, then that may be the reason.

I suppose Capstone works for you in C? You can verify your Pascal output with the output of "cstool -d", and compare.

**Comment by Coldzer0** [comment]
yes you right about the alignment :D 

i used the FreePascal compiler ALIGN Directive 

```
{$IfDef CPU64}
  {$ALIGN 8}
{$Else}
  {$ALIGN 4}
{$EndIf}
```

and it works fine & cstool works fine too ;)


thanks

**Comment by aquynh** [comment]
Cool, let us know if you public your tool, or use it in some products!

**Comment by Coldzer0** [comment]
it's already public, i started last **january**
but back then i didn't have time to finish it 

you can find it here https://github.com/Coldzer0/Coldhook

the code right now is a mess :D 
i'm rewriting it so it looks more readable & usable

**Comment by aquynh** [comment]
that looks cool! hope to see new update, and a better README for your hooking engine.

cheers.
