### ISSUE TITLE
In X86_64 AT&T operand for "and","or","xor" is not right 

### ISSUE THREAD

**Issue by yanlin0816** [aquynh/capstone#1047]
For some logic instructions, in AT&T syntax, the operand type is wrong.

For this :and" instruction, in Intel syntax:
48  83  e4  f0            and		rsp, 0xfffffffffffffff0 
but in AT&T syntax, it is:
48  83  e4  f0           andq       $0xfffffff0, %rsp

This instruction will cause  "Error: operand type mismatch"

**Comment by aquynh** [comment]
fixed now, please confirm.

**Comment by aquynh** [comment]
next time you can provide testcase with "cstool", like below:

```
$ cstool x64att "48 83 e4 f0"
0  48 83 e4 f0                          andq	$0xfffffffffffffff0, %rsp
```

sometimes you may want to use -d option:

```
$ cstool -d x64att "48 83 e4 f0"
0  48 83 e4 f0                          andq	$0xfffffffffffffff0, %rsp
	Prefix:0x00 0x00 0x00 0x00
	Opcode:0x83 0x00 0x00 0x00
	rex: 0x48
	addr_size: 8
	modrm: 0xe4
	disp: 0x0
	sib: 0x0
	imm_count: 1
		imms[1]: 0xfffffffffffffff0
	op_count: 2
		operands[0].type: IMM = 0xfffffffffffffff0
		operands[0].size: 8
		operands[1].type: REG = rsp
		operands[1].size: 8
```
