### ISSUE TITLE
Get groups information

### ISSUE THREAD

**Issue by thvnx** [aquynh/capstone#1048]
Groups field is empty when I disassemble some ARM64 instructions (I am using the OCaml bindings).

For instance, command `cstool -d arm64 "0x0100261e"` prints the *Groups* field:
```bash
cstool -d arm64 "0x0100261e"
0  01 00 26 1e  fmov	w1, s0
	op_count: 2
		operands[0].type: REG = w1
		operands[1].type: REG = s0
	Groups: fparmv8 
```
But, not `cstool -d arm64 "0x2100044b"`:
```bash
cstool -d arm64 "0x2100044b"
0  21 00 04 4b  sub	w1, w1, w4
	op_count: 3
		operands[0].type: REG = w1
		operands[1].type: REG = w1
		operands[2].type: REG = w4
```

How can I get the group info for this example?

**Comment by aquynh** [comment]
So this insn does not belong to any special groups.

Which group do you expect in this case?

**Comment by thvnx** [comment]
OK (well, I was thinking of something like **int** group).

So, if I understand, the only groups available (within arm64), are JUMP, CRYPTO, FPARMV8, NEON, and CRC?

**Comment by aquynh** [comment]
Yes, iirc.

You can add new groups if you wish to, and send pull req to get them merged

**Comment by thvnx** [comment]
I'll try. Thanks for your help!
