### ISSUE TITLE
Enclose global variables in namespace

### ISSUE THREAD

**Issue by illera88** [aquynh/capstone#1101]
Hi,
There are some global variables like [`arch_init`](https://github.com/aquynh/capstone/blob/8998a3a1d5efd7f4f641fac2a54cd427dec270d1/cs.c#L54) that have a common name that can produce link errors with when used with other big projects. Using a prefix like `cs_` or enclosing them in a namespace will help avoiding those naming problems.

Cheers

**Comment by aquynh** [comment]
Would you mind sending a pull req to fix this?

**Comment by illera88** [comment]
Done ;)

Congrats for the project!
