### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by neo85** [aquynh/capstone#1110]
Hi, 
capstone 3.0.4 and 3.0.5-rc3 are not able to disassemble following byte sequence
{0x0f, 0x85, 0x05, 0x00, 0x00, 0x00}

capstone 2.1.2 and other disassemblers have no problem with it .

**Comment by aquynh** [comment]
can you confirm this is still an issue with latest code from "master" branch, and also "next" branch?

what is the expected output?

**Comment by neo85** [comment]
Im sorry, it works. 
I was greedy and used CAPSTONE_X86_REDUCE.
My bad.
