### ISSUE TITLE
Error while compiling a BF1 cheat

### ISSUE THREAD

**Issue by Jeimy041** [aquynh/capstone#1120]
So here´s my error hope u can help me fixing it. I use Visual Studio 2017, btw Thanks!!!

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'Capstone/include/capstone.h': No such file or directory	BF1 Internal	c:\users\bassy´s\desktop\prueba\bf1-internal-master\bf1 internal\stdafx.h	55

**Comment by tmfink** [comment]
This does not sound like a Capstone bug, but a bug in how your project is set up.

Maybe you did not download Capstone source to the expected directory?

**Comment by Jeimy041** [comment]
Wtf why is this opened, yes that was the issue a year ago LMAO
