### ISSUE TITLE
ARM: Incorrect register access information for BX and BLX

### ISSUE THREAD

**Issue by Theorigor** [aquynh/capstone#1126]
For ARM BX/BLX instructions there is no `pc` register in the list of accessed for write registers.

Same as #826 but for BX and BLX (and probably BXJ but I have not tested it).

Tested with commit 863ec0aba8fbfdc83090ba21d3afad9e1a51d96c.

**Comment by aquynh** [comment]
fixed now, please confirm

**Comment by Theorigor** [comment]
Thank you for the fix!

Unfortunately, I am quite busy right now. I am putting on my mid-term todo list to update my capstone version and check the fix.

**Comment by Theorigor** [comment]
I can now confirm this is fixed for my use-case.

**Comment by firodj** [comment]
hi @aquynh, for `ARM_tBX` may be you misspell to include `ARM_REG_PC` in the group field, or maybe it is just typo.

https://github.com/aquynh/capstone/blob/e8967c684f01b0701b31d036a395e99e466f2dca/arch/ARM/ARMMappingInsn.inc#L12943

**Comment by aquynh** [comment]
indeed, do you want to send a pull req to fix this?

**Comment by aquynh** [comment]
@firodj, this is fixed now with   https://github.com/aquynh/capstone/commit/8f4cc4e80d2c8635b06be9fe193eb6e3c6bd357f
