### ISSUE TITLE
m68k oobreadcrash

### ISSUE THREAD

**Issue by radare** [aquynh/capstone#1128]
It was originally reported in r2, but this issue belongs to capstone

https://github.com/radare/radare2/issues/9852

**Comment by radare** [comment]
this is one, but there are many more crashes in the m68k disassebler of capstone that assume the buffer is 4 byte length

**Comment by emoon** [comment]
I can take a look. Also @radare if bugs aren't reported here it's hard for me to fix anything so statements like "tired of waiting" isn't really fair if I don't have any idea about the bug(s).

**Comment by radare** [comment]
The “tired of waiting” comment was not in the capstone issue. And totally unrelated to you. I didnt knew this was an issue in capstone until i tried to fix it in r2. The reason is because i was busy last week and i was expecting others to fix crashes for me. So dont take that stuff that personal next time.

Thanks for having a look at this.

**Comment by emoon** [comment]
Fair enough. I will try to sort this out later today or tomorrow but I can't promise anything.

**Comment by emoon** [comment]
@radare Just FYI I have a tentative fix for this issue here https://github.com/aquynh/capstone/pull/1130 but I want to wait for a review by the original author of that part of the code first.

**Comment by radare** [comment]
👍

**Comment by emoon** [comment]
@radare The PR has now been merged. If you find any other m68k related issues please let me know ASAP and I will look into them.

**Comment by radare** [comment]
Awesome thanks! Ill revert my workarounds in r2 and update capstone dependency. Sure! Will report anything i see.

**Comment by emoon** [comment]
👍
