### ISSUE TITLE
Possible race condition with archs_enable()

### ISSUE THREAD

**Issue by tmfink** [aquynh/capstone#1168]
In working on the [Rust bindings](https://github.com/capstone-rust/capstone-rs), I discovered a possible race condition with `archs_enable()`. It uses lock-free initialization.

~~~c
static void archs_enable(void)
{
    static bool initialized = false;

    if (initialized)
        return;

#ifdef CAPSTONE_HAS_ARM
    ARM_enable();
#endif
#ifdef CAPSTONE_HAS_ARM64
    AArch64_enable();
#endif
#ifdef CAPSTONE_HAS_MIPS
    Mips_enable();
#endif
#ifdef CAPSTONE_HAS_POWERPC
    PPC_enable();
#endif
#ifdef CAPSTONE_HAS_SPARC
    Sparc_enable();
#endif
#ifdef CAPSTONE_HAS_SYSZ
    SystemZ_enable();
#endif
#ifdef CAPSTONE_HAS_X86
    X86_enable();
#endif
#ifdef CAPSTONE_HAS_XCORE
    XCore_enable();
#endif


    initialized = true;
}
~~~

`archs_enable()` is called at the beginning of `cs_version()`, `cs_support()`, `cs_open()`, `cs_option()`.

Multiple threads could conceivably call `cs_open()` and have interleaving executions before `initialized` is `true`. It seems like none of `*_enable()` functions rely on global state.
But, can we assume that such initialization is safe on all CPU architectures (X86, ARM, etc.)?

In order to get around this potential problem in the Rust bindings, I used a [synchronization feature](https://github.com/capstone-rust/capstone-rs/blob/56c0ebb5915c3ae9ba18aa16785da3828a24550e/src/capstone.rs#L97-L121) to ensure that `archs_enabled()` was called by one thread before initialization.

Even if this is not a race condition, I think there should be a comment explaining that this is a lock-free initialization and that no locking is required. Thanks.

**Comment by aquynh** [comment]
Yes there is a potential issue like you said. Feel free to send in pull req
to fix it, thanks.
