### ISSUE TITLE
ARM and Thumb Architecture

### ISSUE THREAD

**Issue by valour01** [aquynh/capstone#1190]
Hi, I am new to capstone and this is a very powerful tool

Recently, I am working on a binary on ARM architecture. Inside this binary, some instructions are ARM while the others are thumb mode. My question is below:

Give the bytecode and specify the architecture. For example, ARM. Does capstone know to transfer to Thumb after some BX instructions. Are there any methods for capstone to distinguish between arm and thumb or it has to be specified by the users? Many Thanks

**Comment by radare** [comment]
Obviously no. Capstone is just a disassembler. Not an emulator or binary parser where the information of thumb/arm switches lives in. R2 may help you on this

**Comment by valour01** [comment]
Thanks for your reply. I see.
