### ISSUE TITLE
RISC-V support plan?

### ISSUE THREAD

**Issue by citypw** [aquynh/capstone#1193]
Hi,

We've been trying to reverseing a RISC-V binary blob by radare2:
https://github.com/hardenedlinux/firmware-anatomy/tree/master/bin_blobs/hifive_unleashed

 Some disassembly code seems not good as other arch like x86.  Then we figured that r2 doesn't use capstone for disasm the RISC-V code for now. Do you guys have any plan to support RISC-V?

**Comment by aquynh** [comment]
Yes we do. There is a pull req for this, but that is not ready to be merged
yet.

**Comment by citypw** [comment]
Awesome, looking forward to it. Good news is SiFive is going to open source the fsbl binblobs. But we may still need more powerful RE tools for RISC-V in the future.
