### ISSUE TITLE
Java bindings broken in #1194

### ISSUE THREAD

**Issue by keenk** [aquynh/capstone#1203]
The change to the size of disp in #1194 causes the jna read from the java bindings to be misaligned.

Test case: Run the provided java test class TestX86
Result: Array index out of bounds
Note: Running run.sh in the java bindings with no argument does not exhibit this behavior. The x86 test from that script comes from TestBasic.java and does not actually run TestX86

I have created a pull request #1202 that updates the type of the disp variable in the java bindings as well as adds an Encoding class to expose the newly added structure to the java bindings.

**Comment by aquynh** [comment]
merged that, thanks!

can you update TestX86, so it accesses these new fields?

at the same time, can you please check if there is anything wrong with Java binding in the "master" branch?

**Comment by keenk** [comment]
Sure thing! I'll submit another pull request when its done.

**Comment by keenk** [comment]
Pull request #1208 now prints the new class and also prints registry access modes that were missing. Its still missing printouts for groups.
