### ISSUE TITLE
wrong retf

### ISSUE THREAD

**Issue by radare** [aquynh/capstone#1204]
`0x00000000      cafeba     retf 0xffffffffffffbafe`

ollydis shows `retf 47870`

**Comment by aquynh** [comment]
Is this regression, or a new issue?

**Comment by radare** [comment]
i didnt upgraded to the latest capstone because this test breaks.. but new output looks good.. so maybe this issues is fixed in recent next.

```
-0x004019da   # 3: ror ebp, 0xffffffffffffffe5
+0x004019da   # 3: ror ebp, 0xe5
```

**Comment by aquynh** [comment]
So problem is solved?

**Comment by aquynh** [comment]
Fixed, please confirmed
