### ISSUE TITLE
vbroadcasti128 cannot be decoded

### ISSUE THREAD

**Issue by oleavr** [aquynh/capstone#1206]
Capstone's `next` branch is unable to decode the following instruction:

```
c4 e2 7d 5a 0c 0e  vbroadcasti128 (%rsi,%rcx), %ymm1
```

The `master` branch is however able to decode it. This regression was introduced by 54d50712884092854d5e7998ced30c02d36f1341.

**Comment by aquynh** [comment]
Is this the regression you mentioned, or a new issue?

**Comment by oleavr** [comment]
This is the regression blocking me from moving Frida to the `next` branch.

**Comment by aquynh** [comment]
Can you find out which commit caused this?

**Comment by aquynh** [comment]
An instruction is missing, so this is not a regression?

**Comment by oleavr** [comment]
It is a regression. `X86_INS_VBROADCASTI128` is present on `master` but missing on `next`.

**Comment by oleavr** [comment]
@aquynh You removed it in 54d50712884092854d5e7998ced30c02d36f1341.

**Comment by oleavr** [comment]
Perhaps just bad luck on when the `next` branch was refreshed with changes from upstream:
http://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20150309/265226.html

**Comment by mur47x111** [comment]
Any update on this? I hit the same issue. Was able to decode in 3.0.5 but not in 4.0.

**Comment by aquynh** [comment]
currently testing, but soon:

```
$ ./cstool/cstool -d x64att "c4 e2 7d 5a 0c 0e"
 0  c4 e2 7d 5a 0c 0e                 vbroadcasti128	(%rsi, %rcx), %ymm1
	Prefix:0x00 0x00 0x00 0x00 
	Opcode:0xc4 0xe2 0x7d 0x00 
	rex: 0x40
	addr_size: 8
	modrm: 0x0
	disp: 0x0
	sib: 0xe
		sib_base: rsi
		sib_index: rcx
		sib_scale: 1
	op_count: 2
		operands[0].type: MEM
			operands[0].mem.base: REG = rsi
			operands[0].mem.index: REG = rcx
		operands[0].size: 16
		operands[1].type: REG = ymm1
		operands[1].size: 32
	Registers read: rsi rcx
```

**Comment by aquynh** [comment]
now fixed in the "next" branch (which will be released as v5), thanks!

(the "next" branch now supports all the latest X86 extensions)

**Comment by casasnovas** [comment]
Is v5 going to release any time soon or shall a smaller fix be back-ported for this issue?  @oleavr reported this almost 2 years ago.
