### ISSUE TITLE
*mov al, byte [0x7611c4c7]* only has 1 operand?

### ISSUE THREAD

**Issue by windhl** [aquynh/capstone#1209]
hi, everyone
when I use capstone to disassemble the x86-32bit trace, I got a error.
The binary code is "\xa0 \xc7 \xc4 \x11 \x76" and the instruction is " mov al, byte [0x7611c4c7] ",  I think there are 2 operands, but capstone-3.0 version give me there is only 1 operand.
Is this my mistake or some other reason?
Thanks all!

**Comment by aquynh** [comment]
This was fixed in latest github code. You can test this input with `cstool
-d x32 a0c7c41176`

**Comment by windhl** [comment]
thanks a lot！！
