### ISSUE TITLE
NASM syntex deos not supported anymore?

### ISSUE THREAD

**Issue by eternalklaus** [aquynh/capstone#1227]
In your ISSUE #998 , NASM syntex added on capstone. 
However on your newest capstone, I cannot use `CS_OPT_SYNTAX_NASM`.
Also, I could not find `CS_OPT_SYNTAX_NASM` in arch/X86/X86IntelInstPrinter.c.
`NASM` syntex does not supported anymore?

**Comment by aquynh** [comment]
that was not merged. can you pick it up, fix all the issues, and send a pull req again?

**Comment by eternalklaus** [comment]
Oh it does not merged yet. thank you for reply.
