### ISSUE TITLE
About 'repz' prefix handling.

### ISSUE THREAD

**Issue by eternalklaus** [aquynh/capstone#1229]
```
f3c3   # repz ret 
```
Using capstone, above byte pattern is disassembled into `retl` (`c3`).
I think it should be `repz ret`

**Comment by aquynh** [comment]
REPZ is irrelevant for RET, that is why Capstone removed it.

**Comment by eternalklaus** [comment]
Of course. 
however as `repz ret` is also a valid instruction, 
I think there's no reason to change it into `ret`, instead of `repz ret`.

**Comment by aquynh** [comment]
Repz Ret is invalid, according to Intel manual.

Also, semantically Repz Ret is wrong, because what it does is just Ret,
when the CPU ignores the prefix for this instruction.
