### ISSUE TITLE
Please add offset parameter to cs_disasm for java

### ISSUE THREAD

**Issue by KYHSGeekCode** [aquynh/capstone#1252]
When I try to call cs_disasm via JNI/JNA from java code, I need to implement a new function that accepts offset argument, because I don't want to copy all the bytes of a preread file's bytes into a new buffer just to call the cs_disasm, which assumes that the array passed has the code from index 0.

I would be very appreciated or may I contribute here?

**Comment by aquynh** [comment]
yes, pull req is welcome!

**Comment by KYHSGeekCode** [comment]
@E3V3A I think I am so lazy or busy to create a pull request for a three-line function. (I was almost forgot this issue.. sorry) I may create one some day, but maybe not now. Well, I may post the code here and leave a reference of my utilizations of capstone library for java.(Actually, android)

`CAPSTONE_EXPORT size_t CAPSTONE_API cs_disasm2(csh handle, const uint8_t *code,size_t code_offset,
														size_t code_size,uint64_t address,size_t count,cs_insn **insn)
		{
			return cs_disasm(handle,(const uint8_t *)(code+code_offset),code_size-code_offset,address,count,insn);
		}`

And my JNI code of [the poject(Android-Disassembler)](https://github.com/KYHSGeekCode/Android-Disassembler)

[Link to github](https://github.com/KYHSGeekCode/Android-Disassembler/blob/master/hello-jni.cpp)

**Comment by KYHSGeekCode** [comment]
@E3V3A  Also I made [android capstone example using jna.](https://github.com/KYHSGeekCode/Android-capstone-example)

Hope they help you and others!

**Comment by aquynh** [comment]
pull req, please

**Comment by KYHSGeekCode** [comment]
Pull requested, hope it helps!
