### ISSUE TITLE
Operand  in x64:cmp marked as written

### ISSUE THREAD

**Issue by jdhiser** [aquynh/capstone#1253]
Compare does not set any of it's operands, it only implicitly sets the eflags regsiter.  Capstone erroneously reports operand[0] as read/write:

```
$ ./cstool -d x64 "0x80    0xbc    0x24    0x70    0x01    0x00    0x00    0x00"
 0  80 bc 24 70 01 00 00 00                          cmp	byte ptr [rsp + 0x170], 0
	Prefix:0x00 0x00 0x00 0x00 
	Opcode:0x80 0x00 0x00 0x00 
	rex: 0x0
	addr_size: 8
	modrm: 0xbc
	disp: 0x170
	sib: 0x24
		sib_base: rsp
		sib_scale: 1
	imm_count: 1
		imms[1]: 0x0
	op_count: 2
		operands[0].type: MEM
			operands[0].mem.base: REG = rsp
			operands[0].mem.disp: 0x170
		operands[0].size: 1
		operands[0].access: READ | WRITE
		operands[1].type: IMM = 0x0
		operands[1].size: 1
	Registers read: rsp
	Registers modified: rflags
	EFLAGS: MOD_AF MOD_CF MOD_SF MOD_ZF MOD_PF MOD_OF

```

as of:

```
$ git branch
* (detached from bfa649f)
  master
```

**Comment by aquynh** [comment]
Which version is this?

Can you try with master version?

**Comment by jdhiser** [comment]
As mentioned in the report, I was on hash bfa649f, which is near master.    Also happens on current master:

$ ./cstool -d x64 "0x80    0xbc    0x24    0x70    0x01    0x00    0x00    0x00"
 0  80 bc 24 70 01 00 00 00                          cmp	byte ptr [rsp + 0x170], 0
	Prefix:0x00 0x00 0x00 0x00 
	Opcode:0x80 0x00 0x00 0x00 
	rex: 0x0
	addr_size: 8
	modrm: 0xbc
	disp: 0x170
	sib: 0x24
		sib_base: rsp
		sib_scale: 1
	imm_count: 1
		imms[1]: 0x0
	op_count: 2
		operands[0].type: MEM
			operands[0].mem.base: REG = rsp
			operands[0].mem.disp: 0x170
		operands[0].size: 1
		operands[0].access: READ | WRITE
		operands[1].type: IMM = 0x0
		operands[1].size: 1
	Registers read: rsp
	Registers modified: rflags
	EFLAGS: MOD_AF MOD_CF MOD_SF MOD_ZF MOD_PF MOD_OF

$ git branch
* master

**Comment by jdhiser** [comment]
Confirmed fixed:

```
$ ./cstool -d x64 "0x80    0xbc    0x24    0x70    0x01    0x00    0x00    0x00"
 0  80 bc 24 70 01 00 00 00                          cmp	byte ptr [rsp + 0x170], 0
	Prefix:0x00 0x00 0x00 0x00 
	Opcode:0x80 0x00 0x00 0x00 
	rex: 0x0
	addr_size: 8
	modrm: 0xbc
	disp: 0x170
	sib: 0x24
		sib_base: rsp
		sib_scale: 1
	imm_count: 1
		imms[1]: 0x0
	op_count: 2
		operands[0].type: MEM
			operands[0].mem.base: REG = rsp
			operands[0].mem.disp: 0x170
		operands[0].size: 1
		operands[0].access: READ
		operands[1].type: IMM = 0x0
		operands[1].size: 1
	Registers read: rsp
	Registers modified: rflags
	EFLAGS: MOD_AF MOD_CF MOD_SF MOD_ZF MOD_PF MOD_OF

```
