### ISSUE TITLE
How to use capstone on EVM bytecode?

### ISSUE THREAD

**Issue by herrBez** [aquynh/capstone#1261]
Sorry to bother you. I am new to capstone. I read the documentation but I cannot find a way to use capstone on EVM bytecode. In the [guides about the different languages](https://www.capstone-engine.org/lang_c.html) apparently, it is not mentioned.

How should it work?

**Comment by aquynh** [comment]
see this sample code https://github.com/aquynh/capstone/blob/master/tests/test_evm.c
