### ISSUE TITLE
Invalid operand size for 0x67 prefix + REX.W

### ISSUE THREAD

**Issue by SweetVishnya** [aquynh/capstone#1263]
`[eax]` operand size should be 64 bit, but capstone says it's 32.
```
"\x67\x48\x89\x18"  # mov [eax], rbx
```
Also check this one:
```
"\x67\x48\x8b\x03"  # mov rax, [ebx]
```
0x67 + REX.W gives 64 bit operand size:
https://wiki.osdev.org/X86-64_Instruction_Encoding#Operand-size_and_address-size_override_prefix

Reference issue https://github.com/JonathanSalwan/Triton/issues/729

**Comment by Oloshka** [comment]
Actually, this issue is fixed in "next" branch. So, I added cstest for it in PR #1407.

**Comment by aquynh** [comment]
close, thanks!
