### ISSUE TITLE
Installation through CMake doesn't install pkg-config

### ISSUE THREAD

**Issue by ael-code** [aquynh/capstone#1268]
If capstone is configure through CMake then make install won't install any pkg-config file.

While those are installed if I use the Makefile included in the released tar archive

**Comment by aquynh** [comment]
do you mean file `capstone.pc` is missing?

**Comment by ael-code** [comment]
> do you mean file `capstone.pc` is missing?

Yes

**Comment by aquynh** [comment]
should be fixed now. please report if you still have issues, thanks.
