### ISSUE TITLE
Announcing D bindings

### ISSUE THREAD

**Issue by bohlender** [aquynh/capstone#1280]
Hey @aquynh, 

I've written [capstone-d](https://github.com/bohlender/capstone-d), which provides idiomatic D-bindings for the full API of libcapstone v3.0.5, except for the dynamic memory management option.

The bindings are fully documented, regression-tested w.r.t. to the outputs of [your tests](https://github.com/aquynh/capstone/tree/3.0.5/tests), and also [available through DUB](http://code.dlang.org/packages/capstone-d) (D's package management).

While only the most prominent architectures (x86, arm, arm64) are supported in the [current version](https://github.com/bohlender/capstone-d/releases/tag/v0.1.0), I will add the less popular ones soon, too.

Feel free to add `capstone-d` to your [list of bindings](https://github.com/aquynh/capstone/blob/master/bindings/README) and/or let me know if you have questions or find something  to be amiss.

**Comment by aquynh** [comment]
please consider submitting a pull req to add your binding to https://github.com/aquynh/capstone/blob/master/bindings/README, thanks!
