### ISSUE TITLE
Is it possible to change mode from ARM to Intel mode?

### ISSUE THREAD

**Issue by KYHSGeekCode** [aquynh/capstone#1283]
Is it valid to do like this:

```
cs_open(CS_ARCH_ARM, CS_MODE_ARM, &handle);
// from now on disassemble Arm code ....

cs_option(handle, CS_OPT_MODE, CS_ARCH_X86); // dynamically change engine's mode at run-time
// from now on disassemble X86 code ....

```

Or should I call `cs_open` again to change engine's architecture?

**Comment by aquynh** [comment]
sorry no, you can only change the mode on the same architecture.

in your case, it is best to create another separate engine.

**Comment by KYHSGeekCode** [comment]
Thank you for your reply!
