### ISSUE TITLE
v3 vs next(aka 4) binary compatibility

### ISSUE THREAD

**Issue by ret2libc** [aquynh/capstone#1284]
Can I upgrade capstone library from v3.0.5 to v4-alpha without recompiling my programs that depend on it? Is capstone binary retro-compatible (e.g. all public structures keep the same memory layout, etc.) ?

**Comment by kfirstri** [comment]
Any news? I got some issues that were fixed in "next" branch that haven't been released yet and i'm confused whether I can just compile it on my own and use it.

**Comment by aquynh** [comment]
there are some internal changes, but if you just use the APIs, version 4
(which is in master branch now) is compatible with v3.

for now, you can ignore the next branch (merged into master few months
ago), and just use the master branch: it is quite stable.

**Comment by ret2libc** [comment]
But that's just about API compatibility as far as I understand. Binary compatibility between v3 and v4 is not guaranteed, is it?

**Comment by aquynh** [comment]
That depends. You can find out if the changes affect you by diffing
include/*.h between 2 versions. Pay attention to changes in insn structures.

**Comment by kfirstri** [comment]
Thanks @aquynh! any plans to create a new release from master branch?

**Comment by XVilka** [comment]
@ret2libc @aquynh so I guess it is time to find out.

**Comment by aquynh** [comment]
for potential incompatibility, please see https://github.com/aquynh/capstone/issues/1315, the "Broken" section.
