### ISSUE TITLE
Can not find -lcapstone

### ISSUE THREAD

**Issue by yasaminmahmoodi** [aquynh/capstone#1285]
Hello,

I try to buid taintgrind (https://github.com/wmkhoo/taintgrind). I uses capstone. During build process of taintgrind it gives that error:

/usr/bin/ld: skipping incompatible ./capstone-3.0.4//libcapstone.a when searching for -lcapstone
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5/../../../libcapstone.a when searching for -lcapstone
/usr/bin/ld: skipping incompatible //usr/lib/libcapstone.a when searching for -lcapstone
/usr/bin/ld: cannot find -lcapstone
collect2: error: ld returned 1 exit status

**Comment by aquynh** [comment]
We recommend newer version v3.0.5.

Did you report this to that project?

**Comment by yasaminmahmoodi** [comment]
OK, I will try the newest version.
Yes I did.

Thank you
