### ISSUE TITLE
MSYS2 support

### ISSUE THREAD

**Issue by amirgon** [aquynh/capstone#1289]
https://github.com/aquynh/capstone/blob/f01c267f889e932b069a559ce0c604c1ae986c0a/Makefile#L305

When building under MSYS2, CC version information contains "MSYS" instead of "MINGW" signature.  
I suggest changing it to something like 

    IS_MINGW := $(shell $(CC) --version 2>/dev/null | grep -i "\(mingw\|MSYS\)" | wc -l)

**Comment by aquynh** [comment]
would you please send a pull request?

**Comment by E3V3A** [comment]
@amirgon 
If you use `grep -i` you may as well use `msys` and not `MSYS`.

**Comment by amirgon** [comment]
> @amirgon
> If you use `grep -i` you may as well use `msys` and not `MSYS`.

@E3V3A That's right. Do you think it's worth another merge?

**Comment by nelsonjchen** [comment]
IMO, it's one of those better to be explicit things so it stands out. 

On that note, this issue should probably document what exactly is the output of some of the `gcc --version`s involved even though this was resolved.

```
$ gcc --version
gcc.exe (Rev3, Built by MSYS2 project) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
root@07d51ca32d40:/# x86_64-w64-mingw32-gcc --version
x86_64-w64-mingw32-gcc (GCC) 7.3-win32 20180506
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR **PURPOSE.**
```
