### ISSUE TITLE
Who would be insterested in joining a new fork of this project?

### ISSUE THREAD

**Issue by E3V3A** [aquynh/capstone#1293]
After having spent nearly two months watching the painful non-progress of Capstone, I think it is time to consider making a more user-friendly and progressive fork of the project.  It is in my honest experience that unless something is really starting to move, this project will be another potentially fantastic project on which it's tombstone will not read RIP, but DBL, *Death By Loneliness* (or ignorance!)

However, I would like to hear more clearly from the maintainers of this project-trilogy before taking on such an endeavor. I would like to know what their plans are and whether or not they would help support such an obligation. (I have been in brief contact with @aquynh who stated he will look into cases and issues and consider adding people to help with the maintenance. That was > 1 months ago, and essentially nothing has happened since.)

Currently there are **789 Capstone forks** out there, and **several dozens of those, contain potentially valuable additions and fixes to Capstone**. There are currently **19 pending PR requests that are not making any progress**, (the oldest one from 2015), for no other reason than lack of participation of the owners of this project. Then we have the **306 open issues**, where the majority is lacking clear or  actionable response from the maintainers or are out of date and can be closed. 

This is a very sad and an extreme case of counter productivity of an otherwise potentially great project. 

I would love to hear what other developer participants think about this? (There are 267 people watching the project, so I assume there should be at least 26 people concerned. So if you are concerned, please write your opinion here.)

I would love to see the revival of this place and having an active RE community more involved. 
Anyway, at the end of the day, I just want to see shit moving along and making progress, and I am happy to contribute and help doing so.

Free :beers: and :heart:  to all!

**Comment by XVilka** [comment]
I think first we/you should define a list of the goals for the fork. Like ARM 8.3/8.4/8.5/etc,... So it will be easier to show the exact problems and what will be solved.

**Comment by E3V3A** [comment]
> 
> 
> I think first we/you should define a list of the goals for the fork. Like ARM 8.3/8.4/8.5/etc,... So it will be easier to show the exact problems and what will be solved.

Sound like a great idea! Yes, my main interest is to fix the ARM stuff, but there are many other potentially useful features that is sleeping around in the many unmerged, cancelled PRs or in obscure fragmented forks and issues. 

More generally you can look at the [ToDo list in this fork](https://github.com/CapstoneReloaded/capstone/issues/1).  

**But that said. I believe the most important thing for such a fork, is to allow a ~5-10 people to help maintain the issues and PRs, with repo access to do so.**  This would be done by following a more organized and clearly stated PR QA testing schema, that anyone should be able to follow. 

Second, github is full of very useful progress tracking, issues tracking and labeling tools. This should be put to good use, and it's beyond me why this is not already used here.

**Comment by aquynh** [comment]
i got some external supports, so can now announce that we will have Capstone v4 out in middle of December. there is no more delay this time.

after that we will move to Capstone v5. i will post more about that later.

**Comment by XVilka** [comment]
Support or not - this issue talking not about the release, this issue
talking about reviving the development with tons of PRs not merged and
issues stuck for years. So having the v4 release doesn't solve this and
problem still persist.

**Comment by XVilka** [comment]
Multiple people review PRs, multiple people merge them. It is highly
subjective, if someone is unsure - he waits for another person to decide,
but those cases are not that common.

**Comment by E3V3A** [comment]
@aquynh 

> No, all the open PRs have some issues, so i cannot merge them.

That is not true at all. Have you actually looked at them!? About half the PRs can be merged right now. Others were requesting feedback from you, or someone who could help, and the PR was then ignored for such a long time that the user sending it, gave up and deleted his/her repo. Yet, for many other PRs you are making unreasonable requests from the PR author/user to perform some testing on a rather complicated framework (you?) designed. None of this make any sense, and is totally counter productive. People run away from this project kicking and screaming. 

The only people who can help you, are the ones coming here, sending you loads of PRs, and you have simply decided not to let them help you! That you (and everyone else) has other obligations and little time to maintain this, is completely understandable, but what is not understandable is the complete lack of flexibility regarding letting more people in, on your project and your refusal to help all those who are trying to help you, and who have possibly helped make this project work in the first place. 

I have no idea what your fears are all about, but given the number of externally dependent projects, depending on this one, you have been pissing off a lot of people, by ignoring a vast number of friendly requests to update, maintain, or simply fix basic things.

Anyway, I am also fed up of trying to help someone who doesn't want it, and who's only interest is to hold on to, and sob over their dying horse. So you will unlikely hear much from me here again, unless absolutely essential for other users. 

In the meantime, everyone is welcome to join the team at:

## [CapstoneReloaded](https://github.com/CapstoneReloaded/capstone)

A fun place where your PRs will be taken seriously and your contributions are appreciated!

:peace_symbol:  :heart:  and :sparkles:

**Comment by aquynh** [comment]
i am not a rockstar developer, but this reminds me of this tweet.

https://twitter.com/ryanchenkie/status/1067801413974032385

this is a nature of OSS, you should understand: i have the main responsibility on maintaining this project, but on the other hand, i am doing all this work for free, and can only work on it in my spare time, when i feel comfortable. in return, it is fair that i dont feel i owe anybody anything.

Capstone is still alive, just slower than before. regarding the future, our goal is to make it less dependent on me as possible. hope to make the plan for v5 out soon, but only when it is ready.
