### ISSUE TITLE
ARM: ARM_STR_POST_REG missing when setting writeback

### ISSUE THREAD

**Issue by atkdef** [aquynh/capstone#1296]
https://github.com/aquynh/capstone/blob/4948fd1b56bb32634ec17d214de99bda7db410eb/arch/ARM/ARMInstPrinter.c#L377-L384

"STR Rd, [Rn], Rm" currently does not set writeback to true. Not sure if it's caused by missing a case shown above.

**Comment by aquynh** [comment]
fixed now, please confirm

**Comment by atkdef** [comment]
https://github.com/aquynh/capstone/blob/098b1402a3a3154482646d0ad311e4bfdc077c46/arch/ARM/ARMInstPrinter.c#L377-L386

The fix is fine, but if the empty line is used to group instructions, shouldn't ARM_STRB_POST_IMM be in STR group instead of the LDR one? Thanks for the fix anyway.

**Comment by aquynh** [comment]
that blank line is a mistake, yes ;-)

thanks for reporting.
