### ISSUE TITLE
Destination operand access is read instead of write (MMX/SSE move opcodes)

### ISSUE THREAD

**Issue by ClarkColeman** [aquynh/capstone#1304]
The following instructions have the memory destination operand (first operand) marked as read instead of written. They are actually written but not read.

movd [rsp], xmm0

movq qword [rsp + 0x40], xmm0

I suspect the following also have the same problem, based on error logs, but they come from a huge binary and I have not stepped into gdb yet:

movdqu [r13], xmm1

movdqa [rsp + 0x40], xmm1

movdqa [rsp + 0x50], xmm1

**Comment by aquynh** [comment]
please, could you provide the input (in hexcode), and paste the output of `cstool -d` here?

**Comment by aquynh** [comment]
also, please provide the version you are using, and double check with the latest code from master branch.

**Comment by aquynh** [comment]
fixed in "v4" branch at https://github.com/aquynh/capstone/tree/v4, and will be released as v4.0.2 soon.

let me know if you still have issues.
