### ISSUE TITLE
x86 cmp - incorrect access mode for memory operands

### ISSUE THREAD

**Issue by abenkhadra** [aquynh/capstone#1308]
instruction `cmp` does not modify its operands. However, capstone sets access mode `CS_AC_WRITE` for variants of `cmp` that have a memory operand. For instance, consider this instruction

 `cstool -d x64 "83 3d a1 75 21 00 04"`

cstool output using the latest master is below. Clearly, only `CS_AC_READ` should be set. I have a fix for this [here](https://github.com/abenkhadra/capstone/commit/7093b3cc62eaa54ba291dad8019c9a3fbe8b632b) but my fix changes files that are presumably automatically generated from tablegen files. Fixing this issue in the original tablegen files might be better. Nevertheless, please let me know if you are interested in a PR. 

```
 0  83 3d a1 75 21 00 04                             cmp	dword ptr [rip + 0x2175a1], 4
	Prefix:0x00 0x00 0x00 0x00 
	Opcode:0x83 0x00 0x00 0x00 
	rex: 0x0
	addr_size: 8
	modrm: 0x3d
	disp: 0x2175a1
	sib: 0x0
	imm_count: 1
		imms[1]: 0x4
	op_count: 2
		operands[0].type: MEM
			operands[0].mem.base: REG = rip
			operands[0].mem.disp: 0x2175a1
		operands[0].size: 4
		operands[0].access: READ | WRITE
		operands[1].type: IMM = 0x4
		operands[1].size: 4
	Registers read: rip
	Registers modified: rflags
	EFLAGS: MOD_AF MOD_CF MOD_SF MOD_ZF MOD_PF MOD_OF
```

**Comment by aquynh** [comment]
that fix is good enough, please do pull req, i will merge right away
