### ISSUE TITLE
fuzzallcorp is failing on release 4.0 tarball

### ISSUE THREAD

**Issue by trofi** [aquynh/capstone#1310]
Noticed when attempted to package `capstone-4.0` to Gentoo:

```
$ wget -c https://github.com/aquynh/capstone/archive/4.0.tar.gz
$ tar xf 4.0.tar.gz
$ cd capstone-4.0
$ make -j$(nproc)
$ make check
...
Trying suite/MC/AArch64/basic-a64-instructions.s.cs
./suite/fuzz/fuzz_bindisasm suite/fuzz/corpus-libFuzzer-capstone_fuzz_disasmnext-latest/
Invalid directory
```

Missing data?

**Comment by aquynh** [comment]
`make check` is mainly for Linux distro. @catenacyber, should we separate fuzz targets into a new Makefile target, like "fuzz"?

**Comment by catenacyber** [comment]
The problem here is that you need to download the full corpus from capstone fuzz repo to run the full tests

This is done by travis with 
```
wget https://github.com/groundx/capstonefuzz/raw/master/corpus/corpus-libFuzzer-capstone_fuzz_disasmnext-latest.zip
unzip corpus-libFuzzer-capstone_fuzz_disasmnext-latest.zip -d suite/fuzz
```

So, the proposed pull request checks if the directory is present to run the tests

**Comment by aquynh** [comment]
@trofi, please confirm this is fixed now. (by @catenacyber)

**Comment by trofi** [comment]
:next branch works fine for me. Thank you!
