### ISSUE TITLE
'make install DESTDIR=/foo' installs files into /foo/foo/

### ISSUE THREAD

**Issue by trofi** [aquynh/capstone#1311]
Noticed when attempted to package capstone-4.0 to Gentoo:

```
$ wget -c https://github.com/aquynh/capstone/archive/4.0.tar.gz
$ tar xf 4.0.tar.gz
$ cd capstone-4.0
$ make -j$(nproc)
$ mkdir -p __i__
$ make install DESTDIR=$(pwd)/__i__
...
install -m0755 ./libcapstone.so.4 /tmp/y/capstone-4.0/__i__/tmp/y/capstone-4.0/__i__/usr/lib
install -m0644 ./libcapstone.a /tmp/y/capstone-4.0/__i__/tmp/y/capstone-4.0/__i__/usr/lib
```

Note how `/tmp/y/` leaked into `__i__` target. `$(DESTDIR)` gets prepended twice.

**Comment by blshkv** [comment]
I filed the same 1 min later ;-)
https://github.com/aquynh/capstone/issues/1312

**Comment by aquynh** [comment]
waiting for your pull req ;-)

**Comment by aquynh** [comment]
fixed now, please confirm.

**Comment by aquynh** [comment]
this is the related commit: https://github.com/aquynh/capstone/commit/4568e7c1cb9a876ba45b75ffae9b7c4978839dce

**Comment by trofi** [comment]
`make install` seems to work fine! Thank you!

I also noticed `uninstall` has `LIBDIR` prefixed with `DESTDIR`:

```Makefile
uninstall:
    ...
    rm -f $(DESTDIR)$(LIBDIR)/lib$(LIBNAME).*
```

**Comment by aquynh** [comment]
right, do you mind making a pull req to fix that line?

**Comment by aquynh** [comment]
should be fixed now, thanks!
