### ISSUE TITLE
Python: skipdata_setup does not accept None for callback

### ISSUE THREAD

**Issue by MarSoft** [aquynh/capstone#1316]
According to [documentation](https://www.capstone-engine.org/skipdata.html#2-customize-the-data-instructions-mnemonic), one should be able to set `skipdata` instruction mnemonic using this code:
```
md = Cs(CS_ARCH_X86, CS_MODE_64)
md.skipdata_setup = ('db', None, None)
md.skipdata = True
```
But in reality this does not work:
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    md.skipdata_setup = ('db', None, None)
  File "/tmp/env/lib/python3.7/site-packages/capstone/__init__.py", line 908, in skipdata_setup
    _skipdata_opt.callback = CS_SKIPDATA_CALLBACK(_cb)
TypeError: argument must be callable or integer function address
```
A partial workaround would be to provide a dummy callback like this `md.skipdata_setup = ('db', lambda b, o, u: 4, None)` but in such case the return value should depend on the architecture.

Actually I think we should use different approach: rather than using single `skipdata_setup` property, have `skipdata_mnem` property for mnemonic and `skipdata_callback = (callback, argument)` for callback.
We even already have a fileld `_skipdata_mnem` set in the constructor but it is not used anywhere.

**Comment by MarSoft** [comment]
`skipdata_setup` property could be left there for compatibility. But we should anyway fix it to allow `None` for callback.

**Comment by aquynh** [comment]
Can you have a pull req to allow None callback?

The other suggestions sound good to me.

**Comment by MarSoft** [comment]
Workaround until the PR is merged and deployed: pass `0` instead a function, like this - `md.skipdata_setup = ('db', 0, None)`

**Comment by aquynh** [comment]
reopen this issue, as i still cant figure out how to fix this crash on MacOS yet.

**Comment by MarSoft** [comment]
Reproduced the crash on MacOS. Steps to reproduce:
1. Set `skipdata callback` using any available method;
2. Enable `skipdata`;
3. Try to disassemble some code which contains incomprehensible instruction, e.g. `\x00\x00\x00\x00` with CS_ARCH_ARM64.
4. Process will crash with either `Segmentation fault: 11` or  `Illegal instruction: 4` (could not reproduce the latter more than once).

Code to reproduce:
```
from capstone import *

def cb(b, s, o, d):
    print(b, s, o, d)
    return 4
cap = Cs(CS_ARCH_ARM64, CS_MODE_ARM)
cap.skipdata = True
cap.skipdata_callback = cb
data = bytes(4)  # 4 zero bytes
print('Disassembling...')
print(list(cap.disasm_lite(data, 0)))
```
Result:
```
$ python test.py
Disassembling...
Segmentation fault: 11
```
Notice the callback was not called.

And yet another issue on mac. If you touch skipdata settings in any way (e.g. `cap.skipdata = ('foo', None, None)`) then skipdata starts using *empty string* for mnemonic.

**Comment by MarSoft** [comment]
Very interesting! This somehow interferes with the debugger. If I add a `breakpoint()` in the beginning of `skipdata_setup` setter, and just enter `continue` command to the debugger, then everything works correctly! Both `mnemonic` and `callback` work as expected.
Seems that this bug is unrelated to the original issue, so I'll move it to the separate thread.

**Comment by MarSoft** [comment]
Did more testing. If I *enter* `skipdata_setup` setter with debugger - even if I put breakpoint *in its end*, after everything is already done - then things work fine. But if I don't enter it then we get the problem.

Hm. Maybe `_skipdata_opt` structure is passed by pointer and then is garbage collected and overwritten?

**Comment by MarSoft** [comment]
Yeah, I am right! If I store a `weakref.proxy` to the `_skipdata_opt` to a global variable then its callback is called when the `_skipdata_opt` is destroyed.
When I enter the setter with `gdb`, `_skipdata_opt` is only destroed in the end of program life. And if I don't enter it then `_skipdata_opt` is destroyed immediately after leaving setter, before we use `capstone.disasm_lite` in the sample script above.
After that, Python overwrites its inner stuff which C code uses by reference.

**Comment by MarSoft** [comment]
Just encountered similar problem (skipdata instruction getting "auto-switched") on Linux with `Capstone==4.0.1`.  First skipdata instructions became `''`, then `'h\x04'`.
So the issue is not specific to Mac only.
Hope the new release will be rolled out soon :)

Workaround I used for now:
```
for ins in cap.disasm(code, addr):
    if ins.id == 0:
        ins._raw.mnemonic = b'mymnem'  # where b'mymnem' being the expected mnemonic but as bytes
    ... further processing ...
```

**Comment by aquynh** [comment]
Yes we will release v4.0.2 next month.
