### ISSUE TITLE
arm thumb thb instruction shift in Capstone 4

### ISSUE THREAD

**Issue by disconnect3d** [aquynh/capstone#1317]
Is the difference in TBH arm thumb instruction introduced in capstone 4.0 correct?

On 3.0.5:
```
$ LD_PRELOAD=../libcapstone.so ./cstool -h | head -n1
Cstool for Capstone Disassembler Engine v3.0.5

$ LD_PRELOAD=../libcapstone.so ./cstool -d thumb "d0 e8 11 f0"
0  d0 e8 11 f0  tbh	[r0, r1, lsl #1]
	op_count: 1
		operands[0].type: MEM
			operands[0].mem.base: REG = r0
			operands[0].mem.index: REG = r1
			Shift: 2 = 1
	Groups: thumb2 jump
```

On 4.0:
```
$ ./cstool -h | head -n1
Cstool for Capstone Disassembler Engine v4.0.0

$ ./cstool -d thumb "d0 e8 11 f0"
 0  d0 e8 11 f0  tbh	[r0, r1, lsl #1]
	op_count: 1
		operands[0].type: MEM
			operands[0].mem.base: REG = r0
			operands[0].mem.index: REG = r1
			operands[0].mem.lshift: 0x1
		operands[0].access: READ
	Registers read: r0 r1
	Groups: thumb2 jump
```

**Comment by disconnect3d** [comment]
In 3.0.5 the `operand.shift` is 2, in 4.0 it is 0. Is that correct?

**Comment by aquynh** [comment]
> in 4.0 it is 0.

which part is 0??

**Comment by disconnect3d** [comment]
```python
from capstone import *

print('Capstone', __version__)

code = b'\xD0\xE8\x11\xF0'

md = Cs(CS_ARCH_ARM, CS_MODE_THUMB)
md.detail = True
for i in md.disasm(code, 0x1000):
    print("0x%x:\t%s\t%s" % (i.address, i.mnemonic, i.op_str))

insn = i
operand = insn.operands[0]

print('imm {o.imm} reg {o.reg} setend {o.setend} type {o.type} shift_type {o.shift.type} shift_val {o.shift.value}'.format(o=operand))
```

Capstone 3.0.5:
```
$ python caparmtest.py
Capstone 3.0.5
0x1000:	tbh	[r0, r1, lsl #1]
imm 66 reg 66 setend 66 type 3 shift_type 2 shift_val 1
```

Capstone 4.0:
```
$ python caparmtest.py
Capstone 4.0.0
0x1000:	tbh	[r0, r1, lsl #1]
imm 66 reg 66 setend 66 type 3 shift_type 0 shift_val 0
```

**Comment by aquynh** [comment]
yes it is confused. what do you think we should change?

**Comment by disconnect3d** [comment]
@aquynh Maybe we should revert the change/remove the `op.mem.lshift` so that we have only one shift thing?

**Comment by disconnect3d** [comment]
> let me see what is best to do.

Capstone 4.0 kinda breaks this on the `op.shift` thing. We can either remove the `op.mem.lshift` or make it a bit longer move e.g.:
* add a comment that `op.mem.lshift` is deprecated for a next 4.0.x or 4.x release
* fix/set proper `op.shift` value when `op.mem.lshift` is set (so yeah, this value could be fetched in two different ways)
* add some info to changelog regarding `op.shift` and `op.mem.lshift`
* remove `op.mem.lshift` in some future release version and write about it in the changelog

What do you think about it? Would you like such PR?

**Comment by aquynh** [comment]
i think for now the safest choice is (3), and we can put that into include/capstone/arm.h

**Comment by aquynh** [comment]
then (2) also looks good
