### ISSUE TITLE
Invalid instruction group in v4.0 (Arm+Thumb)

### ISSUE THREAD

**Issue by bohlender** [aquynh/capstone#1323]
While upgrading the D bindings, I've found that v4.0 returns invalid instruction groups for arm+thumb. The byte sequence is actually an excerpt from your test suite.

On v3.0.5
```
./cstool -d thumb x70x47x00
0  70 47  bx	lr
	op_count: 1
		operands[0].type: REG = lr
	Groups: thumb jump
```

On v4.0 (and current HEAD e8967c6)
```
$ ./cstool -d thumb x70x47x00
 0  70 47  bx	lr
	op_count: 1
		operands[0].type: REG = lr
		operands[0].access: READ
	Registers read: lr
	Registers modified: pc
	Groups: thumb (null) jump
```
As you can see the latest Capstone version returns the Arm instruction groups `150`,`11`,`1`, which correspond to `thumb`, something invalid and `jump` respectively.

**Comment by aquynh** [comment]
fixed now, please confirm.

**Comment by bohlender** [comment]
Thanks for the quick fix. Working as expected.
