### ISSUE TITLE
Setting syntax for MIPS not possible in v4 (CS_ERR_OPTION)

### ISSUE THREAD

**Issue by bohlender** [aquynh/capstone#1324]
The following code works without any problems with v3.0.5 but crashes for v4 (and master 8f4cc4e) for any syntax option. Even setting to the _default_ setting yields the CS_ERR_OPTION error code (6).

```C
#include <stdio.h>
#include <capstone/capstone.h>

int main() {
    csh handle;
    cs_err err = cs_open(CS_ARCH_MIPS, CS_MODE_MIPS32 | CS_MODE_BIG_ENDIAN, &handle);
    if (err) {
        printf("Failed on cs_open() with error returned: %u\n", err);
        abort();
    }

    err = cs_option(handle, CS_OPT_SYNTAX, CS_OPT_SYNTAX_DEFAULT);
    if (err) {
        printf("Failed on cs_option() with error returned: %u\n", err);
        abort();
    }
}
```
The Capstone test suite for MIPS does not change the syntax option, which is why this behaviour has gone unnoticed for v4.

**Comment by aquynh** [comment]
but this is not a bug: since Mips does not support changing the syntax, cs_option() reports an error. your code verifies the returned value, which is good.

**Comment by aquynh** [comment]
yes v4 changes its behavior, as v3 is silent on unsupported option, and v4 corrects that.

**Comment by bohlender** [comment]
While it is reasonable to report an error when trying to change the syntax for Mips, I was expecting it at least to work fine with the default value. That's what the engine is initialised with anyway, and setting it to `CS_OPT_SYNTAX_DEFAULT` would not result in changing the syntax option after all.

However if this is by design, I'll stick with it. Thanks for the quick reply.
