### ISSUE TITLE
clang-analyzer issue in /shlr/capstone/arch/M680X/M680XDisassembler.c	

### ISSUE THREAD

**Issue by radare** [aquynh/capstone#1329]
* Value stored to 'address' is never read

http://ci.rada.re/job/radare2-scan-build/6510/clangScanBuildBugs/browse/report-958222.html#EndPath

**Comment by radare** [comment]
should be `*address += 2;`

**Comment by aquynh** [comment]
@aladur, please confirm.

**Comment by aladur** [comment]
There is a fix for this issue on fork aladur/capstone.

**Comment by aquynh** [comment]
Pull req, please.
