### ISSUE TITLE
[x86] Can't decode 'nop reg'

### ISSUE THREAD

**Issue by P1224** [aquynh/capstone#1335]
> cstool.exe x32 "0F 1F C0"
> ERROR: invalid assembly code

Should be 'nop eax'.

**Comment by aquynh** [comment]
is this from version 4.0?

**Comment by P1224** [comment]
yeap

**Comment by aquynh** [comment]
Does this really reads EAX register?

**Comment by aquynh** [comment]
is this documented?

**Comment by P1224** [comment]
It's documented as multi-byte no-operation instruction 'NOP r/m32' in Intel Instruction Set Reference.
While 'nop dword ptr [eax]'(0F1F00) is well decoded by capstone, 'nop eax' is not. 
Since 'nop dword ptr [eax]'(0F1F00) doesn't really read [eax](tested on cpu), maybe it's the same for 'nop eax'.

**Comment by P1224** [comment]
There is another problem in decoding x64 instruction 'nop qword ptr[rax]'(480F1F00), REX.W is set but capstone doesn't decode it.

> cstool.exe -d x64 "48 0F 1F 00"
 0  48 0f 1f 00                                      nop        dword ptr [rax]
        Prefix:0x00 0x00 0x00 0x00
        Opcode:0x0f 0x1f 0x00 0x00
        rex: 0x48
        addr_size: 8
        modrm: 0x0
        disp: 0x0
        sib: 0x0
        op_count: 1
                operands[0].type: MEM
                        operands[0].mem.base: REG = rax
                operands[0].size: 4
                operands[0].access: READ
        Registers read: rax

**Comment by aquynh** [comment]
now fixed in the "next" branch (which will be released as v5), thanks!
