### ISSUE TITLE
python bindings for capstone next fail to install missing libcapstone.so.4

### ISSUE THREAD

**Issue by bennofs** [aquynh/capstone#1337]
Install for python binding on next fails with:

```
      LINK    libcapstone.so.5
      AR      libcapstone.a
    ar: creating ./libcapstone.a
    error: [Errno 2] No such file or directory: 'libcapstone.so.4'
```

I think this is because `VERSIONED_LIBRARY_FILE` needs to be updated for version 5
https://github.com/aquynh/capstone/blob/da93a194b80a354f4840798f78a9f48c2db424b4/bindings/python/setup.py#L59-L70

**Comment by aquynh** [comment]
Correct, do you mind sending a pull req to fix that?

**Comment by bennofs** [comment]
Sorry right should've made a PR (when I started writing the issue I didn't know the fix was so simple)

**Comment by aquynh** [comment]
fixed, thanks!
