### ISSUE TITLE
The 4.1 branch is gone

### ISSUE THREAD

**Issue by radare** [aquynh/capstone#1350]
This broke r2 build, which is the one we are suposed to use now? next? master? neo? no more 5.x either?

**Comment by aquynh** [comment]
"master", as i just merged it, and deleted it. This will be released as
v4.1 later

"next" is for v5, but at the moment it is same as "master".

>

**Comment by radare** [comment]
so, where is the 4.x development going to happen now? in master or in another branch? I switched to master in r2 to fix the build for now

**Comment by aquynh** [comment]
v4.1 is in master branch now.

**Comment by radare** [comment]
its broken again, i'll look into a different approach to solve this branch management hell

**Comment by aquynh** [comment]
All tests passed, so what is broken?
