### ISSUE TITLE
Capstone 4.0.1 X86 Binary Always Build With DIET MODE?

### ISSUE THREAD

**Issue by 9ee1** [aquynh/capstone#1351]
Hello:

I am not sure if this was a design decision that was made so if it was, I apologize.

As of Capstone 4.0.1, it seems there is a build option/switch set somewhere that always builds the X86 binary with DIET MODE. I downloaded the pre-built binaries from the website in case I did something wrong and it seems they suffer from the same issue.

Can someone confirm if that is the case or if I am doing something wrong?

Thanks!

**Comment by aquynh** [comment]
Something sounds wrong on your machine, as that option is off by default.

Can you paste the output of "cstool -v" here? It should not have "diet=1"
there.

**Comment by 9ee1** [comment]
OK, you're right. There has to be something else wrong with the .NET Binding then. This is my mistake.

cstool indicates DIET MODE is off. And I double checked the build options and there isn't something wrong.

But for some reason, whenever I call `cs_support` from C#, it always says DIET is enabled but only for the X86 library. Curious ...

**Comment by 9ee1** [comment]
I am going to go ahead and close this ticket since this looks like a problem on my end.
