### ISSUE TITLE
Race in X86_insn_reg_intel

### ISSUE THREAD

**Issue by awgil** [aquynh/capstone#1358]
X86_insn_reg_intel() function in arch/X86/X86Mapping.c creates a sorted array for fast lookups on first execution. However, since it is done without any kind of synchronization, it is possible for two threads to try building the sorted array in parallel and interfere with each other.

**Comment by radare** [comment]
Which solution do you think it will work best as long as capstone have nothing to do with thread handling. I think a design decission from the leader would be helpful

**Comment by aquynh** [comment]
the best solution is just hardcode that sorted lookup array, but we have to remember updating it if the list is changed.

**Comment by awgil** [comment]
While hardcoding the sorted lookup seems to be the best solution, I'm not really comfortable making it due to following concerns:
* The keys seem to come from some auto-generated enum, but I don't understand the process of this generation. In particular, is there some guarantee that enum values can't change after regeneration?
* Manually sorting 100+ entries is error-prone during maintenance, so it would require adding either some debug assertion or some unit test to validate that list always remains sorted. I don't know enough about capstone infrastructure to determine the best place to put such test/assertion (what is the "debug-only" condition in capstone codebase? what is the supported way of performing assertions that work on all platforms? how unit tests are written? etc.).
* Some of the entries of the table are under #ifndef CAPSTONE_X86_REDUCE check; why is it necessary? If it is to remain in sorted hardcoded array, it would need to be duplicated, which would look really messy.
* Why is binary search optimization done only for insn_regs_intel array? For example, it is not done for very similar insn_regs_att array - why? If it is a simple oversight, it would probably make sense to create some binary search utility rather than hardcoding algorithm in each lookup function. What is the appropriate place for such algorithms (maybe there is even one already)? I'm more of a C++ programmer, and I don't know idiomatic C ways of writing generic algorithms (is taking void* + function pointer for element access a-la qsort really the best way?..)

**Comment by aquynh** [comment]
> While hardcoding the sorted lookup seems to be the best solution, I'm not really comfortable making it due to following concerns:
> 
> * The keys seem to come from some auto-generated enum, but I don't understand the process of this generation. In particular, is there some guarantee that enum values can't change after regeneration?

no, so this solution is not perfect.

> * Manually sorting 100+ entries is error-prone during maintenance, so it would require adding either some debug assertion or some unit test to validate that list always remains sorted. I don't know enough about capstone infrastructure to determine the best place to put such test/assertion (what is the "debug-only" condition in capstone codebase? what is the supported way of performing assertions that work on all platforms? how unit tests are written? etc.).
> * Some of the entries of the table are under #ifndef CAPSTONE_X86_REDUCE check; why is it necessary? If it is to remain in sorted hardcoded array, it would need to be duplicated, which would look really messy.
> * Why is binary search optimization done only for insn_regs_intel array? For example, it is not done for very similar insn_regs_att array - why? If it is a simple oversight, it would probably make sense to create some binary search utility rather than hardcoding algorithm in each lookup function. What is the appropriate place for such algorithms (maybe there is even one already)? I'm more of a C++ programmer, and I don't know idiomatic C ways of writing generic algorithms (is taking void* + function pointer for element access a-la qsort really the best way?..)

yes it is a good idea to refactor some code so they can be shared.

to solve this issue, we can also sacrifice some performance by just use linear searching, instead of binary searching.

**Comment by aquynh** [comment]
in the next v5 (WIP), i will just hardcode the list in ascending order for binary search. to make sure future change does not corrupt the list, we will have some testcase running on every commit (using Travis), which will report immediately if corruption happens.

**Comment by aquynh** [comment]
now fixed in the "next" branch (which will be released as v5), thanks!
