### ISSUE TITLE
Static linkinging error - Visual Studio 2017

### ISSUE THREAD

**Issue by 1982Dmitry** [aquynh/capstone#1370]
I'm trying to link capstone but getting errors about unresolved symbols for capstone.lib, I'm using recent release of the library

![image](https://user-images.githubusercontent.com/10502637/52335874-66383300-29fb-11e9-9459-7aeee8e4bbd5.png)

**Comment by aquynh** [comment]
perhaps because that lib was not built with static runtime. you can get the latest code, install cmake, and from MSVC prompt, build Capstone yourself with:

```
mkdir build
cd build
..\nmake.bat
```

let me know if the resulted capstone.lib works for you.

**Comment by 1982Dmitry** [comment]
It works!
