### ISSUE TITLE
Capstone 4.0.1 package on PyPI does not include MOS65xx architecture

### ISSUE THREAD

**Issue by JarrettBillingsley** [aquynh/capstone#1387]
Sorry if this is the wrong place to report this; I'm not sure who's responsible for the package up on PyPI.

I did `pip install capstone`, and did this:

```python
>>> import capstone
>>> [a for a in dir(capstone) if a.startswith('CS_ARCH')]
['CS_ARCH', 'CS_ARCH_ALL', 'CS_ARCH_ARM', 'CS_ARCH_ARM64', 'CS_ARCH_EVM', 'CS_ARCH_M680X', 'CS_ARCH_M68K', 'CS_ARCH_MAX', 'CS_ARCH_MIPS', 'CS_ARCH_PPC', 'CS_ARCH_SPARC', 'CS_ARCH_SYSZ', 'CS_ARCH_TMS320C64X', 'CS_ARCH_X86', 'CS_ARCH_XCORE']
```

It has all the architectures except `CS_ARCH_MOS65XX`.

I cloned this repo and built it from scratch, using `python setup.py install` instead, and it properly lists all the architectures.

**Comment by aquynh** [comment]
That is right: this arch is only available in v5. If you want it, get
latest code from Github.

**Comment by JarrettBillingsley** [comment]
Oh! My bad. I didn't realize this was a feature for the next version.
