### ISSUE TITLE
m68k: data race initializing global g_instruction_table in build_opcode_table()

### ISSUE THREAD

**Issue by tmfink** [aquynh/capstone#1397]
The global array `g_instruction_table` init in `M680XDisassembler.c:build_opcode_table()` is a race condition.

Declaration:
https://github.com/aquynh/capstone/blob/de952a3e5a519b4a0d0dd2ef921a755891860ca6/arch/M68K/M68KDisassembler.c#L250-L251

Initialization:
https://github.com/aquynh/capstone/blob/de952a3e5a519b4a0d0dd2ef921a755891860ca6/arch/M68K/M68KDisassembler.c#L3787-L3827

This caused problems while working on the Rust language bindings. The tests are run in parallel:
    - PR: https://github.com/capstone-rust/capstone-rs/pull/60
    - Travis CI failure: https://travis-ci.org/capstone-rust/capstone-rs/jobs/498529801#L623

**Possible solutions**:
- Introduce synchronization in `build_opcode_table()`
    - Would require adding a threading library dependency (like pthread)
- Declare array with appropriate values statically
    - Most efficient (run time) method
    - Does not add extra dependencies or change API
    - Requires deeper knowledge of m68k code
    - May require writing a script to generate C declaration
- Introduce `capstone_init()` function that must be called before any other Capstone functions
    - API breaking change
    - Less ergonomic for users
- Move the global variable into the private `cs_struct`
    - Less efficient: wastes time initializing and memory

Similar past issue: #1171

**Comment by aquynh** [comment]
@emoon, i think the solution (2) is the best.

**Comment by radare** [comment]
Imho a library initializer/constructor would be cleaner but that will break backwards compat.

**Comment by emoon** [comment]
I would agree with @radare that a `init` function would be cleaner but (2) wouldn't break anything so I guess is what needs to be done. I guess what I need to do is to write a script that generates the table. I can include the script as an optional thing that people that changes the code may need to use. Users in general will never need to poke around in this code so having a manual step isn't the biggest issue I would say and in many cases one wouldn't need to change this anyway.

I can try to look at this during the week and hopefully today.

**Comment by aquynh** [comment]
> I would agree with @radare that a `init` function would be cleaner but (2) wouldn't break anything so I guess is what needs to be done. I guess what I need to do is to write a script that generates the table. I can include the script as an optional thing that people that changes the code may need to use. Users in general will never need to poke around in this code so having a manual step isn't the biggest issue I would say and in many cases one wouldn't need to change this anyway.

m68k is a stable architecture, without any future update (?), so this is one time change, and should work well.

**Comment by emoon** [comment]
Yeah I think it will be fine.

**Comment by tmfink** [comment]
@emoon definitely include the script that is used to generate the array. That will make future contributions easier.  :-)

**Comment by emoon** [comment]
@tmfink yes, that is the plan :)

**Comment by radare** [comment]
Overcomplicating the implementwtion of a library messing with threads, mutexes, locks and such when it just needs a decent api is a bad idea imho. Because the null chk in the fini call as well as the handler resolution instead of just using a pointer holding the initialized library would be other changes i would appreciate to see in the next release if you are in the mood to change the api

**Comment by emoon** [comment]
Well the fix in this case won't involve any threading setup but I agree it would be nice with an init call but I will do the pre-create table approach here.

**Comment by emoon** [comment]
It's important to realize with this change there will be a file with ~65535 lines of code in it. While no compilers these days will have any issues with (esp as it's data only) it will likely bump the compile times a bit.

**Comment by tmfink** [comment]
We may want such a large file to be #include'd instead of dropped in
directly.

**Comment by emoon** [comment]
Sure it can be an include.

**Comment by radare** [comment]
That will probably hurt in the final binary size. And capstone is already quite big...

**Comment by aquynh** [comment]
Including big files is what we have been doing for x86 & other LLVM based
archs. And 64k files are nothing, no worry :-)

**Comment by aquynh** [comment]
Unfortunately we have to choose between performance & size. For now, most
efforts are to make the core faster.

For X86, i have been doing many optimization on the binary size, because
people want to put Capstone inside OS kernels or so. There is no such
demand for other archs.

Of course there are other options available, such as selected build only
archs you need, or the diet mode.

**Comment by emoon** [comment]
Alright. I will implement this on Friday. Expect a PR then

**Comment by fanfuqiang** [comment]
Why not add a C11 atomic flag?
`
typedef struct {
	void (*instruction)(m68k_info *info);    /* handler function */
        _Atomic _Bool is_init;         /* C11 atomic type */
	uint word2_mask;              /* mask the 2nd word */
	uint word2_match;             /* what to match after masking */
`

**Comment by aquynh** [comment]
Because we want to support all compilers?

**Comment by fanfuqiang** [comment]
> Because we want to support all compilers?

It's part of standard C11 language, all platforms, and compilers can support.

**Comment by aquynh** [comment]
Even older compiler versions?

**Comment by fanfuqiang** [comment]
> Even older compiler versions?

Well, maybe not.
compilers released after 2011 should be works.

**Comment by emoon** [comment]
I can use the `C11` atomics for this yes if @aquynh think it's acceptable to require a `C11` compatible compiler. Also there is no need to have `is_init` per entry. It's possible to rewrite the init loop instead and have several threads working on setting up the array with just one atomic counter.

**Comment by aquynh** [comment]
No please. You never know which compilers users are using, so better if we
dont force them.

You will not believe, but i had to use 20+ years old compiler, and i had no
choice.

**Comment by emoon** [comment]
Ouch :( ok, well I have a PR for the static table anyway.

**Comment by tmfink** [comment]
Other issue with using atomics:
- It's slower/more complicated than just having the table defined statically
- There could be complications with calling into the C code from other language (such as Rust) where the caller needs to obey some extra logic
- C11 means the standard was defined in 2011; compilers can be slow to adopt the standard. Different compilers may also only support parts of the standard.

**Comment by emoon** [comment]
To be fair having the table static has it's issue also:
* Slower compile times
* More memory usage during compilation

Also the calling code from the outside would be identical when using atomic so that wouldn't be much of an issue. Actually the creation of the table would be faster because multiple threads would do it at the same time but that it's not really a big issue as it's only being done once.

But as written above `atomics` won't be used anyway and I have the PR ready for the static table anyway.

**Comment by tmfink** [comment]
@emoon Can we redefine `instruction_struct` to use smaller types (such as `uint16_t`) instead of `uint`?

https://github.com/aquynh/capstone/blob/de952a3e5a519b4a0d0dd2ef921a755891860ca6/arch/M68K/M68KDisassembler.c#L240-L244

Also, while you are already modifying the file, can you eliminate the `uint` `#define`? The width can change on different architectures. If we only need 32 bits, then we should say `uint32_t`.
https://github.com/aquynh/capstone/blob/de952a3e5a519b4a0d0dd2ef921a755891860ca6/arch/M68K/M68KDisassembler.c#L62-L64

Thanks for your work!

**Comment by emoon** [comment]
Sure I can fix that and thanks :)

**Comment by emoon** [comment]
With https://github.com/aquynh/capstone/pull/1408 being merged can this be closed now?

**Comment by aquynh** [comment]
close, thanks!
