### ISSUE TITLE
v4 branch is not compatible with v4.0.1

### ISSUE THREAD

**Issue by david942j** [aquynh/capstone#1399]
Both structures `cs_detail` and `cs_insn` are changed in branch v4 but not in release 4.0.1.
[Diff](https://github.com/aquynh/capstone/compare/4.0.1...v4#diff-3ed2fb46c3301c77d4bee7888a49fcd1R286)

**Comment by aquynh** [comment]
oops that M68k fix entered that, somehow (https://github.com/aquynh/capstone/issues/1315)

@emoon @erique i think we should revert that, just for v4.0.x, to keep it backward compatible. what is the best solution now?

**Comment by aquynh** [comment]
we are maintaining v4.0.x in this branch https://github.com/aquynh/capstone/tree/v4

**Comment by emoon** [comment]
Either the change gets reverted or 4.0 needs to be patched.

**Comment by erique** [comment]
yeah, i think we need to have the m68k fixes only enter the next major version (v5 iirc?), and keep 4.x as is / as before.

**Comment by aquynh** [comment]
yes "next" branch is for v5.0

so i just revert #1344 in "v4"? including the change in M68KInstPrinter.c? (i am asking because it does not seem to relate to this pull req)

**Comment by erique** [comment]
correct - it is not related; you can leave it in if you want to.

**Comment by aquynh** [comment]
i reverted with the commit https://github.com/aquynh/capstone/commit/ee2037f761d133adaceb18caacde35529aec9582, and pick up that unrelated code with https://github.com/aquynh/capstone/commit/e4e383bbf7221058ca39e35a55bb712147d803aa

**Comment by aquynh** [comment]
close, thanks
