### ISSUE TITLE
find arm instruction like the "aese.8/sha1c.32/sha256h.32/vmull.p64" not disassemble

### ISSUE THREAD

**Issue by ajisky** [aquynh/capstone#1403]
hello, I find some arm instruction not disassemble with the capstone engine, but they can run.
and use the gdb tool can disassemble.
machinecode is 0x0003B0F3, gdb know is "aese.8 q0,q0"
machinecode is 0x400c00F2, gdb know is "sha1c.32 q0,q0,q0"
machinecode is 0x400c00F3, gdb know is "sha256h.32 q0,q0,q0".
machinecode is 0x000EA0F2, gdb know is "vmull.p64 q0,q0,q0".
and last time report the bugs about thumb "ldaex/stlex" not disassemble have not fix.
thanks for resovle the question.

**Comment by aquynh** [comment]
We are working on a major update for arm, that should handle this & other
new instructions.

**Comment by radare** [comment]
Any estimation of when this update will be ready?

**Comment by aquynh** [comment]
In March

**Comment by aquynh** [comment]
actually these code are forever supported. you can try with v4.0.1, or with "next" branch, using **thumbv8** mode.

```
$ cstool thumbv8 "0xb0 0xff 0x02 0x03 0x02 0xef 0x44 0x0c 0xb9 0xff 0xc2 0x02 0xe0 0xef 0xa1 0x0e"
 0  b0 ff 02 03  aese.8	q0, q1
 4  02 ef 44 0c  sha1c.32	q0, q1, q2
 8  b9 ff c2 02  sha1h.32	q0, q1
 c  e0 ef a1 0e  vmull.p64	q8, d16, d17
```
