### ISSUE TITLE
m68k: reg_pair off by one

### ISSUE THREAD

**Issue by tmfink** [aquynh/capstone#1406]
If we modify `test_m68k.c` to print out the `M68K_OP_REG_PAIR` case:

~~~diff
diff --git a/tests/test_m68k.c b/tests/test_m68k.c
index 9eb37104..df6cef7b 100644
--- a/tests/test_m68k.c
+++ b/tests/test_m68k.c
@@ -137,7 +137,12 @@ static void print_insn_detail(cs_insn *ins)
                                break;
                        case M68K_OP_REG_BITS:
                                printf("\t\toperands[%u].type: REG_BITS = $%x\n", i, op->register_bits);
-
+                               break;
+                       case M68K_OP_REG_PAIR:
+                               printf("\t\toperands[%u].type: REG_PAIR = (%s, %s)\n", i,
+                                       cs_reg_name(handle, op->reg_pair.reg_0),
+                                       cs_reg_name(handle, op->reg_pair.reg_1));
+                               break;
                }
        }

~~~

Then we can see an off-by-one error (`d3, d4` instead of `d4, d5`):

~~~
0x1020: mulu.l  d0, d4:d5
        op_count: 2
        reading from reg: d0
        writing to reg:   d4
        writing to reg:   d5
        groups_count: 0
                operands[0].type: REG = d0
                operands[1].type: REG_PAIR = (d3, d4)
~~~

We can see the error in how the internal instruction printing works:

https://github.com/aquynh/capstone/blob/40b8bfa39788c8e99b01a542ebe43ef582f807dc/arch/M68K/M68KInstPrinter.c#L125-L129

The actual `m68k_reg` value should be stored, not `reg - M68K_REG_D0`.

**Comment by aquynh** [comment]
@emoon please ack.

**Comment by emoon** [comment]
Looks good! Thanks for the fix.

**Comment by aquynh** [comment]
Great, please pull req.

**Comment by david942j** [comment]
I also found this behavior when developing the Ruby bindings, but I thought it  was intended at that time. I agree to fix this bug but this will somehow break user interface (users might expect always increasing one to the reg pair), at least to me, I need to fix my bindings' tests once this fix is released.

**Comment by aquynh** [comment]
close, thanks
