### ISSUE TITLE
cs-next llvm update

### ISSUE THREAD

**Issue by radare** [aquynh/capstone#1456]
After upgrading r2 to capstone-next I discovered a bunch of regressions:

* [x] ARM64_VESS is no longer there
* [x] On X86: X86_INS_FADDP X86_INS_UD2B X86_INS_FADD
* [x] 83 broken tests in the r2 testsuite https://api.travis-ci.org/v3/job/518226592/log.txt

I will update this issue with more regressions if found, could you confirm if thoes missing enums are on purpose?

Related PR https://github.com/radare/radare2/pull/13688

**Comment by aquynh** [comment]
On Wed, Apr 10, 2019, 18:30 radare <notifications@github.com> wrote:

> After upgrading r2 to capstone-next I discovered a bunch of regressions:
>
>    - ARM64_VESS is no longer there
>
>
Yes, i removed that because it overlaps with ARM64_VAS.


>    - On X86: X86_INS_FADDP X86_INS_UD2B X86_INS_FADD
>
>
Can you elaborate what is wrong with these X86 instructions?

>
>

**Comment by radare** [comment]
> On 10 Apr 2019, at 12:34, Nguyen Anh Quynh <notifications@github.com> wrote:
> 
> On Wed, Apr 10, 2019, 18:30 radare <notifications@github.com> wrote:
> 
> > After upgrading r2 to capstone-next I discovered a bunch of regressions:
> >
> > - ARM64_VESS is no longer there
> >
> >
> Yes, i removed that because it overlaps with ARM64_VAS.

ok looks good then. ill keep the old vess code to support cs4
> 


> > - On X86: X86_INS_FADDP X86_INS_UD2B X86_INS_FADD
> >
> >
> Can you elaborate what is wrong with these X86 instructions?

those enums are no longer there

**Comment by aquynh** [comment]
On Wed, Apr 10, 2019, 18:35 radare <notifications@github.com> wrote:

>
>
> > On 10 Apr 2019, at 12:34, Nguyen Anh Quynh <notifications@github.com>
> wrote:
> >
> > On Wed, Apr 10, 2019, 18:30 radare <notifications@github.com> wrote:
> >
> > > After upgrading r2 to capstone-next I discovered a bunch of
> regressions:
> > >
> > > - ARM64_VESS is no longer there
> > >
> > >
> > Yes, i removed that because it overlaps with ARM64_VAS.
>
> ok looks good then. ill keep the old vess code to support cs4
> >
>
>
> > > - On X86: X86_INS_FADDP X86_INS_UD2B X86_INS_FADD
> > >
> > >
> > Can you elaborate what is wrong with these X86 instructions?
>
> those enums are no longer there
>

I think those instructions were wrongly included in v4. If you have hexcode
of them, please paste here, so i can look at that again.

**Comment by radare** [comment]
Also 83 broken tests in the r2 testsuite

https://api.travis-ci.org/v3/job/518226592/log.txt

**Comment by aquynh** [comment]
i am not familiar with that huge log format. can you paste the relevant issues here?

**Comment by radare** [comment]
Just search for 'XX]' and you'll see the way to reproduce, the expected output and what's happening.

Let me check some:

```
-            0x000028f4      05dd4de2       sub sp, sp, 0x140           ; sp=0x177eb0
+            0x000028f4      05dd4de2       sub sp, sp, 0x140           ; sp=0x178130
```

this comment is generarted by r2 by using the infromation in RAnalOp which is filled by checking the info in the capstone cs_insn structure. The following screenshot shows that the id for this arm32 instruction is wrong. cs-next says it's id=2 (ADD) and cs-master say it's SUB (which is correct, and that maps to 216)

<img width="1680" alt="Screenshot 2019-04-10 at 17 49 50" src="https://user-images.githubusercontent.com/917142/55893749-37843780-5bb9-11e9-8ab8-c39315cc38d9.png">

The 2nd regression is caused by the same problem because the emulation esil string is generated by following the cs_insn information, which cs-next say 106, and master 92. so the plugin gets confused and constructs a wrong expression.

<img width="1266" alt="Screenshot 2019-04-10 at 17 52 08" src="https://user-images.githubusercontent.com/917142/55894242-0f490880-5bba-11e9-8492-e76ddd285c68.png">


To confirm the issue i have modified cstool to show the ins->id so I can confirm the problem is not in r2 side or caused by inconsistent linking and compiling with different versions of capstone.

Here's the proof

<img width="570" alt="Screenshot 2019-04-10 at 17 55 48" src="https://user-images.githubusercontent.com/917142/55894224-0821fa80-5bba-11e9-8f91-75d4fd8d96db.png">

I can continue checking regressions, but i bet most of them will be caused by this ins->id bug

**Comment by radare** [comment]
I have checked some other non-arm based regressions and found some interesting ones on x86:

```
cs-master (x86-32) => d50a     aad 0xa
cs-next (x86-32) => d50a     aad
```

this is imho an improvement, not a regression, but next to it there's already a regression. this instruction is no longer disassembled properly:


```
cs-master (x86-32) 6200 => "bound eax, qword [eax]"
cs-next (x86-32) 6200 => "invalid"
```

**Comment by aquynh** [comment]
that SUB is a mistake. i just pushed a fix for that.

on BOUND instruction, LLVM does not recognize this. i will patch it, and update X86 in few days.

**Comment by aquynh** [comment]
i looked at those "XX]", but cant really get what is relevant with Capstone.

**Comment by aquynh** [comment]
fixed the BOUND instruction now.

```
$ cstool x32 6200
 0  62 00           bound	eax, qword ptr [eax]
```

**Comment by aquynh** [comment]
to make it easier to confirm this kind of issue, now `cstool` prints out the instruction ID & instruction name, like below.

```
$ cstool -d x32 6200    
 0  62 00                                            bound	eax, qword ptr [eax]
	ID: 53 (bound)
	Prefix:0x00 0x00 0x00 0x00 
	Opcode:0x62 0x00 0x00 0x00 
	rex: 0x0
	addr_size: 4
	modrm: 0x0
	disp: 0x0
	sib: 0x0
	op_count: 2
		operands[0].type: REG = eax
		operands[0].size: 4
		operands[0].access: WRITE
		operands[1].type: MEM
			operands[1].mem.base: REG = eax
		operands[1].size: 8
		operands[1].access: READ
	Registers read: eax
	Registers modified: eax
	Groups: not64bitmode 
```

**Comment by radare** [comment]
Now there are 78 broken tests (before 83).

Sumarizing ARM/THUMB/ARM64 failures:

* [ ] The BIC instruction for arm-thumb also have wrong id (07d0cde3       bic sp, sp, 7 )
* [ ] same with LSL instruction on arm32 with bytes 3102a0e1
* [ ] Same with mvn 6ff01201 (arm-thumb)
* [ ] same with cmp..

I see several other instructions having the ID field wrong. and thats why most of those tests are failing. can you review the ARM instruction ids? (thumb, arm and arm64), because there seems to be many of them wrong.

On x86 there are 2 more wrong disassemblies (or inconsistent from what we have in cs4), at least that the r2 testsuite is able to catch:

* [ ] The 96 opcode swaps the arguments (xchg eax, esi vs xchg esi, eax)
* [ ] d15e48         rcr dword [esi + 0x48], 1 ->rcr dword [esi + 0x48]  # note teh missing '1'
* [ ] BIC instruction 07d0cde3 have wrrong ID too

**Comment by radare** [comment]
you can press the checkboxes when fixed, so we can track the sub-items in this issue

**Comment by aquynh** [comment]
the issue of ARM instruction ID should be fixed now

**Comment by aquynh** [comment]
RCR of X86 will be fixed in few days

**Comment by aquynh** [comment]
the RCR issue of X86 is fixed now: https://github.com/aquynh/capstone/commit/a16c74a14bea6f1d8fff5f8104e1ad5a6fd22012

**Comment by aquynh** [comment]
the RCR issue of X86 is fixed now: https://github.com/aquynh/capstone/commit/a16c74a14bea6f1d8fff5f8104e1ad5a6fd22012

**Comment by aquynh** [comment]
the RCR issue of X86 is fixed now: https://github.com/aquynh/capstone/commit/a16c74a14bea6f1d8fff5f8104e1ad5a6fd22012

**Comment by aquynh** [comment]
i fixed few more AArch64 instruction ID.

**Comment by radare** [comment]
Yay, our testsuite is green, but there are still some small code glitches to fix. Let me say:

is this expected?

```
#if CS_API_MAJOR > 4
        case X86_INS_PFADD:
#else
        case X86_INS_FADDP:
#endif
```

* UD2B is gone (onlny UD2 is available)

**Comment by radare** [comment]
Seems like travis lied to me, there are still 16 broken tests:

* ATT syntax doesnt replace small hex numbers into dec (  b8 00 00 00 00     movl	$0x0, %eax) (in cs4 its mov $0, %eax)
* on arm64 (0c008012) iss mov w12, -1, but the instruction information is wrong (32)

```
    "opex": {
      "operands": [
        {
          "type": "reg",
          "value": "w12"
        },
        {
          "type": "imm",
          "value": 32
        }
      ]
    },
```

Ive seen the other failing tests are also related to wrong instruction information (imm issues mainly)

**Comment by aquynh** [comment]
fixed the MOV instruction:

```
$ cstool x32att "b8 00 00 00 00"
 0  b8 00 00 00 00                                   movl	$0, %eax
```

**Comment by aquynh** [comment]
fixed the MOV instruction of ARM64

**Comment by aquynh** [comment]
> Yay, our testsuite is green, but there are still some small code glitches to fix. Let me say:
> 
> is this expected?
> 
> ```
> #if CS_API_MAJOR > 4
>         case X86_INS_PFADD:
> #else
>         case X86_INS_FADDP:
> #endif
> ```

yes.

> * UD2B is gone (onlny UD2 is available)

yes UD2 is the former UD2B

**Comment by radare** [comment]
we got several regressions switching from 15 to 66 broken tests (all of them on ARM), here's one of them, which i guess is also affecting many others:

The bytes a200871e0 in ARM is disassembled as `add r0, r1, r2, lsr 1`

this is (afaik) r0=(r1+(r2>>1))

the problem is that cs5 is making this shift to be applied to both args like this: r0=(r1>>1) + (r2>>1)

here's the proof using cstool
```
$ ./cstool -d arm a20081e0
 0  a2 00 81 e0  add	r0, r1, r2, lsr #1
	ID: 2 (add)
	op_count: 3
		operands[0].type: REG = r0
		operands[0].access: WRITE
		operands[1].type: REG = r1
		operands[1].access: READ
			Shift: 3 = 1
		operands[2].type: REG = r2
		operands[2].access: READ
			Shift: 3 = 1
	Registers read: r1 r2
	Registers modified: r0
	Groups: arm
```

**Comment by aquynh** [comment]
fixed now.

```
$ cstool -d arm a20081e0
 0  a2 00 81 e0  add	r0, r1, r2, lsr #1
	ID: 2 (add)
	op_count: 3
		operands[0].type: REG = r0
		operands[0].access: WRITE
		operands[1].type: REG = r1
		operands[1].access: READ
		operands[2].type: REG = r2
		operands[2].access: READ
			Shift: 3 = 1
	Registers read: r1 r2
	Registers modified: r0
	Groups: arm 
```

**Comment by radare** [comment]
Uhm, that only solved 1 issue. This is another one:

```
3102a0e1 in arm32
```

cstool only shows 2 regs, not 3
```
$ ./cstool -d arm 3102a0e1
 0  31 02 a0 e1  lsr	r0, r1, r2
	ID: 99 (lsr)
	op_count: 2
		operands[0].type: REG = r0
		operands[0].access: WRITE
		operands[1].type: REG = r1
		operands[1].access: READ
	Registers read: r1
	Registers modified: r0
	Groups: arm
```
this can be confirmed in r2's opex

cs4:
```
    "opex": {
      "operands": [
        {
          "type": "reg",
          "value": "r0"
        },
        {
          "type": "reg",
          "value": "r1"
        },
        {
          "type": "reg",
          "value": "r2"
        }
      ]
    },
```

cs5:
```
    "opex": {
      "operands": [
        {
          "type": "reg",
          "value": "r0"
        },
        {
          "type": "reg",
          "value": "r1"
        }
      ]
    },
```

**Comment by radare** [comment]
I think that it will be good if capstone could have this checks in the testsuite, this is: generate a kv database with HEXPAIRS where key is the hexpairs of the mnemonic and the value the opex representation (what your cstool prints, but in one line for simplicity). then just run this in cs4, and run it again in cs5 and you'll see all those regressions.

I'm spending more time analyzing the rest of issues and many of them are similar problems but in different instructions, and im pretty sure im not covering all of them. And i think that will benefit the whole stability of capstone.

**Comment by radare** [comment]
Meanwhile more regressions:

* [ ] ff18 before it was lcall and now its call (confirm if its on purpose)
* [ ] d40a aam have the same change as "aad" (numeric argument)

Current broken archs according to the r2 testsuite: x86, arm, thumb, arm64

The improvements in cs5 ive observed:

* Consistency with 0 vs 0x0
* aam/aad honor the argument
* xchg swap args properly

i will see when all the emulation tests pass how to get my suite to work with those inconsistencies between cs4/cs5 (0 vs 0x..., xchg) because my testsuite runs in cs4 and cs5 (and some distros use it to run on cs3)

**Comment by aquynh** [comment]
fixed that LSR instruction:

```
$ cstool -d arm 3102a0e1
 0  31 02 a0 e1  lsr	r0, r1, r2
	ID: 99 (lsr)
	op_count: 3
		operands[0].type: REG = r0
		operands[0].access: WRITE
		operands[1].type: REG = r1
		operands[1].access: READ
		operands[2].type: REG = r2
		operands[2].access: READ
	Registers read: r1 r2
	Registers modified: r0
	Groups: arm 
```

**Comment by aquynh** [comment]
that change on ff18 is correct.

**Comment by aquynh** [comment]
the change on AAM & AAD is also right

**Comment by aquynh** [comment]
what else is broken now?

**Comment by radare** [comment]
Now there are 63 XX

Some more random issues:

* [ ] arm64 ac416f2a  orn (with wrong id "MVN")
* [ ] arm64 6b010152 eor vs eon
* [ ] arm64 28ad0a9b msub vs mneg

**Comment by aquynh** [comment]
fixed these, and few others. keep them coming.

i am reviewing ARM64 instruction mapping at the same time.

**Comment by radare** [comment]
Another one, and ill wait for travis to finish another run

* [ ] arm32 04109de4 in cs4 was "pop r1", in cs5 it's "ldr r1, [sp], 4" wtf

**Comment by aquynh** [comment]
Semantically they are the same, so not really a bug here

**Comment by aquynh** [comment]
it is debatable that we should do this alias, but to be consistent with CS4, i did it anyway.

```
$ cstool -d arm 04109de4
 0  04 10 9d e4  pop	{r1}
	ID: 127 (pop)
	op_count: 1
		operands[0].type: REG = r1
		operands[0].access: WRITE
	Write-back: True
	Registers read: sp
	Registers modified: sp r1
	Groups: arm 
```

**Comment by radare** [comment]
Yay last commit is just 5 XX. Good work!

* [ ] arm64 15008052    movz -> mov http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0802a/MOVZ.html
* [ ] arm64 ed1f0032    orr => ID (mov)
* [ ] arm64 68 05 7b b3    bfi => ID (bfm)
* [ ] arm64 68 0d 40 b3 bfxil => ID(bfm)
* [ ] arm64 ea7bbd52 movz -> mov ID (mov) - this instruction is movz, not mov

**Comment by aquynh** [comment]
fixed the ID issues of ORR, BFI & BFXIL.

```
$ cstool -d arm64 ed1f003268057bb3680d40b3
 0  ed 1f 00 32  orr	w13, wzr, #0xff
	ID: 515 (orr)
	op_count: 3
		operands[0].type: REG = w13
		operands[0].access: WRITE
		operands[1].type: REG = wzr
		operands[1].access: READ
		operands[2].type: IMM = 0xff
		operands[2].access: READ
	Registers read: wzr
	Registers modified: w13

 4  68 05 7b b3  bfi	x8, x11, #5, #2
	ID: 944 (bfi)
	op_count: 4
		operands[0].type: REG = x8
		operands[0].access: READ | WRITE
		operands[1].type: REG = x11
		operands[1].access: READ
		operands[2].type: IMM = 0x5
		operands[2].access: READ
		operands[3].type: IMM = 0x2
		operands[3].access: READ
	Registers read: x8 x11
	Registers modified: x8

 8  68 0d 40 b3  bfxil	x8, x11, #0, #4
	ID: 945 (bfxil)
	op_count: 4
		operands[0].type: REG = x8
		operands[0].access: READ | WRITE
		operands[1].type: REG = x11
		operands[1].access: READ
		operands[2].type: IMM = 0x0
		operands[2].access: READ
		operands[3].type: IMM = 0x4
		operands[3].access: READ
	Registers read: x8 x11
	Registers modified: x8
```

**Comment by aquynh** [comment]
MOVZ of Arm64 is alias of MOV. if you look at the semantics, they are the same, so 15008052 & ea7bbd52 are not really issue.

**Comment by radare** [comment]
now we have back to 60 XX. i fixed a bug in my arm.cs plugin (i was using the V8 flag when it was not suposed to be used) those are some other of the issues im observing:

```
XX] db/asm/arm_16 arm,16: caea2106 => "pkhtb r6, sl, r1, asr 0x20" (disassemble)
$ r2
-pkhtb r6, sl, r1, asr 0x20
+pkhtb r6, sl, r1
[XX] db/asm/arm_16 arm,16: c3ea2503 => "pkhtb r3, r3, r5, asr 0x20" (disassemble)
$ r2
-pkhtb r3, r3, r5, asr 0x20
+pkhtb r3, r3, r5
```

* [ ] aff30480 thumb wfe.w -> wfe.ww (same for yield.w -> yield.ww) and wfi
this is missing asr/shfit argument for the pkhtb instruction

**Comment by radare** [comment]
this arm64 mov immediate doenst looks correct

```
  {
    "opcode": "mov w10, -0x14210000",
    "disasm": "mov w10, -0x14210000",
    "mnemonic": "mov",
    "esil": "32,w10,=",
    "sign": false,
    "prefix": 0,
    "id": 488,
    "opex": {
      "operands": [
        {
          "type": "reg",
          "value": "w10"
        },
        {
          "type": "imm",
          "value": 32
        }
      ]
    },
```

**Comment by radare** [comment]
Actually the bad use of the V8 was not in my side. i have reverted the change. V8 is susposed to be used with ARM or THUMB, and some instructions are now being "invalid" when disassembled with this mode:

those were working in capstone4

```
$ ./cstool/cstool thumbv8 5cecc946
ERROR: invalid assembly code
$ ./cstool/cstool thumb 5cecc946
 0  5c ec c9 46  mrrc	p6, #0xc, r4, ip, c9
```

can you confirm if this is a regression or expected behaviour?

**Comment by aquynh** [comment]
> this arm64 mov immediate doenst looks correct
> 
> ```
>   {
>     "opcode": "mov w10, -0x14210000",
>     "disasm": "mov w10, -0x14210000",
>     "mnemonic": "mov",
>     "esil": "32,w10,=",
>     "sign": false,
>     "prefix": 0,
>     "id": 488,
>     "opex": {
>       "operands": [
>         {
>           "type": "reg",
>           "value": "w10"
>         },
>         {
>           "type": "imm",
>           "value": 32
>         }
>       ]
>     },
> ```

fixed now.

**Comment by radare** [comment]
```
bytes: 660f3810c0
cs4-pblendvb xmm0, xmm0
cs5+pblendvb xmm0, xmm0, xmm0 <- a new argument!
```

* [ ] What is EIZ? 

in cs4 this was `lea esi, [esi]`
```
$ cstool/cstool x32 8db42600000000
 0  8d b4 26 00 00 00 00                             lea	esi, [esi + eiz]
pancakes-MBP:capstone pancake$ cstool/cstool -d x32 8db42600000000
 0  8d b4 26 00 00 00 00                             lea	esi, [esi + eiz]
	ID: 332 (lea)
	Prefix:0x00 0x00 0x00 0x00
	Opcode:0x8d 0x00 0x00 0x00
	rex: 0x0
	addr_size: 4
	modrm: 0xb4
	disp: 0x0
	sib: 0x26
		sib_base: esi
		sib_scale: 1
	op_count: 2
		operands[0].type: REG = esi
		operands[0].size: 4
		operands[0].access: WRITE
		operands[1].type: MEM
			operands[1].mem.base: REG = esi
			operands[1].mem.index: REG = eiz
		operands[1].size: 4
		operands[1].access: READ
	Registers read: esi eiz
	Registers modified: esi
	Groups: not64bitmode
```

another x86-32
```
660f2f00 => "comisd xmm0, xmmword [eax]"[34m (disassemble)[33m[39m  

$ r2 
[35m-comisd xmm0, xmmword [eax][39m
[35m[39m[32m+comisd xmm0, qword [eax][39m
```


* [ ] another spurious repne

```
x86-32 f20f1100 
$ r2 
-movsd qword [eax], xmm0[39m
+repne movsd qword [eax], xmm0[39m
```

**Comment by aquynh** [comment]
hmm is REPNE valid for MOVSD?

**Comment by aquynh** [comment]
pushed a commit to remove EIZ register

**Comment by aquynh** [comment]
fixed those alias with .w

```
$ cstool thumb aff30480
 0  af f3 04 80  sev.w	
```

**Comment by aquynh** [comment]
i think `660f3810c0 = pblendvb xmm0, xmm0, xmm0` is correct

**Comment by aquynh** [comment]
fixed `pkhtb`

```
$ cstool thumb caea2106
 0  ca ea 21 06  pkhtb	r6, sl, r1, asr #0x20
```

**Comment by aquynh** [comment]
what is the output of other disassemblers for `660f2f00`?

GDB seems to get the same output as Capstone.

**Comment by aquynh** [comment]
> Actually the bad use of the V8 was not in my side. i have reverted the change. V8 is susposed to be used with ARM or THUMB, and some instructions are now being "invalid" when disassembled with this mode:
> 
> those were working in capstone4
> 
> ```
> $ ./cstool/cstool thumbv8 5cecc946
> ERROR: invalid assembly code
> $ ./cstool/cstool thumb 5cecc946
>  0  5c ec c9 46  mrrc	p6, #0xc, r4, ip, c9
> ```
> can you confirm if this is a regression or expected behaviour?

LLVM seems to flag this as incorrect encoding for Thumbv8, so i think this is right.

**Comment by aquynh** [comment]
according to http://faydoc.tripod.com/cpu/movsd.htm, MOVSD + REPNE is valid, so Capstone v4 is wrong, and we are right with v5.

**Comment by aquynh** [comment]
i fixed everything you reported, except X32 `660f2f00`.

**Comment by radare** [comment]
dont think so

**Comment by radare** [comment]
thanks for all those quick fixes, i'll run again, and let you know again, i'll mark all those bugs in cs4 in the testuite

**Comment by aquynh** [comment]
Since X32 `660f2f00` says Qword, it is not wrong on the size. Even better, it is compatible with Gdb output, so we can keep it that way, and dont need to "fix" it.

**Comment by aquynh** [comment]
fixed the xmmword issue.

```
$ cstool -d x32 660f2f00
 0  66 0f 2f 00                                      comisd	xmm0, xmmword ptr [eax]
	ID: 116 (comisd)
	Prefix:0x00 0x00 0x66 0x00 
	Opcode:0x2f 0x00 0x00 0x00 
	rex: 0x0
	addr_size: 4
	modrm: 0x0
	disp: 0x0
	sib: 0x0
	op_count: 2
		operands[0].type: REG = xmm0
		operands[0].size: 16
		operands[0].access: READ
		operands[1].type: MEM
			operands[1].mem.base: REG = eax
		operands[1].size: 16
		operands[1].access: READ
	Registers read: xmm0 eax
	Registers modified: eflags
	EFLAGS: MOD_CF MOD_ZF MOD_PF RESET_OF RESET_SF RESET_AF
	Groups: sse2 
```

**Comment by aquynh** [comment]
> dont think so

let me know if you can confirm that `REPNE MOVSD` is invalid.

**Comment by radare** [comment]
according to this yes, its valid, didnt tested on real hardware, but i guess cs4 was wrong in here too

http://faydoc.tripod.com/cpu/movsd.htm <http://faydoc.tripod.com/cpu/movsd.htm>

**Comment by radare** [comment]
The x86 tests look good to me (cs4 had some bugs that are fixed in this branch +1). but for thumb+v8:

Thumb v8
=======

* [ ] 96ed1d83  "ldc p3, c8, [r6, 0x74]"
* [ ] eaee1193 "mcr p3, 7, sb, c10, c1, 0" 
* [ ] 49ecea6c => "mcrr p12, 0xe, r6, sb, c10"
* [ ] 73ee1d9c => "mrc p12, 3, sb, c3, c13, 0" (
* [ ] 5cecc946 => "mrrc p6, 0xc, r4, ip, c9"
* [ ] 88ed9586 => "stc p6, c8, [r8, 0x254]"
* [ ] 88ed9586 => "stc p6, c8, [r8, 0x254]" 
* [ ] 69ec1723 => "stcl p3, c2, [sb], -0x5c"

I have checked the documentation and they should be available in the aarch32 profile of the armv8 cpu, those are disassembled properly in cs4, but not in ics5, can you take a look at this?

the way to test is:

```
$ ./cstool thumbv8 69ec1723
ERROR: invalid assembly code
$ ./cstool thumb 69ec1723
 0  69 ec 17 23  stcl	p3, c2, [sb], #-0x5c
$
```

**Comment by radare** [comment]
Maybe you are right and this is not valid thumbv8

https://github.com/gcc-mirror/gcc/blob/master/gcc/testsuite/gcc.target/arm/acle/stcl.c

**Comment by radare** [comment]
Apart from that thumb-v8 issues (which i can "solve" by making the r2 plugin not use the v8 bit)

The other issue that i have is relateed to the esil thumb/ARM emulation, but i didnt identified why changing capstone broke this. i 'll investigate on this. after those '2' fixes i'll merge cs5 in r2. And add risc.cs support

**Comment by radare** [comment]
Ok, finally got some spare time to review all those instructions.

Those are priviledged instructions because they are accessing coprocessors. the armv8 standard specifies that there's no need to fully support armv7 in the arch32 mode, so i assume manufacturers remove random instructions here and there to make the 32bit core of the armv8 cpus simpler.

Those are valid instructions on thumb firmwares, i have a bunch of real samples with those. so i assume i should just not assuming v8 cpu by default when disassembling thumb code.

Other fun facts:

* GNU disassembler consider those instructions to be related to the FPU
* GHIDRA say this is invalid, even for pre-v8 cpu modes :(

I'll fix that and look into the arm/thumb regression that is happening. and update my PR and see what happens. ill try to merge capstone5 support before the end of this week

**Comment by radare** [comment]
Yay! found the reason of the emulation regression, and its because someone was hardcoding the capstone constants which changed in cs5 (they were the same in cs3 and cs4). so now its more solid. and shouldnt break again if ids change.

So. tonight i will update all the x86 tests and do not enforce v8 for thumb by default. so the user will be able to set cortex or v8 if they want. and that will be done from RBin depending on the binary loaded.

Thanks!!

**Comment by radare** [comment]
Oops. i have fixed the v8 and emulation bugs in r2, and after rebasing im having 58 XX :/ 

by examining them ive observed the following regressions that should be fixed in capstone:

* [ ] 0f2300  mov dr0, eax => invalid
* [ ] 0f2200 mov cr0, eax => invalid
* [ ] 0f2100 mov eax, dr0 => invalid
* [ ] f70800000000 test dword [eax], 0" => invalid
* [ ] f60800 test byte [eax], 0 => invalid

i have verified the instructions are valid with udis86, cs3, cs4, ghidra and binutils

```
$ ./cstool x32 f60800
ERROR: invalid assembly code
$ rasm2 -d f60800
test byte [eax], 0
$
```

**Comment by aquynh** [comment]
So anything left unfixed now?

**Comment by radare** [comment]
Yes

**Comment by aquynh** [comment]
Can you put them all in 1 place?

**Comment by radare** [comment]
wat

**Comment by radare** [comment]
what do you mean by putting them all in one place?

its only this

 0f2300 mov dr0, eax� => invalid
  0f2200 mov cr0, eax => invalid
  0f2100 mov eax, dr0 => invalid
  f70800000000 test dword [eax], 0" => invalid
  f60800 test byte [eax], 0 => invalid

**Comment by aquynh** [comment]
these instructions requires updating tablegen, and takes sometime. i will do that by this weekend.

**Comment by radare** [comment]
thanks

**Comment by radare** [comment]
any updates?

**Comment by aquynh** [comment]
working on that.

**Comment by aquynh** [comment]
fixed now.

```
$ cstool x32 "0f2300 0f2200 0f2100 f70800000000 f60800"   
 0  0f 23 00                                         mov	dr0, eax
 3  0f 22 00                                         mov	cr0, eax
 6  0f 21 00                                         mov	eax, dr0
 9  f7 08 00 00 00 00                                test	dword ptr [eax], 0
 f  f6 08 00                                         test	byte ptr [eax], 0
```

**Comment by radare** [comment]
Thanks! all arm and x86 looks good now, but i've observed some ppc regressions.

Here's one:
```
$ ./cstool  -d ppc64be 4b000000
 0  4b 00 00 00  b	0x3000000
	ID: 15 (b)
	op_count: 1
		operands[0].type: IMM = 0x3000000
	Groups: jump
```

check this 0x300000 that appears from nowhere.

When do you plan to merge this branch into master? may be good to merge x86  and arm64, and keep this branch for testing and stabilizing the other updates.

**Comment by aquynh** [comment]
yes i am looking into those PPC issues.

i want to update 2 remaining architectures Mips & Sparc, before merging next into master.

**Comment by aquynh** [comment]
> Thanks! all arm and x86 looks good now, but i've observed some ppc regressions.
> 
> Here's one:
> 
> ```
> $ ./cstool  -d ppc64be 4b000000
>  0  4b 00 00 00  b	0x3000000
> 	ID: 15 (b)
> 	op_count: 1
> 		operands[0].type: IMM = 0x3000000
> 	Groups: jump
> ```
> 
> check this 0x300000 that appears from nowhere.
> 

is this correct now?

```
$ cstool  -d ppc64be 4b000000
 0  4b 00 00 00  b	0xffffffffff000000
	ID: 15 (b)
	op_count: 1
		operands[0].type: IMM = 0xffffffffff000000
	Groups: jump 
```

**Comment by radare** [comment]
Yes. This output looks consistent with capstone4.

I end up adding an option in r2-master to pick capstone5 instead of 4 or 3. I will update the tests when you finish the update on all the archs.

But all the tests right now look correct with the next branch. So i think we can close this issue for now. I wont be testing further changes in this branch until it gets merged back.

Thanks!

**Comment by radare** [comment]
Closing this issue as long as all the problems have been fixed already. What's left to release capstone5?

**Comment by DMaroo** [comment]
> > Yay, our testsuite is green, but there are still some small code glitches to fix. Let me say:
> > is this expected?
> > ```
> > #if CS_API_MAJOR > 4
> >         case X86_INS_PFADD:
> > #else
> >         case X86_INS_FADDP:
> > #endif
> > ```
> 
> yes.

@aquynh

I don't think this is true. The `X86_INS_PFADD` instruction is a part of the [3DNow!](https://en.wikipedia.org/wiki/3DNow!) ISA extension (`PFADD` = packed floating-point addition). Whereas, `X86_INS_FADDP` used to represent floating-point addition with a stack pop. In the Capstone instruction enum, you have entries for `FMULP`, `FSUBP`, `FDIVP` and so on for the rest of the arithmetic instruction families. Only `FADDP` seems to be missing. 

Moreover, when disassembling the bytes for a `FADDP` instruction, we get a `X86_INS_FADD` as the output, which is incorrect given that other arithmetic instruction of the same category are handled correctly. In any case, using `X86_INS_PFADD` in it's place is not correct.

I genuinely think this is a regression and `FADDP` should be added in the instructions enum. I would be happy to send a patch doing so.

**Comment by Rot127** [comment]
The problem is that it is not enough to just add it to the enum. The disassembler is a generated state machine which had to be updated as well.

But it is not possible to update it manually because the tables of the state machine have to be to be generated.
Since we have no x86 support in auto-sync currently (and probably won't, if no one wants to spend quite some time on it), this can't be done easily.

Also in the current LLVM definitions `FADD` is [defined as alias](https://github.com/llvm/llvm-project/blob/e2972389111e30a93a21cf8c5f4d2284cbb60268/llvm/lib/Target/X86/X86InstrAsmAlias.td#L389). While `PFADD` is [defined as actual instruction](https://github.com/llvm/llvm-project/blob/e2972389111e30a93a21cf8c5f4d2284cbb60268/llvm/lib/Target/X86/X86Instr3DNow.td#L59).

@DMaroo Could you check if `FADD` is really not defined as alias in the ISA? If it is, the current CS behavior is correct. If not, we would need to open an issue in LLVM.

**Comment by DMaroo** [comment]
Although `FADDP` and `FADD` are defined as aliases, there is a `FADD` instruction in the enum whereas there isn't an `FADDP` instruction. So is the case for `MUL` and `MULP`, which are also defined as aliases but have their own entries in the Capstone instruction enum. It's also quite surprising that `FMULP` has the same occurrences as `FADDP`, but one shows up in the enum and the other does not.

There is no concept of instruction aliasing in the x86 ISA reference (the only instruction alias mentioned in the reference is `NOP` and `XCG (E)AX (E)AX`, which is not relevant to this discussion).

As for modifying it, although it being a bad idea, we could modify the `.td` files. But I suppose that would be a bug in LLVM rather than Capstone. I believe that the `.td` files are correct. Maybe the Capstone code generation is missing the `FADDP` instruction due to some bug.

**Comment by Rot127** [comment]
> Although FADDP and FADD are defined as aliases, there is a FADD instruction in the enum whereas there isn't an FADDP instruction.

I can't say for sure, but this might be a prioritization issue. If an instruction has an alias, it is always used. Hence the "alias" of `FADDP` is always emitted before the actual `FADDP` instruction.

> As for modifying it, although it being a bad idea, we could modify the .td files. But I suppose that would be a bug in LLVM rather than Capstone

You can definitely open an issue on the LLVM repo. But either way, we currently can't fix this here easily.
You can try your luck with the [legacy sync tools](https://github.com/capstone-engine/capstone/tree/next/suite/synctools) to update x86. But I wouldn't spend too much time on it. It is way simpler to handle this exception in Rizin (I hope).
