### ISSUE TITLE
cs5 in master

### ISSUE THREAD

**Issue by radare** [aquynh/capstone#1460]
Sorry again, but i tried to rollback to master and find out master is defined as CS5.. so i have no way to make ifdefs to make my code work on cs4 and cs5,. also thi sis confusing because by grepping it seems like java still is considered cs4 and python reports version 5, which is not correct because it lacks lot of enums found in next, so its abi breaking

https://github.com/aquynh/capstone/blob/master/include/capstone/capstone.h#L50

**Comment by radare** [comment]
This was changed in f1fc51bd09dce0b139834bdddc1741524166d45b and 5c634289b45ce48b8a742b633ef8ea1aff08b468 is related

Also, i though this was suposed to be 4.0.2, but the patch that is switching to NEXT 5, is also changing the current version from 4.1 to 5.0, skipping out the 4.0.2 . so im confused again by this. im doing a hacky patch to rollback this commit.

**Comment by aquynh** [comment]
You should avoid master branch for now: for 4.x, use v4 branch instead.

**Comment by radare** [comment]
So summarizing:

* master = almost head (it's not clear to me when things from next got merged here?)
* next = head (active development happening only in this branch)
* v4 = ongoing development for the v4 branch, which will become 4.0.2 at some point (or 4.1)
* v3.. = keep head for each previous release

Can you confirm those v branches will not be removed? The v4 branch worked as expected for r2.

thanks

**Comment by aquynh** [comment]
master was merged with next by some mistakes, so everybody should ignore that for now.

"v3" = v3.0.x (but i dont plan to release any new version based on this)
"v4" is for maintenance release 4.0.x (next release is 4.0.2).
"next" is for development

i will merge next into master when we are ready for v5 alpha release.

yes, i will not remove any "v*" branch.
