### ISSUE TITLE
PowerPC: Wrong operand type of condition register manipulation instructions

### ISSUE THREAD

**Issue by ceeac** [aquynh/capstone#1469]
In the 'next' branch, the PPC condition register manipulation instructions (`crxor`, `crand`, `crandc` etc.) have PPC_OP_REG type operands. Example:
```bash
cstool -d ppc64be "\x4c\x02\x39\x82"
 0  4c 02 39 82  crxor	0, 2, 7
	ID: 225 (crclr)
	op_count: 3
		operands[0].type: REG = r0
		operands[1].type: REG = r2
		operands[2].type: REG = r7
```
These operand types should probably be PPC_OP_CRX or PPC_OP_IMM similar to #971.

**Comment by aquynh** [comment]
this output of LLVM is a bit confused. looks like it should be like this:

```
4c 02 39 82 = crxor	CR0LT, CR0EQ, CR1UN
```

is this correct?

**Comment by ceeac** [comment]
I think so, yes.

**Comment by aquynh** [comment]
fixed now in "next" branch. i think the output is better than "v4" now.

```
$ cstool -d ppc64be "\x4c\x02\x39\x82"       
 0  4c 02 39 82  crxor	cr0lt, cr0eq, cr1un
	ID: 234 (crxor)
	op_count: 3
		operands[0].type: REG = cr0lt
		operands[1].type: REG = cr0eq
		operands[2].type: REG = cr1un
```
