### ISSUE TITLE
Update Windows kernel-mode support for v4

### ISSUE THREAD

**Issue by tandasat** [aquynh/capstone#1474]
This is a placeholder ticket to drive discussion for this work.

**Comment by tandasat** [comment]
@aquynh what do you think about the below deprecation?

* Requires VS2017+ WDK10 instead of VS2010 + WDK8.1
VS2017 is 2 years old, and WDK10 is 4 years old. We cannot keep supporting old environment due to maintenance cost (ie, I do not have older versions than those), and devs using older tools should need to move to the newer ones for productivity and security reasons.

**Comment by aquynh** [comment]
How do you build this, with VS and on .sln file?

**Comment by tandasat** [comment]
The way to build the Capstone for Windows kernel will not change, ie, from Visual Studio.

**Comment by aquynh** [comment]
Can we also do this with cmake + cmdline?

We have nmake.bat for building on Windows now, and i prefer that to using
VS.

**Comment by tandasat** [comment]
It should be fine. Where is an instruction or document for that?

By the way, can you give me a link to the PR that removed myinttypes.h? It broke Windows kernel build. Not meant to restore but want to know what happened to it.

**Comment by aquynh** [comment]
on how to build with cmake/cmdline, see https://github.com/aquynh/capstone/blob/master/COMPILE_CMAKE.TXT

in short, run the following cmd from MSVC prompt:

```
mkdir build
cd build
..\nmake.bat
```

instead of building everything, if you just want to build only X86 architecture, do:

```
mkdir build
cd build
..\nmake.bat x86
```

**Comment by aquynh** [comment]
regarding myinttype.h, i think that was modified by you in the commit 3c49d92b9cda0881e3fb00af364b2556174bcc04?

otherwise, look at "git log", and search for platform.h can give some clues...

**Comment by tandasat** [comment]
@aquynh which branch do you want me to target for the PR? Is branch off from and target `v4` ok?

**Comment by aquynh** [comment]
Yes v4, please.

I believe that we can cherrypick for "next" branch later.

**Comment by tandasat** [comment]
I have created https://github.com/aquynh/capstone/issues/1484 for CMake support. Will close this as the primary change for support was merged.
