### ISSUE TITLE
vs2017 build version 4.0.1 error

### ISSUE THREAD

**Issue by taodaqiao** [aquynh/capstone#1583]
vs2017 15.9.19 
build  capstone_static_winkernel
\tms320c64x.h(11): fatal error C1083:  “stdint.h”: No such file or directory

build cstool
 error LNK2019:Unresolved external symbol print_insn_detail_evm，The symbol in the function print_details Referenced
2>E:\C library\capstone-4.0.1\msvc\x64\Debug\cstool.exe : fatal error LNK1120: 1 unresolved external command

**Comment by aquynh** [comment]
Can you try with "v4" branch?

**Comment by taodaqiao** [comment]
"v4" branch is ok, thanks

**Comment by smclinden** [comment]
I'm seeing this same issue with VS 2019 Community and on both V4 and Master.

LNK2001 unresolved external symbol print_insn_detail_mos65xx
LNK2001 unresolved external symbol print_insn_detail_evm
