### ISSUE TITLE
add python 3.8 support 

### ISSUE THREAD

**Issue by blshkv** [aquynh/capstone#1584]
https://github.com/aquynh/capstone/blob/master/bindings/python/setup.py#L228

It is probably as easy as simply adding a one single line into the setup.py

**Comment by aquynh** [comment]
pull req please.

**Comment by aquynh** [comment]
@rhelmot, i suppose that we can remove all the lines from https://github.com/aquynh/capstone/blob/master/bindings/python/setup.py#L225-L228, and just keep "Python 3"?

**Comment by rhelmot** [comment]
So far as I know these lines were added by you, not me, and have nothing to do with whether the package is compatible with a given version. The relevant field for that is `python_requires`. I was just able to install and run capstone in a python 3.8 interpreter, so like, this is purely for aesthetics and tagging.

**Comment by aquynh** [comment]
ok i removed all, just keep "Python 3", thanks.
