### ISSUE TITLE
armv8 aarch64 swpa instruction not decoded

### ISSUE THREAD

**Issue by RobertHenry6bev** [aquynh/capstone#1585]
The armv8 aarch64 swpa instruction (atomic swap) is not decoded by capstone. 

See http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0801g/rgc1476202879521.html

This instruction comes to us by invoking the /usr/bin/aarch64-linux-gnu-gcc-9 intrinsic __atomic_compare_exchange_n (I make no guarantee this is the right use of the intrinsic):
int success = __atomic_compare_exchange_n (&data[0], &expected, /*desired*/17, /*weak*/0, __ATOMIC_ACQUIRE, __ATOMIC_ACQUIRE);

gnu objdump reports:
   f8a08020        swpa    x0, x0, [x1]
but capstone reports (I think I initialize capstone correctly):
 0xf8a08020 .byte 0x20, 0x80, 0xa0, 0xf8

capstone's failure to disassemble this instruction means that qemu doesn't emulate it.

**Comment by aquynh** [comment]
Try with the "next" branch?

**Comment by RobertHenry6bev** [comment]
The "next" branch correctly decodes swpa. Now it seems that qemu still doesn't emulate it, but that's not this code's problem.  thank you!
