### ISSUE TITLE
New v4 release eta wen?

### ISSUE THREAD

**Issue by radare** [aquynh/capstone#1595]
Latest release was done > 1year ago (2019 Jan) f9c6a90489be7b3637ff1c7298e45efafe7cf1b9

There's a 4.0.2 commit in 0e531eefd9acf7bd337524d0b9f3ddeb15338eb0 but it have no tag, so this release never happened at all, in this whole year there have been 126 commits after 4.0.1 and, despite being old and WAY behind the v5 branch we all wanted to be released > 1 year ago it will be good to have a new release of the v4 branch.

I won't be bugging about the v5(next) branch release because i assume that won't happen in the next 5 years, but distros like Debian will appreciate having an update with all the bug fixes that happened in the v4 branch in the last year.

**Comment by XVilka** [comment]
Relevant https://github.com/aquynh/capstone/issues/1319#issuecomment-567882173
What about creating capstone GitHub organization? Like you did for https://github.com/unicorn-engine ? And add more maintainers? Some projects that rely on capstone can help with the maintenance @aquynh

**Comment by radare** [comment]
![https://media.giphy.com/media/11R5KYi6ZdP8Z2/source.gif](https://media.giphy.com/media/11R5KYi6ZdP8Z2/source.gif)

**Comment by aquynh** [comment]
will be next week, if not this week.

**Comment by XVilka** [comment]
It's less than 1 minute of work:
```
git tag
git push --tags
```

**Comment by aquynh** [comment]
Not just tag, there are other things to prepare.

**Comment by radare** [comment]
if you need some help on all those other things to prepare we are always ready to help

**Comment by radare** [comment]
Hello?

**Comment by radare** [comment]
Periodic release reminder

**Comment by ccarpenter04** [comment]
You know radare isn't the only one that's been sitting around patiently waiting. I'm a bit frustrated by the lack of communication as well.

**Comment by XVilka** [comment]
@aquynh so what about creating capstone GitHub organization? Like you did for https://github.com/unicorn-engine ? And add more maintainers? Some projects that rely on capstone can help with the maintenance.

**Comment by casasnovas** [comment]
@aquynh Any news about this? What's the state of the next branch too?  Thanks.

**Comment by XVilka** [comment]
One more reminder again.

**Comment by radare** [comment]
@aquynh we are all waiting for your answer

**Comment by aquynh** [comment]
it was out:  http://www.capstone-engine.org/Version-4.0.2

sorry for the super delay.
