### ISSUE TITLE
CS_ARCH_X86, disasm "monitor" instruction fail

### ISSUE THREAD

**Issue by baosj0** [aquynh/capstone#1683]
![image](https://user-images.githubusercontent.com/30098075/93180377-a29c4b00-f769-11ea-93a4-e3a5e89a5848.png)

![image](https://user-images.githubusercontent.com/30098075/93180406-b21b9400-f769-11ea-9cf4-aaeddfedca8b.png)

**Comment by baosj0** [comment]
//0F 01 FB                          mwaitx  rax, rcx, rbx
and this one fail too

**Comment by aquynh** [comment]
i tried this with the "next" branch, using cstool:

```
$ cstool x32 0f01fb0f01fa
 0  0f 01 fb                                         mwaitx
 3  0f 01 fa                                         monitorx
```

**Comment by baosj0** [comment]
> i tried this with the "next" branch, using cstool:
> 
> ```
> $ cstool x32 0f01fb0f01fa
>  0  0f 01 fb                                         mwaitx
>  3  0f 01 fa                                         monitorx
> ```

oh , i'm using release version 4.0.2. Seems I should use a newer version.
