### ISSUE TITLE
Invalid x86 instruction ID and garbage in the mnemonics string

### ISSUE THREAD

**Issue by joxeankoret** [aquynh/capstone#1728]
Hi!

I'm trying to use Capstone as a statically linked library in a Windows project. It turns out that the most basic examples do not properly work for some reason I don't understand. For example, if I disassemble "\x90" it returns in `insn[0].id` the value 0x1EE instead of 0x1E7, and `insn[0].mnemonic` returns the string `\xCD\xCD\xCD\xCD\xCD\xCD\xCD\xCDNOP\x90` (8 bytes of 0xCD, uninitialized stuff, and the proper string).

The only preprocessor directive I'm using is CAPSTONE_HAS_X86 in both the the statically linked library and the project where it's being used.

Any idea about what am I doing wrong?

**Comment by aquynh** [comment]
I am pretty sure something is wrong with your setup, somewhere. Maybe you
can verify on another clean machine?

Try to use the "next" branch, btw.

**Comment by joxeankoret** [comment]
I found the "bug": there were 2 different capstone directories for 2 different versions. So, the problem was me :) Thanks for the help Quynh!
