### ISSUE TITLE
oss-fuzz integration fail

### ISSUE THREAD

**Issue by vanhauser-thc** [aquynh/capstone#1738]
Hi!

the oss-fuzz integration fails for afl++ when test_corpus.py is called from the build script. This loads libcapstone.so.
The reason is that when building the python bindings afl++ instruments the libcapstone.so, wheras for honggfuzz and libfuzzer they do not as CFLAGS are dropped. as afl++ uses its own compiler and instrumentation is not affected by CFLAGS ... - this is the reason of the fail.

I think all that is needed is setting `export AFL_NOOPT=1`
in the middle when this is happening:
```
+ cd /src/capstonev4/bindings/python
+ sed -i -e s/#print/print/ capstone/__init__.py
+ export CFLAGS=
+ CFLAGS=
+ python setup.py install
```

**Comment by aquynh** [comment]
please pull req.

**Comment by vanhauser-thc** [comment]
I can fix it in the oss-fuzz capstone build.sh script. will do it there.
