### ISSUE TITLE
How to group together registers?

### ISSUE THREAD

**Issue by NickTsl** [aquynh/capstone#1755]
I'm writing a IDA python script to remove junk code, by keeping track of register modifications. The problem is, different registers are treated as individual registers in capstone. For example, CX is seen as a different register from ECX.

Consider the following example: 
```
mov cx, 5
mov ecx, 500
```

the first line would obviously be considered junkcode, however I have no easy or clean way of determining that it is a junk write, because ecx and cx are treated as individual, seperate registers with different IDs. Is there an easy way of knowing that CX is the same register as ECX?

**Comment by keenk** [comment]
Unfortunately I think you'll have to write your own sub-register to register mapping. Would be nice if Capstone kept track of this, but as far as I know it does not.

**Comment by NickTsl** [comment]
```RegisterGroups = [
    [X86_REG_AH, X86_REG_AL, X86_REG_AX, X86_REG_EAX, X86_REG_RAX],
    [X86_REG_BH, X86_REG_BL, X86_REG_BX, X86_REG_EBX, X86_REG_RBX],
    [X86_REG_CH, X86_REG_CL, X86_REG_CX, X86_REG_ECX, X86_REG_RCX],
    [X86_REG_DH, X86_REG_DL, X86_REG_DX, X86_REG_EDX, X86_REG_RDX],
    [X86_REG_R8, X86_REG_R8D, X86_REG_R8W, X86_REG_R8B],
    [X86_REG_R9, X86_REG_R9D, X86_REG_R9W, X86_REG_R9B],
    [X86_REG_R10, X86_REG_R10D, X86_REG_R10W, X86_REG_R10B],
    [X86_REG_R11, X86_REG_R11D, X86_REG_R11W, X86_REG_R11B],
    [X86_REG_R12, X86_REG_R12D, X86_REG_R12W, X86_REG_R12B],
    [X86_REG_R13, X86_REG_R13D, X86_REG_R13W, X86_REG_R13B],
    [X86_REG_R14, X86_REG_R14D, X86_REG_R14W, X86_REG_R14B],
    [X86_REG_R15, X86_REG_R15D, X86_REG_R15W, X86_REG_R15B],
    [X86_REG_DIL, X86_REG_DI, X86_REG_EDI, X86_REG_RDI],
    [X86_REG_SIL, X86_REG_SI, X86_REG_ESI, X86_REG_RSI],
]```


💪
