### ISSUE TITLE
Adding headers to SOURCES in CMakeLists.txt

### ISSUE THREAD

**Issue by yegord** [aquynh/capstone#180]
Headers should be included into the SOURCES in CMakeLists.txt. Otherwise, they will not be shown in the MSVC project generated by CMake, which is probably not very good. (Taken from PR179 discussion.)

**Comment by learn-more** [comment]
This should be solved with my commits from the 3.0 branch

**Comment by aquynh** [comment]
yes, this should be closed now. thanks.
