### ISSUE TITLE
cs_insn mnemonic isn't 0'd before use. 

### ISSUE THREAD

**Issue by ConnorRigby** [aquynh/capstone#1971]
First of all, this is a very cool project, i've enjoyed using it a lot!

I'd accept this as a non-issue, just something i ran into while integrating `capstone`.

```c
total_size = sizeof(cs_insn) * cache_size;
total = cs_mem_malloc(total_size);
if (total == NULL) {
	// insufficient memory
	handle->errnum = CS_ERR_MEM;
	return 0;
}
```

This `total` value gets used without being zeroed or anything, meaning that it might not be printable. One easy fix is 

```c
	total_size = sizeof(cs_insn) * cache_size;
	total = cs_mem_calloc(sizeof(cs_insn), cache_size);
	if (total == NULL) {
		// insufficient memory
		handle->errnum = CS_ERR_MEM;
		return 0;
	}
```

which solved the problem for me. Let me know if more information is needed, i'll admit this is my first day using Capstone, so it's possible i'm missing something as to why this isn't needed.

**Comment by aquynh** [comment]
What is wrong with "total" not being zero out?

**Comment by ConnorRigby** [comment]
![image](https://user-images.githubusercontent.com/21150830/224121127-5d92961d-7e45-46a8-9cc9-cc3aa74c5d66.png)

The `fill_insn()` function writes directly into the memory allocated by this function without sanitizing it. This seems to lead to to artifacts in the malloced arrays. I Can share the code for this if it helps. It's not particularly notable or interesting. I copied the example from the readme

**Comment by trufae** [comment]
I submitted similar prs in the past but at least at the time calloc was considered slow and it was prefered to initialize every field if needed instead. Imho that's tedious and barely optimal or maintainable. And memset will always be faster than filling fields one by one. And in any case if its about speed there are better places to look at for optimizing

**Comment by ZehMatt** [comment]
> I submitted similar prs in the past but at least at the time calloc was considered slow and it was prefered to initialize every field if needed instead. Imho that's tedious and barely optimal or maintainable. And memset will always be faster than filling fields one by one. And in any case if its about speed there are better places to look at for optimizing

If performance is a concern the primary objective should be to avoid allocations at all cost, this is the wrong way to go about performance.
