### ISSUE TITLE
Capstone crashed for some ARM instructions

### ISSUE THREAD

**Issue by 1Husin-Alhaj** [aquynh/capstone#1983]
When Capstone encounters with these instruction, it throws and exception. The instrcutions are:
arithmetic instruction (addeq)
Store instruction (strcs)
Mov instruction (moveq, movteq)

**Comment by Rot127** [comment]
This will likely be fixed with https://github.com/capstone-engine/capstone/pull/1949
Could you nonetheless post the instructions bytes here please? I'd like to add them as test.

**Comment by Rot127** [comment]
Never mind. There are already plenty of tests for those instructions.
