### ISSUE TITLE
Deprecated modules

### ISSUE THREAD

**Issue by pcotret** [aquynh/capstone#2005]
## `pkg_resources`
https://github.com/capstone-engine/capstone/blob/master/bindings/python/capstone/__init__.py#L269
https://discuss.python.org/t/deprecating-importlib-resources-legacy-api/11386

`pkg_resources` seems to be deprecated from Python 3.9.

## `distutils`
https://peps.python.org/pep-0632/

`distutils` is deprecated since Python 3.10 and no longer installed in Python 3.12 (https://docs.python.org/3.12/whatsnew/3.12.html).

For instance, it's used in Python bindings:
https://github.com/capstone-engine/capstone/blob/next/bindings/python/capstone/__init__.py#L346

## Discussion
Should we just put a warning somewhere like "works with Python x.xx" or maybe thinking about an alternative for these modules?

**Comment by kabeor** [comment]
This will be fix before we release v5.0.

**Comment by peace-maker** [comment]
@kabeor What's the path forward for Capstone 5.0? Migrate away from the deprecated libraries? I'd like to help with this if it's the only thing left blocking a release.

**Comment by kabeor** [comment]
@peace-maker Yes, this issue is the only left thing I believe:)

**Comment by peace-maker** [comment]
What's the minimum python version you want to support?

**Comment by XVilka** [comment]
@peace-maker according to https://github.com/capstone-engine/capstone/issues/1993#issuecomment-1519712226 they plan to support Python 2.7 as the lowest version. As for Python 3, see https://endoflife.date/python - looks like it's either 3.7 (EOL in 2 weeks), or 3.8

**Comment by Rot127** [comment]
Closed by https://github.com/capstone-engine/capstone/pull/2400
