### ISSUE TITLE
ARM Thumb: MSR instruction not recognized

### ISSUE THREAD

**Issue by rchtsang** [aquynh/capstone#2014]
Capstone Version 4.0.2 (installed from pip)
Mac M1 Pro (macOS Ventura 13.3)

```python
>>> from capstone import *
>>> from capstone.arm_const import *
>>> cs = Cs(CS_ARCH_ARM, CS_MODE_THUMB)
>>> cs.detail = 1
>>> insn = next(cs.disasm(b'\x82\xf3\x08\x88', 4))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
StopIteration
```

Expected `msr   msp, r2`

**Comment by rchtsang** [comment]
just checked, this also happens in v5.0.0-rc2

**Comment by Rot127** [comment]
This is going to be fixed with https://github.com/capstone-engine/capstone/pull/1949

Here is the result:
```
./cstool cortexm "\x82\xf3\x08\x88"
 0  82 f3 08 88  msr	msp, r2
```

Note that you need to enable the correct flags (`CS_MODE_THUMB | CS_MODE_MCLASS` = `cortexm`). Especially the update I mentioned above will be way more strict with these.

**Comment by rchtsang** [comment]
fantastic! thank you so much!

any idea when that PR is going to be merged and released? 
I'm fine with working directly with that PR for now, but I am submitting my work to a conference and if readers need to work with a particular PR, it'll hurt reproducibility.

**Comment by Rot127** [comment]
Can't try it currently myself. But have you checked if it works with the `next` branch when you add the `CS_MODE_THUMB | CS_MODE_MCLASS` flags?

>
> any idea when that PR is going to be merged and released?

Merging depends on @kabeor and @aquynh and when they find the time to review it.

Release will not be before July.

9 may 2023 20:25:42 Ryan Tsang ***@***.***>:

**Comment by rchtsang** [comment]
🤦 ugh i'm dumb. yeah that worked. 

gotcha, thank you, looking forward to it!
