### ISSUE TITLE
macOS universal build seems broken in v5/next

### ISSUE THREAD

**Issue by gdbinit** [aquynh/capstone#2020]
The `mac-universal` option to `make.sh` seems broken in the v5 and next branches when trying to build x86_64 and arm64 (Apple Silicon) universal binary.

First `LIBARCHS` in `Makefile` only contains a `x86_64` target arch and lacks `arm64` target there. This is also the required fix to build universal binary in the v4 branch.

The automatic dependencies feature introduced in the v5/next branch also breaks the universal build. To fix it the `functions.mk` needs to be edited and the first line from compile function removed or commented out to disable the automatic dependencies.

With these two fixes the `mac-universal` option will build working x86_64 and arm64 universal binary, both static and dynamic if so configured.

What is the best way to fix this in the Capstone project? Add a check in `functions.mk` or somewhere else that disables the automatic dependencies for universal builds or is this something critical that the project depends on? This was the way other projects seem to be solving this issue as far as I could find.

The `LIBARCHS` fix seems pretty easy unless I'm failing to see any other impact or dependencies on this.

**Comment by kabeor** [comment]
It will be nice if you'd like to create a PR:)

**Comment by gdbinit** [comment]
https://github.com/capstone-engine/capstone/pull/2024
