### ISSUE TITLE
cstool has dependency in static library but there is logical inconsistency in options

### ISSUE THREAD

**Issue by gdbinit** [aquynh/capstone#2025]
If `CAPSTONE_STATIC=NO` is passed to `make.sh` the build will fail because `cstool` has dependency on `libcapstone.a` static library.

The only check made is when `CAPSTONE_BUILD_CORE_ONLY` is used for macOS kernel version and kind of is internal option only (not referred in documentation).

Does it make it sense to put a fix for this to not build `cstool` if `CAPSTONE_STATIC=NO` is set or is it just an implicit assumption and not relevant?

**Comment by XVilka** [comment]
@Rot127 what do you think on this one. I personally think cstool should be independent of the type of the library it built with - static or dynamic, it should work in both cases.

**Comment by Rot127** [comment]
> what do you think on this one. I personally think cstool should be independent of the type of the library it built with - static or dynamic, it should work in both cases.

I agree. Though @kabeor mentioned often now that `make.sh` will not be supported anymore and only the `cmake` build will be maintained.

Using `cmake` one should be able to compile `cstool` statically or dynamically as they wish.
https://github.com/capstone-engine/capstone/blob/a026fc4fe493a6f209e50f6fd8fd7aa3b6418c06/CMakeLists.txt#L35-L39

**Comment by XVilka** [comment]
As the `make.sh` file is still here in 5.0, it's probably better to fix this. And if it's deprecated, better to remove it completely in the 6.0, for example.

**Comment by Rot127** [comment]
Wasn't the `make` way of building to be removed anyway? @kabeor You mentioned this several times I think.

**Comment by XVilka** [comment]
@kabeor @aquynh what should we do with that? Ideally, it would be nice to fixed, should we remove it?

**Comment by kabeor** [comment]
Well for me, I just leave Makefile there and no plan to touch it. It's so complicated to contributors (always updating every building way which causes a lot of unnecessary confusion). But don't remove it, if anyone would like to maintain Makefile way, welcome. CMake way is the first tier in the future for Capstone.

**Comment by XVilka** [comment]
Should be this closed then as there are no plans to fix it? @kabeor

**Comment by Rot127** [comment]
Close this one now because the `make` build is considered deprecated. Especially with v6 Alpha coming.
