### ISSUE TITLE
Setup Coverity GitHub Action

### ISSUE THREAD

**Issue by XVilka** [aquynh/capstone#2029]
Capstone already has a [project page on Coverity Scan](https://scan.coverity.com/projects/capstone-next?tab=overview) (probably also makes sense to write them email to rename it just to "capstone") but it wasn't uploaded for a long time (last analyzed on Jan 02, 2019). It's possible to setup the automated GitHub Actions job to do just that.

You can use a token from that page, define it in the secrets and setup a worker similar to what we have in Rizin: 
https://github.com/rizinorg/rizin/blob/dev/.github/workflows/coverity-scan.yml

It is especially important for the `auto-sync` project since huge chunks of the code are overwritten.

cc @kabeor @Rot127 

It will also close these issues as outdated:

- [x] https://github.com/capstone-engine/capstone/issues/931
- [x] https://github.com/capstone-engine/capstone/issues/1112
- [x] https://github.com/capstone-engine/capstone/issues/1166

**Comment by Rot127** [comment]
It would be good to have this before the `auto-sync` release. I tried my best to cover all the new code via tests, but I couldn't manage to get `perf` running in my VM. So can't say for sure if all code paths are covert.

**Comment by kabeor** [comment]
Ok, let me try later:) Last time, the github action for llvm-capstone almost kills me (hard to debug).
