### ISSUE TITLE
Add more issue/PR labels

### ISSUE THREAD

**Issue by XVilka** [aquynh/capstone#2039]
1. Add architecture labels: x86, arm, mips, etc
2. Add bindings labels: python, java, ocaml, other languages
3. Probably new label for `auto-sync`-related files once it's merged
4. Something else I forgot?

By adding [GitHub Action for autolabeler](https://github.com/actions/labeler), PRs changing corresponding files could get the corresponding labels automatically.

https://github.com/capstone-engine/capstone/labels

**Comment by Rot127** [comment]
Regarding point 3:
Labels could be something like:
- `LLVM-module-files` (`inc` and translated),
- `CS-module-files` (`ARCHModule.*`, `ARCHMapping.*` etc.)
- `CS-core-files` (`cs_priv.h`, `cstool.c` etc.)
- `LLVM-core-files` (`MCInst.*`, `MCInstrDesc.*` etc.)
- `auto-sync-files`
- `something for the rest`.

**Comment by XVilka** [comment]
@kabeor @aquynh

**Comment by XVilka** [comment]
@kabeor could you please add those?

**Comment by kabeor** [comment]
1,2,3 basic done

**Comment by XVilka** [comment]
Now it is fixed, thanks everyone!
