### ISSUE TITLE
A Letter Prior to the Official Release of Capstone v5.0

### ISSUE THREAD

**Issue by kabeor** [aquynh/capstone#2053]
Hello everyone,

It has been three years since the last official release of v4.0.2.

We are excited to announce that we are preparing to release version 5.0 of the capstone-engine on GitHub. But before the official release, we would like to gather your valuable feedback on the recently published 5.0rc4 version. We have created an issue specifically for this purpose and would greatly appreciate it if you could take the time to test the 5.0rc4 version and share your experiences with us. (Python bindings is also released on pypi, using `pip install capstone --pre` I guess 🤔)

Your feedback will play a crucial role in helping us identify any potential issues or improvements needed before the final release. Please feel free to report any bugs, suggest enhancements, or provide general comments on the 5.0rc4 version.

Indeed, there are still some minor issues in the current code, such as inconsistent binding versions, and so on. These issues will be fixed before the official release. I will keep this issue open for five days, and then proceed with the official release. 

By the way, have you noticed that the repository's project board has some new content? Furthermore, I will create a new issue to gather everyone's suggestions shortly.

Thank you for your continuous support and contributions. Your feedback is instrumental in making capstone-engine better with each release. We look forward to hearing from you!

Best regards,
your good neighbor kabeor:)

**Comment by XVilka** [comment]
How is the release going? Seems everything was fixed that was necessary for it?

**Comment by XVilka** [comment]
A few more notes regarding the release once tagged:
- Please update the site - main page with features (supported architectures in particular), and http://www.capstone-engine.org/download.html
- Pascal/Delphi bindings seem to be removed (repo doesn't exist)
- At the Download page ChangeLog link refers to abandoned wiki page, should be ChangeLog in the repository instead
- At http://www.capstone-engine.org/showcase.html please add also Rizin and Cutter links
- The GitHub button at the site refers to the old GitHub repository

**Comment by kabeor** [comment]
V5.0 has been released. However, still pin this issue for a while, as there are some good suggestions that can be referred to.

**Comment by aquynh** [comment]
Please send pull req to add your projects to the Showcase page.

**Comment by Rot127** [comment]
Can be unpinned I guess?
