### ISSUE TITLE
[Test] issues.cs Segmentation fault(11) when using make compile

### ISSUE THREAD

**Issue by kabeor** [aquynh/capstone#2059]
https://github.com/capstone-engine/capstone/actions/runs/5117561940/jobs/9200760293#step:8:1015

```
[-] Detailed report for issues.cs:

	[+] Unknown test: 
		Test failed with exception: Segmentation fault(11)

	[+] Unknown test: 
		Test failed with exception: Segmentation fault(11)
...
```

Cause by commit https://github.com/capstone-engine/capstone/commit/6c3a899646b02ff9030cfd38ccad068b4f2ba1eb

**Comment by kabeor** [comment]
@imbillow Would you like to take a look?

**Comment by b1llow** [comment]
> @imbillow Would you like to take a look?

I'll come and check when I have some free time later.
