### ISSUE TITLE
repz prefix on ret instruction

### ISSUE THREAD

**Issue by adamjseitz** [aquynh/capstone#2062]
It appears this was previously mentioned (#1229) but I believe not enough context was included.

`repz ret` is generated by gcc in some cases as an optimization for AMD platforms, see the following references for more info:

https://repzret.org/p/repzret/
https://gcc.gnu.org/legacy-ml/gcc-patches/2003-05/msg02117.html

Clients of capstone may care that the `repz` prefix is present here; although it is functionally the same, it is not necessarily the same in terms of performance or instruction size. Compilers generate this instruction in real code.

**Comment by kabeor** [comment]
Fixed.
