### ISSUE TITLE
Access violation when compiled as 32-bit programs by the latest MSVC on Windows

### ISSUE THREAD

**Issue by kubo** [aquynh/capstone#2064]
My CI tests have failed since MSVC was upgraded from version 17.5.0 (internal version 14.35.32215) to 17.6.4 (14.36.32532). This may be fixed when MSVC is upgraded again. I'm not sure whether it is due to capstone or MSVC.

> **Note**
> Upgrading MSVC from 17.6.4 to 17.6.5 fixed this issue.

I reproduced it by the following batch.

Test batch: https://github.com/kubo/capstone-x86-issue/blob/master/test.bat
```bat
@echo off
git clone --depth=1 https://github.com/capstone-engine/capstone.git
mkdir build-win64
cd build-win64
cmake ..\capstone -A x64
cmake --build . --config Release
cd ..
mkdir build-win32
cd build-win32
cmake ..\capstone -A Win32
cmake --build . --config Release
cd ..
echo build-win64\Release\cstool.exe x32 "55 8b ec"
build-win64\Release\cstool.exe x32 "55 8b ec"
echo build-win64\Release\cstool.exe x32 "55 8b ec a1 00 e0 a5 00 5d c3"
build-win64\Release\cstool.exe x32 "55 8b ec a1 00 e0 a5 00 5d c3"
echo build-win32\Release\cstool.exe x32 "55 8b ec"
build-win32\Release\cstool.exe x32 "55 8b ec"
echo build-win32\Release\cstool.exe x32 "55 8b ec a1 00 e0 a5 00 5d c3"
build-win32\Release\cstool.exe x32 "55 8b ec a1 00 e0 a5 00 5d c3"
```

Output: https://github.com/kubo/capstone-x86-issue/actions/runs/5368452153/jobs/9739134325#step:3:467
```
build-win64\Release\cstool.exe x32 "55 8b ec"
 0  55                                               push	ebp
 1  8b ec                                            mov	ebp, esp
build-win64\Release\cstool.exe x32 "55 8b ec a1 00 e0 a5 00 5d c3"
 0  55                                               push	ebp
 1  8b ec                                            mov	ebp, esp
 3  a1 00 e0 a5 00                                   mov	eax, dword ptr [0xa5e000]
 8  5d                                               pop	ebp
 9  c3                                               ret	
build-win32\Release\cstool.exe x32 "55 8b ec"
 0  55                                               push	ebp, 
 1  8b ec                                            mov	ebp, espqword ptr :[*24842024], 
build-win32\Release\cstool.exe x32 "55 8b ec a1 00 e0 a5 00 5d c3"
Error: Process completed with exit code -1073741819.
```

cstool compiled as a 64-bit program decoded both `"55 8b ec"` and `"55 8b ec a1 00 e0 a5 00 5d c3"` correctly.
cstool compiled as a 32-bit program decoded `"55 8b ec"` with extra unexpected characters ("," and "qword ptr :[*24842024],") and stopped by access violation (0xC0000005 => -1073741819) when decoding `"55 8b ec a1 00 e0 a5 00 5d c3"`.

**Comment by Rot127** [comment]
Can you add the `valgrind` trace for this?

**Comment by kubo** [comment]
> Can you add the `valgrind` trace for this?

No, I can't. `valgrind` doesn't support Windows.

**Comment by kubo** [comment]
I reported this to Microsoft. https://developercommunity.visualstudio.com/t/MSVC-x86-1436-or-later-generates-incorr/10405585
I think that it is due to MSVC.
