### ISSUE TITLE
macOS python wheel for 5.0.0rc4 claims to be universal2 but is actually just amd64

### ISSUE THREAD

**Issue by twizmwazin** [aquynh/capstone#2066]
When pip installing capstone on an apple silicon mac, pip will select the universal2 wheel as compatible. However, it then fails to import because the library cannot be loaded due to the architecture mismatch. Installing from source with `pip install --pre --no-binary capstone capstone` seems to work fine however.

**Comment by XVilka** [comment]
Likely changes needed in https://github.com/capstone-engine/capstone/blob/next/bindings/python/build_wheel.sh

**Comment by XVilka** [comment]
Maybe cibuildwheel could be used:
- https://cibuildwheel.readthedocs.io/en/stable/faq/
- https://cibuildwheel.readthedocs.io/en/stable/setup/#github-actions

**Comment by XVilka** [comment]
See https://github.com/capstone-engine/capstone/pull/2099

**Comment by kabeor** [comment]
should have been fixing in #2099. will publish in 5.0.1.

**Comment by cunji123** [comment]
WOW!

**Comment by cunji123** [comment]
WOW!

**Comment by Grazfather** [comment]
This is still broken on 5.0.1 for me.

**Comment by d235j** [comment]
This bug is still present in v5.0.2. In addition, the ARM wheel ships an x86_64 .dylib.

**Comment by Rot127** [comment]
Fixed in `v5.0.3`. This time for real
