### ISSUE TITLE
[cstest] `issue.cs` testing is broken

### ISSUE THREAD

**Issue by Rot127** [aquynh/capstone#2069]
In the `next` branch `cstest` is broken. It can not test the `issue.cs` files anymore.

**Way to reproduce**

- Build `cstest` as described in `suite/cstest/README.md`
- Run: `./build/cstest -f issue.cs`
- Enjoy a bunch of seg faults

Note that `cstool` disassembles fine. So this is an issue with `cstest` only.

But note that this wasn't detected by the CI! Probably because the `cstest_report.py` script treats `Segmentation faults` as `0 errors`.

**Comment by XVilka** [comment]
@kabeor this is the major issue and the release blocker, in my opinion.

**Comment by kabeor** [comment]
Yep, shouldn't release until fixed this.

**Comment by Rot127** [comment]
I'll take care of it so we can release. But we really really need to rewrite testing. And add it to the CI. Definitely before `v6`.

**Comment by Rot127** [comment]
Ok, this was weird. I was sure I tested it on next. But now it works. So it was my mistake. Good news for the release.
