### ISSUE TITLE
5.0.0rc4 branch instruction imm ambiguous

### ISSUE THREAD

**Issue by vacuastreas** [aquynh/capstone#2072]
```
>>> import capstone
>>> capstone.version_bind()
(5, 0, 1280)
>>> cs = capstone.Cs(capstone.CS_ARCH_ARM64, capstone.CS_MODE_ARM)
>>> cs.detail = True
>>> inst_bytes = b'\x07\x00\x00\x14'
>>> inst = cs.disasm(inst_bytes, 0xfffffff044444444)
>>> inst = next(inst)
>>> inst
<CsInsn 0xfffffff044444444 [07000014]: b #0xfffffff044444460>
>>> operand = inst.operands[0]
>>> hex(operand.imm)
'-0xfbbbbbba0'
```
operand.imm currently outputs as signed version of the branch label which is incorrect.
Should it be:
- the unsigned label
- the signed imm26 encoded in the instruction
    - multiply by 4
    - without multiply by 4

**Comment by XVilka** [comment]
Related https://github.com/capstone-engine/capstone/issues/2056

**Comment by Rot127** [comment]
https://github.com/capstone-engine/capstone/issues/2056 is exactly the problem. Just scaled up to 64bit values.

In `printAlignedLabel` the address is correctly calculated as `uint64_t`
```c
uint64_t imm = (MCOperand_getImm(Op) * 4) + MI->address;
```

and later assigned to an `int64_t imm`:

```c
MI->flat_insn->detail->arm64.operands[MI->flat_insn->detail->arm64.op_count].imm = imm;
```

I doubt though that we going to fix this before the release?

**Comment by XVilka** [comment]
@Rot127 it's a hard thing to fix properly without big changes AFAIK. It's better to do that during the breaking season of merging `auto-sync` PRs, IMHO.

**Comment by Rot127** [comment]
Yes. Also I wouldn't count on LLVM having all the operand type information correct. This kind of info is often neglected.
