### ISSUE TITLE
ImportError in the Python package

### ISSUE THREAD

**Issue by jbremer** [aquynh/capstone#208]
Hey,

Just wanted to mention that after doing ``pip install capstone``, see also https://pypi.python.org/pypi/capstone/2.1, it doesn't actually work yet :-( Namely, on my Ubuntu 14.04 it doesn't find the dynamic library; ```ImportError: ERROR: fail to load the dynamic library.```

Thanks in advance :)

**Comment by aquynh** [comment]
we have released v3.0.1, and now the **capstone** package on PyPi automatically build & install the core into the same directory with Python module. so there is no more external dependency. see https://pypi.python.org/pypi/capstone/3.0.1

however, it is inconvenient to compile the core on Windows, as usually you do not have C compiler installed. in that case, there is another PyPi module named "capstone-windows", which embeds the prebuilt Windows core inside, so no compilation is needed. see https://pypi.python.org/pypi/capstone-windows

please report if you still have issues. thanks.

thanks.
