### ISSUE TITLE
Version 5.0 32-bit crash

### ISSUE THREAD

**Issue by CandyMan30** [aquynh/capstone#2083]
Has anyone used the 32 bit version 5.0 of Capstone disassembler? My program crashes on the second call to cs_disasm_iter() for the x86_64 architecture. Version 5.0 64-bit as well as the previous version 4.0.2 32-bit works fine.

**Comment by XVilka** [comment]
Please provide more details - stacktrace, minimal reproducer, if possible.

**Comment by CandyMan30** [comment]
Here my Pascal minimal code.
[CapstoneTest.zip](https://github.com/capstone-engine/capstone/files/12036936/CapstoneTest.zip)

**Comment by hzqst** [comment]
Are you using msvc 2022 ? if yes then this might be the same issue: https://github.com/capstone-engine/capstone/issues/2064

**Comment by CandyMan30** [comment]
I received the compiled libraries from a trusted friend and I confirm that it is a compiler error.

**Comment by kubo** [comment]
Upgrading to  Visual Studio 2022 version 17.6.5 may fix this issue.

In the [release note](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#1765--visual-studio-2022-version-1765):

> * Fixed an issue where switches over unsigned 64-bit integers could cause a crash on x86 and ARM targets.

**Comment by kabeor** [comment]
Closed now. Feel free to reopen it if there is any issue.
