### ISSUE TITLE
PowerPC regressions in v5.0

### ISSUE THREAD

**Issue by wargio** [aquynh/capstone#2087]
1. The `ppc_op_crx` are not being set in capstone v5 (this applies for `X.crx.reg` and for `X.crx.cond`).

The issue is linked to these lines:
- https://github.com/capstone-engine/capstone/blob/8ae8f68ea3abb7a68071908bad02baa39742870c/arch/PowerPC/PPCInstPrinter.c#L350
- https://github.com/capstone-engine/capstone/blob/8ae8f68ea3abb7a68071908bad02baa39742870c/arch/PowerPC/PPCInstPrinter.c#L131

2. `XORI` sometimes is marked as `XNOR` even if is not `XORI r0, r0, 0`
3. Some instructions are correctly decoded and their fields are wrongly set:
- Prints `rldicl` but is set as `PPC_INS_CLRLDI`.
- Prints `rlwinm` but is set as `PPC_INS_CLRLWI`.
- Prints `cmpw` but is set as `PPC_INS_CMP`
- Prints `cmpd` but is set as `PPC_INS_CMP`
- Prints `cmplw` but is set as `PPC_INS_CMPL`
- Prints `cmpld` but is set as `PPC_INS_CMPL`
- Prints `cmpwi` but is set as `PPC_INS_CMPI`
- Prints `cmpdi` but is set as `PPC_INS_CMPI`
- Prints `cmplwi` but is set as `PPC_INS_CMPLI`
- Prints `cmpldi` but is set as `PPC_INS_CMPLI`

**Comment by XVilka** [comment]
It doesn't make sense to invest fixing them and it's better to wait for https://github.com/capstone-engine/capstone/pull/2013 to get merged if it *ever happens*

**Comment by XVilka** [comment]
These regressions could be prevented by running tests on CI for every commit and PR, see https://github.com/capstone-engine/capstone/issues/1984

**Comment by Rot127** [comment]
Mappings are fixed in https://github.com/capstone-engine/capstone/pull/2333.

But it is not worth to fix the first point. This is done in the `next` branch.
So I mark this as `wontfix` and close it with https://github.com/capstone-engine/capstone/pull/2333.

**Comment by XVilka** [comment]
Should be this closed then? @Rot127
