### ISSUE TITLE
Wheel for aarch64 broken since yesterday

### ISSUE THREAD

**Issue by patryk4815** [aquynh/capstone#2102]
This code just broke aarch64 build:
- https://github.com/capstone-engine/capstone/commit/e897c6c94a0fb65fef7b73eab0e4af94938ce269

Now im getting error:
```
Unknown machine: aarch64
```

Capstone was working fine since yesterday on aarch64. Why it was deleted?

Please add `manylinux2014_aarch64`

**Comment by XVilka** [comment]
Likely this piece:
```py
        machine = platform.machine()
        if machine == "i686":
            # manylinux2014 is the last which supports x86 in dockercross
            sys.argv.insert(idx + 1, 'manylinux2014-x86')
        elif machine == "x86_64":
            sys.argv.insert(idx + 1, 'manylinux_2_28-x64')
        else:
            raise ValueError("Unknown machine: " + machine)
```
You can send a PR expanding this condition.

Anyway, I think wheels building should be moved to this instead (and it will support more architectures out of the box): https://github.com/capstone-engine/capstone/pull/2099

cc @Rot127 @kabeor

**Comment by kabeor** [comment]
should have be fixed in #2099. plz have a try.

**Comment by patryk4815** [comment]
@kabeor still issue:
```
 ERROR: capstone-5.0.0.post1-py3-none-linux_aarch64_310.whl is not a supported wheel on this platform.
 ```
 
 Generateed filename need to be:
 ```
 capstone-5.0.0.post1-py3-none-linux_aarch64.whl
 ```
 acoding to: https://packaging.python.org/en/latest/specifications/binary-distribution-format/#file-name-convention

**Comment by kabeor** [comment]
@patryk4815 Hi. How did you build it?

**Comment by patryk4815** [comment]
How i build (most of "packers" works like this):
```
cd ./bindings/python
python setup.py sdist
mkdir -p dist
pip wheel --verbose --no-index --no-deps --no-clean --no-build-isolation --wheel-dir dist .
cd dist
pip install ./*.whl
```

Anyway on macos:
```
$ pip3 install capstone-5.0.0.post1-py3-none-macosx_13_arm64_311.whl
ERROR: capstone-5.0.0.post1-py3-none-macosx_13_arm64_311.whl is not a supported wheel on this platform.
```

How .whl filenames should be generated (i don't know about windows names), example:
```
capstone-5.0.0.post1-py3-none-macosx_13_0_arm64.whl
capstone-5.0.0.post1-py3-none-macosx_10_15_x86_64.whl
capstone-5.0.0.post1-py3-none-linux_aarch64.whl
capstone-5.0.0.post1-py3-none-linux_x86_64.whl
```

Using `distutils.util.get_platform` 
> The platform tag is simply distutils.util.get_platform() with all hyphens - and periods . replaced with underscore _.

^ This will work fine for windows/linux, but not for macos... 🤮 On macos it return `macosx-13-arm64` but .whl require format `macosx_13_0_arm64`
So for macos better use: `platform.mac_ver()` -> returns `('13.5', ('', '', ''), 'arm64')`

**Comment by patryk4815** [comment]
Anyway on macos:
```
$ pip3 install capstone-5.0.0.post1-py3-none-macosx_13_arm64_311.whl
ERROR: capstone-5.0.0.post1-py3-none-macosx_13_arm64_311.whl is not a supported wheel on this platform.
```
