### ISSUE TITLE
5.0.0post1 Mac universal wheel is invalid for AArch64

### ISSUE THREAD

**Issue by flit** [aquynh/capstone#2129]
The `capstone-5.0.0.post1-py3-none-macosx_10_9_universal2.whl` wheel seems to contain x86_64 but not AArch64 code. Thus, when loaded on an AArch64 Mac (M1 in my case), `dlopen()` returns an error.

This exception is from [pyocd](https://github.com/pyocd/pyOCD) attempting to import capstone (newlines inserted):

```
 Error: dlopen(/VENV_DIR/lib/python3.11/site-packages/capstone/lib/libcapstone.dylib, 0x0006): tried: 
'/VENV_DIR/lib/python3.11/site-packages/capstone/lib/libcapstone.dylib' (mach-o file,
but is an incompatible architecture (have 'x86_64', need 'arm64')), 
'/System/Volumes/Preboot/Cryptexes/OS/VENV_DIR/lib/python3.11/site-packages/capstone/lib/libcapstone.dylib' (no such file),
 '/VENV_DIR/lib/python3.11/site-packages/capstone/lib/libcapstone.dylib' 
(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by patryk4815** [comment]
Probably it will be fixed: https://github.com/capstone-engine/capstone/issues/2066#issuecomment-1645755087

**Comment by flit** [comment]
Closing as duplicate of #2066. (I did search for various terms related to MacOS and universal wheel, but still didn't manage to find it. 😓 )
