### ISSUE TITLE
arm64 unimplemented instructions

### ISSUE THREAD

**Issue by Talos878** [aquynh/capstone#2130]
There appears to be a couple unimplemented arm64 instructions between ida and capstone. These are from ida

21 7d a8 c8 CAS             X8, X1, [X9]
08 81 3f b8 SWP             WZR, W8, [X8]
08 31 29 f8 LDSET           X9, X8, [X8]
08 01 29 b8 LDADD           W9, W8, [X8]
20 7d 22 48 CASP            X2, X3, X0, X1, [X9]
08 11 29 f8 LDCLR           X9, X8, [X8]
08 01 69 b8 LDADDL          W9, W8, [X8]
20 81 68 f8 SWPL            X8, X0, [X9]
61 7e e9 88 CASA            W9, W1, [X19]
08 01 a9 f8 LDADDA          X9, X8, [X8]
21 fd aa c8 CASL            X10, X1, [X9]

**Comment by Rot127** [comment]
Those will be added in `v6` with https://github.com/capstone-engine/capstone/pull/2026
If everything runs smoothly #2026 should be merged into `next` in during August.

Please note, that this will come with a big refactor of the `AArch64` module itself. See https://github.com/Rot127/capstone/blob/v6-release-guide/docs/cs_v6_release_guide.md
