### ISSUE TITLE
COMPILE_CMAKE.TXT text error

### ISSUE THREAD

**Issue by baosj0** [aquynh/capstone#2159]
line 40 41
`- CAPSTONE_ARCHITECUTRE_DEFAULT: Whether architectures are enabled by default.
      Set this of OFF with -DCAPSTONE_ARCHITECUTRE_DEFAULT=OFF to dissable all architectures by default.`

ARCHITECUTRE       -should be-> ARCHITEC TU RE

**Comment by kabeor** [comment]
Thanks for pointing out! Fixed in https://github.com/capstone-engine/capstone/commit/080314d5b3f288274ed8e2ea48adcc03669b9c57.
