### ISSUE TITLE
Documentation for x86 instruction groups

### ISSUE THREAD

**Issue by wenkokke** [aquynh/capstone#2175]
Is there any documentation on the miscellaneous x86 instruction groups listed in [include/capstone/x86.h](https://github.com/capstone-engine/capstone/blob/5fb8a423d4455cade99b12912142fd3a0c10d957/include/capstone/x86.h#L1937-L1977)?

**Comment by Rot127** [comment]
I'm not aware of any in Capstone (can't search currently for it). But those groups were generated at some point from LLVM. So you should be able to find descriptions in the [LLVM source](https://github.com/llvm/llvm-project/tree/main/llvm/lib/Target/X86).

You should be able to find the original definitions of those groups by "grepping" in the LLVM `td` files.

So something like:

```
grep "<group-name>" llvm/lib/Target/X86/*.td
```

The names are probably renamed in CS or caps are changed. So try some variations.

Also search for "features" in LLVM. In LLVM instructions are not assigned a "group" but are enabled/disabled based on CPU features present. Those features are then termed groups here.

**Comment by Rot127** [comment]
Please don't forget to close the issue, if this helped you.
