### ISSUE TITLE
Possible support for Coldfire

### ISSUE THREAD

**Issue by Kaltxi** [aquynh/capstone#2186]
Could you advise me on the difficulty of adding Coldfire arch support? As I understand it is assembly-compatible with M68K which is already supported, but has different machine code/object code representaion. Will that help in adding support, or will it requre implementation from the ground up?

**Comment by Rot127** [comment]
Is there a LLVM fork which supports it? If yes you could implement it via `auto-sync`, our update tool.
That one of the maintainers will implement is is unlikely. See https://github.com/capstone-engine/capstone/issues/2089
