### ISSUE TITLE
Missing group for ARM bx instruction

### ISSUE THREAD

**Issue by Quentin01** [aquynh/capstone#2190]
Hi,

In `ARMGenCSMappingInsn.inc` there is multiple variations of the instruction `bx`:
 - when `bx` is done with a regular register like `bx r3`, there is the group `ARM_GRP_JUMP`
 - when `bx` is done with `lr`, there is no group indicating that this is a jump or a ret

There isn't any `ARM_GRP_RET` group yet, but maybe we should add it and change `bx lr` to use it, or at least it should have the group `ARM_GRP_JUMP` as it is kind of a return jump.

I'm not sure how to proceed with the modification to do it as this file is autogenerated from LLVM and I don't know if the issue is in the LLVM data or in the computation of the data to generate this file. So, I'm opening this issue if someone know how to fix that.

Edit: The issue should probably be tackled on [llvm-capstone](https://github.com/capstone-engine/llvm-capstone) by using `isReturn` in `PrinterCapstone.cpp:getReqFeatures`. However, as I don't especially know this code, I will let someone more experimented with it fix it.

**Comment by Rot127** [comment]
`bx lr` definitely should be of group jump. I'll look into it.

Adding a return group is possible. Not in LLVM though IMHO, but in `ARMMapping.c` where we add the other non-LLVM groups.

**Comment by Rot127** [comment]
I forgot if it is already implemented for ARM. But if it is, this is likely a work around:
 But `bx lr` is likely an alias for some `bx` variant and has the group missing because of that. You can try to run cstool with the `-r` option. It should give you the details of the real instruction.

For the API you should enable one of the detail options `CS_DETAIL_something`. Sorry, can't look it up currently.

**Comment by Quentin01** [comment]
> `bx lr` definitely should be of group jump. I'll look into it.
> 
> Adding a return group is possible. Not in LLVM though IMHO, but in `ARMMapping.c` where we add the other non-LLVM groups.

Thanks for your work on capstone!

> I forgot if it is already implemented for ARM. But if it is, this is likely a work around: But `bx lr` is likely an alias for some `bx` variant and has the group missing because of that. You can try to run cstool with the `-r` option. It should give you the details of the real instruction.
> 
> For the API you should enable one of the detail options `CS_DETAIL_something`. Sorry, can't look it up currently.

Using the `-r` option isn't changing the result:
```
$ cstool -r -d arm "1e ff 2f e1"
 0  1e ff 2f e1  bx	lr
	ID: 48 (bx)
	op_count: 1
		operands[0].type: REG = r14
		operands[0].access: READ
	Registers read: r14
	Groups: IsARM HasV4T
```

The `-r` option is setting the option `CS_OPT_DETAIL_REAL` but it isn't changing the result too.

However it's okay, I don't particularly need a quick fix, I have a workaround for my use case.

**Comment by Rot127** [comment]
@kabeor https://github.com/capstone-engine/capstone/pull/2191 your turn :)
