### ISSUE TITLE
SystemZ Vector Load with alignment hint

### ISSUE THREAD

**Issue by juergenchrist** [aquynh/capstone#2194]
Hi,

when trying to disassemble a SystemZ Vector Load instruction that includes an alignment hint, capstone does not recognize this instruction:
```
$ cstool -d systemz 0xe70050003006
ERROR: invalid assembly code
```
Without the alignment hint, everything works fine:
```
$ stool -d systemz 0xe70050000006
 0  e7 00 50 00 00 06  vl	%v0, 0(%r5)
	ID: 1966 (vl)
	op_count: 2
		operands[0].type: REG = v0
		operands[1].type: MEM
			operands[1].mem.base: REG = 5
	Groups: vector 
```
I guess the third operand (4-bit immediate M3 with possible values 0 for no alignment, 3 for doubleword aligned, and 4 for quadword aligned) is currently not parsed/supported.  Would it be possible to add this?

Thanks.

**Comment by XVilka** [comment]
The best way to update System Z deficiencies is to do the "auto-sync" with the mainstream LLVM like it was done for ARM, ARM64, PPC, Tricore, Alpha: https://github.com/capstone-engine/capstone/issues/2015
There is currently a lack of hands working on the project, and System Z, sadly, is not yet one of our (Rizin team) priorities. Thus, they could do such an update if people want to contribute. If there is a desire to proceed - we could describe the process in detail.
 There is some short documentation already:
- https://github.com/capstone-engine/capstone/pull/2217
- https://github.com/capstone-engine/capstone/blob/next/docs/cs_v6_release_guide.md
- https://github.com/capstone-engine/capstone/blob/next/docs/AutoSync.md
