### ISSUE TITLE
ARM Thumb instruction MRS cannot be decoded

### ISSUE THREAD

**Issue by yakamoz423** [aquynh/capstone#2207]
Opcode:
```
 80037d8:	f3ef 8010 	mrs	r0, PRIMASK
```

Bit view:
![image](https://github.com/capstone-engine/capstone/assets/45655135/e984d647-1ef7-460a-bd74-f5ef94c9e597)

It should be:
![image](https://github.com/capstone-engine/capstone/assets/45655135/4b24a11e-164e-4497-929c-54be9008566c)

But I got:
```shell
$ ./cstool thumbbe f3ef8010
ERROR: invalid assembly code
```

I'm using d78d0ca2c67af559f468319e85d8bcf68b478abc latest next version.

**Comment by Rot127** [comment]
This should be a `cortexm` instruction.
Please try it with `cstool cortexm <bytes>`

With the auto-sync update the features are now checked more strictly.

**Comment by yakamoz423** [comment]
> This should be a `cortexm` instruction. Please try it with `cstool cortexm <bytes>`
> 
> With the auto-sync update the features are now checked more strictly.

Thank you for your guidance! It helps a lot.
