### ISSUE TITLE
Python bindings failing to disassemble single instruction

### ISSUE THREAD

**Issue by m1stadev** [aquynh/capstone#2208]
Hi,
I'm attempting to disassemble a single instruction as a test with the python bindings, and they seem to be failing.
Here's my code:
```py
from capstone import CS_ARCH_ARM64, CS_MODE_ARM, Cs

data = b'\xe0\x03\x17\xaa' # mov x0, x23

cs = Cs(CS_ARCH_ARM64, CS_MODE_ARM)

for i in cs.disasm(data, 0x1000):
    print(f'{i.mnemonic} {i.op_str}')
```

I'd expect some output along the lines of `mov x0, x23`, but I get nothing. Using `CS_MODE_LITTLE_ENDIAN` or `CS_MODE_ARM + CS_MODE_LITTLE_ENDIAN` for the mode doesn't seem to make a difference. Running this on Python 3.11.6 on an ARM Mac running macOS 14.1.1.

**Comment by Rot127** [comment]
Is this the next brach?

If yes, please see the [release guide](https://github.com/Rot127/capstone/blob/v6-release-guide/docs/cs_v6_release_guide.md) about the changes (e.g. `CS_ARCH_ARM64` -> `CS_ARCH_AARCH64`).

**Comment by m1stadev** [comment]
> Is this the next brach?
> 
> If yes, please see the [release guide](https://github.com/Rot127/capstone/blob/v6-release-guide/docs/cs_v6_release_guide.md) about the changes (e.g. `CS_ARCH_ARM64` -> `CS_ARCH_AARCH64`).

That fixed it, thanks!
