### ISSUE TITLE
the result of regs_access() for lsr is not correct?

### ISSUE THREAD

**Issue by Gavin0210** [aquynh/capstone#2213]
```
from capstone import *
from capstone.arm64 import *
cs = Cs(CS_ARCH_ARM64, CS_MODE_LITTLE_ENDIAN)
CODE = bytes.fromhex('0d7e0a53')
cs = Cs(CS_ARCH_ARM64, CS_MODE_ARM)
cs.detail=True
for i in cs.disasm(CODE, 0):
    print(i.regs_access())
    print("%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))
```
the arm64 code is 'lsr    w13, w16, #0xa '
why w13 is read and write? Obviously the access of reg w13 is write, no read.
the capstone version is 5.0.1
python verison is 3.10.10

**Comment by Rot127** [comment]
Can you please check if it still happens on next branch?
Mind the name change from ARM64 to ARch64 and other changes which will come in v6:
https://github.com/Rot127/capstone/blob/v6-release-guide/docs/cs_v6_release_guide.md

**Comment by Gavin0210** [comment]
> Can you please check if it still happens on next branch? Mind the name change from ARM64 to ARch64 and other changes which will come in v6: https://github.com/Rot127/capstone/blob/v6-release-guide/docs/cs_v6_release_guide.md
how to use the v6 in python ? The capstone in source of pip is 5.0.1?

**Comment by kabeor** [comment]
@Gavin0210 checkout to `next` branch.

```bash
cd bindings/python
python setup.py install
```

The code should be changed to:

```python
from capstone import *
from capstone.aarch64 import *
cs = Cs(CS_ARCH_AARCH64, CS_MODE_LITTLE_ENDIAN)
CODE = bytes.fromhex('0d7e0a53')
cs = Cs(CS_ARCH_AARCH64, CS_MODE_ARM)
cs.detail=True
for i in cs.disasm(CODE, 0):
    print(i.regs_access())
    print("%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))
```

The result is:

```
([204], [201])
0:      lsr     w13, w16, #10
```

**Comment by kabeor** [comment]
you can also using cstool for testing:

```bash
$ ./cstool -d aarch64 "0x0d7e0a53"
 0  0d 7e 0a 53  lsr    w13, w16, #10
        ID: 1200 (ubfm)
        Is alias: 1619 (lsr) with ALIAS operand set
        op_count: 2
                operands[0].type: REG = w13
                operands[0].access: WRITE
                operands[1].type: REG = w16
                operands[1].access: READ
                        Shift: type = 3, value = 10
        Registers read: w16
        Registers modified: w13
```
