### ISSUE TITLE
ARM64: Unable to decode `fmlalb`, `fmlalt`, `fmlallbb`, `fmlallbt`, `fmlalltb`, `fmlalltt` instructions

### ISSUE THREAD

**Issue by TIHan** [aquynh/capstone#2270]
The following instructions are not able to be decoded with `cstool`:

- `FMLALB <Zda>.H, <Zn>.B, <Zm>.B[<imm>]`
- `FMLALT <Zda>.H, <Zn>.B, <Zm>.B[<imm>]`
- `FMLALLBB <Zda>.S, <Zn>.B, <Zm>.B[<imm>]`
- `FMLALLBT <Zda>.S, <Zn>.B, <Zm>.B[<imm>]`
- `FMLALLTB <Zda>.S, <Zn>.B, <Zm>.B[<imm>]`
- `FMLALLTT <Zda>.S, <Zn>.B, <Zm>.B[<imm>]`

The decoder just fails and stops.

**Comment by Rot127** [comment]
Those ones seem to be added with LLVM-18. At least this is the version I can find the first regression tests in LLVM for. We will update it after the https://github.com/capstone-engine/capstone/pull/2231 is done. Which should be this month, if anything goes by plan.

**Comment by TIHan** [comment]
Thanks for the update!
