### ISSUE TITLE
Remove or update java and ocaml bindings

### ISSUE THREAD

**Issue by Rot127** [aquynh/capstone#2282]
The bindings for `java` and `ocaml` are massively out of date and not tested. It is certain that they don't work with the current `next`.

Would propose to remove them. Updating will be difficult because of https://github.com/capstone-engine/capstone/issues/2089. And there were no bug reports in the recent months. Suggesting that they are pretty much not used.

If anyone is interested in updating them again, they can just restore them and work from there.
WDYT?

**Comment by keenk** [comment]
I haven't gotten to continue my work with Capstone in recent months, but I hope to eventually and it is based on the Java bindings.
