### ISSUE TITLE
Pip install capstone doesn't work

### ISSUE THREAD

**Issue by ScraperMan2002** [aquynh/capstone#2284]
I use "pip install capstone" to install capstone because some program called Qiling uses it, but when I run the program that calls Qiling that calls capstone, I get this:

```
OSError: dlopen(/Users/[MYUSERNAME]/Library/Python/3.9/lib/python/site-packages/capstone/lib/libcapstone.dylib, 0x0006): tried: '/Users/[MYUSERNAME]/Library/Python/3.9/lib/python/site-packages/capstone/lib/libcapstone.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/[MYUSERNAME]/Library/Python/3.9/lib/python/site-packages/capstone/lib/libcapstone.dylib' (no such file), '/Users/[MYUSERNAME]/Library/Python/3.9/lib/python/site-packages/capstone/lib/libcapstone.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

What's going on? I've tried everything like installing capstone via GitHub, installing capstone via brew, nothing works.

**Comment by Rot127** [comment]
This was fixed in https://github.com/capstone-engine/capstone/pull/2221. But the new version was not yet released. You can build the Python bindings either on your own, or wait until v5.0.2

**Comment by Rot127** [comment]
Ah, just found the duplicate issue: https://github.com/capstone-engine/capstone/issues/2066
