### ISSUE TITLE
Is there a stable [next] version available?

### ISSUE THREAD

**Issue by Youlor** [aquynh/capstone#2288]
Which commit can I use, Thanks!

**Comment by Rot127** [comment]
Not yet. The `next` branch is in general the development branch. Once we release `v6` this will be stable. I will open a tracking issue in the next days with todos for `v6`.
ping me please, if I forget it. Until than the `TODO for refactored archs` list in https://github.com/capstone-engine/capstone/issues/2015 should give you a good idea what is still missing (except the LLVM revisions listed there).

**Comment by Rot127** [comment]
Created a milestone for `v6`. Please follow this one. We will at some point make a pre-release of it.
