### ISSUE TITLE
MacOS wheel only contains x86_64 version of the libcapstone.dylib despite the package claims to be universal

### ISSUE THREAD

**Issue by xusheng6** [aquynh/capstone#2301]
I installed capstone using `pip install capstone` and the installation succeeds. However, when I try to run Python and import capstone, I am met with the following error:

```
OSError: dlopen(/opt/homebrew/lib/python3.11/site-packages/capstone/lib/libcapstone.dylib, 0x0006): tried: '/opt/homebrew/lib/python3.11/site-packages/capstone/lib/libcapstone.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/python3.11/site-packages/capstone/lib/libcapstone.dylib' (no such file), '/opt/homebrew/lib/python3.11/site-packages/capstone/lib/libcapstone.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
```

I checked the wheel for macOS (https://files.pythonhosted.org/packages/56/c9/936a81a0707fbd2650a94c9297e36c4c2cf34f51695fb1f6fd39de1b3247/capstone-5.0.1-py3-none-macosx_10_9_universal2.whl), and found the `libcapstone.dylib` is x86_64 only, and not universal, as it claims to be (on https://pypi.org/project/capstone/#files). 

I tested `brew install capstone` and it gives me an arm64 `libcapstone.dylib` in `/opt/homebrew/Cellar/capstone/5.0.1/lib`. I figured out a workaround that is to copy the dylib from the brew installation folder to the pip installation folder. 

### Work environment

| Questions                                | Answers
|------------------------------------------|--------------------
| OS/arch/bits                             | MacOS AArch64,
| Architecture                             | armv8
| Source of Capstone                       | pip
| Version/git commit                       | v5.0.1

### Steps to reproduce the behavior

- Use code markdown `CODE` to make your code visible

### Additional Logs, screenshots, source code,  configuration dump, ...

Drag and drop zip archives containing the Additional info here, don't use external services or link.
Screenshots can be directly dropped here.

**Comment by Rot127** [comment]
Thanks for the report! I close this as duplicate because it:
- Was fixed in https://github.com/capstone-engine/capstone/pull/2221. But the new version was not yet released. You can build the Python bindings either on your own, or wait until `v5.0.2`
- Had a primary (duplicate) issue: https://github.com/capstone-engine/capstone/issues/2066

**Comment by andiradulescu** [comment]
@Rot127 when is `v5.0.2` planned for release? I don't see a date [here](https://github.com/capstone-engine/capstone/milestone/6). Thanks!

**Comment by Rot127** [comment]
@andiradulescu `v5.0.2` is released after https://github.com/capstone-engine/capstone/pull/2400 is merged by @kabeor.
