### ISSUE TITLE
Got abnormal behavior when set CS_OPT_DETAIL_REAL without CS_OPT_ON

### ISSUE THREAD

**Issue by yakamoz423** [aquynh/capstone#2302]
### Work environment

| Questions                                | Answers
|------------------------------------------|--------------------
| OS/arch/bits                             | Windows x86
| Architecture                             | armv8
| Source of Capstone                       | git clone & cmake mingw
| Version/git commit                       | next, 0d12bcacd75da8ba02f6294505e7bedd55002a66

### Expected behavior

According to [cs_v6_release_guide](https://github.com/capstone-engine/capstone/blob/next/docs/cs_v6_release_guide.md#instruction-alias), I just set `cs_option(handle, CS_OPT_DETAIL, CS_OPT_DETAIL_REAL);`, and I found the details is part invalid. 

Changing code to `cs_option(handle, CS_OPT_DETAIL, (CS_OPT_ON | CS_OPT_DETAIL_REAL));`, it works.

I think it's better to make CS_OPT_DETAIL_REAL implicitly turn on the detials? or maybe the doc need to update, and don't generate groups and condition info and condition when detail turned off.

### Actual behavior

console print `ERROR: Too many groups defined in instruction mapping.`
and groups info pile up while no other details.
![This image is not captured from cstool.](https://github.com/capstone-engine/capstone/assets/45655135/f957fd3a-36c9-432b-8e07-02aa1b0177b6)

### Steps to reproduce the behavior

Command:
```shell
cstool -r armbe e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201e3c00201 0x233
```

**Comment by Rot127** [comment]
This gets fixed with https://github.com/capstone-engine/capstone/pull/2469

Unfortunately, implicitly enabling details for only `CS_OPT_DETAIL_REAL` doesn't work. Because we could not disable them afterwards.
because `CS_OPT_OFF = 0`, `CS_OPT_DETAIL_REAL | CS_OPT_OFF == CS_OPT_DETAIL_REAL`.

Refactoring options is one of the many things on the list though.
