### ISSUE TITLE
test_tms320c64x.c does not abort when not enabled

### ISSUE THREAD

**Issue by cmcneish** [aquynh/capstone#2383]
Compare:
https://github.com/capstone-engine/capstone/blob/1a6921f5cc3e1084a6658ad05ed2c00a7ff1fd00/tests/test_tms320c64x.c#L153
https://github.com/capstone-engine/capstone/blob/1a6921f5cc3e1084a6658ad05ed2c00a7ff1fd00/tests/test_arm.c#L290

This means that checking that `abort()` has been called in the test when tms320c64x isn't enabled will fail.

All other architecture-specific tests seem ok

**Comment by Rot127** [comment]
I'll start to modernize the whole testing anyways. So this will be fixed with it.
