### ISSUE TITLE
Create a Debian Package on releases

### ISSUE THREAD

**Issue by AndrewQuijano** [aquynh/capstone#2398]
### Feature

- [ ] New architecture module
- [ ] Support for processor extension
- [ ] Add more instruction details (elaborated below)
- [ ] Binding support for: `language`
- [X] Other (elaborated below)

**Describe the feature you'd like**
Please update your CI such that when you create a release, you also create a Debian Package, I provided an example of how this is used for PANDA.

https://github.com/panda-re/panda/releases/tag/v1.8.34
https://github.com/panda-re/panda/tree/dev/panda/debian

**Additional context**
Utilizing a Debian package would be useful to save time on builds as the users would only need to download the package instead of repeatedly compile it for every build. This process should not be too difficult to build and would greatly improve efficiency as things like branch v5 wouldn't be needed as someone can just grab the package from the release.

Based on the screenshots, it shows that the current apt packages only have the outdated versions of libcapstone4 and libcapstone-dev. The package I propose should have both packages in one go.

![image](https://github.com/user-attachments/assets/7c5a9754-73ed-43bf-8735-81284ecf766c)
![image](https://github.com/user-attachments/assets/6902f630-3b1f-4bc3-ba50-fba71c566dae)

**Comment by kabeor** [comment]
It would be great if you could help contribute a PR for this feature.

**Comment by AndrewQuijano** [comment]
@kabeor 

Sure I can give it a try, would be nice to know the following as I'm not familiar with libcapstone and am just going to rely a lot what was done here.
https://github.com/panda-re/panda/blob/dev/panda/debian/Dockerfile

1- where are the output files of `make install` located at?
2- Where would you like me to put the workflow to create the package and put the debian package in the release?

**Comment by AndrewQuijano** [comment]
@kabeor, I started some initial work on making the Capstone Debian package. I'm stuck on something, but if you got a bit of time to help with this last step, that would be amazing. Not sure when I can get another crack at this.

**Comment by AndrewQuijano** [comment]
@kabeor Actually, I figured it out, the packaging seems to work, updated your CI too.
