### ISSUE TITLE
test_riscv.py failing

### ISSUE THREAD

**Issue by KelvinChung2000** [aquynh/capstone#2405]
### Work environment

| Questions                                | Answers
|------------------------------------------|--------------------
| OS/arch/bits                             | Pop os
| Architecture                             | x86
| Source of Capstone                       | pip
| Version/git commit                       | v5.0.1

### Expected behavior
When running the `bindings/python/tests/test_riscv.py` should not be fault. 

### Actual behavior
Getting the following:
  File "/home/kelvin/capstone/./bindings/python/tests/test_riscv.py", line 45, in print_insn_detail
    if i.access == CS_AC_READ:
AttributeError: 'RISCVOp' object has no attribute 'access'

### Steps to reproduce the behavior
calling `python3 ./bindings/python/tests/test_riscv.py` from the root directory of Capstone git clone

### Additional Logs, screenshots, source code,  configuration dump, ...
![image](https://github.com/user-attachments/assets/4e5a75b9-fb0d-4f5d-a7b7-917d48a3174c)

I found this problem because when I try to use `regs_access` for a `CsInsn`, which I am also getting errors. This led me to find an example and find this. The cause of the error is not the same. Should I open another issue about that?

**Comment by Rot127** [comment]
I currently rewrite testing. So this one will be fixed with https://github.com/capstone-engine/capstone/pull/2384

**Comment by KelvinChung2000** [comment]
I would also like to ask about the `regs_access` issue. Should I open another issue for a bug report?

**Comment by Rot127** [comment]
Ah yes, please do so.
