### ISSUE TITLE
Typos in Python arm64 bindings

### ISSUE THREAD

**Issue by david942j** [aquynh/capstone#2411]
I noticed this typo when reviewing Python bindings code on the v5 branch.

```
class Arm64OpSmeIndex(ctypes.Structure):
    _fileds_ = (
        ('reg', ctypes.c_uint),
        ('base', ctypes.c_uint),
        ('disp', ctypes.c_int32),
    )
```

"__fileds__" should be "__fields"

Same typo exists (and gets more) on the next branch, in both `class AArch64OpSme(ctypes.Structure)` and `class AArch64OpPred(ctypes.Structure)`

Unsure what may be broken in the Python binding but I believe they should be fixed anyway. I am sending pull requests.

**Comment by Rot127** [comment]
Thanks, bindings are not yet properly tested. But will be with https://github.com/capstone-engine/capstone/pull/2384
