### ISSUE TITLE
capstone_static.vcxproj does not include mapping.c

### ISSUE THREAD

**Issue by hsebs** [aquynh/capstone#2433]
### Work environment

| Questions                                | Answers
|------------------------------------------|--------------------
| OS/arch/bits                             | Debian arm 64, MacOS AArch64, MacOS x86, Windows x86 etc.
| Architecture                             | ppc, x86, cortexm, armv8 etc.
| Source of Capstone                       | `git clone`, brew, pip, release binaries etc.
| Version/git commit                       | v5.0.1, <commit hash>

### Expected behavior

- no link error with capstone_static.lib

### Actual behavior

- link errors
  - ex) LNK2001: unresolved external symbol mapping_get_op_access

### Steps to reproduce the behavior

- build capstone_static.lib and build pe file with it.

### Additional Logs, screenshots, source code,  configuration dump, ...

Drag and drop zip archives containing the Additional info here, don't use external services or link.
Screenshots can be directly dropped here.

**Comment by Rot127** [comment]
We are probably going to remove those project files. Visual Studio is very much capable of generating them from the cmake files.

But for the `v5` branch this is a welcome fix.

**Comment by Rot127** [comment]
Closes by https://github.com/capstone-engine/capstone/pull/2434
