### ISSUE TITLE
ARM SBC and ADC update_flags always true

### ISSUE THREAD

**Issue by jabba2989** [aquynh/capstone#247]
It seems like that for ```sbc``` and ```adc``` (ARMv7-M Thumb2 Code) ```update_flags``` is always ```true``` even though the ```'s'``` suffix is omitted:

```
0x1000: (EB610102)	sbc.w	r2, r1, r1  
					op_count: 3
						operands[0].type: REG = r2
						operands[1].type: REG = r1
						operands[2].type: REG = r1
					Update-flags: True
0x1004: (EB410102)	adc.w	r1, r1, r2
					op_count: 3
						operands[0].type: REG = r1
						operands[1].type: REG = r1
						operands[2].type: REG = r2
					Update-flags: True
0x1008: (4191)		sbcs     r1, r2
					op_count: 2
						operands[0].type: REG = r1
						operands[1].type: REG = r2
					Update-flags: True
```
I used the official release (capstone 3.0). 
Is this a known issue?

**Comment by aquynh** [comment]
*adc* & *sbc* update CPSR, thus update flags, no?

**Comment by jabba2989** [comment]
Even if ```'s'``` is omitted? From the Reference Manual, it shouldn't (at least the condition flags should not be affected). Are any other bits in ```CPSR``` (or ```APSR``` for Profil-M) affected with absent ```'s'``` suffix?
add,sub and other arithmetic instructions work as expected.

**Comment by aquynh** [comment]
fixed in the *next* branch with your name credited: https://github.com/aquynh/capstone/commit/67fe1c2547b5660609e6d55781caa66db5c13a9f

thanks.

**Comment by jabba2989** [comment]
Works for me. Thanks.

**Comment by aquynh** [comment]
please report if you find similar issues in other instructions.

thanks.
