### ISSUE TITLE
ARM LDR wrong writeback

### ISSUE THREAD

**Issue by jabba2989** [aquynh/capstone#253]
I'm using the latest version (next branch) with the python binding.The  code was compiled for ARMv7-M (Cortex M4F).
It seems that the last case is not properly implemented in Capstone (ARMv7-M Reference Manual Page A8-89):
```
LDR<c><q> <Rt>, [<Rn> {, #+/-<imm>}]           Offset: index==TRUE , wback==FALSE
LDR<c><q> <Rt>, [<Rn>, #+/-<imm>]!              Pre-indexed: index==TRUE , wback==TRUE
LDR<c><q> <Rt>, [<Rn>], #+/-<imm>               Post-indexed: index==FALSE , wback==TRUE
```
As you can see for the last case (post indexed), even though``` !``` is ommitted there happens a write back.
but my results with capstone (next branch) are:
```
0x1000:	ldr	r1, [r2], #4  (Thumb 0xF8521F04)
	op_count: 3
		operands[0].type: REG = r1
		operands[1].type: MEM
			operands[1].mem.base: REG = r2
		operands[2].type: IMM = 0x4
```
As you can see there happens no writeback (I checked it, writeback == false). This also happens for other memory instructions.
Does anyone else experience similar results?

**Comment by aquynh** [comment]
yes, we miss the last case as currently we rely on the presence of *!* to decide if the instruction does writeback.

(1) can you share your Arm manual? (via Dropbox/GoogleDrive etc)

(2) can you list all the similar instructions (with hexcode) having the same issue?

thanks.

**Comment by jabba2989** [comment]
(1) https://www.dropbox.com/sh/x5uwenop1p7ecoi/AABzQzJk-jI2HRzdlAqWqpfba?dl=0

(2) Basically all Thumb Load/Store Instructions from the ARMv7-M IS with similar layout (immediate) should be affected (don't know about the ones from the pure ARM IS):
```
immediate versions of:
LDR, LDRB, LDRH, LDRSB, LDRSH, LDRD, STR, STRB, STRH, STRD
```
I have tested the following instructions:
```
ldrd r1, r3, [r2], #4    machine code: E8F2 1301
ldr r1, [r2], #4           machine code: F852 1B04
ldrb r1, [r2], #4         machine code: F812 1B04
ldrh r1, [r2], #4         machine code: F832 1B04
ldrsh r1, [r2], #4       machine code: F932 1B04
ldrsb r1, [r2], #4       machine code: F912 1B04
str r1, [r2], #4           machine code: F842 1B04
strb r1, [r2], #4         machine code: F802 1B04
strh r1, [r2], #4         machine code: F822 1B04
strd r1, r3, [r2], #4    machine code: E8E2 1301
```
Note that I took them from the ARMv7-M IS and not from the more complex ARMv7-A/R IS
Btw: I recommend http://svr-acjf3-armie.cl.cam.ac.uk/main.cgi

**Comment by aquynh** [comment]
this issue also involved STD & LDC instructions (and the variants).

can you pull the *next* branch, recompile everything (using `./make.sh` to be sure), then confirm your problem is fixed?

thanks.

**Comment by jabba2989** [comment]
I have checked it and it works for me. Thanks for your effort!

**Comment by aquynh** [comment]
please report if you find similar issue with other instructions, thanks.
