### ISSUE TITLE
[BPF] Update the BPF arch to match the current specification

### ISSUE THREAD

**Issue by Roeegg2** [aquynh/capstone#2544]
### Feature

- [ ] New architecture module
- [ ] Support for processor extension
- [x] Add more instruction details (elaborated below)
- [ ] Binding support for: `language`
- [x] Other (elaborated below)

**Describe the feature you'd like**
Update the BPF architecture to the current [specification](https://datatracker.ietf.org/doc/rfc9669/)

**Additional context**
* Add `JUMP32` instruction class
* Add `SDIV`, `SMOD`, `MOVSX` instructions
* Add `ATOMIC` instruction modifier
* Add `XCHG` and `CMPXCHG` instructions

I think that's everything that needs to be updated, but if you do find something I'm missing, please let me know.

**Comment by Roeegg2** [comment]
If it's OK I would love to implement that :)

**Comment by Rot127** [comment]
Sure, go ahead!

**Comment by Roeegg2** [comment]
Apparently since around 2019 eBPF programs can jump backwards in code too, so all of the branch instructions are invalid now too... (offset is interpreted as signed value instead of unsigned)
I suspect there are other similar major changes too. 
Should we add an option for different major eBPF versions? So we can still support older programs.

**Comment by Rot127** [comment]
Quickly skimmed the [kernel ISA](https://docs.kernel.org/bpf/standardization/instruction-set.html#jump-instructions) and the [RFC ISA](https://www.rfc-editor.org/rfc/rfc9669.html#name-jump-instructions). They seem to match. So you can change the `bpf_op_mem::disp` to be a 64bit field and cast it to what the instruction uses.
