### ISSUE TITLE
cs_open aways  return CS_ERR_ARCH

### ISSUE THREAD

**Issue by BaiFeng666** [aquynh/capstone#2545]
```

	csh handle;
	cs_insn* insn;
	size_t count;

	auto r = cs_open(CS_ARCH_X86, CS_MODE_64, &handle);
	printf("error: %d\n", r);
```

i use base example

**Comment by Rot127** [comment]
Please fill out the issue template. What architecture are you on? What branch/Capstone version do you use do you use?

**Comment by BaiFeng666** [comment]
i just use `vcpkg install Capstone:x64-windows-static`

and CPU: AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz
i dont know what is architecture ..

**Comment by Rot127** [comment]
This is an issue with the `vcpkg` package. It builds Capstone by default with all architectures turned off. You have to open an issue in the `vcpkg` repository. Or somehow pass the build option `CAPSTONE_SUPPORT_X86=ON` to `vcpkg`.

**Comment by Starfelll** [comment]
use `vcpkg install Capstone[x86]:x64-windows-static`

**Comment by 1438250** [comment]
Why isn't the entire architecture packaged by default? VCPKG should not be blamed for the problem



> This is an issue with the `vcpkg` package. It builds Capstone by default with all architectures turned off. You have to open an issue in the `vcpkg` repository. Or somehow pass the build option `CAPSTONE_SUPPORT_X86=ON` to `vcpkg`.

**Comment by Rot127** [comment]
> Why isn't the entire architecture packaged by default? 

All architectures are enabled by default, see:
https://github.com/capstone-engine/capstone/blob/6461ed0843a677f0b689488132ce73d2083ca11e/CMakeLists.txt#L80

and 

https://github.com/capstone-engine/capstone/blob/6461ed0843a677f0b689488132ce73d2083ca11e/CMakeLists.txt#L151-L160
