### ISSUE TITLE
Disassembly Error, Incorrect access flag of LEA instruction in x86

### ISSUE THREAD

**Issue by venkyqz** [aquynh/capstone#2562]
### Work environment

| Questions                                | Answers
|------------------------------------------|--------------------
| OS/arch/bits                             | x86_64 Ubuntu 20.04
| Architecture                             | x86_64
| Source of Capstone                  | `git clone`, default on `next` branch.
| Version/git commit                   | v6.0.0, [d7be5f9](https://github.com/capstone-engine/capstone/commit/d7be5f9f9ff701f8b3f502b2f4500ca8bde44c0c)

### Instruction bytes giving faulty results

```
0x48 0x8d 0x14 0x7f
```

### Expected results

```
$ ./cstool -d x64 "488d147f"
 0  48 8d 14 7f                                      lea        rdx, [rdi + rdi*2]
        ID: 332 (lea)
       ...
        op_count: 2
               ...
                operands[1].type: MEM
                ...
                operands[1].access: NONE
                ...
```

### Steps to get the wrong result

With `cstool`:

```
$ ./cstool -d x64 "488d147f"
 0  48 8d 14 7f                                      lea        rdx, [rdi + rdi*2]
        ID: 332 (lea)
       ...
        op_count: 2
               ...
                operands[1].type: MEM
                ...
                operands[1].access: READ
                ...
```        

### Additional Logs, screenshots, source code,  configuration dump, ...
- After enabling the detail option in the capstone with `cs_option(cs_hnd, CS_OPT_DETAIL, CS_OPT_ON)`, we can get the detailed encoding of the x86 instruction with `cs_x86 *cs_x86_insn = &(cs_insn->detail->x86)`. Fields in `cs_x86_op` record the decoding or describe the semantics of x86 instructions. For example, the field `access` in `cs_x86_op` describes how the operand is accessed when executing the instruction. 
- **The semantic of `LEA` is to load the effective address of operands[1] into the operands[0], which means that it will not either read or write the operands[1]**.
- So the `operands[1].access` should be `NONE` instead of `READ`. The Zydis's decoding result shown below aligns with my thoughts. It sets the `action` field of the register operand to `WRITE` and the memory operand to `NONE`.
``` sh
$ ./ZydisInfo -64 "488d147f"
== [    BASIC ] ============================================================================================
   MNEMONIC: lea [ENC: DEFAULT, MAP: DEFAULT, OPC: 0x8D]
     LENGTH:  4
        SSZ: 64
       EOSZ: 64
       EASZ: 64
   CATEGORY: MISC
    ISA-SET: I86
    ISA-EXT: BASE
 EXCEPTIONS: NONE
 ATTRIBUTES: HAS_MODRM HAS_SIB HAS_REX 
  OPTIMIZED: 48 8D 14 7F 

== [ OPERANDS ] ============================================================================================
##       TYPE  VISIBILITY  ACTION      ENCODING   SIZE  NELEM  ELEMSZ  ELEMTYPE                        VALUE
--  ---------  ----------  ------  ------------   ----  -----  ------  --------  ---------------------------
 0   REGISTER    EXPLICIT       W     MODRM_REG     64      1      64       INT                          rdx
 1     MEMORY    EXPLICIT    NONE      MODRM_RM     64      1       0       INT  TYPE  =                AGEN
                                                                                 SEG   =                  ds
                                                                                 BASE  =                 rdi
                                                                                 INDEX =                 rdi
                                                                                 SCALE =                   2
                                                                                 DISP  =  0x0000000000000000
--  ---------  ----------  ------  ------------   ----  -----  ------  --------  ---------------------------

== [      ATT ] ============================================================================================
   ABSOLUTE: lea (%rdi,%rdi,2), %rdx
   RELATIVE: lea (%rdi,%rdi,2), %rdx

== [    INTEL ] ============================================================================================
   ABSOLUTE: lea rdx, qword ptr ds:[rdi+rdi*2]
   RELATIVE: lea rdx, qword ptr ds:[rdi+rdi*2]

== [ SEGMENTS ] ============================================================================================
48 8D 14 7F 
:  :  :  :..SIB
:  :  :..MODRM
:  :..OPCODE
:..REX
```

**Comment by Rot127** [comment]
This looks like Zydis has another definition for the scope of access. In Capstone the operand in this case is considered the "memory".
And because `lea` is reading the memory, the operand is read.

If you want to know how the single register (`rdi`) is accessed for this case, one needs to check the `regs_read`/`regs_write` details.

**Comment by Rot127** [comment]
Capstone basically has a hierarchy like this:

```
operands:
   rdx : register
   ea  : memory (effective address)
      sub-operands of ea:
          rdi : register
```

**Comment by venkyqz** [comment]
> This looks like Zydis has another definition for the scope of access. In Capstone the operand in this case is considered the "memory". And because `lea` is reading the memory, the operand is read.
> 
> If you want to know how the single register (`rdi`) is accessed for this case, one needs to check the `regs_read`/`regs_write` details.



> Capstone basically has a hierarchy like this:
> 
> ```
> operands:
>    rdx : register
>    ea  : memory (effective address)
>       sub-operands of ea:
>           rdi : register
> ```

Well received. Thank you for your explanation. I will close this issue.
