### ISSUE TITLE
[AArch64] ldp instruction misses one immediate operand 

### ISSUE THREAD

**Issue by venkyqz** [aquynh/capstone#2564]
### Work environment

| Questions                                | Answers
|------------------------------------------|--------------------
| OS/arch/bits                             | x86_64 Ubuntu 20.04
| Architecture                             | x86_64
| Source of Capstone                  | `git clone`, default on `next` branch.
| Version/git commit                   | v6.0.0, [e46838](https://github.com/capstone-engine/capstone/commit/e46838ed974948b4446c7c478508409e0000aeaa)

### Instruction bytes giving faulty results

```
0x48 0x83 0xec 0x28
```

### Expected results

It should be:
```sh
 $ ./cstool -d aarch64 "4883ec28"
 0  48 83 ec 28  ldp    w8, w0, [x26], #-0x9c
        ID: 616 (ldp)
        op_count: 3
                operands[0].type: REG = w8
                operands[0].access: WRITE
                operands[1].type: REG = w0
                operands[1].access: WRITE
                operands[2].type: MEM
                        operands[2].mem.base: REG = x26
                        operands[2].mem.disp: 0xffffff64
                        post-indexed: true
                operands[2].access: READ
                operands[3].type: IMM = -0x9c
        Write-back: True
        Registers read: x26
        Registers modified: x26 w8 w0

```

### Steps to get the wrong result

With `cstool`:

```sh
 $ ./cstool -d aarch64 "4883ec28"
 0  48 83 ec 28  ldp    w8, w0, [x26], #-0x9c
        ID: 616 (ldp)
        op_count: 3
                operands[0].type: REG = w8
                operands[0].access: WRITE
                operands[1].type: REG = w0
                operands[1].access: WRITE
                operands[2].type: MEM
                        operands[2].mem.base: REG = x26
                        operands[2].mem.disp: 0xffffff64
                        post-indexed: true
                operands[2].access: READ
        Write-back: True
        Registers read: x26
        Registers modified: x26 w8 w0

```        

### Additional Logs, screenshots, source code,  configuration dump, ...
The fourth immediate operand is missing as illustrated. The problem seems similar to [this one](https://github.com/capstone-engine/capstone/issues/1854)

**Comment by Rot127** [comment]
The immediate is the `operands[2].mem.disp: 0xffffff64`. The immediate is the disponent of the memory address. So it is considered part of the memory operand.

**Comment by venkyqz** [comment]
> The immediate is the `operands[2].mem.disp: 0xffffff64`. The immediate is the disponent of the memory address. So it is considered part of the memory operand.

Well received. Thank you for getting back to me so quickly. I will close this issue.
