### ISSUE TITLE
Python Bindings Binary Distribution

### ISSUE THREAD

**Issue by zachriggle** [aquynh/capstone#260]
Python and PyPI support binary distributions, with the `bdist` target.  In order for this to work, `setup.py` has to not do crazy things to build `libcapstone.so`.

For an example of how to properly distribute a native python `Extension`, see my [pull request](https://github.com/bwall/HashPump/pull/10/files) for the `HashPump` library where I added a Python binding to it.

Specifically, see [setup.py](https://github.com/bwall/HashPump/blob/3f347c415eb27d577c4198f71de171943e097c75/setup.py#L4-L6). The source needs to be inside the Python package, and an `Extension` needs to be created.

This would require moving the `bindings/` directory out of the `capstone` repository, and inverting the relationship.

**Comment by zachriggle** [comment]
It also looks like the Python bindings for `capstone` are not proper bindings, but rather use `ctypes` to shuttle data around.

A native extension would need to be written to expose the APIs in a Pythonic manner.

See [hashpumpy.cpp](https://github.com/bwall/HashPump/blob/3f347c415eb27d577c4198f71de171943e097c75/hashpumpy.cpp) for an example of this.

**Comment by aquynh** [comment]
yes, the current binding uses `ctypes` because it is easier to implement.

fee free to fix `setup.py` if you can & send us PR, thanks.

**Comment by zachriggle** [comment]
This is obsolete because capstone is self-building when installed via pip
