### ISSUE TITLE
ARM IT-block bug

### ISSUE THREAD

**Issue by pzread** [aquynh/capstone#264]
Hi,
I found that ITBlock->size is set to 0 every time _ARM_getInstruction and _Thumb_getInstruction called.
```
ARMDisassembler.c
line 453:    ud->ITBlock.size = 0;
line 697:    ud->ITBlock.size = 0;
```
But since it's used to check if the instructions after ARM_INS_IT are in IT-block or not, set to 0 cause IT-block's instructions are incorrectly moved out of the block and their condition flag go wrong.

Incorrect output
```
0x000104c2 ite eq
0x000104c4 movs r0, #0x17
0x000104c6 mov.w r0, #-1
```
Correct output (after remove those two lines
```
0x000104c2 ite eq
0x000104c4 moveq r0, #0x17
0x000104c6 movne.w r0, #-1
```

**Comment by aquynh** [comment]
On Sat, Feb 14, 2015 at 10:23 PM, PZ Read <notifications@github.com> wrote:

> Hi,
> I found that ITBlock->size is set to 0 every time _ARM_getInstruction and
> _Thumb_getInstruction called.
>
> ARMDisassembler.c
> line 451:    ud->ITBlock.size = 0;
> line 692:    ud->ITBlock.size = 0;
>
> But since it's used to check if the instructions after ARM_INS_IT are in
> IT-block or not, set to 0 causes IT-block's instructions are incorrectly
> moved out and their condition flag go wrong.
>
> Incorrect output
>
> 0x000104c2 ite eq
> 0x000104c4 movs r0, #0x17
> 0x000104c6 mov.w r0, #-1
>
> Correct output (after remove those two lines
>
> 0x000104c2 ite eq
> 0x000104c4 moveq r0, #0x17
> 0x000104c6 movne.w r0, #-1
>
>
please provide the input (hexcode) that triggers the problem, so i can test
it.

thanks.

**Comment by aquynh** [comment]
On Sat, Feb 14, 2015 at 11:15 PM, Nguyen Anh Quynh <aquynh@gmail.com> wrote:

>
>
> On Sat, Feb 14, 2015 at 10:23 PM, PZ Read <notifications@github.com>
> wrote:
>
>> Hi,
>> I found that ITBlock->size is set to 0 every time _ARM_getInstruction and
>> _Thumb_getInstruction called.
>>
>> ARMDisassembler.c
>> line 451:    ud->ITBlock.size = 0;
>> line 692:    ud->ITBlock.size = 0;
>>
>> But since it's used to check if the instructions after ARM_INS_IT are in
>> IT-block or not, set to 0 causes IT-block's instructions are incorrectly
>> moved out and their condition flag go wrong.
>>
>> Incorrect output
>>
>> 0x000104c2 ite eq
>> 0x000104c4 movs r0, #0x17
>> 0x000104c6 mov.w r0, #-1
>>
>> Correct output (after remove those two lines
>>
>> 0x000104c2 ite eq
>> 0x000104c4 moveq r0, #0x17
>> 0x000104c6 movne.w r0, #-1
>>
>>
> please provide the input (hexcode) that triggers the problem, so i can
> test it.
>

looks like your fix (removing those 2 lines) is correct.
would you mind sending a pull request on Github?

(do not forget to provide the input triggering the problem for track
record, however)


thanks.

**Comment by pzread** [comment]
OK, here is the sample hex code
`\x0C\xBF\x17\x20\x4F\xF0\xFF\x30`

**Comment by pzread** [comment]
confirmed fixed. thanks
