### ISSUE TITLE
cmp al, XX : bad operand size for XX

### ISSUE THREAD

**Issue by joelpx** [aquynh/capstone#285]
binary = b"\x3c\x12\x80\xfc\x12\x80\xfb\x12\x80\xff\x12"
md = Cs(CS_ARCH_X86, CS_MODE_64)
md.detail = True
for i in md.disasm(binary, len(binary)):
    print("%s %s" % (i.mnemonic, i.op_str))
    j = 0
    for op in i.operands:
        print("  %d: size=%d" % (j, op.size))
        j += 1

Result : 

cmp al, 0x12
  0: size=1
  1: size=8
cmp ah, 0x12
  0: size=1
  1: size=1
cmp bl, 0x12
  0: size=1
  1: size=1
cmp bh, 0x12
  0: size=1
  1: size=1

Only for "cmp al, 0x12" the size of the second operand is 8.

**Comment by aquynh** [comment]
fixed in the `next` & `master` branch, please confirm, thanks.

**Comment by joelpx** [comment]
It looks good.
