### ISSUE TITLE
[x86] Wrong Operand Size (shl esi, 8)

### ISSUE THREAD

**Issue by cynecx** [aquynh/capstone#296]
Basically when disassembling "shl esi, 8" (0xC1, 0xE6, 0x08) the second operand "8" has a wrong size.

The member "cs_x86_op::size" has the value of 0x04 but shouldn't it be 0x01 ?

According to http://ref.x86asm.net/coder32.html#xC1 the second operand should be an imm8 so the correct size would be one byte...

**Comment by aquynh** [comment]
Thanks for reporting. This issue would take time to fix, as it is harder to
track the size of immediate operands.

We care more about register and memory operands, which are vital for
analysis apps. So while we need to fix this, the issue itself does not
really matter much for now.

**Comment by aquynh** [comment]
this instruction is actually `SHL32ri`, so the size of immediate operand is 4.

this problem with the size of immediate operands has been fixed in the "next" branch now. let me know if you still find something wrong, thanks.

**Comment by cynecx** [comment]
Yep, it works :) Thanks.

**Comment by obs1dium** [comment]
>this instruction is actually SHL32ri, so the size of immediate operand is 4.

It exclusively uses 8-bit immediate values, though.
