### ISSUE TITLE
Some ARM memory ops improperly decoded by capstone

### ISSUE THREAD

**Issue by igotti-google** [aquynh/capstone#297]
T2 encodings of LDR and STR allows for memory operands like
[Rn,Rm{,LSL #imm2}]
which cannot be represented by Capstone's
typedef struct arm_op_mem {
        unsigned int base;      // base register
        unsigned int index;     // index register
        int scale;      // scale for index register (can be 1, or -1)
        int disp;       // displacement/offset value
} arm_op_mem;

unless scale is (1 << imm2), which doesn't seem to be the case. Maybe better approach is to add 
int index_shift

**Comment by aquynh** [comment]
i think this has been fixed long ago in the `next` branch (but not in *3.x* series). see this issue https://github.com/aquynh/capstone/issues/265, and let me know if that solves your problem.

for sample code, see `tests/test_arm.c` (or `bindings/python/test_arm.py` if you prefer Python code)

thanks.

**Comment by igotti-google** [comment]
Thanks for the info. Are there plans of releasing stable version of 'next' as 4.0 in foreseeable future?

**Comment by aquynh** [comment]
i want to implement the new API `cs_regs_access()` for all the architectures before v4.0 is released.

http://capstone-engine.org/op_access.html    <=== on X86 is supported at the moment.

this will take time, but if community join in to help, the version 4.0 will be out sooner.

https://github.com/aquynh/capstone/wiki/Capstone-4.0---New-API-to-provide-explicit-registers
