### ISSUE TITLE
Regressions on an x86 opcode disassembly

### ISSUE THREAD

**Issue by Maijin** [aquynh/capstone#298]
Hi o/

We've ( @radare project) detected a regression on following opcode on next branch:
* f390 /\ pause
* 66f3f20f59ff /\ mulsd xmm7, xmm7
* f2660f59ff /\ mulsd xmm7, xmm7

[XX]  148  x86: x86.cs: [PAUSE]               
Command:  /usr/bin/radare2 -e cfg.plugins=false -e scr.color=0 -N -q -i /tmp/r2-regressions//x86-rad.KdL4jL   malloc://32 > /tmp/r2-regressions//x86-out.Thzhs8 2> /tmp/r2-regressions//x86-err.yEvNYP
File: malloc://32
Script: 
e asm.arch=x86.cs
e asm.bits=32
wx f390
pi 1

[XX]  1  x86_sse: x86.cs: [MULSD]               

Command:  /usr/bin/radare2 -e cfg.plugins=false -e scr.color=0 -N -q -i /tmp/r2-regressions//x86_sse-rad.L6H47N   malloc://32 > /tmp/r2-regressions//x86_sse-out.Yxu2Va 2> /tmp/r2-regressions//x86_sse-err.eNvvRt
File: malloc://32
Script: 
e asm.arch=x86.cs
e asm.bits=32
wx 66f3f20f59ff
pi 1

Diff: --- /tmp/r2-regressions//x86_sse-exp.hKlIjR	2015-03-25 19:11:12.315373666 +0100
+++ /tmp/r2-regressions//x86_sse-out.Yxu2Va	2015-03-25 19:11:12.327373667 +0100
@@ -1 +1 @@
-mulsd xmm7, xmm7
+invalid

[XX]  4  x86_sse: x86.cs: [MULSD]               

Command:  /usr/bin/radare2 -e cfg.plugins=false -e scr.color=0 -N -q -i /tmp/r2-regressions//x86_sse-rad.wQiTx4   malloc://32 > /tmp/r2-regressions//x86_sse-out.MSqu7B 2> /tmp/r2-regressions//x86_sse-err.kdUD1m
File: malloc://32
Script: 
e asm.arch=x86.cs
e asm.bits=32
wx f2660f59ff
pi 1

Diff: --- /tmp/r2-regressions//x86_sse-exp.1KIbvH	2015-03-25 19:11:12.363373667 +0100
+++ /tmp/r2-regressions//x86_sse-out.MSqu7B	2015-03-25 19:11:12.371373667 +0100
@@ -1 +1 @@
-mulsd xmm7, xmm7
+invalid

Regards,

https://github.com/radare/radare2-regressions

**Comment by aquynh** [comment]
When did this regression start?

Does this happen with master branch?

**Comment by aquynh** [comment]
Would be great if you can do `git bisec` to pinpoint the commit causing the issue.

Thanks.

**Comment by Maijin** [comment]
Doesn't happen with master branch

**Comment by radare** [comment]
we have scripts in r2 to automate bisecting regressions and a full testsuite which is constantly growing, capstone should have the same its just few lines of shellscript.

All this stuff must be done automatically, it’s not human’s work.

**Comment by aquynh** [comment]
Can you do a PR to put that script under suite/ ? 

Thanks

**Comment by radare** [comment]
that script doesnt exists for capstone. the ones we have depend on r2, i have checked out a bit the suite/ directory and it’s full of awful shellscripts and the python scripts are testing the system capstone and not the one from git.

so the pullreq will require a bit of rewrite and i dont think having an r2 script in there will benefit because you already have your own disassembler test, but its just incomplete, just add that instruction in the suite, and define a travis or jenkins to build that thing on every commit to detect regressions at time.

**Comment by aquynh** [comment]
On Mon, Mar 30, 2015 at 7:20 PM, radare <notifications@github.com> wrote:

> that script doesnt exists for capstone. the ones we have depend on r2, i
> have checked out a bit the suite/ directory and it’s full of awful
> shellscripts and the python scripts are testing the system capstone and not
> the one from git.
>
> so the pullreq will require a bit of rewrite and i dont think having an r2
> script in there will benefit because you already have your own disassembler
> test, but its just incomplete, just add that instruction in the suite, and
> define a travis or jenkins to build that thing on every commit to detect
> regressions at time.
>
>
these approaches are not mutually exclusive, so we can do both at the same
time.
it is good to be able to bisect automatically to debug issues that are not
exposed by test suite.

**Comment by radare** [comment]
This is why i have r2 regressions in a separate repository, so i can use the r2-v script to build several versions of r2 and test every commit against a specific test or group of tests easily. Its not fully automated, but travis is helping a lot too. I would recommend you to use it too.

Also, our tests can be easily translated to yours by using an awk oneliner.

Sorry i am very busy these days and i dont have time to do this for your project. Let me know if you have any question about it

**Comment by aquynh** [comment]
i have other priorities now, so will get back to this when possible.
if community can step up implementing some ideas here, then great.

**Comment by aquynh** [comment]
@maijin: on the 2 code below:

- 66f3f20f59ff =  mulsd xmm7, xmm7
- f2660f59ff =  mulsd xmm7, xmm7

can you tell me where did you get these code? these look like bogus code to me, thus flagging as *invalid* instructions by the *next* branch, and i think that is right.

on the *pause* instruction, it was fixed with the latest commit in the *next* branch, please confirm.

thanks.

**Comment by aquynh** [comment]
oops sorry there were some mistakes on my side. fixed all the code you reported in the `next` branch now, please confirm.

**Comment by Maijin** [comment]
ok it works :+1:
