### ISSUE TITLE
LEA instruction shouldn't have READ flag set.

### ISSUE THREAD

**Issue by chaplja** [aquynh/capstone#301]
As shown here: http://capstone-engine.org/op_access.html - access flags for LEA instruction are: "operands[1].access: READ". It should be neither READ or WRITE, simply zero or another special flag, but that is up to you. The memory calculated in LEA is not accessed in any way.

**Comment by aquynh** [comment]
good catch! fixed now in http://capstone-engine.org/op_access.html

this API is new, so no doubt we will have bugs here and there. please report if you find something else broken, thanks.

**Comment by aquynh** [comment]
Here is the fix for this issue (with your name credited): https://github.com/aquynh/capstone/commit/228ec96de5ee2766f9867854e7b822d4d8260aee

Thanks.

**Comment by WorksButNotTested** [comment]
These changes were reverted in https://github.com/aquynh/capstone/commit/aceb2bb8a14e3fcc4554f77a775c2d578177e556
