### ISSUE TITLE
negative byte value is expanded

### ISSUE THREAD

**Issue by radare** [aquynh/capstone#305]
wrong negative byte value
```
$ rasm2 -d 348b
xor al, 0xffffff8b
```

should be like udis:
```
$ rasm2 -a x86.udis -d 348b
xor al, 0x8b
```

**Comment by aquynh** [comment]
fixed in the *next* branch, thanks.

**Comment by learn-more** [comment]
In case someone stumbles upon this and is wondering what the cause is: sign extension.
Explained here: http://en.wikipedia.org/wiki/Sign_extension
