### ISSUE TITLE
LEA EAX, DWORD [EAX] ->  LEA EAX,  [EAX]

### ISSUE THREAD

**Issue by Maijin** [aquynh/capstone#306]
The following instruction doesn't contain the "dword" indication anymore. Bug?

[XX]  232  x86: x86.cs: [LEA EAX, DWORD [EAX]]

Command:  /usr/bin/radare2 -e cfg.plugins=false -e scr.color=0 -N -q -i /tmp/r2-regressions//x86-rad.dEg0TF   malloc://32 > /tmp/r2-regressions//x86-out.2yKewh 2> /tmp/r2-regressions//x86-err.deNScP
File: malloc://32
Script: 
e asm.arch=x86.cs
e asm.bits=32
wx 8d00
pi 1

Diff: --- /tmp/r2-regressions//x86-exp.fA6smk	2015-04-04 15:48:54.749199540 +0200
+++ /tmp/r2-regressions//x86-out.2yKewh	2015-04-04 15:48:54.757199541 +0200
@@ -1 +1 @@
-lea eax, dword [eax]
+lea eax, [eax]

**Comment by aquynh** [comment]
yes, there was some changes in how the core handles LEA. 

but this is not a bug, so any reason why you prefer the old way (having `DWORD PTR` in front of `[EAX]`)?

**Comment by hlide** [comment]
As long as they could not lead to any ambiguity, I see no reason indeed. The only possible data size are: WORD, DWORD and QWORD but we can already deduce it from destination register (for instance, AX, EAX and RAX in LEA [R|E]AX, []). You could say BYTE, WORD, DWORD are mostly necessary only when they are destinations and source is an immediate, which is not the case for LEA.

**Comment by Maijin** [comment]
I was just asking because most of the opcodes have such indication but I get the point of @hlide Thanks :+1:
