### ISSUE TITLE
Use of uninitialized variable in the ARM disassembler

### ISSUE THREAD

**Issue by trufae** [aquynh/capstone#312]
the android ndk surprised me today with this warning:
```
arch/ARM/ARMInstPrinter.c: In function 'printRegisterList':
arch/ARM/ARMInstPrinter.c:1470:84: warning: 'access' may be used uninitialized in this function [-Wmaybe-uninitialized]
    MI->flat_insn->detail->arm.operands[MI->flat_insn->detail->arm.op_count].access = access;
```

For me this looks like a bug in the NDK, but maybe im missing something. I guess the code will be more readable and easy to maintain if grouped the whole implementation inside #ifdef CAPSTONE_DIET ... instead of having multiple blocks and conditionals inside each loop (which makes loops slow).

**Comment by aquynh** [comment]
the idea is that `access` is only available in non-diet mode. the reason is that diet mode is designed to be as small as possible. should we change this to make this field always available?

and this warning is clearly wrong to me.

**Comment by radare** [comment]
I have found several other bugs in many versions of the android ndk. Its
definitevly a crappy toolchain. So feel free to close this bug. But i just
wanted to spot that the diet ifdef is making the code a bit dirty in the
way that its used.

**Comment by learn-more** [comment]
The warning itself is valid,
since the compiler cannot deduce that no one is changing that condition in the meantime.

A simple solution would be to initialize it to 0, which is good practice anyway.

**Comment by aquynh** [comment]
fixed with this PR: https://github.com/aquynh/capstone/pull/329.

thanks
