### ISSUE TITLE
Target register not in implicit register for JMP and CALL on x86/AMD64

### ISSUE THREAD

**Issue by zachriggle** [aquynh/capstone#334]
This is similar to #321.  For JMP and CALL instructions, the target register is not in the list of registers read.

This is true for any of the permutations of the instruction, e.g. `jmp eax`, `jmp [eax]`, `jmp [eax+ebx*4+0x10]` etc.

```py
from capstone import *
from capstone.arm import *

md = Cs(CS_ARCH_X86, CS_MODE_32)
md.detail = True

for i in md.disasm('\xff\xe0', 0x38):
    print "0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str)

    if len(i.regs_read) > 0:
        print("\tImplicit registers read: "),
        for r in i.regs_read:
            print("%s " %i.reg_name(r)),
        print

    if len(i.regs_write) > 0:
        print("\tImplicit registers written: "),
        for r in i.regs_read:
            print("%s " %i.reg_name(r)),
        print

    if len(i.groups) > 0:
        print("\tThis instruction belongs to groups:"),
        for g in i.groups:
            print("%u" %g),
        print
```

```
0x38:   jmp     eax
        This instruction belongs to groups: 161 1
```

**Comment by zachriggle** [comment]
Actually it looks like this extends to most instructions, e.g. `mov ebx, [eax]` does not claim to read either register.

**Comment by aquynh** [comment]
is this the "master" or "next" branch? your sample code works fine on the "next" branch now.

for other cases, please provide the hexcode for testing.

thanks

**Comment by zachriggle** [comment]
This was on `next`, but it looks like the install script for `setup.py` doesn't work properly.

I was able to successfully generate the bindings with the sdist target.
