### ISSUE TITLE
(SOLVED) Capstone compile issues on Dev c++(Mingw) Windows 7(64) and XP.

### ISSUE THREAD

**Issue by conii** [aquynh/capstone#335]
#######################################################################
Hi all.Firstly sorry is my bad English.
Yesterday i download capstone -3.0.2.zip from official capstone site.
In my office pc Windows 7 64bit when extract zip file and run test.exe its sucessfully run.
Small output:
#########################################################################
C:\Users\Devel\Desktop>test.exe
> ****************
> Platform: X86 16bit (Intel syntax)
> Code: 0x8d 0x4c 0x32 0x08 0x01 0xd8 0x81 0xc6 0x34 0x12 0x00 0x00
> Disasm:
> 0x1000: lea             cx, word ptr [si + 0x32]
> 0x1003: or              byte ptr [bx + di], al
> 0x1005: fadd            dword ptr [bx + di + 0x34c6]
> 0x1009: adc             al, byte ptr [bx + si]
> 0x100b:
>
> ****************
> Platform: X86 32bit (ATT syntax)
> Code: 0x8d 0x4c 0x32 0x08 0x01 0xd8 0x81 0xc6 0x34 0x12 0x00 0x00
> Disasm:
> 0x1000: leal            8(%edx, %esi), %ecx
> 0x1004: addl            %ebx, %eax
> 0x1006: addl            $0x1234, %esi
> 0x100c:
##############################################################
But i cannot run this file in my XP error says:Not valid PE.

Over compile time in Dev c++ 
I manual adding include directory in compiler include directory also library file add in my project all is ok.
I copy and paste example source from offical site.
And press F7 button to compile script Compiler says error:
#########################################################################
Compiler: Default compiler
Building Makefile: "C:\Users\Devel\Desktop\Makefile.win"
Executing  make...
mingw32-make.exe -f "C:\Users\Devel\Desktop\Makefile.win" all
gcc.exe -c main.c -o main.o -I"C:/MinGW/include"  -I"C:/MinGW/include/curl" 
-I"C:/MinGW/include/openssl" 
-I"C:/Users/Devel/Dropbox/capstone-3.0.2-win32/capstone-3.0.2-win32/include"   
-masm=intel

gcc.exe main.o  -o "Project1.exe" -L"C:/MinGW/lib" -L"C:/MinGW/lib/curl"
-L"C:/MinGW/lib/openssl"
../Dropbox/capstone-3.0.2-win32/capstone-3.0.2-win32/capstone.lib  

Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
../Dropbox/capstone-3.0.2-win32/capstone-3.0.2-win32/capstone.lib(CMakeFiles/capstone-static.dir/cs.c.obj):(.text$mn+0x7):
undefined reference to `__security_cookie'
../Dropbox/capstone-3.0.2-win32/capstone-3.0.2-win32/capstone.lib(CMakeFiles/capstone-static.dir/cs.c.obj):(.text$mn+0x4e):
undefined reference to `@__security_check_cookie@4'
c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe:
../Dropbox/capstone-3.0.2-win32/capstone-3.0.2-win32/capstone.lib(CMakeFiles/capstone-static.dir/cs.c.obj):
bad reloc address 0x4e in section `.text$mn'
c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: final link
failed: Invalid operation
collect2.exe: error: ld returned 1 exit status

C:\Users\Devel\Desktop\Makefile.win:27: recipe for target 'Project1.exe' failed

mingw32-make.exe: *** [Project1.exe] Error 1

Execution terminated
##########################################################################
On my XP compiler error:
###########################################################################
Warning: .drectve `/DEFAULTLIB:"LIBCMT" /DEFAULTLIB:"OLDNAMES" ' unrecognized 
Warning: .drectve `/DEFAULTLIB:"LIBCMT" /DEFAULTLIB:"OLDNAMES" ' unrecognized 
Warning: .drectve `/DEFAULTLIB:"LIBCMT" /DEFAULTLIB:"OLDNAMES" ' unrecognized 
Warning: .drectve `/DEFAULTLIB:"LIBCMT" /DEFAULTLIB:"OLDNAMES" ' unrecognized 
Warning: .drectve `/DEFAULTLIB:"LIBCMT" /DEFAULTLIB:"OLDNAMES" ' unrecognized

**Comment by aquynh** [comment]
can you confirm that you are using **Windows XP 64bit**, and you downloaded the right file `http://capstone-engine.org/download/3.0.2/capstone-3.0.2-win64.zip`, but its `test.exe` fails to work ?

**Comment by mrexodia** [comment]
the problem (still) is that capstone has a dll, but no corresponding .lib files. You are trying to statically link capstone crossing MinGW and Visual Studio (which does not work). Either compile capstone using MinGW completely yourself or dynamically link using [these](https://mega.co.nz/#!T1IyDYwT!thCZPW0l8n4YHoMtt0uCQRDReNa74MtflT5tU3OoGjE) lib files (this requires you to have capstone.dll in your program directory).

**Comment by conii** [comment]
Oh yes!
mrexodia today i download your uploaded file.İ forgot GCC library file extension (*.a) :dancers: 
And I renew compile source its okey!
Thank mrexodia and aquynh(For such support) and i want to apologize for tired you.
Grateful!

**Comment by aquynh** [comment]
so this means `capstone.lib` in `http://capstone-engine.org/download/3.0.2/capstone-3.0.2-win64.zip` does not work for you?

is there any way to compile libraries that work for both MingW & MSVC?

**Comment by conii** [comment]
Maybe yes.
Because Mingw compiler cannot support Microsoft Compile Static Library such as (*.lib) file!
Mingw static library is *.a file.
I could write code over Windows Api LoadLibrary and GetProcAddress for dynamically call capstone.dll file but its too long.as for MSVC I dont test MSVC because i do not use.
But test.exe works in Windows 7(32 and 64 i tested it).

**Comment by aquynh** [comment]
@mrexodia: how did you compile with MingW on Windows? did you just run "make.sh"?

(i dont have a machine with MingW, so cannot test this)

**Comment by mrexodia** [comment]
Didn't compile with MinGW. I used `gendef` and `dlltool` to generate the file from `capstone.dll`

See this source for more info: https://bitbucket.org/mrexodia/genlib/src/master/main.cpp

I'll try compiling with MinGW in a few minutes.

**Comment by aquynh** [comment]
so could you compile with MingW?

**Comment by mrexodia** [comment]
Ah, thanks for reminding me! I'll try it later today...

**Comment by aquynh** [comment]
so did you try with MingW yet?

**Comment by mrexodia** [comment]
Tested just now, CMake is working good. Here are my steps:

1. Install MinGW from [here](https://sourceforge.net/projects/mingw-w64)
2. Then go to the installation directory and open `mingw-w64.bat` (this will open a new command shell)
3. Go to the capstone clone directory
4. Run `cmake -G "MinGW Makefiles"
5. Run `mingw32-make`

This only generates x64 binaries. I think for x32 you need some different options or something. I will figure it out.

**Comment by aquynh** [comment]
On Fri, May 1, 2015 at 12:13 AM, mrexodia <notifications@github.com> wrote:

> Tested just now, CMake is working good. Here are my steps:
>
>    1. Install MinGW from here <https://sourceforge.net/projects/mingw-w64>
>    2. Then go to the installation directory and open mingw-w64.bat (this
>    will open a new command shell)
>    3. Go to the capstone clone directory
>    4. Run `cmake -G "MinGW Makefiles"
>    5. Run mingw32-make
>
> This only generates x64 binaries. I think for x32 you need some different
> options or something. I will figure it out.
>
thanks for the report.

have you tried with ./make.sh? if you find any issues with it, a PR would
be awesome!

**Comment by mrexodia** [comment]
Windows doesn't support `.sh` files so cmake is the only way.

**Comment by aquynh** [comment]
On Fri, May 1, 2015 at 12:55 AM, mrexodia <notifications@github.com> wrote:

> Windows doesn't support `.sh` files so cmake is the only way.
>

to run "make.sh" on Windows, i guess you can run MingW inside Cygwin

**Comment by mrexodia** [comment]
Yea, but cygwin produces files that only run with the cygwin
libraries,which sucks. CMake works flawlessly and is much easier.

**Comment by aquynh** [comment]
FYI, the issue of "not valid PE" on Windows XP has been fixed in the latest released 3.0.3, so now the same binaries work on all Windows platforms (Windows XP & later versions)

http://capstone-engine.org/Version-3.0.3.html

**Comment by crazybytes** [comment]
To get rid of the undefined reference to __security_cookie you need to include the bufferoverflowu.lib to the linker.
