### ISSUE TITLE
Makefile:180: recipe for target 'capstone-build' failed

### ISSUE THREAD

**Issue by 230v** [aquynh/capstone#343]
make[2]: *** No rule to make target 'libcapstone.a'.  Stop.
Makefile:180: recipe for target 'capstone-build' failed
make[1]: *** [capstone-build] Error 2
Makefile:31: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by aquynh** [comment]
Can you provide more details: how did you compile, your enviroment, Capstone version etc?

**Comment by 230v** [comment]
I want compile radare2, he auto clone latest capstone from git. Enviroment - Arch Linux i686, all updates.
