### ISSUE TITLE
for "rcl %edx, $1 (D1 D2), capstone does not recognize constant immediate operand.

### ISSUE THREAD

**Issue by bipulr** [aquynh/capstone#346]
I noticed that capstone does not correctly decode byte code corresponding to rcl %edx, $1, but it decodes correctly rol %edx, $1. 

The reason I can see that in OpInfo, value corresponding to RCL32r1  is so low,  22542U, that "switch ((Bits >> 20) & 31) { " in printInstruction() evaluates to zero and "case 14: op_addImm(MI, 1)" is not triggered. That is not the case with rol.

Can you please let me know how arch/X86/X86GenAsmWriter1.inc  file is generated. I do not see any tool integrated in capstone package. How I can fix this??

**Comment by aquynh** [comment]
this is correctly handled in Intel syntax, but not in AT&T syntax. i thought that was how AT&T handled this, but it seems every other disassemblers do it differently.

hope to fix this issue this weekend, if i have enough time.

regarding your question on how those .inc files are generated: we reuse LLVM code, and those files are originally generated by LLVM. we have to format them to be suitable for Capstone. some manual step is involved here however, so it is not totally automatic.

find more about this here: http://llvm.org/docs/TableGen/.

thanks.

**Comment by bipulr** [comment]
Thanks for the reply.

But, by default syntax is CS_OPT_SYNTAX_INTEL as set in init() in arch/X86/X86Module.c. Right?? I am using CS_OPT_SYNTAX_INTEL only.

**Comment by bipulr** [comment]
I think in OpInfo entry corresponding to , RCL8r1, RCL16r1, RCL32r1 and RC64r1 need to be ORed with 14 << 20. This is how I get them correctly now. Same for corresponding RCR variation.

**Comment by aquynh** [comment]
yes, Intel is the default syntax, and i dont think you will have this problem, which is only for AT&T syntax.

no worry, i will fix all of the similar instructions.

thanks.

**Comment by bipulr** [comment]
I am facing the problem with intel syntax also. I tried with the test program in capstone package as well. Even if you check http://www.cenigma.org/ which is based on capstone, that also decodes rcl/rcr with const $1 operand incorrectly.

As of now I have changed corresponding values in OpInfo by ORing it with 14 << 20, and so far it is working correctly after that. But a proper fix would be always desirable.

Thanks.

**Comment by aquynh** [comment]
Cenigma is still using the older version of Capstone, hence you see the issue.

I am quite sure this problem for Intel syntax has been fixed long ago in the "next" branch, where we put all the development effort now. So check it out yourself to see if your issue is solved: https://github.com/aquynh/capstone/tree/next. Just in case, you can always get the latest code from "next" branch at https://github.com/aquynh/capstone/archive/next.zip.

Expect to see this fixed in "next" for AT&T syntax soon.

**Comment by bipulr** [comment]
Sorry it was closed by mistake

**Comment by bipulr** [comment]
In master branch this issue is there, but yes in next branch this issue is fixed for intel syntax.

So I think I must start using next branch. Please advise.

**Comment by aquynh** [comment]
branch "master" has fixed this issue now. let me know if you still have problems.

thanks.

**Comment by bipulr** [comment]
Ok, I tried this on master and it is now working for intel syntax.

**Comment by aquynh** [comment]
the issue has been fixed for AT&T in "master", too.

FYI, the "master" was released as 3.0.3 few days ago & included this fix.

will fix this for the "next" branch when i have more time.

**Comment by aquynh** [comment]
fixed this issue in the "next" branch for both AT&T and Intel syntax: https://github.com/aquynh/capstone/commit/fb59de4a87e76c86d2e7f68a791b4fd755172b6a

let me know if you still have issues, thanks.
