### ISSUE TITLE
jump/call/rip-relative displacement wrong?

### ISSUE THREAD

**Issue by mrexodia** [aquynh/capstone#347]
When you have these instructions
```asm
77833BED | CC                  | int3                              |
77833BEE | EB 07               | jmp ntdll.77833BF7                | ; <= talking about this one
77833BF0 | 33 C0               | xor eax,eax                       |
77833BF2 | 40                  | inc eax                           |
77833BF3 | C3                  | ret                               |
77833BF4 | 8B 65 E8            | mov esp,dword ptr ss:[ebp-18]     |
77833BF7 | C7 45 FC FE FF FF FF| mov dword ptr ss:[ebp-4],FFFFFFFE | ; <= destination
77833BFE | E8 62 08 F9 FF      | call ntdll.777C4465               |
```

capstone will disassemble the instruction correctly (as `jmp 77833BF7`), but in the structural representation you get an immediate operand with the value `77833BF5`. This feels wrong to me (because you have to add the instruction size if you write your custom disassembler with syntax highlighting).

Same happens to `call` and rip-relative instructions (with rip-relative you need to do `instruction address + operand.mem.displ + instruction.size` to get the destination address).

Is this desired behavior, if it is was there any documentation for it? I struggled with it badly at first :+1:

**Comment by aquynh** [comment]
On Fri, May 1, 2015 at 6:53 AM, mrexodia <notifications@github.com> wrote:

> When you have these instructions
>
> 77833BED | CC                       | int3                                    |77833BEE | EB 07                    | jmp ntdll.77833BF7                      | ; <= talking about this one77833BF0 | 33 C0                    | xor eax,eax                             |77833BF2 | 40                       | inc eax                                 |77833BF3 | C3                       | ret                                     |77833BF4 | 8B 65 E8                 | mov esp,dword ptr ss:[ebp-18]           |77833BF7 | C7 45 FC FE FF FF FF     | mov dword ptr ss:[ebp-4],FFFFFFFE       | ; <= destination77833BFE | E8 62 08 F9 FF           | call ntdll.777C4465                     |
>
> capstone will disassemble the instruction correctly (as jmp 77833BF7),
> but in the structural representation you get an immediate operand with the
> value 77833BF5. This feels wrong to me (because you have to add the
> instruction size if you write your custom disassembler with syntax
> highlighting).
>
> Same happens to call and rip-relative instructions (with rip-relative you
> need to do instruction address + operand.mem.displ + instruction.size to
> get the destination address).
>

do you mean the disassembly output & operands[].imm have different values
in this case?

is this with "master" or "next" branch?

**Comment by mrexodia** [comment]
yea, i believe it's with the latest release (so i assume thats `master`). I'll check `next` soon.

**Comment by aquynh** [comment]
at least this seems to be OK in the "next" branch, which is always the latest code.

btw, the "master' branch is just for the stable release 3.x. meanwhile, "next" will be out as v4.0 when released.

**Comment by mrexodia** [comment]
yea, it was fixed. thanks!
