### ISSUE TITLE
ARM: lsr id != ARM_INS_LSR

### ISSUE THREAD

**Issue by joelpx** [aquynh/capstone#348]
The id of lsr is equal to ARM_INS_MOV. It's the same for lsl.

```
#!/usr/bin/env python3
from capstone import CS_ARCH_ARM, Cs
from capstone.arm import ARM_INS_MOV, ARM_INS_LSR

binary = b"\x23\x32\xa0\x11"

md = Cs(CS_ARCH_ARM, CS_ARCH_ARM)
md.detail = True

print("mov:", ARM_INS_MOV, ", lsr:", ARM_INS_LSR)

for i in md.disasm(binary, 0):
    print("id:", i.id, i.mnemonic, i.op_str)
```

Result : 
```
mov: 80 , lsr: 412
id: 80  lsrne r3, r3, #4
```

**Comment by joelpx** [comment]
In fact it's good, the second register contains the shift, and the instruction can be interpreted like a mov. But is it normal that the id is equal to ARM_INS_MOV ?

**Comment by aquynh** [comment]
this is a bug. fixed with the latest commit to the "next" branch, please confirm.

thanks.

**Comment by aquynh** [comment]
fyi, in the case you reported, LSR is just alias of MOV, hence your observation that it can also be interpreted like MOV.

**Comment by joelpx** [comment]
Fixed. Thanks.
