### ISSUE TITLE
x86: instruction int takes a byte

### ISSUE THREAD

**Issue by joelpx** [aquynh/capstone#351]
Before upgrading to the next branch, the immediate of `int 0x80` was equal to 128. Now it's -128 so I checked the operand size, and it's wrong. The size is actually equal to 4 instead of 1.

**Comment by aquynh** [comment]
fixed the immediate value of INT (and few others) in the "next" branch now, please confirm.

regarding the immediate size, it is not correct for some reasons that i havent got time to solve that yet. i dont think that matters much for now, anyway. see this related issue https://github.com/aquynh/capstone/issues/296.

thanks.

**Comment by joelpx** [comment]
Alright, no problem. I don't see the commit, did you push something ?

**Comment by aquynh** [comment]
yes, i forgot to push that. can you pull again now?

the commit is https://github.com/aquynh/capstone/commit/a118474625f2d8c3ad5c75dac7fffcb9dc364c90

thanks.

**Comment by joelpx** [comment]
That's ok, thanks.

**Comment by obs1dium** [comment]
>this instruction is actually SHL32ri, so the size of immediate operand is 4.
It exclusively uses 8-bit immediate values, though.
