### ISSUE TITLE
capstone does not decode immediate operand correctly for in and out instruction because of sign extension it does for immediate operand 

### ISSUE THREAD

**Issue by bipulr** [aquynh/capstone#353]
out 0xa2, %al ===> byte code E6 A2

Capstone output from master branch (below). It decoder 0xa2 as negative number because most significant bit in one byte 0xa2 is 1 and it did sign extension. Also the size of immediate operand should be one byte, capstone decodes it as 8 bytes.

Is there a way to selectively not enable sign extension for any specific instruction in capstone framework.

Platform: X86 64 (Intel syntax)
Code:0xe6 0xa2 
Disasm:
0x1000:	out	-0x5e, al
	Prefix:0x00 0x00 0x00 0x00 
	Opcode:0xe6 0x00 0x00 0x00 
	rex: 0x0
	addr_size: 8
	modrm: 0x0
	disp: 0x0
	sib: 0x0
	imm_count: 1
		imms[1]: 0xffffffffffffffa2
	op_count: 2
		operands[0].type: IMM = 0xffffffffffffffa2
		operands[0].size: 8
		operands[1].type: REG = al
		operands[1].size: 1

0x1002:

**Comment by aquynh** [comment]
can you confirm if this is also a problem on the "next" branch?

make sure to reinstall both the core & binding (like Python) when you
switch to the "next" branch.


thanks.

**Comment by aquynh** [comment]
i think this has been fixed in the "next" branch, so it is a good idea for
you to use that branch, rather than the "master" branch.

**Comment by bipulr** [comment]
Yes in next brach it is fine. Is next branch is stable enough to use? Please advise.

latform: X86 64 (Intel syntax)
Code:0xe6 0xa1 
Disasm:
0x1000:	out	0xa1, al

	Prefix:0x00 0x00 0x00 0x00 
	Opcode:0xe6 0x00 0x00 0x00 
	rex: 0x0
	addr_size: 8
	modrm: 0x0
	disp: 0x0
	sib: 0x0
	imm_count: 1
		imms[1]: 0xa1
	op_count: 2
		operands[0].type: IMM = 0xa1
		operands[0].size: 1
		operands[1].type: REG = al
		operands[1].size: 1
		operands[1].access: READ
	Registers read: al

0x1002:

**Comment by aquynh** [comment]
yes it is pretty stable. a good thing is that a lot of new features & new
instructions enter "next", but not "master".

**Comment by aquynh** [comment]
fixed in the "master" branch now, thanks.
