### ISSUE TITLE
x86_64: Details for call instruction list $sp in regs_read

### ISSUE THREAD

**Issue by zachriggle** [aquynh/capstone#358]
```
print(ins.address, ins.bytes, ins.mnemonic, ins.op_str, map(ins.reg_name, ins.regs_read))
(4319976L, bytearray(b'\xe8\xe3\xf6\xff\xff'), u'call', u'0x41e1d0', [u'rsp'])
```

Presumably this should be `rip`, since the call is `rip`-relative, or perhaps `rsp` should be in `regs_write` since it is modified.

**Comment by aquynh** [comment]
can you post the full code instead of only one line?

do you mean RIP/EIP should be in `regs_read[]` array? i am not sure if RIP/EIP should be included, as it is read/modified by every instruction, but not only CALL.

**Comment by hlide** [comment]
rsp is read AND written

**Comment by hlide** [comment]
@aquyynh your remark abour *rip* makes sense

**Comment by zachriggle** [comment]
I was trying to guess what the intent was.  All GRP_CALL and GRP_JUMP are understood to modify the program counter, so there's not *really* a need to mark `rip` as modified.

However, the offset is `rip`-relative, so `rip` being *read* is probably something that should show up -- as opposed to `jmp rcx` or something.

The `GRP_CALL` can be ~= understood to modify the stack pointer by convention.  I have no preference, but I would advocate that whatever `push` does should also be done for `call`.  In any case, `rsp` is certainly not *read* by a `call` instruction.

```
>>> from capstone import *
>>> md=Cs(CS_ARCH_X86, CS_MODE_64)
>>> md.detail=True
>>> ins=md.disasm(b'\xe8\xe3\xf6\xff\xff',4319976).next()
>>> print(ins.address, ins.bytes, ins.mnemonic, ins.op_str, map(ins.reg_name, ins.regs_read))
(4319976L, bytearray(b'\xe8\xe3\xf6\xff\xff'), u'call', u'0x41e1d0', [u'rsp'])
```

**Comment by aquynh** [comment]
yes, if PUSH modify stack register, CALL should do the same.

regarding RSP is read by CALL, yes what i mean is it is referenced by this instruction (thus *read*)

on the RIP is read by this relative CALL, i think that makes sense.

can you send in a PR to fix these issues? the files should be patched are `X86MappingInsn.inc` & `X86MappingInsn_reduce.inc`.

thanks.

**Comment by hlide** [comment]
@zachriggle
`CALL target` is like
```
        PUSH offset back
        JMP target
back:
```
so yes *CALL* reads *RSP* because it modified the same way as *PUSH*, that is: ```RSP = RSP - 8```

**Comment by hlide** [comment]
As for making *rip* as read, I think it could be interesting especially for memory access which used *rip* as a base. For *call*, well why not, since it is more like `PUSH RIP + bytes to skip; JMP target`indeed. Note that, *lea* why not a strictly a memory access is also a potential candidate to read *rip* too.

**Comment by aquynh** [comment]
fixed with this commit https://github.com/aquynh/capstone/commit/94fbce14957502fa61090b7b044b5ab46f7cf77e ("next" branch), please confirm.

thanks.
