### ISSUE TITLE
64 bit PowerPC support (imm is int32_t)

### ISSUE THREAD

**Issue by randomstuff** [aquynh/capstone#364]
The `imm` variant of an instruction is defined as as [`int32_t`](https://github.com/aquynh/capstone/blob/3ab509192ab23b665c1702b9968f7a4efd5b8811/include/ppc.h#L69). Indeed, an immediate cannot be wider than that in a PowerPC instruction. However, for branching instruction with AA=0, the field contains the real target address (offset + CIA) instead of the offset: the real target address might be outside of the 32 bit address space. Shouldn't the `imm` field be defined as a `uin64_t` in order to properly support 64-bit PowerPC?

**Comment by aquynh** [comment]
yes, this was overlooked because initially we did not intend to use absolute address for target.

would you mind doing a pull request to fix that? please base that on the "next" branch, but not the "master" branch as this changes the API.

thanks.

**Comment by randomstuff** [comment]
Proposed patch is in [PR#366](https://github.com/aquynh/capstone/pull/366).

**Comment by aquynh** [comment]
patch merged, thanks!
