### ISSUE TITLE
amd64 pcmpeqb decoding regression

### ISSUE THREAD

**Issue by c01db33f** [aquynh/capstone#369]
The following instruction seems to decode incorrectly using the latest capstone 3.03 release:

00000000  66450F74E0        pcmpeqb xmm12,xmm8

This previously decoded correctly; now it decodes to 

pcmpeqb mm4, mm0

This appears to be an incorrect decoding of the prefix bytes; since this is the correct decoding for the following:

00000000  0F74E0            pcmpeqb mm4,mm0

**Comment by aquynh** [comment]
Is this with "next" or "master" branch?

**Comment by aquynh** [comment]
Oh i see that is 3.0.3. Can you try again with the "next" branch? Be sure
to fresh reinstall the bindings.

**Comment by c01db33f** [comment]
Issue is present on 'master' head. I'll test with 'next' branch now

**Comment by c01db33f** [comment]
Decodes correctly on 'next' head; see output from test_x86.static.

0x1029:

****************
Platform: X86 64 (Intel syntax)
Code:0x66 0x45 0x0f 0x74 0xe0 
Disasm:
0x1000:	pcmpeqb	xmm12, xmm8

	Prefix:0x00 0x00 0x66 0x00 
	Opcode:0x0f 0x74 0x00 0x00 
	rex: 0x45
	addr_size: 8
	modrm: 0xe0
	disp: 0x0
	sib: 0x0
	op_count: 2
		operands[0].type: REG = xmm12
		operands[0].size: 16
		operands[0].access: READ | WRITE
		operands[1].type: REG = xmm8
		operands[1].size: 16
		operands[1].access: READ
	Registers read: xmm12 xmm8
	Registers modified: xmm12

0x1005:

**Comment by aquynh** [comment]
thanks for the confirmation.

**Comment by c01db33f** [comment]
Oh, also noting; this instruction previously decoded correctly; so it is a regression at least from 3.0.1

**Comment by aquynh** [comment]
yes i am aware of this problem, but still not sure how to fix that yet.
