### ISSUE TITLE
ARM64: stub wrong memory reference

### ISSUE THREAD

**Issue by radare** [aquynh/capstone#373]
```
3ff11f38       sturb wzr, [x9, 0xffffffffffffffff]
```

GNU disassembles this as -1

**Comment by aquynh** [comment]
will look closer, but in general it is hard to know when to display positive number or negative number.

**Comment by radare** [comment]
would be good to know what IDA does here.

**Comment by aquynh** [comment]
basically, this is when we print out an immediate. the question is: when do we want to print it as a positive number, and when do we want to print it as negative number?

**Comment by radare** [comment]
Is threating it as signed 64bit integer problematic?

**Comment by aquynh** [comment]
what do you mean?

**Comment by radare** [comment]
Higher bit defines sign

**Comment by aquynh** [comment]
but the point is sometimes we might want to print that as positive number.

**Comment by radare** [comment]
but never when this immediate is used as a delta for a base register, do we?

**Comment by aquynh** [comment]
this is really personal taste, IMO.

at least we can always print 0xffffffffffffffff as -1. what do you think?

**Comment by aquynh** [comment]
i just pushed out a fix, so for memory operands we print immediate as signed int64 rather than uint64: https://github.com/aquynh/capstone/commit/b6f0d440b26d73ffc2e0c6d48ad0cd76a5c96974

let me know if this introduces any unwanted issues, thanks.

**Comment by radare** [comment]
Thanks! Iwill update cs in r2 and let you know if i find any regression.
