### ISSUE TITLE
struct InternalInstruction, need fields : immediateOffset and displacementOffset

### ISSUE THREAD

**Issue by Worobow** [aquynh/capstone#374]
I need to get these two fields:

 immediateOffset and displacementOffset.

/*Offsets from the start of the instruction to the pieces of data, which is    needed to find relocation entries for adding symbolic operands */

How is it better to do?

Also need   displacementSize and  immediateSize.

**Comment by aquynh** [comment]
here in **test_x86.c** you can see how to extract all the information you want to:

https://github.com/aquynh/capstone/blob/master/tests/test_x86.c
