### ISSUE TITLE
Warnings when building master with MSVC

### ISSUE THREAD

**Issue by yegord** [aquynh/capstone#375]
Hi! I get the following warning when build Capstone (master) with MSVC 2010, 32-bit:

`..\capstone\arch\ARM\ARMInstPrinter.c(1290): warning C4244: 'function' : conversion from 'uint64_t' to 'bool', possible loss of data`

Could you fix this?

Link to the buildbot report: http://lists.derevenets.com/pipermail/capstone-buildbot/2015-May/000000.html

**Comment by aquynh** [comment]
fixed in both "master" & "next": https://github.com/aquynh/capstone/commit/106e0f1567b69efaceae145bbcd70e74065ce509

thanks.
