### ISSUE TITLE
Adding test build target, fixing a CMake warning

### ISSUE THREAD

**Issue by yegord** [aquynh/capstone#376]
CMake 3.0.2 on Linux, when configuring capstone, prints me the following warning:
```
CMake Warning (dev) at CMakeLists.txt:358 (add_executable):
  Policy CMP0037 is not set: Target names should not be reserved and should
  match a validity pattern.  Run "cmake --help-policy CMP0037" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.
```
This is because you create an executable called `test`, which leads to creating a target called `test`. The latter name is usually reserved for the targets running tests.

My proposal is
1. To rename the `test` executable to something else.
2. To add the test build target running all tests. See ADD_TEST CMake's command.

Link to the buildbot report with the above message: http://lists.derevenets.com/pipermail/capstone-buildbot/2015-May/000002.html

**Comment by aquynh** [comment]
On Sun, May 24, 2015 at 8:47 PM, yegord <notifications@github.com> wrote:

> CMake 3.0.2 on Linux, when configuring capstone, prints me the following
> warning:
>
> CMake Warning (dev) at CMakeLists.txt:358 (add_executable):
>   Policy CMP0037 is not set: Target names should not be reserved and should
>   match a validity pattern.  Run "cmake --help-policy CMP0037" for policy
>   details.  Use the cmake_policy command to set the policy and suppress this
>   warning.
>
> This is because you create an executable called test, which leads to
> creating a target called test. The latter name is usually reserved for
> the targets running tests.
>
> My proposal is
> 1. To rename the test executable to something else.
> 2. To add the test build target running all tests. See ADD_TEST CMake's
> command.
>

does this mean either (1) or (2) will solve the problem?

if so, i prefer solution (2), as it does not affect anything (like docs).
can you send a PR to do that?

thanks.

**Comment by yegord** [comment]
(1) will solve the problem.
(2) is just for convenience: CMake projects normally have `test` target that runs tests, maybe you should also have one, especially since it is easy to add.
I have already sent a PR, you are looking at it. :)
Thanks!

**Comment by aquynh** [comment]
yes, PR means Pull Request.
