### ISSUE TITLE
Capstone's next branch does not build with MSVC 2010

### ISSUE THREAD

**Issue by yegord** [aquynh/capstone#377]
Hi!

Probably, you include the system `<inttypes.h>` (which is absent in MSVC 2010) instead of the local replacement: http://lists.derevenets.com/pipermail/capstone-buildbot/2015-May/000001.html

**Comment by aquynh** [comment]
On Sun, May 24, 2015 at 8:50 PM, yegord <notifications@github.com> wrote:

> Hi!
>
> Probably, you include the system (which is absent in MSVC 2010) instead of
> the local replacement:
> http://lists.derevenets.com/pipermail/capstone-buildbot/2015-May/000001.html
>

hmm i think we do not have this problem with later version of MSVC??

**Comment by yegord** [comment]
Right. Later MSVC versions have inttypes.h.

**Comment by aquynh** [comment]
currently we include `inttypes.h` via `myinttypes.h`, which has:

    #if defined(_MSC_VER) && _MSC_VER <= 1700
    #include "msvc/headers/inttypes.h"

if i am not wrong, `_MSVC_VER` of MSVC2010 is *1600*, thus it should include `msvc/headers/inttypes.h`. so why do you still have this error?

can you confirm your version? that should be in the output of `cl /?`

**Comment by yegord** [comment]
You include inttypes.h as `<inttypes.h>` in `https://github.com/aquynh/capstone/blob/next/arch/PowerPC/PPCInstPrinter.c`. Perhaps, you should include `myinttypes.h` instead.

**Comment by aquynh** [comment]
On Sun, May 24, 2015 at 9:29 PM, yegord <notifications@github.com> wrote:

> You include inttypes.h as <inttypes.h> in
> https://github.com/aquynh/capstone/blob/next/arch/PowerPC/PPCInstPrinter.c.
> Perhaps, you should include myinttypes.h instead.
>

right. can you change that line to:

    #include "../../myinttypes.h"

and see if it fixes the issue?

if it does, please send a PR :-)

thanks,
