### ISSUE TITLE
Bug in capstone for windows

### ISSUE THREAD

**Issue by kevinkoo001** [aquynh/capstone#379]
Hello, 

I am reporting this because this might be a bug in capstone for Windows (x86). While I have tested a quite number of disassembling using capstone, I found that there was a case which did not disassemble in Windows as intended.

Here is a code snippet. It just returns an empty string with no opcode.
```
CODE = '\x66\x0f\x73\xd8\x04'
from capstone import *
md = Cs(CS_ARCH_X86, CS_MODE_32)
for i in md.disasm(CODE, 0x1000):
   print "0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str)
```

Meanwhile, in capstone for linux, I was able to get an appropriate result as following:
```
0x1000: psrldq  xmm0, 4
```

Thanks for great library - capstone!

**Comment by aquynh** [comment]
On Fri, May 29, 2015 at 12:53 AM, Hyungjoon Koo <notifications@github.com>
wrote:

> Hello,
>
> I am reporting this because this might be a bug in capstone for Windows.
> While I have tested a quite number of disassembling using capstone, I found
> that there was a case which did not disassemble in Windows as intended.
>
> Here is a code snippet. It just returns an empty string with no opcode.
>
> CODE = '\x66\x0f\x73\xd8\x04'
> from capstone import *
> md = Cs(CS_ARCH_X86, CS_MODE_32)
> for i in md.disasm(CODE, 0x1000):
>    print "0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str)
>
> Meanwhile, in capstone for linux, I was able to get an appropriate result
> as following:
>
> 0x1000: psrldq  xmm0, 4
>
>
i think this issue has been fixed in the "next" branch. can you check that
out and confirm?

(for Windows, you can just compile yourself with the MSVC project under
msvc/ directory)

thanks.

**Comment by aquynh** [comment]
btw, this sounds strange: you got different results on Windows & Linux? that is not possible to me, as the bug, if existent, should be present on both platforms. do you make sure to use the same version??

**Comment by kevinkoo001** [comment]
Well, I am using version 3.0.3 on Windows and 3.0.2 on Linux.
Yeah, I got a different result. Haven't checked the "next" branch yet. What's the version of the next?

**Comment by aquynh** [comment]
On Fri, May 29, 2015 at 1:17 AM, Hyungjoon Koo <notifications@github.com>
wrote:

> Well, I am using version 3.0.3 on Windows and 3.0.2 on Linux.
>

ok, it is understandable now: 3.0.2 and 3.0.3 handle this code differently,
but this is not because of the platform.

so it is a good idea to use the same version on all platform.

> Yeah, I got a different result. Haven't checked the "next" branch yet.
> What's the version of the next?
>

that will become v4.0 when it is released in the future.
at the moment "next" branch is our development branch, but it is stable
enough for X86, so dont be afraid to use it.

NOTE: when you install the "next" branch, be sure to reinstall the Python
binding from "next" as well, because the existent Python binding in your
machine (for v3.x) is not compatible with the "next" core (v4.0)

**Comment by kevinkoo001** [comment]
Thanks for the tip. I guess I have to use 3.0.2 for Windows for the time being because I don't want to reinstall Python. Can I migrate 3.0.3 into lower version in Windows?

**Comment by aquynh** [comment]
version 3.0.3 & 3.0.2 are compatible, if this is what you are asking.

however, as you noted, version 3.0.2 handles your code correctly, while
version 3.0.3 does not.
but version 3.0.3 fixes some annoying bugs in X86, so if you are OK with
the above issue, use v3.0.3.

so using the "next" version is a good idea that i recommend, and compile it
for Windows is trivial.

**Comment by aquynh** [comment]
fixed in the "master" branch now, thanks.
