### ISSUE TITLE
commit e1bde17b6b756d6b85dff4f783fbc6d634dd370c

### ISSUE THREAD

**Issue by ChengyuSong** [aquynh/capstone#383]
Introduced regression for lots of SSE instructions

**Comment by aquynh** [comment]
yes, i am well aware of this issue.
this has been fixed in the "next" branch long ago, so it is a good idea to use it now.
("next" is our development branch, and will be released as v4.0 in the future)

**Comment by aquynh** [comment]
fixed in the "master" branch now.
version 3.0.4 will be released soon with this fix, thanks.
