### ISSUE TITLE
Thumb disassembler memory corruption with IT sequence

### ISSUE THREAD

**Issue by igotti-google** [aquynh/capstone#385]
Very long sequence of IT instructions may randomly overwrite data in the disassembler structure.
This patch fixes it: https://gist.github.com/igotti-google/d6c2fe7aee51e51a6a67

**Comment by aquynh** [comment]
Can you do a pull request, please?

**Comment by aquynh** [comment]
can you provide an input triggering this problem, so i can test it?

**Comment by igotti-google** [comment]
Unfortunately I cannot redistribute the binary where I've seen this behavior. But likely:
  ITTTT EQ
repeated couple hundred times is what you need.

**Comment by igotti-google** [comment]
See https://github.com/aquynh/capstone/pull/386
