### ISSUE TITLE
Python exception after sys.exit

### ISSUE THREAD

**Issue by joelpx** [aquynh/capstone#387]
After a sys.exit an exception is randomly triggered.

```
import sys
# arch type doesn't matter
from capstone import CS_ARCH_ARM, Cs
md = Cs(CS_ARCH_ARM, CS_ARCH_ARM)
sys.exit(0)
```

Output : 
```
Exception ignored in: <bound method Cs.__del__ of <capstone.Cs object at 0x7efc58e0bc18>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/capstone/__init__.py", line 696, in __del__
TypeError: 'NoneType' object is not callable
```

Tested on 3.0.3 + python3

**Comment by aquynh** [comment]
this does not to happen with Python2, right?

**Comment by aquynh** [comment]
i tested this issue on Python 3.4.0 on Ubuntu 14.04 64-bit, and have no error at all.

what is your environment?

so your system has this issue at this line in `__init__.py`:

    status = _cs.cs_close(ctypes.byref(self.csh))

however, we already have a check `_cs is not None` before this line, so i dont see why this bug happens.

can you debug this code to see what really causes this error?

thanks.

**Comment by aquynh** [comment]
the reason is that the library is unloaded without notifying our binding, and we still call its function after that.

**Comment by aquynh** [comment]
fixed with this commit for both "master" & "next" branches: https://github.com/aquynh/capstone/commit/3808eec03330341a09f8017c5370dbf6a4fa1c13. please confirm, thanks.

**Comment by joelpx** [comment]
It looks good.

**Comment by joelpx** [comment]
And you are correct, it seems that it doesn't happen to python2

**Comment by joelpx** [comment]
Note: I'm using python 3.4.3 on archlinux 64

**Comment by aquynh** [comment]
this fixed the potential problem for Python 2 as well.
