### ISSUE TITLE
OOB write size 4 in XCoreInstPrinter.c:173

### ISSUE THREAD

**Issue by felixgr** [aquynh/capstone#389]
We have discovered an out-of-bounds write access of size 4 in set_mem_access at arch/XCore/XCoreInstPrinter.c:173 of capstone-3.0.3.

Code:
MI->flat_insn->detail->xcore.operands[MI->flat_insn->detail->xcore.op_count].type = XCORE_OP_MEM;

Reproduce data:
printf "\xef\x0f\xa7\x80" > sample

**Comment by felixgr** [comment]
Let me know if you need further code or details to reproduce or help with analyzing the root cause of the memory corruption.

**Comment by felixgr** [comment]
Reproduce with repro.c:
https://gist.github.com/felixgr/21ed36aed630978668aa

**Comment by aquynh** [comment]
fixed with the commit https://github.com/aquynh/capstone/commit/7c2f5b615a34513865455d779bb4a47c61476d66 in both "master" & "next" branches. please confirm, thanks!

**Comment by felixgr** [comment]
Confirmed fix is working
