### ISSUE TITLE
SEGV at PPCDisassembler.c:341 (decodeCRBitMOperand)

### ISSUE THREAD

**Issue by felixgr** [aquynh/capstone#395]
Reproduced on a34fc3a (branch "next") with CAPSTONE_USE_SYS_DYN_MEM and AddressSanitizer.

Also see fuzzing /testing harness:
https://gist.github.com/felixgr/21ed36aed630978668aa

```
printf f7ff7e7e6e647e7fff7e10002626263d7e5c48 | xxd -p -r > testcase1
printf 0d80200000803f00001043230ed04400804c4322022d0300807c3001207c4320934f2000214cc8002140820014 | xxd -p -r > testcase2
```

In decodeCRBitMOperand, CountTrailingZeros_64(Imm) returns 64 which will result into OOB indexing into the CRRegs global const: `	MCOperand_CreateReg0(Inst, CRRegs[7 - 64]);`

**Comment by aquynh** [comment]
fixed with the commit https://github.com/aquynh/capstone/commit/011bf8bf8488371fb251ce75ffef4b636ba1a6c8, please confirm.

thanks.

**Comment by felixgr** [comment]
Thanks for the fix. Verified.
