### ISSUE TITLE
Python3.3.2 ctypes.ArgumentError on disasm methode

### ISSUE THREAD

**Issue by will-tam** [aquynh/capstone#396]
Hello.

I just installed and tried the Python tutorial for Capstone, but the 
**disasm(CODE, 0x1000)** 
method sent me:

>Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/usr/lib/python3.3/site-packages/capstone/__init__.py", line 817, in disasm
>    res = _cs.cs_disasm(self.csh, code, len(code), offset, count, ctypes.byref(all_insn))
>ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type

The same happen with the **disasm_lite(CODE, 0x1000)** method

Python 3 ver 3.3.2
CTypes ver 1.1.0

Very nice program i could appreciate in couple of *radare2* program.

Thanks.

**Comment by aquynh** [comment]
which Capstone version are you using?

can you paste the whole Python script here, so i can try it?

thanks

**Comment by will-tam** [comment]
I use this last GitHub Capstone version, **3.0.3**
The version_bind() method returns **3.0.768**

The used code is
```
from capstone import *

CODE = "\x55\x48\x8b\x05\xb8\x13\x00\x00"

md = Cs(CS_ARCH_X86, CS_MODE_64)
for (address, size, mnemonic, op_str) in md.disasm_lite(CODE, 0x1000):
	print "0x%x:\t%s\t%s" %(address, mnemonic, op_str)
```

Thanks

**Comment by aquynh** [comment]
do you have this problem with Python2?

**Comment by aquynh** [comment]
your Python script has some issues. see the corrected code below:

    from capstone import *

    CODE = b"\x55\x48\x8b\x05\xb8\x13\x00\x00"

    md = Cs(CS_ARCH_X86, CS_MODE_64)
    for (address, size, mnemonic, op_str) in md.disasm_lite(CODE, 0x1000):
        print ("0x%x:\t%s\t%s\n" %(address, mnemonic, op_str))

note how CODE is defined (with **b** in front). this is not only for Python3, but also applies for Python2 as well.

finally, in Python3 `print` should be called with `()`, unlike in Python2. this is a good practice, because the code above is guaranteed to work in both Python2 & Python3.

**Comment by aquynh** [comment]
the tutorial at http://capstone-engine.org/lang_python.html was fixed accordingly to support both Python2 & Python3 now.

thanks.

**Comment by will-tam** [comment]
I am so sorry, i mistook my  **commented Jun 16, 2015 **. I wrote it before to go to job, and i forgot to change the print line with mine *print()*.
And YOU RIGHT the problem came from the little poor letter **b** i completely also forgot.

It work perfectely!

Thanks you very much for your answers
