### ISSUE TITLE
Broken Android cross compilation on OSX

### ISSUE THREAD

**Issue by evilsocket** [aquynh/capstone#400]
I'm running OSX with the Android NDK correctly installed and in the $PATH ( I use it on a daily basis so I'm 100% sure the installation is ok ):

    which arm-linux-androideabi-gcc
    /Users/evilsocket/android/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc

When I execute:

    ./make.sh cross-android

I get the following errors:

    rm -f  ./cs.o ./utils.o ./SStream.o ./MCInstrDesc.o ./MCRegisterInfo.o  ./arch/ARM/ARMDisassembler.o ./arch/ARM/ARMInstPrinter.o ./arch/ARM/ARMMapping.o ./arch/ARM/ARMModule.o  ./arch/AArch64/AArch64BaseInfo.o ./arch/AArch64/AArch64Disassembler.o ./arch/AArch64/AArch64InstPrinter.o ./arch/AArch64/AArch64Mapping.o ./arch/AArch64/AArch64Module.o  ./arch/Mips/MipsDisassembler.o ./arch/Mips/MipsInstPrinter.o ./arch/Mips/MipsMapping.o ./arch/Mips/MipsModule.o  ./arch/PowerPC/PPCDisassembler.o ./arch/PowerPC/PPCInstPrinter.o ./arch/PowerPC/PPCMapping.o ./arch/PowerPC/PPCModule.o  ./arch/Sparc/SparcDisassembler.o ./arch/Sparc/SparcInstPrinter.o ./arch/Sparc/SparcMapping.o ./arch/Sparc/SparcModule.o  ./arch/SystemZ/SystemZDisassembler.o ./arch/SystemZ/SystemZInstPrinter.o ./arch/SystemZ/SystemZMapping.o ./arch/SystemZ/SystemZModule.o ./arch/SystemZ/SystemZMCTargetDesc.o  ./arch/X86/X86DisassemblerDecoder.o ./arch/X86/X86Disassembler.o ./arch/X86/X86IntelInstPrinter.o ./arch/X86/X86ATTInstPrinter.o ./arch/X86/X86Mapping.o ./arch/X86/X86Module.o  ./arch/XCore/XCoreDisassembler.o ./arch/XCore/XCoreInstPrinter.o ./arch/XCore/XCoreMapping.o ./arch/XCore/XCoreModule.o ./MCInst.o
    rm -f ./libcapstone.* ./capstone.*
    rm -f ./capstone.pc
    cd tests && /Applications/Xcode.app/Contents/Developer/usr/bin/make clean
    rm -rf ./test.o ./test_detail.o ./test_skipdata.o ./test_iter.o ./test_arm.o ./test_arm64.o ./test_mips.o ./test_ppc.o ./test_sparc.o ./test_systemz.o ./test_x86.o ./test_xcore.o ./test ./test_detail ./test_skipdata ./test_iter ./test_arm ./test_arm64 ./test_mips ./test_ppc ./test_sparc ./test_systemz ./test_x86 ./test_xcore ./*.exe ./*.static ./libcapstone.* ./capstone.*
    rm -f ./tests/libcapstone.so
    cd bindings/python && /Applications/Xcode.app/Contents/Developer/usr/bin/make clean
    rm -rf ./build src/ dist/ README
    rm -f capstone/*.so
    rm -rf prebuilt/win64/capstone.dll
    rm -rf prebuilt/win32/capstone.dll
    cd bindings/java && /Applications/Xcode.app/Contents/Developer/usr/bin/make clean
    rm -rf ./capstone/*.class
    rm -rf ./*.class ./*.log ./*.jar
    cd bindings/ocaml && /Applications/Xcode.app/Contents/Developer/usr/bin/make clean
    rm -f *.[oa] *.so *.cm[ixoa] *.cmxa *.mli test test_detail test_x86 test_arm test_arm64 test_mips test_ppc test_sparc test_systemz test_xcore
      CC      cs.o
    arm-linux-androideabi-gcc: error: i386: No such file or directory
    arm-linux-androideabi-gcc: error: x86_64: No such file or directory
    arm-linux-androideabi-gcc: error: unrecognized command line option '-arch'
    arm-linux-androideabi-gcc: error: unrecognized command line option '-arch'
    make: *** [cs.o] Error 1

**Comment by gygl09** [comment]
yes, I faced the same problem in mac. I also spent some time to fix it, but failed.
Anyway, I can easily compile it in linux. If you want the static link library, I can transfer it to you.

**Comment by aquynh** [comment]
if you compile with `V=1 ./make.sh cross-android`, you will see the full details of compiled commands, and can figure out what is wrong.

**Comment by evilsocket** [comment]
Actually @jduck fixed this in [his own fork](https://github.com/jduck/capstone).

**Comment by aquynh** [comment]
i already merged his PR at https://github.com/aquynh/capstone/pull/401 to the "master" branch.

thanks.

**Comment by evilsocket** [comment]
cool!
