### ISSUE TITLE
__ctype_tolower_loc is undefined in arm64

### ISSUE THREAD

**Issue by gygl09** [aquynh/capstone#402]
when I add libcapstone.a into my project, an error happened: 
> "in the function A64NamedImmMapper_fromString (AArch64BaseInfo.c): undefined reference to `__ctype_tolower_loc'."

It's wired. Do you know the reason?

I guess it is because Android ndk can not find tolower() in Android libc. So I replaced tolower() in compare_lower_str(), and then I recompiled capstone. Finally, I can successfully compile the whole project:
```
static bool compare_lower_str(char *s1, char *s2)
{
        bool res;
        char *lower = cs_strdup(s2), *c;
        for (c = lower; *c; c++) {
                if (*c >= 'A' && *c <= 'Z')
                        *c += 0x20;
        }
        /* *c = (char)tolower((int) *c); */

        res = (strcmp(s1, lower) == 0);
        cs_mem_free(lower);

        return res;
}
```

**Comment by gygl09** [comment]
If I am worry, correct me please :)

**Comment by aquynh** [comment]
this is weird. which Android NDK version are you using?

**Comment by gygl09** [comment]
Yes, it is. I used the newest one "android-ndk-r10e" for Linux 64-bit (x86). 
Anyway, at least it works :)

**Comment by aquynh** [comment]
cool, lets see if some Android experts experienced this issue..

**Comment by aquynh** [comment]
i have some doubts here: actually when you compiled Capstone (succesfully?), you already compiled some static binaries in `tests/`. you can find under this directory those files: `test_arm.static`, `test_arm64.static`, `test_x86.static`, etc. 

this means there is no issue linking `libcapstone.a` to applications, so why do you have this issue with your own app?

**Comment by gygl09** [comment]
Originally, I used Ubuntu's cross compilers to compile capstone and used ndk to compile my project. 

Now, I tried your new patch on make.sh, which means I can compile everything with ndk. Finally, the error disappeared.
