### ISSUE TITLE
MIPS: SUBU wrong id

### ISSUE THREAD

**Issue by joelpx** [aquynh/capstone#409]
Tested on CS `3.0.3` and `4.0-alpha1`.

```
from capstone import *
from capstone.mips import MIPS_INS_SUBU

md = Cs(CS_ARCH_MIPS, CS_MODE_MIPS32 | CS_MODE_LITTLE_ENDIAN)
binary = b"\x23\x10\x62\x00"

print("MIPS_INS_SUBU =", MIPS_INS_SUBU)

for i in md.disasm(binary, 0):
    print(i.mnemonic, i.id)
```

Result (values from 3.0.3) : 
```
MIPS_INS_SUBU = 542
subu 583
```
583 is the id of `NEGU` and not `SUBU`.

**Comment by hlide** [comment]
Knowing that *negu rd, rt* is an alias instruction for *subu rd, $0, rt*, but *rs* is clearly not $0 here (it is $v1) so it is an issue.

**Comment by aquynh** [comment]
fixed with the commit https://github.com/aquynh/capstone/commit/2ad9eb2a4362d194164736f4969e791826936a03 in both "master" & "next".

please confirm, thanks.

**Comment by joelpx** [comment]
Fixed thanks
