### ISSUE TITLE
longest x86 instruction

### ISSUE THREAD

**Issue by mrexodia** [aquynh/capstone#410]
Hey,

Recently saw an article about the longest x86 instruction, but capstone disassembles it differently from the author of the article. Take a look if you want: http://blog.onlinedisassembler.com/blog/?p=23

Greetings

**Comment by aquynh** [comment]
do you mean the long instruction in the form of `66 66 66 66 … 66 66 89 E5`, with **unlimited** number of prefix `66` ? this is the theory, but i doubt the author of above article checked if it works in reality. 

last time i tried on a physical machine, Intel CPU refuses to run if the instruction is longer than 15 bytes. so 13 bytes of `66` + `89 e5` is accepted by real CPU, but 14 bytes of `66` + `89 e5` is rejected. and Capstone behaves exactly like this now.

thanks.

**Comment by mrexodia** [comment]
I meant this one:

```
lock add DWORD PTR ds:[esi+ecx*4+0x12345678],0xefcdab89

67 66 f0 3e 81 84 8e 78 56 34 12 89 ab cd ef
```

**Comment by aquynh** [comment]
is this 16bit or 32bit insn?

**Comment by aquynh** [comment]
in 16bit, Capstone decodes this as:

    `lock add	dword ptr ds:[esi + ecx*4 + 0x12345678], 0xefcdab89`

so this is correct, right?

**Comment by hlide** [comment]
yes it's correct. Don't worry too much. Just a small precision, on machine earlier than 386 you can exceed this limit and that's what the article was talking about, but I really doubt a lot of people are coding for those machines nowadays.

**Comment by mrexodia** [comment]
On 32 bit it disassembles as

```
lock add word ptr ds:[si + 0x788e], 0x3456
adc cl, byte ptr [ecx - 0x6f103255]
```

It might be correct, but I just don't know that's why I was asking :)

**Comment by hlide** [comment]
You need to be in 16-bit mode to have "lock add DWORD PTR ds:[esi+ecx*4+0x12345678],0xefcdab89" because of the presence of prefixes 0x66 and 0x67.
