### ISSUE TITLE
invalid x86 disassembly

### ISSUE THREAD

**Issue by radare** [aquynh/capstone#411]
this is a regression catched by r2 testsuite
```
-and esp, 0xfffffff0
+and esp, 0xf0
```

**Comment by aquynh** [comment]
is this the next branch? what is the hexcode & hardware mode?

**Comment by radare** [comment]
both fail:
```
$ rasm2 -a x86 -b 64 -d 4883e4f0
and rsp, 0xf0
$ rasm2 -a x86 -b 32 -d 83e4f0
and esp, 0xf0
```

**Comment by aquynh** [comment]
Which branch?

**Comment by radare** [comment]
I always use next

**Comment by hlide** [comment]
meseems the issue is due to forgetting to sign-extend an 8-bit immediate to a 32/64-bit value

**Comment by aquynh** [comment]
can you confirm that the latest commit in "next" fixes this issue?

**Comment by hlide** [comment]
instructions like BT, BTC, BTR, BTS has an unsigned 8-bit immediate to tell which bit to test/alter in a register or in memory operand.

> When an 8-bit immediate value is used in the instruction, this operand is taken modulo 16/32/64, so the range of immediate bit offsets is 0..15/31/63. This allows any bit within a register to be selected.

> For memory bit strings, this immediate field gives only the bit offset within a word/doubleword/quadword. Immediate bit offsets larger than 15/31/63 are supported by using the immediate bit offset field in combination with the displacement field of the memory operand: Real Address = Effective Address + (2/4/8 * (BitOffset DIV 16/32/64)) and Index = BitOffset & 7.

**Comment by radare** [comment]
confirmed. looks good again.
