### ISSUE TITLE
Wrong operand length for many instructions

### ISSUE THREAD

**Issue by ChaosLeader** [aquynh/capstone#412]
I'm trying to write a tool for automated analysis which keeps track of registers. Therefore it is critical to know the operand size (and preferrably the offset in the instruction).

However there are many instructions where the output of the length of the operands is wrong. For some it is correctly computed (disassembled with x86 32bits):

- Correct
```asm
F6 45 08 01       test  [ebp+08h], 1     ; gives inst length: 4, imm length: 1, disp length: 1
68 56 45 34 12    push  12345678h        ; gives inst length: 5, imm length: 4
```

- Wrong
```asm
89 47 30          mov   [edi+30h], eax   ; gives inst length: 3, disp length: 4
8B 4D 0C          mov   ecx, [ebp+0Ch]   ; gives inst length: 3, disp length: 4
6A 02             push  2                ; gives inst length: 2, imm length: 4
```

**Comment by aquynh** [comment]
this is supposed to be already fixed in the "next" branch. can you try again & report the results?

**Comment by aquynh** [comment]
on the disp length, that will be the same in "next" branch. is this a critical issue? (most people do not care about this)

**Comment by ChaosLeader** [comment]
Yes for me it's absolutely critical and I would be glad if you find some time to fix this.
Output is from the next branch (it fixed quite some errors compared to the master branch)

**Comment by aquynh** [comment]
`disp length: 4`   <---- how did you get this info?

**Comment by ChaosLeader** [comment]
```c++
for (int i = 0; i < 8; i++)
{
	auto &operand = inst.detail->x86.operands[i];
	switch (operand.type)
	{
	case X86_OP_IMM:
		std::cout << "immLen: " << std::dec << (int)opcode->immLen << ", ";
		break;

	case X86_OP_MEM:
		std::cout << "dispLen: " << std::dec << (int)opcode->dispLen << ", ";
		break;
	}
}
```

**Comment by aquynh** [comment]
where is this C++ binding from?
 
the `dispLen` is not from the Capstone core, but created by this binding.
you need to look at their code to see how they have `dispLen` there.

**Comment by ChaosLeader** [comment]
It's just the name. But as far as I see it the length of operand type mem is wrong. It shouldn't matter which operand I take. It's size should never be bigger than the size of the whole instruction.

**Comment by aquynh** [comment]
but this code (calculating `dispLen`) is not coming from Capstone, how can i fix it?

**Comment by ChaosLeader** [comment]
Oh my bad. I thought directly reading from the output data is fine.

I'll try the function when I'm back home.

**Comment by hlide** [comment]
This is again the same issue as discussed with two other issues : we don't know the size of a displacement value encoded in an instruction. The displacement size is taken wrongly from the data size of the memory operand which is indeed a 32-bit data, hence 4 bytes, whereas it should have been 1 byte as it is encoded. @aquynh proposed to add some macros to get the right size by fetching that kind information through *modrm* and *sib* encodings. I found it a bit hackish, but a guess to get a true reflection of the instruction details (each component described every details about how to decompose  or disassemble itself) would be a big and long task.

**Comment by ChaosLeader** [comment]
Ok, I have double checked my code and I do it the same way as done in the x86 example.
