### ISSUE TITLE
Fail to load the dynamic library

### ISSUE THREAD

**Issue by MrNox** [aquynh/capstone#413]
Hi,

I have a problem:

File "/usr/local/lib/python3.4/dist-packages/capstone/__init__.py", line 250, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.

Any idea? Can you help me?

OS: Ubuntu 14.04

Regards!

**Comment by aquynh** [comment]
are you using the old version?

can you get the latest one (3.0.3), or latest code from "master" branch & try again?

another easy way is to install from PyPi:

    $ sudo pip3 install capstone

**Comment by ihciah** [comment]
When I tried `pip install capstone`, it install a `.so` file to the wrong place.
`/usr/local/lib/python2.7/dist-packages/usr/lib/python2.7/dist-packages/capstone/libcapstone.so` which is meant to be at `/usr/local/lib/python2.7/dist-packages/capstone/libcapstone.so`
Manually moving the file can solve the problem.

**Comment by aquynh** [comment]
here is an attempt to solve this issue: https://github.com/aquynh/capstone/pull/589
if you can, please try and report the result. 

thanks.

**Comment by rex2er** [comment]
sudo apt-get install python-capstone

this command above resolved the same issue on my machine (ubuntu xenial 16.04.1)
hope it helps!

**Comment by banescusebi** [comment]
The previous suggestions didn't work for me, but 
`$ sudo pip install capstone==3.0.5rc2`
worked
