### ISSUE TITLE
Missing "repz" in mnemonic of "repz js"

### ISSUE THREAD

**Issue by stfairy** [aquynh/capstone#415]
For bytes `0xF3 0x78 0x00`, Capstone outputs `js` as the `insn->mnemonic`.

An online disassembler shows `repz js`: https://www.onlinedisassembler.com/odaweb/jrp8H6Eo/0

From Intel manual, `0xF3` stands for `repz`.

Is this a feature or a bug?

I'm using Version 4.0-alpha1

**Comment by aquynh** [comment]
REP does not go with JS, so that prefix should not be counted at all.

so Capstone is right here, but ODA reports wrong result. They use Gnu disassembler, which is joke.

thanks.
