### ISSUE TITLE
MIPS Lexra support...

### ISSUE THREAD

**Issue by nihilus** [aquynh/capstone#420]
Lexra-varaints of MIPS binaries breaks the MIPS disassembler.
See: http://www.lysator.liu.se/%7Enietzsche/mipsbin/lld2d_4181

**Comment by hlide** [comment]
I got some documents about Lexra CPU and they are not exactly MIPS (no LWL/LWR, just MIPS I with a lot of specific instructions). They sound very lovely.

**Comment by nihilus** [comment]
They are not :-( They have some special extensions especially since their IP was bought up by third parties.
Broken cache lines etc... and yes, the missing unaligned access stuff. But 'SmoothCore, Radiax, and NetVortex are trademarks of Lexra, Inc.' as my CPU data sheet states.

**Comment by aquynh** [comment]
so this should be a new mode for Mips i think.
however, i doubt that there are many users for this work to make it worthy.

**Comment by hlide** [comment]
yes, that was my point.

**Comment by nihilus** [comment]
well, objdump doesn't crash on it at least :)

**Comment by nihilus** [comment]
And about the user-base: every heard of this SoC vendor named Realtek??? 
They still use Lexra specific code in their CPUs, albeit after rtl8196b I think they implemented SWR,SWL,LWL and LWR for next generations.

**Comment by nihilus** [comment]
Seems like the crash was fixed in 3.0.4. :-)

**Comment by aquynh** [comment]
i dont think we fixed anything in Mips recently.
how did you reproduce the crash?
