### ISSUE TITLE
Wrong instruction compare with otool in terminal

### ISSUE THREAD

**Issue by vedon** [aquynh/capstone#422]
![9d412aa6-6a1a-4b4e-9c6a-a8fb3b016af9](https://cloud.githubusercontent.com/assets/1811570/8738759/2feacef2-2c66-11e5-9759-80b2e7a59e86.png)
![60c060e9-d237-4e93-ac3f-bf1a775ddab3](https://cloud.githubusercontent.com/assets/1811570/8738758/2fe3535c-2c66-11e5-8704-1d1e0bda68bd.png)

when i use capstone to disam the WebCore ,I get 0x1961a8000 not 27222 ? can you give me some advices? thx in advance!

**Comment by aquynh** [comment]
the reason is that Capstone gives you the absolute address, not relative address.
meanwhile, the tool in your screenshot (Hopper?) gives you the relative address. hence the difference.

**Comment by vedon** [comment]
I very  appricate you reply so soon !!  I get the same result from  capstone as the hopper(as the screen shot highlight) . I do not understand the 0x18f75500 .

**Comment by vedon** [comment]
I use the 0x18f755000 ,I can't get the right result for the x19. When i use the otool to get the disam code ,x0 = (((27226 << 12) + pc )& ~0xfff) + 4000 + 8 . Could you give me some advice to get the right result with the 0x18f755000 .??

**Comment by vedon** [comment]
![9d412aa6-6a1a-4b4e-9c6a-a8fb3b016af9](https://cloud.githubusercontent.com/assets/1811570/8744387/65d14846-2ca9-11e5-9ae2-52c68f63d46d.png)
![c817580b-8278-4923-9d9a-d5eb1fc6b8f0](https://cloud.githusercontent.com/assets/1811570/8744388/65fc86c8-2ca9-11e5-9818-2577756057a4.png)

the result is different with otool ,Could you explain it to me ,please.

**Comment by vedon** [comment]
![9d412aa6-6a1a-4b4e-9c6a-a8fb3b016af9](https://cloud.githubusercontent.com/assets/1811570/8744408/98c9a496-2ca9-11e5-8152-2dd3077aeafb.png)
![c817580b-8278-4923-9d9a-d5eb1fc6b8f0](https://cloud.githubusercontent.com/assets/1811570/8744409/98c9a9fa-2ca9-11e5-9fef-f8c6fc88876c.png)
the result is different with otool ,Could you explain it to me ,please.

**Comment by hlide** [comment]
Open right your mind! with otool the binary was open in a different absolute address (the one to the left of instruction) starting with 0x18 as prefix. With capstone, the same binary is open with absolute address startig with 0x19 as prefix. otool display two infos: the relative address and the absolute address. Capstone only give you absolute address. Just do (0x195246bf8 + 27226 << 12) & -4096 and you got 0x19bca0000. Voilà !

**Comment by vedon** [comment]
@hlide   wow!!!! you do a great help for me , Buy the way ,how did you konw this fomular ((0x195246bf8 + (27226 << 12)) & -4096) .

Do you have any website for me to get the information  about this ?Wait for your reply ,thx in advance!!

**Comment by hlide** [comment]
I just remembered that I have seen that somewhere there were instructions to get the effective address aligned to page boundary so I just applied the usual formula to do so (1 << 12 = 4096 --> 4KB). I'm pretty sure you can find that kind of documentation from ARM website.

**Comment by vedon** [comment]
ok! thx ,and what about the & -4096 ?I not sure what it means? 

How to revert the formular to get the 27226
uint64_t offset = ((0x19bc6b000 | 4096) - 0x195246bf8) >>12;
and the offset is not equal to 27226.

**Comment by hlide** [comment]
x & ~4095 == x & -4096 == x & 0xFFFFF000

**Comment by vedon** [comment]
@hlide thx for reply so soon ! Great great great help!

**Comment by vedon** [comment]
@hlide  (0x19bc6b000 - (0x195246bf8 & -4096)) >> 12  = 27173 , not 27226.

**Comment by vedon** [comment]
@hlide  why the pc is not the 0x195246bf4 ,must use the address after the instruction adrp?

**Comment by hlide** [comment]
corrected my previous post, it should be 0x19bca0000, not 0x19bc6b000 you gave me, which isn't a 4KB page-aligned address.

**Comment by hlide** [comment]
because *pc* is always on the next instruction when executing an instruction.

**Comment by vedon** [comment]
@hlide  LOL ,I just want to tell you .I can get the address i want ,The issue run all my day before you told me . Thx again !

**Comment by vedon** [comment]
Could you give me your facebook account ,i want to make a friend with you

**Comment by hlide** [comment]
i'm not that hard to find on facebook, especially with my avatar

**Comment by vedon** [comment]
@hlide  the keyword with hlide has lots of people and with the bad network in China ,hard to find you .:(

**Comment by hlide** [comment]
and having a cat-rabbit as avatar, I doubt it.

**Comment by vedon** [comment]
![3a14a721-539d-4838-8007-50a736aeca98](https://cloud.githubusercontent.com/assets/1811570/8771276/08daeeee-2ef2-11e5-8713-d3cae2a9e6b8.png)
@hlide   
the r0 value is equal   ((0x51a << 16) | (0x4ea0) + 0x34d32adc) ; 
Am i right ???

**Comment by hlide** [comment]
`r0 = *((int*)((0x51a << 16) | (0x4ea0) + pc));` where *pc* is the address **AFTER** `add r0, pc` if I'm not wrong.

**Comment by vedon** [comment]
@hlide  thx again ,FYI ,I send a msg to you on facebook .
