### ISSUE TITLE
Capstone crash when disassembly iOS 9 WebCore framework (Using iPhone 5c).

### ISSUE THREAD

**Issue by vedon** [aquynh/capstone#425]
Capstone crash when disassembly iOS 9 WebCore framework (Using iPhone 5c).
![7bb0291b-bb5c-4efb-951a-4738f498b1cc](https://cloud.githubusercontent.com/assets/1811570/8846562/d7a929ce-315a-11e5-829e-03f167babe2a.png)

**Comment by aquynh** [comment]
hmm, how can Capstone crash at that line??

1) which version are you using?

2) can you narrow down to which input causes this crash?

thanks

**Comment by vedon** [comment]
I just download the zip from you repo . It is the latest.

![47912869-257b-42c4-bbd5-ae23439996f7](https://cloud.githubusercontent.com/assets/1811570/8846785/236eb166-315c-11e5-961e-05594c3928c8.png)
![f7aef01e-c345-4b3b-bf85-b6aa26be6151](https://cloud.githubusercontent.com/assets/1811570/8846784/236e9d8e-315c-11e5-904b-ff55f301cbf1.png)

the  information is enough for figuring out the problem?

**Comment by vedon** [comment]
It is no problem when working with the iOS 8 WebCore framework.

**Comment by aquynh** [comment]
this is because **code** is invalid, but that input comes from *your* program, not from Capstone. (Capstone gets this input to disassemble to return you the assembly).

so this is a bug in your program, not in Capstone.

**Comment by vedon** [comment]
ok , thx ! Do you have any idea about this problem , the same code is ok with iOS 8 ,but crash with iOS 9.

**Comment by vedon** [comment]
Ok ,thx ,I am checking my code .
