### ISSUE TITLE
sparcv9 radare2/capstone

### ISSUE THREAD

**Issue by zonkzonk** [aquynh/capstone#426]
Hi,

in revision d5a8e9dafe81990091ff648f23ffe92c67e34bb8

the following bug happens in sparc code with radare2:

https://github.com/radare/radare2/issues/3008

Greetings
--zlul

**Comment by aquynh** [comment]
can you provide the input (in hexcode format) triggering the problem? the link above looks confused to me.

thanks.

**Comment by zonkzonk** [comment]
see updated issue. I don't know exactly what input bytes trigger this, but you can look at bt full output.
I can also provide valgrind output.

Greetings
--zlul

**Comment by aquynh** [comment]
i looked at that, but it is still not clear what causes the issue.

i can fix this very quickly if you can give me the input (best in hexcode form), so please narrow down on what input triggers this segfault.

thanks.

**Comment by zonkzonk** [comment]
did an additional strace -Divx. Though I did not find the exact input trigger.

**Comment by radare** [comment]
Which version of capstone are you using? The one shipped with r2-git, or using the system one from the last release?

I cannot reproduce your issue with r2.

**Comment by zonkzonk** [comment]
capstone version from r2-git: d5a8e9dafe81990091ff648f23ffe92c67e34bb8

**Comment by radare** [comment]
I have reproduced and tested the issue. it happens with and without detail, also with and without v9 bit set. The crashing bytes are BB 70 00 00. You can reproduce this by building r2 with ASAN or running it with valgrind:

```
$ rasm2 -a sparc -b 32 -d bb700000
```

**Comment by aquynh** [comment]
what is the expected output here?

thanks.

**Comment by radare** [comment]
I guess its an invalid instruction but the problem is that it is segfaulting

**Comment by aquynh** [comment]
confirmed. this bug comes from LLVM itself. 

will see how to fix this, thanks.

**Comment by radare** [comment]
thanks!

**Comment by radare** [comment]
any updates on this?

**Comment by aquynh** [comment]
I can fix this issue now, but will take few days to integrate with the code
properly. will commit the fix in few days.

**Comment by aquynh** [comment]
the right output is `popc	%g0, %i5`

fixed in the "next" branch now. will fix it in "master" branch later.

thanks.

**Comment by radare** [comment]
thanks

**Comment by aquynh** [comment]
fixed in the "master" branch, too.
