### ISSUE TITLE
FreeBSD/pkgsrc and DragonflyBSD/pkgsrc builds fail

### ISSUE THREAD

**Issue by krytarowski** [aquynh/capstone#428]
Results of bulk builds:
https://bulktracker.appspot.com/pkgresults/devel/capstone

```
LIBDATADIR = $(LIBDIR)
ifeq ($(UNAME_S), FreeBSD)
LIBDATADIR = $(DESTDIR)$(PREFIX)/libdata
endif
ifeq ($(UNAME_S), DragonFly)
LIBDATADIR = $(DESTDIR)$(PREFIX)/libdata
endif
```

The above code triggers problems on pkgsrc/FreeBSD and pkgsrc/DragonflyBSD as we use in pkgsrc the uniform paths, so ``LIBDATADIR = $(LIBDIR)`` should be picked for all platforms.

The easiest solution is to patch downstream the code... however I would prefer address this issue upstream. I have no good idea how, maybe an environment variable like ``USE_GENERIC_LIBDATADIR`` or something else.. what do you think?

**Comment by aquynh** [comment]
which version are you using??

**Comment by krytarowski** [comment]
pkgsrc-current with capstone 3.0.4

**Comment by aquynh** [comment]
can you please do a pull-request?

thanks.

**Comment by krytarowski** [comment]
OK, but please suggest me a solution. Is enviroment variable ``USE_GENERIC_LIBDATADIR`` preventing from changing ``LIBDATADIR`` for FreeBSD and DragonflyBSD OK?

**Comment by aquynh** [comment]
i will ask some FreeBSD expert look at this. however, FreeBSD was OK before, as Capstone 2.x is an official package in FreeBSD. so why do we have problem now?

**Comment by krytarowski** [comment]
This issue is local only to pkgsrc - the packages framework for POSIX-like systems. It comes from NetBSD and is used on a dozen of other platforms.

**Comment by aquynh** [comment]
i see. then yes, please add your variable `USE_GENERIC_LIBDATADIR` and send a pull-request, i will merge it.

thanks.

**Comment by krytarowski** [comment]
#429
