### ISSUE TITLE
const_generator x86 EFlags

### ISSUE THREAD

**Issue by learn-more** [aquynh/capstone#439]
When running the const_generator.py script on next, it drops the X86_EFLAGS_[MODIFY|PRIOR|RESET|SET|TEST] constants,
were they removed, or is the script missing them?

**Comment by aquynh** [comment]
yes, this is a bug. these constants should not be removed.
if you can fix this issue, please send a PR. thanks.

**Comment by aquynh** [comment]
already fixed, thanks.
