### ISSUE TITLE
ARM instruction encoding E1F322D1 seems to be incorrectly disassembled

### ISSUE THREAD

**Issue by uxmal** [aquynh/capstone#446]
I'm preparing to integrate Capstone into the [Reko decompiler](https://github.com/uxmal/reko) to replace the only partially completed ARM disassembler in Reko. The unit tests for the old ARM disassembler had captured that the opcode `E1F322D1` disassembles to:

    ldrsb r2, [r3, #33]!

The offset 33 is 0x21 in hexadecimal.

When I run the unit tests using the Capstone disassembler and the [Capstone.NET](https://github.com/9ee1/Capstone.NET) .NET bindings, I get instead:

    ldrsb r2,[r3,#&221]!

Notice how the offset is 0x221. I've [confirmed with others](http://reverseengineering.stackexchange.com/questions/10609/what-is-the-correct-disassembly-for-arm-opcode-e1f322d1) that the offset should indeed be 0x021.

**Comment by uxmal** [comment]
...well how embarrassing. I just looked a little closer, and it turns out Capstone.NET is causing this error. I've opened https://github.com/9ee1/Capstone.NET/issues/9 and will close this issue.

**Comment by uxmal** [comment]
The fix to https://github.com/aquynh/capstone/issues/459 seems to have.broken disassembly for this instruction. With the most recent commit of Capstone, when I disassemble E1F322D1, I get 
```
0x104c: ldrsb   r2, [r3, #0x21]!:
        op_count: 2
                operands[0].type: REG = r2
                operands[1].type: MEM
                        operands[1].mem.base: REG = r3
                        operands[1].mem.disp: 0xffffffdf
        Write-back: True
```
Notice how the incorrect displacement 0xFFFFFFDF differs from the #0x21 in the printed disassembly. As a comparison, ODA reports the positive offset (0x21).

**Comment by aquynh** [comment]
fixed with the latest commit. please confirm, thanks.

**Comment by uxmal** [comment]
Confirmed fixed, thanks!
