### ISSUE TITLE
Far jump selector is given as signed and has wrong size

### ISSUE THREAD

**Issue by 10110111** [aquynh/capstone#448]
This instruction `EA 12 34 56 78 9A BC` is disassembled as `ljmp -0x4366:0x78563412`, and the value of first immediate is `0xffffffffffffbc9a`, and its size is 4. Instead, it should be:

    ljmp 0xbc9a:0x78563412

and the size of the first immediate should be 2 and the value shouldn't be sign-extended.

**Comment by aquynh** [comment]
is this "master" or "next" branch?

thanks.

**Comment by 10110111** [comment]
It's master

**Comment by aquynh** [comment]
fixed now in both "master" & "next" branches.

please confirm, thanks.

**Comment by 10110111** [comment]
Confirming, this is fixed.
