### ISSUE TITLE
Loop instruction implicitly uses *cx register, but Capstone doesn't tell

### ISSUE THREAD

**Issue by 10110111** [aquynh/capstone#449]
The instruction `E2 FE`, i.e. `loop $`, implicitly reads and writes `ecx`/`rcx`/`cx` depending on address size, but Capstone doesn't say this neither in implicit read/write fields, nor in operands.

**Comment by aquynh** [comment]
fixed now in both "master" & "next" branches. please confirm, thanks.

**Comment by 10110111** [comment]
Confirmed fixed.
