### ISSUE TITLE
JMP m16:32 reports wrong operand size

### ISSUE THREAD

**Issue by 10110111** [aquynh/capstone#450]
The instruction `FF 2D 34 35 23 01`, disassembled as `ljmp ptr [0x1233534]`, is reported to have a memory operand of size 4. But the size is actually 6.
(tested on branch master)

**Comment by aquynh** [comment]
can you check to see if this is also decoded wrongly on 16bit & 64bit?

**Comment by radare** [comment]
Yep confirmed that is still wrong. See the failing tests here:

https://travis-ci.org/radare/radare2/jobs/75453939 (search for XX)

the test case we are using is disassembling `e97ae7` in x86-16 at offset f000:1911. And the output diff:
```
-jump: 0x000f008e
+jump: 0x0000008e
```

**Comment by aquynh** [comment]
@radare, this is the issue #111 we are discussing. why dont you go there to discuss ?

**Comment by 10110111** [comment]
I confirm that instruction in my report has wrong sizes in all three bitness modes. Consistently fails to take selector size into account.

**Comment by aquynh** [comment]
fixed. please confirm, thanks.

**Comment by 10110111** [comment]
Confirming fixed.
