### ISSUE TITLE
REPNE STOSW instruction is disassembled as REPNE STOSD in 16 bit mode

### ISSUE THREAD

**Issue by 10110111** [aquynh/capstone#452]
The instruction `F2 AB` in 16 bit mode is `repne stosw`. The non-repeating version of it, `AB`, is correctly disassembled as `stosw`, but when the prefix is added, capstone disassembles it as `repne stosd`. The same with `F3` prefix `REP`.
Also affects `LODSW` instruction, maybe also other string instructions.

**Comment by 10110111** [comment]
See [test C code](https://pastebin.mozilla.org/8842749) to see other such instructions. (Hint: there're no `66` or `67` prefixes in that test, so in 16 bit mode no instruction should have dword operands.)

**Comment by 10110111** [comment]
In fact, all the string instructions with `REP`/`REPNE` prefix appear to have wrong operand sizes when they operate not on byte, namely in 16 bit mode when `66` prefix is not used, and in 32 bit mode when `66` prefix _is_ used. I.e. in all cases, when `REP`/`REPNE` prefix is used, Capstone reports `dword` instead of `word`.

**Comment by aquynh** [comment]
can you make a pull request to put these cases into `suite/regress.py`?

thanks.

**Comment by 10110111** [comment]
Has there been any progress with this? Or are there any difficulties?

**Comment by aquynh** [comment]
i am still figuring out how to fix this without conflicting with other encodings.

if you want to tackle this issue, you are welcome.

**Comment by lhmouse** [comment]
PING?

x64dbg is having the issue here. <https://github.com/x64dbg/x64dbg/issues/1520>

**Comment by aquynh** [comment]
fixed now, please confirm

**Comment by 10110111** [comment]
Great: all my 16-bit tests for string instructions pass now.

**Comment by lhmouse** [comment]
Thanks. :1st_place_medal:
