### ISSUE TITLE
String instructions with REP* prefix are not reported to read and write *CX

### ISSUE THREAD

**Issue by 10110111** [aquynh/capstone#453]
Instructions like `repe/repne lods/stos/scas/movs` read and write `*cx` register to count repetitions. Capstone doesn't report this.
Note that without `rep*` prefix they don't, and in this case Capstone is right.

**Comment by aquynh** [comment]
can you provide the input hexcode so i can test these cases?

**Comment by 10110111** [comment]
`F3 AD`, `F2 AB`, `F2 AC`, for example.

**Comment by aquynh** [comment]
fixed. please confirm, thanks.

**Comment by 10110111** [comment]
Fixed for those instructions which have a detected `rep*` prefix.

**Comment by hlide** [comment]
@aquynh prefixes like *repe* and *repne* need a special attention because when associated with a *lock* prefixes they mean *xacquire/xrelease* (HLE feature) with a notable exception for *XCHG* where *lock* is already implict and still those prefixes mean  *xacquire/xrelease*. Maybe this is already handled but I thought it was better to draw your attention upon it if not. 

http://www.felixcloutier.com/x86/XACQUIRE:XRELEASE.html

**Comment by hlide** [comment]
>Hardware Lock Elision (HLE) adds two new instruction prefixes, XACQUIRE and XRELEASE. These two prefixes reuse the opcodes of the existing REPNE / REPE prefixes (F2H / F3H). On processors that do not support TSX, REPNE / REPE prefixes are ignored on instructions for which the XACQUIRE / XRELEASE are valid, thus enabling backward compatibility.[14]

>The XACQUIRE prefix hint can only be used with the following instructions with an explicit LOCK prefix: ADD, ADC, AND, BTC, BTR, BTS, CMPXCHG, CMPXCHG8B, DEC, INC, NEG, NOT, OR, SBB, SUB, XOR, XADD, and XCHG. The XCHG instruction can be used without the LOCK prefix as well.

>The XRELEASE prefix hint can be used both with the instructions listed above, and with the MOV mem, reg and MOV mem, imm instructions.

>HLE allows optimistic execution of a critical section by eliding the write to a lock, so that the lock appears to be free to other threads. A failed transaction results in execution restarting from the XACQUIRE-prefixed instruction, but treating the instruction as if the XACQUIRE prefix were not present.
