### ISSUE TITLE
INS, OUTS, LODS instructions' REPNE prefix isn't detected

### ISSUE THREAD

**Issue by 10110111** [aquynh/capstone#454]
The instructions `6C`, `6D`, `6E`, `6F`, `AC`, `AD`, when prefixed with REPNE prefix `F2`, lack the prefix in capstone's representation. See [test C code](https://pastebin.mozilla.org/8842749).

**Comment by aquynh** [comment]
fixed. please confirm, thanks.

**Comment by 10110111** [comment]
Not fixed for `F2 AD`.

**Comment by aquynh** [comment]
fixed, please confirm.

**Comment by 10110111** [comment]
Fixed now.
