### ISSUE TITLE
add al,8 instruction appears to have 3 operands when using AT&T syntax

### ISSUE THREAD

**Issue by 10110111** [aquynh/capstone#455]
Some instructions like `04 08` (`add al,8`), `24 05` (`and al,5`), `0C 05` (`or al,5`) are represented correctly with two operands when using Intel syntax, but appear to have three operands when AT&T syntax is in use. Here's a [test C code](https://pastebin.mozilla.org/8842752), reproducing this bug.

**Comment by aquynh** [comment]
fixed, please confirm.

**Comment by 10110111** [comment]
Fixed, at least for the instructions mentioned in the OP.

**Comment by 10110111** [comment]
This remains broken for instructions covered by #458, likely many others.
