### ISSUE TITLE
ARM32 Opcodes 0xE19120D3 and 0xE11120D3 Disassemble Incorrectly

### ISSUE THREAD

**Issue by 9ee1** [aquynh/capstone#459]
Using Capstone 3.0.4:

The ARM instructions 0xE19120D3 (ldrsb\tr2,[r1,r3]) and 0xE11120D3 (ldrsb\tr2,[r1,-r3]) differ only in the bit that indicates the sign of the index register r3. When Capstone returns, the memory operand's index register scale is incorrect; it's -1 for the first instruction and 1 for the second.

See 9ee1/Capstone.NET#12 for more information.

**Comment by aquynh** [comment]
fixed. please confirm, thanks.

**Comment by uxmal** [comment]
I can confirm that most recent Capstone build has resolved this issue.
