### ISSUE TITLE
When is a MOV instruction named MOVABS?

### ISSUE THREAD

**Issue by 10110111** [aquynh/capstone#461]
I'm trying to figure out when Capstone writes `movabs` instead of `mov`. In Intel's docs all the instructions given by Capstone as `movabs` are `mov`. But OTOH, they don't mention `movabs` mnemonic at all.
So what are the exact rules of choosing mnemonic in this case? Does it depend on operand size? Bit-extension behavior? Memory reference presence? Or what?

**Comment by hlide** [comment]
*movabs* is ATT-syntax for `mov al/ax/eax/rax, byte/[d|q]word ptr [<64-bit absolute address>]` or `mov byte/[d|q]word ptr[<64-bit absolute address>], al/ax/eax/rax`

**Comment by 10110111** [comment]
Why does then Capstone disassemble `48 b8 00 e8 98 37 00 00 49 89` as

    movabs rax, -0x76b6ffffc8671800

? This is why my question: Capstone doesn't seem to use the same convention you suggested.

**Comment by hlide** [comment]
it look like the ATT-syntac even under Intel-syntax, probably a miss.

**Comment by hlide** [comment]
ATT-syntax: `movabs -0x76b6ffffc8671800, %rax`

for me there, *capstone* is wrong: it should be `movabs rax, qword ptr [-0x76b6ffffc8671800]`

**Comment by hlide** [comment]
sorry, it is note the same opcode. This is a 64-bit immediate version, not the 64-bit address version you were speaking about. There is a quote I found:
>What's interesting, gdb gives me 48 b8 <imm64> bytes as movabs rax, <imm64> even in disassembly-flavor=intel

I think the reason is probably to disambiguate from a 32-bit version `mov rax, <imm32>` so an assembler can know which one to generate.

**Comment by 10110111** [comment]
Funny, you've found my own comment on StackOverflow :)

**Comment by hlide** [comment]
LOL :)
