### ISSUE TITLE
ARM32 opcode 0xE7695081 disassembles incorrectly

### ISSUE THREAD

**Issue by uxmal** [aquynh/capstone#462]
I'm comparing the output of Capstone with [Online Disassembler](http://www.onlinedisassembler.com). The ARM32 opcode E7695081 yields:
`strb r5,[sb,-r0,lsl #1]`
Online Disassembler yields:
`strb r5,[r9,-r1,lsl #1]`

The low 12 bits, 0x081, indicate r1 as the index register, not r0.

**Comment by aquynh** [comment]
what makes you think that ODA (which uses GNU disassembler inside) is correct, but Capstone is wrong?

**Comment by aquynh** [comment]
ok did not see that you explained above. let me check with the ARM manual, thanks.

**Comment by uxmal** [comment]
My apologies,  a build process keeps pulling in an old version of Capstone that had this problem. Most recent capstone disassembles correctly.
