### ISSUE TITLE
Is there any reason to consider 66 EB 00 the same as EB 00 in 32 bit mode?

### ISSUE THREAD

**Issue by 10110111** [aquynh/capstone#465]
I've tested some unusual jumps, and here are the results for GDB, ndisasm and Capstone versus CPU.

addr: instruction| GDB | ndisasm | capstone | CPU
--------------------|--------|-----------|--------------|------
(32bit) 80484d0: <br/>66 EB 00 |data16<br/> jmp 0x80484d3 | o16<br/> jmp short 0x80484d3 | jmp 0x80484d3 | jmp 0x84d3
(32bit) 8048518: <br/>66 E9 00 00 90 90 | jmpw 0x851c; nop;nop | jmp word 0x851c; nop;nop | jmp 0x851c; nop;nop | jmp 0x851c; nop;nop (**OK**)
(64bit) 40106b: <br/>66 EB 00 | data16 jmp 0x40106e | o16 jmp short 0x40106e | jmp 0x40106e | jmp 0x40106e (**OK**)
(64bit) 4010ac: <br/>66 E9 00 00 90 90 | jmp 0x10b0; nop;nop | jmp qword 0xffffffff90d010b2 | jmp 0x10b0; nop;nop | jmp 0xffffffff90d010b2

Here CPU means the CPUs I checked, namely several Intel's, one VIA's as well as Bochs emulated CPU.
You can see that in 32 bit mode all disassemblers disagree with CPUs on the meaning of `66 EB 00`. **QUESTION 1**: is there any good reason for them to behave so? It seems to be vaguely documented in Intel's docs, which say that higher bits of RIP are masked if `OperandSize=16` and jump is _NEAR_. But apparently this is also true for _SHORT_ jumps.

**QUESTION 2**: Concerning the fourth row of the above table, i.e. 64 bit mode `66 E9 00 00 90 90`, only ndisasm seems to agree with CPUs, while GDB and Capstone appear wrong. Should this be just fixed, or is there again some good reason for current behavior?

The check was done using this C program:

````C
#include <signal.h>
#include <stdlib.h>
#include <stdio.h>

void sigHandler(int signum, siginfo_t* siginfo, void* context_)
{
    printf("ended up at %p\n",siginfo->si_addr);
    exit(0);
}

int main()
{
    struct sigaction act={0};
    act.sa_sigaction=sigHandler;
    act.sa_flags=SA_SIGINFO;
    sigaction(SIGSEGV, &act, NULL);

    void* startAddr;
    asm("mov %0, offset theJump\n":"=r"(startAddr));
    printf("Doing a strange jump:\n %p: 66 EB 00\nExpecting landing at %p...",startAddr,(char*)startAddr+3);
    asm("theJump: .byte 0x66\n.byte 0xEB\n.byte 0x00\n");
    printf("the jump ended up being a no-op, landed where expected\n");

    asm("mov %0, offset nearJump\n":"=r"(startAddr));
    printf("Now trying a near jump followed by two NOPs:\n %p: 66 E9 00 00 90 90\nExpecting landing at %p...",startAddr,(char*)(((size_t)startAddr+4)&0xffff));
    asm("nearJump: .byte 0x66\n.byte 0xE9\n.byte 0x00\n.byte 0x00\n"
            "nop\nnop\n");
    printf("the jump also ended up being a no-op, landed where expected\n");
    return 0;
}
````

**Comment by hlide** [comment]
In AMD documentation, it is pretty clear:

>If the JMP target is specified by a displacement in the instruction, the signed displacement is added to the rIP (of the following instruction), and the result is truncated to 16, 32, or 64 bits depending on
operand size. The signed displacement can be 8 bits, 16 bits, or 32 bits, depending on the opcode and the operand size.
For near jumps in 64-bit mode, the operand size defaults to 64 bits. The E9 opcode results in RIP = RIP + 32-bit signed displacement.

**Comment by hlide** [comment]
To sum up, it looks like:

1) 16/32-bit mode: result truncated to 16/32-bit value according to operand size (for compatibility with legacy code).

2) 64-bit mode: displacement sign-extended to 64-bit value to add (no need for compatibilty).

**Comment by hlide** [comment]
in Intel documentation:
>f64: The operand size is forced to a 64-bit operand size when in 64-bit mode (prefixes that change operand size are ignored for this instruction in 64-bit mode).

Opcode E9 and EB have f64 attribute in the one-byte opcode map.

**Comment by 10110111** [comment]
OK, so current behavior of Capstone (and some others) is just what should be fixed. Thanks.
