### ISSUE TITLE
SGDT and SIDT format arguments strangely

### ISSUE THREAD

**Issue by 10110111** [aquynh/capstone#470]
Example bytes:

````
0F 01 05 A0 90 04 08  sgdt [0x80490a0] // capstone says sgdt ptr [0x80490a0]
0F 01 0D A7 90 04 08  sidt [0x80490a7] // capstone says sidt ptr [0x80490a7]
````

Here the instructions should either have some operand size given (maybe `fword`, although it's not really `seg:offset`), or not say `ptr` at all. Half-way here or there isn't good enough.

**Comment by aquynh** [comment]
So simply removing "ptr" will work?

Thanks

**Comment by 10110111** [comment]
I think yes.

**Comment by 10110111** [comment]
Also `lgdt` and `lidt` are affected:

````
0F 01 15 A0 90 04 08  lgdt [0x80490a0] // capstone says lgdt ptr [0x80490a0]
0F 01 1D A7 90 04 08  lidt [0x80490a7] // capstone says lidt ptr [0x80490a7]
````

**Comment by 10110111** [comment]
This seems to be fixed indeed.

**Comment by aquynh** [comment]
thanks for reporting!
