### ISSUE TITLE
SGDT and SIDT arguments are reported to have wrong sizes

### ISSUE THREAD

**Issue by 10110111** [aquynh/capstone#471]
`lgdt`, `sgdt`, `lidt`, `sidt` should have 48-bit operands in 16- and 32-bit modes and 80-bit operands in 64 bit mode. But capstone reports sizes equal to default operand sizes according to mode.

**Comment by aquynh** [comment]
i have a fix for this issue, but to confirm it, would you mind putting the testcases for these instructions into `suite/regress.py`? thanks.

**Comment by 10110111** [comment]
I fail to see how operand sizes would fit into that structure (again, I don't know python to add this functionality there myself).

**Comment by aquynh** [comment]
Right, so just add the assembly output to that.

Thanks.

**Comment by 10110111** [comment]
Not fixed for 16 bit mode. The argument should have the same size as in 32 bit mode. The difference there is that the offset is saved as zero-extended 24-bit number and loaded ignoring upper byte, but the full argument remains 48 bits.

**Comment by aquynh** [comment]
just pushed another commit. can you check again now?

**Comment by 10110111** [comment]
Pushed where? I don't see anything changed in `next` branch.

**Comment by aquynh** [comment]
can you check again the "next" branch now?

**Comment by 10110111** [comment]
Yeah, fixed now, thanks.

**Comment by aquynh** [comment]
thanks for reporting!
