### ISSUE TITLE
How to handle disasm error?

### ISSUE THREAD

**Issue by mtivadar** [aquynh/capstone#474]
it says that "By default, disasm disassembles all the code until either there is no more code, or it encounters a broken instruction." Is there a way to get over broken instructions? And maybe to retrieve them as an object something like  X86InvalidInstruction (for X86), with a string inside like 'db 0xYY' ? .. or as a valid instruction with mnemonic 'db 0xYY' ...

**Comment by aquynh** [comment]
yes, this is called *SKIPDATA* mode: http://www.capstone-engine.org/skipdata.html

you can find more docs at http://www.capstone-engine.org/documentation.html

**Comment by mtivadar** [comment]
thank you, that's nice implemented.
