### ISSUE TITLE
capstone fails to build on cygwin

### ISSUE THREAD

**Issue by radare** [aquynh/capstone#477]
Recently, r2 moved to use stdbool.h instead of our own true/false defines. this turned into a failure build of capstone from r2 on native windows builds. Latest visual studio supports C99, so im assuming that if you build r2 with visual studio you are not going to use anything older. The same happens when building with cygwin, capstone doesn't makes this assumption and fails with this error:

```
../../shlr/capstone/include/capstone/platform.h:14:23: error: two or more data types in declaration specifiers
 typedef unsigned char bool;
                       ^
```

This is happening because capstone doesn't honors __CYGWIN__.

**Comment by radare** [comment]
Related appveyour demo: https://ci.appveyor.com/project/radare/radare2/build/0.10.0.1588

**Comment by radare** [comment]
Reference https://github.com/radare/radare2/issues/3291

**Comment by aquynh** [comment]
Can you send a PR to fix this? Thanks

**Comment by radare** [comment]
I'm waiting for appveyour to finish the build to confirm the patch:

https://github.com/radare/radare2/commit/f3ea9e63fefacdb9061dcc159c3f6f150ad78720

**Comment by radare** [comment]
yeah it worked https://ci.appveyor.com/project/radare/radare2/build/0.10.0.1620

**Comment by radare** [comment]
this is the patch: https://raw.githubusercontent.com/radare/radare2/f3ea9e63fefacdb9061dcc159c3f6f150ad78720/shlr/capstone-patches/fix-cygwin.patch

**Comment by aquynh** [comment]
can you  please submit a proper PR? thanks.

**Comment by radare** [comment]
See https://github.com/aquynh/capstone/pull/480
