### ISSUE TITLE
Capstone is 5x slower than udis86 analysing x86-64 code in r2

### ISSUE THREAD

**Issue by radare** [aquynh/capstone#481]
We are investigating on that issue, but callgrind shows that the bottleneck is in capstone, not in r2 plugin itself. This can be verified by using the `?t aa` command, right after setting the `e asm.arch=x86.udis` variable, to select a different asm/anal plugin.

**Comment by aquynh** [comment]
yes i am aware of this. would be nice if you can find someone in radare project to look at this problem. optimizing for performance is always the priority.

**Comment by radare** [comment]
Yes @jvoisin noticed this and he's already doing some profiling to determine the main bottlenecks

**Comment by jvoisin** [comment]
[Here is]( http://rghost.net/7TwLWNyPJ ) a callgrind profiling result, as you can see, `cs_disasm`, `insn_find` and `X86_get_ins_id` are slow.

**Comment by radare** [comment]
I did another trace, and looks like main bottleneck is in make_id2insn which allocates and initializes a cache. This can be related to the way we are using the capstone api, but even like this, that function should be called only once, and its called 22.059 times in my test. Can we persist that index cache across various capstone runs?

**Comment by radare** [comment]
Also, the name2insn is iterating over all the keys, when it can be optimized with an O(1) hashtable. but this function is not called frequently

**Comment by radare** [comment]
Confirmed, the analysis module was reinitializing the library on every instruction, this is why this function was called so many times. The speed is similar to udis right now, which is really good. Sorry for the noise.

**Comment by aquynh** [comment]
oh do not stop here. why you are happy, but dont try to make it faster than Udis?

those places you mentioned are where we can really improve the performance further.

**Comment by radare** [comment]
i'll try to fill independent issues for specific performance problems when i have some spare time. actually having a faster cs_open would be good. because it should just initialize some pointers and not take that much time to get the whole hashtable cache ready to use.
