### ISSUE TITLE
LJMP doesn't show "what" PTR the argument is, but does show "PTR"

### ISSUE THREAD

**Issue by 10110111** [aquynh/capstone#492]
Consider the following instruction in 32 bit mode:
````
FF 2D 00 00 00 00   jmp fword ptr [0]
````
It is disassembled as `ljmp ptr [0]` by Capstone, which doesn't make sense. Either `ptr` should go away, or it should be preceded by `fword`.

**Comment by hlide** [comment]
i would expect "far ptr" (vs. "near ptr").

**Comment by 10110111** [comment]
Don't the assemblers which use `ptr` (masm, tasm, ...) take such a jump as `jmp near label` and `jmp far var`, without `ptr`?

**Comment by hlide** [comment]
Those are for direct jumps.

1) direct jumps (no memory access):

* *jump near $+imm<sub>32</sub><sup>±</sup>* will set IP with the immediate value.
* *jump far imm<sub>16</sub><sup>0</sup>:imm<sub>32</sub><sup>±</sup>* will set IP and CS with the pair of immediates.

2) indirect jump (with memory access):

* *jump near ptr [imm<sub>32</sub><sup>±</sup>]* will fetch a 32-bit word (for IP) as target jump
* *jump far ptr [imm<sub>32</sub><sup>±</sup>]* will fetch a 32-bit word (for IP) then a 16-bit word (for CS) as target jump.

But again, it would be what I would expect but I guess using *dword/fword ptr* is not wrong.

**Comment by 10110111** [comment]
BTW, the same happens with `fxsave` and `fxrstor`. They have this orphan `ptr` in their operand. See e.g. these codes (and how the instructions should look):

    0F AE 04 24   fxsave [esp]
    0F AE 0C 24   fxrstor [esp]

**Comment by aquynh** [comment]
fixed with commit https://github.com/aquynh/capstone/commit/10730fa971544a02a8061d25650c5fe2c61db639 for the "next" branch, thanks!

**Comment by 10110111** [comment]
What about ljmp/lcall?

**Comment by aquynh** [comment]
so `FF2D00000000       ljmp	ptr [0]` should be changed to `ljmp	far ptr [0]`?

what is the input for lcall so we can test the fix?

**Comment by 10110111** [comment]
I think we don't need any `far ptr`, since `far` is already encoded in `ljmp` mnemonic. So I suggest the following:

    FF 18    lcall [eax]
    FF 28    ljmp [eax]

But if you strongly want to have that `far ptr`, then I'd change `ljmp`/`lcall` to `jmp`/`call`. But, of course, even `ljmp far ptr`/`lcall far ptr` is still better than `ljmp ptr`/`lcall ptr`.

**Comment by aquynh** [comment]
fixed with this commit https://github.com/aquynh/capstone/commit/a4bdbc81575ff5d9e571237be09b30823cdde122, thanks.

**Comment by 10110111** [comment]
Confirming fixed.
