### ISSUE TITLE
issues of M68k

### ISSUE THREAD

**Issue by aquynh** [aquynh/capstone#494]
attention: @emoon & @nplanel 

i fixed some problems with M68K code here https://github.com/aquynh/capstone/commit/ac63d5b9951e0f94c117232a74874a3ff36a7eec. one notable issue: we should declare variables in the beginning of the functions or blocks to make C99 compilers happy (example is older MSVC compilers)

another major issue is: we cannot declare static variables like https://github.com/aquynh/capstone/blob/m68k/arch/M68K/M68KDisassembler.c#L63 or https://github.com/aquynh/capstone/blob/m68k/arch/M68K/M68Kdasm.c#L194. The problem will show when 2 instances of M68K engines run at the same time, and in this case these instances will share the same static data leading to a mess.

To solve this problem, please see how other archs passing around variables via function arguments (such as *MCInst*). In some special cases, if there is no better choice, it is possible to store these variables into struct **MCInst** (https://github.com/aquynh/capstone/blob/m68k/MCInst.h#L92) or **cs_struct** (https://github.com/aquynh/capstone/blob/m68k/cs_priv.h#L51)

**Comment by nplanel** [comment]
As a workaround, Is setting all the global variables in a struct and declaring this structure as TLS (Thread Local Storage) (__thread) would fit with your coding style ?

**Comment by nplanel** [comment]
Do you have the .clang-format file / could you commit on the root repo ?

**Comment by aquynh** [comment]
regarding TLS: no, i prefer the current method, which i believe is more portable.

on the coding style: i did all the indentation inside vim. i heard clang format is nice, but never use that. i think the problem with it is that not everybody is using llvm/clang, as gcc is still the default compiler on Linux.

**Comment by aquynh** [comment]
another problem is present with this commit: https://github.com/aquynh/capstone/commit/b16658d39e141231edc1ca0d75011980cd61f95f. you can compile and run `tests/test_basic` to see that the disassembly output of M68K is empty. it seems that when *detail* option is not enable like in this case, M68K engine does not produce *mnemonic* and *op_str* ??

**Comment by nplanel** [comment]
@aquynh I done a PR for the global valiables issues, now the code is reentrant.

Regarding the code produce without detail option, we seen that last week, the mnemonic should be generated ; But internally op_str is built from details information.

**Comment by aquynh** [comment]
but currently `tests/test_basic` still produces empty mnemonic & op_str. something must be wrong here.

another thing: would you mind splitting printer code out of `M68KDisassembler.c`, and move all the content of `M68Kdasm.c` to `M68KDisassembler.c`? this way the code is better organized, and also consistent with all other archs.

**Comment by nplanel** [comment]
Hmmm, so that why we are divergent at the implementation ... I can return you the question, why others arch didn't split the vectorized disassembly and his representation/output ?
As you seen in contrib the objdump-m68k python code dump the m68k code as objdump output syntax. (this tool was used to validate the implementation)

So in our case I think we need to always enable opcode decoding (regardless to option detail), by writing in the m68k_info struct and copy the opcode to details in the option is enabled. (like others arch)

So why the CS_OPT_DETAIL exist ? I think it was originally to enhance memory usage and speed, by disabling it, but may I'm wrong ; Could you give me more info of the idea behind ?

**Comment by emoon** [comment]
Also

```
 splitting printer code out of M68KDisassembler.c
```

Where do you suggest we put this code?

(sorry for the low amount of replies, I'm away over the weekend)

**Comment by aquynh** [comment]
@nplanel, i dont really understand your first question. but my idea is to isolate printer & decoder into separate files. for example with ARM, we have `arch/ARM/ARMInstPrinter.c` & `arch/ARM/ARMDisassembler.c`: the former is for producing mnemonic, op_str & other detail info, while the later is for decoding instrutions.

the reason behind `CS_OPT_DETAIL` is that many apps do not really care about all the data that Capstone can produce, but only need mnemonic, op_str and few other basic information. this is why detail is off by default. only advanced apps need to turn on this option to get more details such as operands, instruction groups, etc. to pay for more info, they must accept that disassembling process is slower, and also more memory is consumed.

**Comment by aquynh** [comment]
@emoon, i mean all the decoder code can be put into M68KDisassembler.c, and printer code enters M68KInstPrinter.c

do you plan to have M68KMapping.c later?

**Comment by emoon** [comment]
Sure I can fix that.

The plan is the add the mapping later but we figured that getting the current state in gets the users that want 68K support quite a long way without the support right now.

**Comment by emoon** [comment]
Added https://github.com/aquynh/capstone/pull/496 which does the renaming part.

**Comment by emoon** [comment]
> but currently tests/test_basic still produces empty mnemonic & op_str. something must be wrong here.

I have added some mnemonic is being printed in https://github.com/emoon/capstone/commit/fb01d6d9b11ae081b46f2c26e4c1e7de3793c1df

**Comment by emoon** [comment]
> the reason behind CS_OPT_DETAIL is that many apps do not really care about all the data that Capstone can produce, but only need mnemonic, op_str and few other basic information. this is why detail is off by default. only advanced apps need to turn on this option to get more details such as operands, instruction groups, etc. to pay for more info, they must accept that disassembling process is slower, and also more memory is consumed.

So.. if detail is disabled would it be ok for us to use an internal detail struct that never "gets sent back" that we can be used when we generate the op_str? This would make the disassembly as slow as when detailed is on but tbh that shouldn't be an issue.

**Comment by aquynh** [comment]
yes, but ideally avoid this trick if possible.

**Comment by emoon** [comment]
It would be a bit hard because all the code is based around it. Also the data can still just been seen as an internal state that the outside doesn't need to know about it.

**Comment by aquynh** [comment]
in that case, please document this trick somewhere for future reference.

also, you should make sure `cs_insn.detail` is NULL if detail option is off.

**Comment by emoon** [comment]
Yes will do. Thanks for the info.

**Comment by emoon** [comment]
Is there some way to store "user data" inside *MCInst* ? It seems that for example x86 stores some specific stuff in there.

**Comment by aquynh** [comment]
You can add new fields there. But avoid this if there is other option.

**Comment by emoon** [comment]
Alright. Thanks.

**Comment by emoon** [comment]
Urgh. I can't figure out a good way to do this. Maybe @nplanel has some ideas.

1. I would like to not have m68k_detail struct inside MCInst because that just feels wrong.
2. An better alternative would be to have a void* user_data; ptr there which any backend can use and thus hide implementation details (as could x86)

Problem with 2 is that to have a user_data there is that it needs to be allocated / freed (as it needs to be persistent between GetInstruction and PrintInst)

**Comment by nplanel** [comment]
@emoon : My idea is to use the new struct m68k_info (introduced in #495) that is used internally to remove globals/reentrance code. And copy the operands only if detail option is on.

```
typedef struct m68k_info {
	MCInst *inst;
	uint pc;        /* program counter */
	uint ir;        /* instruction register */
	uint type;
	unsigned int address_mask; /* Address mask to simulate address lines */

        cs_m68k_op operands[M68K_OPERAND_COUNT];
} m68k_info;
```

So basically we always use the operands internally and we just need to copy bad the info after m68k_disassemble() : https://github.com/aquynh/capstone/blob/m68k/arch/M68K/M68KDisassembler.c#L4150

**Comment by emoon** [comment]
@nplanel Yeah I thought of something like that but will it work to just have a single instance of m68k_info on the heap? As if there are multiple instances (that was part of you adding the m68k_info)

**Comment by nplanel** [comment]
Yes sure, each m68k_info instance will be per instruction disassembly / per handle / per instance.

**Comment by nplanel** [comment]
we can just expose operands[M68K_OPERAND_COUNT] on the heap to the printer as, we don't need to expose private info and declare the struct in a common header. (cs_m68k_op is public)

**Comment by nplanel** [comment]
I will do a PR and we can review it

**Comment by emoon** [comment]
> I will do a PR and we can review it

Sounds good! Thanks.

**Comment by nplanel** [comment]
done #500

**Comment by aquynh** [comment]
have you tried to compile on Windows using CMake (see https://github.com/aquynh/capstone/blob/m68k/COMPILE_CMAKE.TXT)? please clear all the compilation issues with MSVC+CMake, if any, then we can merge this to the "next" branch.

besides, if you can also make https://github.com/aquynh/capstone/tree/m68k/msvc to support M68K, it will be perfect. otherwise, we can find somebody to help on this.

finally, https://github.com/aquynh/capstone/tree/m68k/xcode needs to support M68K, too.

thanks.

**Comment by emoon** [comment]
I can take a look at the MSVC issues.

**Comment by aquynh** [comment]
on XCode support, if you cannot do that, we can ask @zneak to help.

**Comment by emoon** [comment]
It depends on which version it has to be. I use Xcode 7 at home which is likely a never version of the format.

**Comment by aquynh** [comment]
i can confirm that on Mac OS X, CMake can compile everything without any issues.

**Comment by emoon** [comment]
yeah, I have coded everything on Mac with CMake so that should work fine.

**Comment by emoon** [comment]
Btw I have only VS2012 as lowest version right now. Do I need to make sure it works on VS2010 also?

**Comment by aquynh** [comment]
i believe that current MSVC solution file is already made for VS 2010, and newer VS versions are also supported (but you have to convert the solution before compiling)

**Comment by emoon** [comment]
yeah that is fine but I'm thinking in the sense of changes for the C/C++ compiler but I don't think that much has changed between VS2010 and VS2012 when it comes to C.

**Comment by zneak** [comment]
I'll check for Xcode.

**Comment by emoon** [comment]
@zneak thanks!

**Comment by aquynh** [comment]
yes, the same code should be compiled on newer MSVC for sure. the most important thing is to check if CMake+MSVC work on Windows with this new M68K code. i expect some minor compiler warnings.

**Comment by emoon** [comment]
Yeah I'm working on fixing them now.

**Comment by emoon** [comment]
Warnings fixed in https://github.com/aquynh/capstone/pull/501

**Comment by zneak** [comment]
Xcode project updated in #502.

By the way @emoon, Xcode 7 still uses the Xcode 3.2 project file format. This is verifiable by clicking the project file in the sidebar, opening the Utilities bar (the right bar), and checking the "Project Format" setting.

**Comment by emoon** [comment]
@zneak ah, good to know :)

**Comment by aquynh** [comment]
now `tests/test_m68k` produces something like this:

    0x101c:	scc.b	d5
	op_count: 1
		operands[0].type: REG = d5

a question: don't you express the information on ".b" in "scc.b" ? this info should be available somehow in `cs_m68k`, given that instruction name is just "scc"?

**Comment by emoon** [comment]
Yes that information is available in cs_m68k.

The print out of "scc.b" is the verbose "output" which 68k assemblers will accept but in this case they will also accept "scc" as sxx is byte sized.

Usually the default size for 68k instructions is word size (16-byte) so if one do

```ASM
move d0,d1 ; lower 16-bit of d0 moved to d1
```

Usually though many people write .w (word) to make it a bit more clear. We could remove printing of .b in this case (as this instruction has only one size) but when instructions can have several sizes I think it's just more clear to include it.

**Comment by aquynh** [comment]
when instruction has several sizes, which info in `cs_m68k` can tell this?

**Comment by aquynh** [comment]
oh i missed that "op_size".

**Comment by emoon** [comment]
Yeah that is the one.

**Comment by aquynh** [comment]
ok, so now is the final request: can you make `bindings/python/test_m68k.py` to produce the output exactly like `tests/test_m68k.c`?

**Comment by emoon** [comment]
Poking @nplanel to fix that one :)

**Comment by nplanel** [comment]
Hahaha, an old one, yeah from the beginning I catch that python and c output must output the same due to regression testing ... I will patch that later.

**Comment by nplanel** [comment]
done in #504 including some other fixes.

**Comment by nplanel** [comment]
Thanks @zneak for the Xcode

**Comment by aquynh** [comment]
i just merged branch "m68k" to "next". CREDITS.TXT was also updated to credit your great works on this new architecture: https://github.com/aquynh/capstone/commit/580ac52b1636f75244075cb74ab1f1797cccfb29

still looking forward to support for instruction groups, so it is even with the rest architectures.

it is even better if you can make this for M68K: http://www.capstone-engine.org/op_access.html

thanks!

**Comment by emoon** [comment]
Awesome! Thanks!

Yes, the plan is to add support for that later on (exactly when I dunno yet)

Will it be best to base the work on the next branch now as it has been merged in as I assume the m68k branch was temporary?

**Comment by aquynh** [comment]
yes, i already deleted the "m68k" branch.

**Comment by emoon** [comment]
Alright! Thanks :)

**Comment by nplanel** [comment]
Cool Thanks :)

**Comment by aquynh** [comment]
Coverity just reported an issue at this line https://github.com/aquynh/capstone/blob/next/arch/M68K/M68KDisassembler.c#L1051: `info` was already referenced on the path leading to this place, so why is there still this NULL verification?

**Comment by nplanel** [comment]
They should not have this test anymore as info is always present now.
I will review and do a new PR later

**Comment by radare** [comment]
While doing the m68k.cs plugin for r2 i have found different segfaults.this is the first one. trying to access outside the array boundaries. i'll report more as soon as they get fixed.

The bytes this usecase is trying to disassemble are 554889e5

<img width="637" alt="screen shot 2015-10-07 at 13 48 57" src="https://cloud.githubusercontent.com/assets/917142/10336681/cc287358-6cfa-11e5-8915-5070fb5dab3b.png">

You can test this stuff by doing `r2 -a m68k.cs ...` using the latest code from git

**Comment by emoon** [comment]
What is the input data you are actually testing with?

**Comment by radare** [comment]
@emoon i already said this in my comment. this is a small snippet if you are lazy to build r2

```
#include <stdio.h>
#include <stdlib.h>
#include <capstone/capstone.h>


int main()
{
        int count;
        static csh handle;
        cs_insn *insn;
        uint8_t fun[] = "\x55\x48\x89\xe5";
        int mode = CS_MODE_BIG_ENDIAN;
        cs_option(handle, CS_OPT_DETAIL, CS_OPT_ON);
        cs_err err = cs_open(CS_ARCH_M68K, CS_MODE_32, &handle);
        if (err) {
                printf("Failed on cs_open() with error returned: %u\n", err);
                abort();
        }
        count = cs_disasm(handle, fun, 4, 0x8000000, 1, &insn);
        printf ("%d\n", count);
        return 0;
}
```

the crash happens because of the `0x8000000` offset. which is used as a delta in that array

**Comment by radare** [comment]
Another issue in the m68k disassembler is the output syntax, because it is using $ as a prefix for hexadecimal numbers, but showing the number itself without the 0x which turns to be really confusing and conflicts with the rest of disassemblers in capstone. I would like to change from $f3 to 0xf3 for example. I'm already doing this fix in the r2 disassembler plugin, but it would be good to have it in main capstone

**Comment by emoon** [comment]
I used $f3 as that is the syntax that all the 68k assemblers I have used accept.

**Comment by emoon** [comment]
> the crash happens because of the 0x8000000 offset. which is used as a delta in that array

Alright. I will take a look at that.

**Comment by emoon** [comment]
@radare I think I know what the issue is. 68000 only has 24-bit address space and base address here isn't masked as it should.

https://github.com/aquynh/capstone/blob/next/arch/M68K/M68KDisassembler.c#L3804

So setting the address to something like 0x80000 will likely make it work. This should of course be fixed but just FYI.

**Comment by emoon** [comment]
Also setting CPU type to 020+ will work also as it has full 32-bit address space.

**Comment by radare** [comment]
In fact, GNU m68k disassembler uses '#0x' as a prefix for immediates

**Comment by radare** [comment]
Btw, `dc.w` is just a "define word", so its not really an instruction, because the other disassembler i use recognises this as an invalid instruction. i can find many other instructions that are disassembled differently comparing them. In r2 we'll soon have a testsuite to verify all the instructions for 68k on GNU, BSD and capstone, so you can compare all this stuff properly, but we should first fix the syntax to use a common one for consistency.

**Comment by emoon** [comment]
Doesn't GNU uses .short <n> which is pretty much the same thing?

**Comment by emoon** [comment]
I'm fine if someone want to add a different output mode (like there is Intel and GNU for x86) but I want to keep the current one.

**Comment by emoon** [comment]
Also @nplanel did a big pass on comparing output from capstone with objdump (m68k) using this https://github.com/emoon/capstone/blob/next/contrib/objdump/objdump-m68k.py and we also found a bunch of bugs in the 68k version of objdump while doing it.

**Comment by radare** [comment]
Interpretting the invalid instructions isnot up to the disassembler
library. See how this thing works in other disassembnlers

**Comment by radare** [comment]
Ok for supporting other syntaxes

**Comment by emoon** [comment]
> Interpretting the invalid instructions isnot up to the disassembler
> library. See how this thing works in other disassembnlers

objdump outputs ".short <number>" when it doesn't know about at a instruction.

**Comment by radare** [comment]
btw, the code from the other m68k disassembler in r2 comes from the netbsd kernel debugger.

**Comment by radare** [comment]
the disassembler library shouldnt display "short/dword/dc.w/..." only return error because it is not able to disassemble it. and right now it returns that it is a valid instruction of 2 bytes with that name.

**Comment by emoon** [comment]
> the disassembler library shouldnt display "short/dword/dc.w/..." only return error because it is not able to disassemble it. and right now it returns that it is a valid instruction of 2 bytes with that name.

We can change that. To me it doesn't matter that much. I will not remove the current output syntax though (but fine with adding another one)

**Comment by nplanel** [comment]
@radare I have done the fixes, thanks for your report.
As you point out we should skipdata, the code was there but not working properly :(
I add a basic boundary checker and fix your crash due to a bad usage of address_line_mask.
+ others fixup/improvements
I tested with latest radare and sound working well +1: 
```
  || ||||   0x00000084    4e41           trap #0x1
  || ||||   0x00000086    5c8f           addq.l #0x6,sp
  || ||||   0x00000088    41f900037451   lea 0x37451.l,a0
  ========< 0x0000008e    6100175e       bsr.w 0x17ee
  ========< 0x00000092    6000ff7a       bra.w 0x1000e
  =====`--> 0x00000096    61000082       bsr.w 0x11a
  || || |   0x0000009a    0c010014       cmpi.b #0x14,d1
  ========< 0x0000009e    6d6c           blt.b 0x10c
  || || |   0x000000a0    0c0100c8       cmpi.b #-0x38,d1
  ========< 0x000000a4    6466           bcc.b 0x10c
  || || |   0x000000a6    13c10003734a   move.b d1,0x3734a.l
  ========< 0x000000ac    6000ff60       bra.w 0x1000e
  ====`---> 0x000000b0    61000068       bsr.w 0x11a
  || |  |   0x000000b4    0c010014       cmpi.b #0x14,d1
  ========< 0x000000b8    6d52           blt.b 0x10c
  || |  |   0x000000ba    0c0100c8       cmpi.b #-0x38,d1
  ========< 0x000000be    644c           bcc.b 0x10c
  || |  |   0x000000c0    13c10003734b   move.b d1,0x3734b.l
  ========< 0x000000c6    6000ff46       bra.w 0x1000e
  || `----> 0x000000ca    4639000307f9   not.b 0x307f9.l
  ||    |   0x000000d0    4a39000307f9   tst.b 0x307f9.l
```
All are in the PR #507

**Comment by emoon** [comment]
Thanks @nplanel

**Comment by nplanel** [comment]
@aquynh last step, don't forget to add M68K on github headline :)

```
Capstone disassembly/disassembler framework: Core (Arm, Arm64, M680x0, Mips, PPC, Sparc, SystemZ, X86, X86_64, XCore) + bindings (Python, Java, Ocaml) http://www.capstone-engine.org
```

**Comment by aquynh** [comment]
fixed. thanks for reminding me this!

**Comment by onesbug** [comment]
```
1>d:\capstone\arch\m68k\m68kdisassembler.c(321): error C2059: 语法错误:“{”
1>d:\capstone\arch\m68k\m68kdisassembler.c(321): error C2065: “value”: 未声明的标识符
1>d:\capstone\arch\m68k\m68kdisassembler.c(321): error C2059: 语法错误:“)”
```
Looks like this code can not compiled under the windows platforms?

**Comment by emoon** [comment]
I have compiled it for windows. Can you paste some more code around those lines?

**Comment by onesbug** [comment]
https://github.com/aquynh/capstone/blob/next/arch/M68K/M68KDisassembler.c#L321
```c++
#define read_imm_16(info) ( { unsigned int value = peek_imm_16(info); (info)->pc+=2; value; } )

static void get_with_index_address_mode(m68k_info *info, cs_m68k_op* op, uint instruction, uint size, bool is_pc)
{
	uint extension = read_imm_16(info); <---- error C2059:syntax error:"{" in here.
                                                                   and error C2065:"value":undeclared identifier
        ....
```
< Does the file look ok for you when you open it in a regular code editor?

Nope,the file is normal,I didn't find any encoding problems.I use msvc2013.
and I'm not sure that read_imm_xx macros are right.

**Comment by nplanel** [comment]
@emoon just remove these macros and implement them as function (I hesitate yesterday) as it will be more compatible with not so advance compiler ... furthermore gcc will inline/optimize by himself.

**Comment by nplanel** [comment]
@emoon add const where it should be (addr, value, ...), const are quite helpful for optimization stage in gcc.

**Comment by emoon** [comment]
@npanel okay can you merge/redo my changes on top of yours and do a new PR?

**Comment by emoon** [comment]
Mine was really just to clean some stuff up. I agree that it's better to keep these as static functions.

**Comment by hlide** [comment]
#define function_like_macro(...) ({...})

those "({ ... })" are a GCC extension.

**Comment by nplanel** [comment]
@emoon  I cherry pick your patch.
Could you check win32/64 compilation on my branch [fix-win32-cleanup](https://github.com/nplanel/capstone/tree/fix-win32-cleanup)

I also fix some missing reference to M68KConf.h (Makefile, xcode)

@zneak could you validate my branch [fix-win32-cleanup](https://github.com/nplanel/capstone/tree/fix-win32-cleanup), If you can still open the Xcode project.

**Comment by emoon** [comment]
@nplanel will do! thank

**Comment by emoon** [comment]
@nplanel code compiles fine (VS2015 tested)

**Comment by emoon** [comment]
I did notice a small issue and that is CAPSTONE_HAS_M68K is missing in the MSVC projects (I likely missed it when I fixed them but I have no idea how I was able to compile it before though)

**Comment by nplanel** [comment]
Did you do a "cmake ." at the root of the project, this will overwrite the root Makefile and set CAPSTONE_HAS_M68K macro

**Comment by emoon** [comment]
No, there are two ways to build on Windows. Either just cmake or the existing msvc projects (which can be found in msvc/) and it's the existing msvc projects that are missing the define.

**Comment by nplanel** [comment]
I updated the msvc projects.

**Comment by emoon** [comment]
@nplanel thanks!

**Comment by zneak** [comment]
@nplanel, the Xcode project in your cleanup branch still opens and builds fine.

**Comment by nplanel** [comment]
@zneak Thanks !
@aquynh Could you merge the PR #513 please

**Comment by nplanel** [comment]
@bughoho : the next branch has been fixed

**Comment by emoon** [comment]
Is there any outstanding issues now or can this one be closed?

**Comment by aquynh** [comment]
only issue left is instruction group i think.

**Comment by emoon** [comment]
With instruction groups in can we close this now? There are of course more improvements that can be don't think we need to keep this open.

**Comment by nplanel** [comment]
@emoon I'm agree with you, I think @aquynh keep it open as tasks tracking.

**Comment by aquynh** [comment]
yes, thanks for all of your efforts!

**Comment by emoon** [comment]
Just FYI I have started with implementing the read/write register lists info over here https://github.com/emoon/capstone/tree/m68k-reg-read-write
