### ISSUE TITLE
48b800000000 => movabs rax, -0x8000000000000000 

### ISSUE THREAD

**Issue by Maijin** [aquynh/capstone#499]
In previous capstone (Hopper):
48b80000000000000080 => movabs rax, 0x8000000000000000       

In radare2 which uses the next branch:
48b80000000000000080 => movabs rax, -0x8000000000000000
                                                                                                                                                                                        

Is this update correct ?

**Comment by hlide** [comment]
should not it be: 48b80000000000000080?

technically a 64-bit word having a value 0x800000000000000, its negation is also 0x800000000000000 (-0x800000000000000 == 0x800000000000000).

**Comment by Maijin** [comment]
Yep you right for "48b80000000000000080" <- corrected

**Comment by hlide** [comment]
I know, it's just merely a question to know if we need to display an unsigned or signed value: if signed, -0x800000000000000<sub>65</sub> is correct because as long as bit 63 is one, it means the value is negative. If unsigned, we must indeed drop the sign indeed.

**Comment by aquynh** [comment]
some instructions prefer unsigned numbers, so never display negative numbers. if this is the case with MOVABS, i can change the core to do that too.

**Comment by aquynh** [comment]
fixed in the "next" branch, please confirm. thanks.
