### ISSUE TITLE
[bug]readOperands wrong behavior

### ISSUE THREAD

**Issue by bughoho** [aquynh/capstone#521]
I found a bug in the next version.

012D1126 |. A3 0C202D01 mov dword ptr ds:[0x12D200C],eax

InternalInstruction::displacement == 0
InternalInstruction::displacementOffset == 0

because readDisplacement has not been executed.
this bug occurred in the readOperands function
https://github.com/aquynh/capstone/blob/master/arch/X86/X86DisassemblerDecoder.c#L2059

**Comment by aquynh** [comment]
`012D1126 |. A3 0C202D01`   <--- what is this input hexcode with `|.` inside?

**Comment by bughoho** [comment]
raw bytes:A3 0C 20 2D 01

**Comment by aquynh** [comment]
this is not a bug in itself, but this means you also have to instrument other places to get what you want (to get the encoding information).

**Comment by bughoho** [comment]
if so,does this mean that cs_insn::cs_detail::cs_x86::disp which implements is not complete?

**Comment by bughoho** [comment]
This is another correct sample:
C7 05 11 11 11 11 22 22 22 22
mov     dword ptr ds:[0x11111111],0x22222222

The InternalInstruction::dispalcement value is:0x11111111;
InternalInstruction::dispalcementOffset value is:2;

but 
A3 11 11 11 11
mov dword ptr ds:[0x11111111],eax

The InternalInstruction::dispalcement value is:0;
InternalInstruction::dispalcementOffset value is:0

Is it not the wrong result?

**Comment by bughoho** [comment]
this is also another correct sample:

3B05 11111111               cmp     eax,dword ptr ds:[0x11111111]

InternalInstruction::dispalcement value is:0x11111111
InternalInstruction::dispalcementOffset value is:2

**Comment by obs1dium** [comment]
I guess this is limited to MOV instructions that take a direct memory offset, which at the moment gets interpreted as an immediate value. Storing it as a memory operand would be better IMO.

**Comment by bughoho** [comment]
yes,i think so.
my ability is limited,hope someone can solve this problem.

**Comment by obs1dium** [comment]
Upon closer inspection, the value gets read as an immediate, but is translated to a memory operand later on. Now to find the best place to set the displacement offset...

**Comment by bughoho** [comment]
good,the problem has been completely solved.
