### ISSUE TITLE
Android ARM no disasm

### ISSUE THREAD

**Issue by Cpruce** [aquynh/capstone#531]
Hi,

I am trying to read the instructions from a function in a .so file built for the Nexus 4 using Snapdragon. I have been able to disassemble the file in ida.

![screenshot from 2015-10-26 14 33 26](https://cloud.githubusercontent.com/assets/2712171/11016867/6a22db98-8542-11e5-9ca7-a4e685a4e183.png)

My guess is that I want to use md = Cs(CS_ARCH_ARM, CS_MODE_ARM). However, no output is produced through 

for (address, size, mnemonic, op_str) in md.disasm_lite(so_file_str, 0xea7c):#func_start_addr_hex):
       print("0x%x:\t%s\t%s" %(address, mnemonic, op_str))

I've mixed this mode with others like CS_MODE_LITTLE_ENDIAN, BIG_ENDIAN, MCLASS, and V8. But no luck in matching something close to ida (I believe Ida's to be true since it correctly identified structure). CS_ARCH_ARM64 also doesn't produce any output.

I have tried with X86 and CS_MODE_THUMB with CS_ARCH_ARM and these do actually produce output, though they seem incorrect.

This is my first project with capstone and it looks like exactly what I need (just reading opcodes from a function) so I understand if the error is just in something I'm doing. Any advice is greatly appreciated.

Thanks for the awesome tool!
Cory

**Comment by radare** [comment]
This is not thumb, and by the screenshot i asume this is a lib from an android app, and 99% of arms nowadays are little endian. You are probably disassembling the wrong offset. Use r2 to verify if thats a capstone bug or not. Also, r2 allows you to switch between physical and virtual addresses easily so it may help you to understand the problem in your code.

**Comment by aquynh** [comment]
sorry that i dont really get what your question is. ARM engine of Capstone works well for many people, so you can be assured that it should be OK.

can you paste your code here, focus on what you are still confused?

thanks.

**Comment by Cpruce** [comment]
radare - Yeah I didn't think it was thumb and the output the mode produced was not surprisingly invalid code. Cool I'll try with r2 soon!

aquynh - Everything of interested is in the OP. Im going to try with r2 first.

Thanks for the input!
Cory

**Comment by Cpruce** [comment]
Got it with r2, thanks!

**Comment by aquynh** [comment]
i dont really understand your question. the code above was to read the whole file content, but then you have to disassemble from the file entry. obviously, the file entry depends on the file format.

just in case, sample code to disassemble ARM code is at https://github.com/aquynh/capstone/blob/master/bindings/python/test_arm.py

**Comment by Cpruce** [comment]
No worries, r2 picked it up at the address and it matches ida
