### ISSUE TITLE
Adding: F0 0F C7 C8 -> lock cmpxchg8b [eax] 

### ISSUE THREAD

**Issue by Maijin** [aquynh/capstone#533]
See here for detail about the instruction: https://en.wikipedia.org/wiki/Pentium_F00F_bug

**Comment by Maijin** [comment]
Is the ceb0t dead ? Could be nice to have it on the next branch by the way :)

**Comment by radare** [comment]
Just use the r2bot in telegram or in cloud.radare.org, also allows to assemble and disassemble using all the r2 asm plugins

**Comment by Maijin** [comment]
@radare haha, I knw, but I wanted to check outside the r2world :P

**Comment by radare** [comment]
There's no such thing

**Comment by aquynh** [comment]
is there any disassemblers  that can handle this code "F0 0F C7 C8"?

yes the bot is offline now because i dont have a host to run it.
you can also try http://cenigma.org for alternative.

**Comment by Maijin** [comment]
@aquynh 
![image](https://cloud.githubusercontent.com/assets/1408600/11060841/10415754-87a3-11e5-96f6-0f63cfca2f19.png)

Looks like a perfect space for putting another menu to choose between next/release branch :)

**Comment by aquynh** [comment]
Capstone either reports a code as valid, or invalid. this is an invalid instruction, so would be confused to return it as legit. if you want to support it, it makes more sense to handle it in your tools.
