### ISSUE TITLE
movabs rax, -0x78000000000 instead of mov rax, 0xfffff88000000000

### ISSUE THREAD

**Issue by Maijin** [aquynh/capstone#541]
Hello,

`movabs rax, -0x78000000000` seems to confuse a lot of user CC @rootbsd . Is there a way to display like udis86: `mov rax, 0xfffff88000000000` ?

**Comment by aquynh** [comment]
is it a good idea to always print immediate in positive form for this instruction?

**Comment by aquynh** [comment]
what is hexcode of this?

**Comment by Maijin** [comment]
48b80000000080f8ffff

**Comment by radare** [comment]
It is useful to not have negative hex values at all. Mainly when reading kernel stuff where higher address bit is set

**Comment by aquynh** [comment]
fixed in the "next" branch now, thanks.
