### ISSUE TITLE
xchg reg1, reg2

### ISSUE THREAD

**Issue by fvrmatteo** [aquynh/capstone#545]
I don't know if I'm doing it wrong, but working with Capstone Next (but also Master) gives me wrong "access" flags on the instruction "xchg reg1, reg2". It should be:

reg1: CS_AC_READ|CS_AC_WRITE
reg2: CS_AC_READ|CS_AC_WRITE

Instead the reg1 is not marked as a write register. I also noticed missing flags on other instructions. Maybe this is not really important because Capstone Next is behind Capstone Master :)

I rely heavily on that flags on my project so it is easy for me to spot missing ones if needed.

**Comment by aquynh** [comment]
please provide information such as the hexcode & mode (32bit or 64bit) so it is possible to confirm the bug & test the fix.

**Comment by fvrmatteo** [comment]
![xchg](https://cloud.githubusercontent.com/assets/5798383/11179178/d84c8ce8-8c51-11e5-96ca-2eac1c2498f6.PNG)

Mode: ARCH_X86 - CS_MODE_32
Optional Information: ON
Instruction: xchg eax, ebp
Hex: 0x95

**Comment by aquynh** [comment]
fixed with this commit in the "next" branch: https://github.com/aquynh/capstone/commit/ed88b001f822e1df91a3092a91e9ecda8df3585d

to clarify: the API cs_regs_access() is only available in the "next" branch, but not "master" branch.

**Comment by fvrmatteo** [comment]
Thanks, more to come, I will open a new Issue with non-working access flags. Also I didn't use cs_regs_access() but directly dumped the detail->x86 structure. Anyway you are right, access flag is only available on Next branch, my fault.

**Comment by aquynh** [comment]
ok, but even better if you can fix that yourself and send in pull request. just look at the commit above and you will see how to update mapping table of register access & eflags.

**Comment by fvrmatteo** [comment]
I will do it Captain! :D hope to do it this week, and time to time when I find them.
