### ISSUE TITLE
Python 3 support: Bind `str` to `c_wchar_p` instead of `c_char_p`

### ISSUE THREAD

**Issue by Raijinili** [aquynh/capstone#557]
(I'm not very familiar with Python's ctypes, but I think I got this right.)

Problem: Python 3 gives an error when a CsError propagates to the top.

Reproduction: `from capstone import *; str(CsError(CS_ERR_DETAIL));`

Cause: CsError's `__str__` function returns a bytes (Python 2 non-unicode string) instead of a str (Python 3 unicode string). Python 3 requires that `__str__` returns a str.

Solution: When setting up the functions in [`__init__.py`](https://github.com/aquynh/capstone/blob/master/bindings/python/capstone/__init__.py), use `ctypes.c_wchar_p` if it's Python 3.

PS: There are also three other functions in `__init__.py` which return `c_char_p`.

*Edit:* I tried the change on my own copy, and it's not doing the right thing.

**Comment by zneak** [comment]
I'm not a ctypes expert either, but my understanding is that a `c_wchar_p` refers to a C `wchar_t*`. Changing it like that is likely to result in gibberish and/or buffer read overflows.

**Comment by Raijinili** [comment]
I guess the only thing to do is to change how `__str__` is defined depending on the version.

**Comment by aquynh** [comment]
@Raijinili, would you send in a pull request for this issue?

**Comment by Raijinili** [comment]
#558

I don't know if the style (the half-indent for condition) is acceptable.

**Comment by Raijinili** [comment]
#559 

I forgot about the indent rules. This version fixes that.

**Comment by aquynh** [comment]
merged the PR to both "master" & "next" branches, thanks!
