### ISSUE TITLE
capstone.__version__ is missing

### ISSUE THREAD

**Issue by egberts** [aquynh/capstone#575]
Due to rapid evolving API changes in capstone before, now, and later.... it would be helpful to have the version of the capstone module such that we can test for it properly.

```python
  import capstone
  if capstone.__version__ > '3.0.4':
    # get access of opcode instruction
  else:
    # skip access of opcode
```
Python community seems to highly recommends this... as outlined in [PEP-0396](https://www.python.org/dev/peps/pep-0396/).

**Comment by aquynh** [comment]
no, i think the better solution is that you should perform version checking in your tool before using newer API. otherwise we have to put multiple checks for various other newer features in the library this way.

**Comment by aquynh** [comment]
we already have `cs_version()` and `version_bind()` to return the core's version & binding's version for your purpose.

**Comment by aquynh** [comment]
please send a pull request if you want to see __version__ in Python package, i will merge it.

thanks

**Comment by aquynh** [comment]
i added __version__ to Python binding, thanks.
