### ISSUE TITLE
Inconsistent output from Java vs. Python bindings

### ISSUE THREAD

**Issue by rjzak** [aquynh/capstone#587]
I wrote Java & Python code to disassemble the Dridex malware: https://www.virustotal.com/en/file/f4001a9689c75dde20769e62157aef1e6eb92b1f66aca8870be48d927b07981e/analysis/

All of the instructions are the same between the Java & Python outputs. However, the address argument for the call instruction is not.

For example, line 36:
`call 0x407c1a`  (Python)
`call 0x701a`  (Java)
I'm sure it's not coincidence that the addresses both end in 0x1a.

Example, line 7:
`call 0x40731c` (Python)
`call 0x671c` (Java)
Both end in 0x1c

Example, line 677:
`call 0x40b5f0` (Python)
`call 0xa9f0`  (Java)
Both end in 0xf0.

Example, line 1678:
`call 0x40b5f0` (Python)
`call 0xa9f0` (Java)
Both end in 0xf0.

And in these cases, the Java version is missing two digits, and the first two digits don't match with Python's middle two digits.

However, both Python & Java agree when the address to be called is an offset of a register value;
Example, line 1160:
`call [ecx + 8]`

Thoughts?

**Comment by aquynh** [comment]
can you write a C code to disassemble the same input? the output will be the point of reference, and whatever is different with that is wrong.

**Comment by aquynh** [comment]
can you provide a testcase so we can confirm this issue & test the fix?

**Comment by rjzak** [comment]
Yes, I'll get on it.

**Comment by rjzak** [comment]
Nguyen Anh Quynh, I'm going to contact you directly so I can send you some samples.

**Comment by rjzak** [comment]
Attached is my test case: a binary, and output from Java/C/Python that does issues with presenting the addresses.
[Capstone_Discrepancies.zip](https://github.com/aquynh/capstone/files/145070/Capstone_Discrepancies.zip)

**Comment by rjzak** [comment]
This is a case of user error on my part, my apologies. Closing the issue.
