### ISSUE TITLE
Capstone-window pypi package is broken

### ISSUE THREAD

**Issue by scudette** [aquynh/capstone#588]
Installing capstone-windows via pip is broken:

```
C:\Users\mic>c:\Python27\Scripts\virtualenv.exe Test
New python executable in Test\Scripts\python.exe
Installing setuptools, pip, wheel...done.

C:\Users\mic>Test\Scripts\activate
(Test) C:\Users\mic>pip install capstone-windows
Collecting capstone-windows
  Downloading capstone-windows-3.0.4.tar.gz (1.3MB)
    100% |################################| 1.3MB 153kB/s
Building wheels for collected packages: capstone-windows
  Running setup.py bdist_wheel for capstone-windows
  Stored in directory: C:\Users\mic\AppData\Local\pip\Cache\wheels\16\19\9c\4fc93ef5ab72ca2604ef6b3dd85b6ff3f9ffb10aafb3eb2b07
Successfully built capstone-windows
Installing collected packages: capstone-windows
Successfully installed capstone-windows-3.0.4
You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

(Test) C:\Users\mic>python
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import capstone
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mic\Test\lib\site-packages\capstone\__init__.py", line 230, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
>>>
>>> ^Z
(Test) C:\Users\mic>dir Test\Lib\site-packages\users\mic\test\Lib\site-packages\capstone\capstone.dll
 Volume in drive C has no label.
 Volume Serial Number is 46F6-6EB2

 Directory of C:\Users\mic\Test\Lib\site-packages\users\mic\test\Lib\site-packages\capstone

02/11/2016  02:44 AM         2,599,424 capstone.dll
               1 File(s)      2,599,424 bytes
               0 Dir(s)   2,817,589,248 bytes free

(Test) C:\Users\mic>dir Test\Lib\site-packages\capstone\capstone.dll
 Volume in drive C has no label.
 Volume Serial Number is 46F6-6EB2

 Directory of C:\Users\mic\Test\Lib\site-packages\capstone

File Not Found

(Test) C:\Users\mic>dir Test\Lib\site-packages\capstone\
 Volume in drive C has no label.
 Volume Serial Number is 46F6-6EB2

 Directory of C:\Users\mic\Test\Lib\site-packages\capstone

02/11/2016  02:44 AM    <DIR>          .
02/11/2016  02:44 AM    <DIR>          ..
02/11/2016  02:44 AM             1,882 arm.py
02/11/2016  02:44 AM             4,017 arm.pyc
02/11/2016  02:44 AM             1,923 arm64.py
02/11/2016  02:44 AM             4,605 arm64.pyc
```

It seems to be putting the dll in the wrong place. It seems to be appending the absolute path of where it wants to put it (in site-packages) to the end of the site-packages.

I think the problem is that the setup.py is using data_files. Searching the internet it appears that data_files is not the correct thing to use because you can not reliably predict where the file will end up. Since you need to ensure the file ends up in the capstone package we should probably use package_data. Additionally distutils is deprecated and the current advice it to use setuptools.

I changed the setup.py a bit:
```
--- setup.py	2015-10-23 22:54:26.443463855 +0200
+++ /tmp/setup.py	2016-02-11 12:15:18.324714375 +0100
@@ -9,8 +9,8 @@
 from distutils import log
 from distutils import dir_util
 from distutils.command.build_clib import build_clib
-from distutils.command.sdist import sdist
-from distutils.core import setup
+from setuptools.command.sdist import sdist
+from setuptools import setup
 from distutils.sysconfig import get_python_lib
 
 # prebuilt libraries for Windows - for sdist
@@ -55,6 +55,7 @@
 
     dir_util.copy_tree("../../arch", "src/arch/")
     dir_util.copy_tree("../../include", "src/include/")
+    dir_util.copy_tree("../../msvc/headers", "src/msvc/headers")
 
     src.extend(glob.glob("../../*.[ch]"))
     src.extend(glob.glob("../../*.mk"))
@@ -77,6 +78,10 @@
     """Reshuffle files for distribution."""
 
     def run(self):
+        try:
+            os.unlink("capstone/capstone.dll")
+        except: pass
+        
         # if prebuilt libraries are existent, then do not copy source
         if os.path.exists(PATH_LIB64) and os.path.exists(PATH_LIB32):
             return sdist.run(self)
@@ -108,10 +113,10 @@
         if SYSTEM in ("win32", "cygwin"):
             # if Windows prebuilt library is available, then include it
             if is_64bits and os.path.exists(PATH_LIB64):
-                SETUP_DATA_FILES.append(PATH_LIB64)
+                shutil.copy(PATH_LIB64, "capstone")
                 return
             elif os.path.exists(PATH_LIB32):
-                SETUP_DATA_FILES.append(PATH_LIB32)
+                shutil.copy(PATH_LIB32, "capstone")
                 return
 
         # build library from source if src/ is existent
@@ -159,7 +164,6 @@
 def dummy_src():
     return []
 
-
 setup(
     provides=['capstone'],
     packages=['capstone'],
@@ -186,6 +190,8 @@
             sources=dummy_src()
         ),
     )],
-
-    data_files=[(SITE_PACKAGES, SETUP_DATA_FILES)],
+    zip_safe=False,
+    package_data = {
+        "capstone": ["*.dll"],
+    }
 )
```

This does a couple of things:
 * It uses setuptools instead of distutils. This makes it possible to build wheels.
 * It copies the right dll into the capstone directory. It will then be included as a package_data dependency when you install it.
 * For sdist it removes the dll so it does not end up in the source.

Finally I would like to ask why the need for a whole new package - `capstone-windows`? I understand that we want to distribute binary packages on windows but why not just upload binary wheels to the main capstone pypi package? This is the supported way of shipping binary distributions for users, giving them the option of building if they want to. Shipping capstone in this way makes users of the package have to twiddle their dependencies depending on the OS (e.g. in our project we need to add capstone-windows on windows and capstone on other OSs).

**Comment by aquynh** [comment]
the reason i put out a separate package for Windows is because the binary size of Windows is quite big (it must include compiled DLL). perhaps having setup.py to download DLLs separately when it installs is a better approach?

**Comment by scudette** [comment]
There is no need to do that - pip will fetch the wheel if it needs to and compiler the source if it doesnt. The wheels are separate packages per OS (so you have one wheel for x86 one for amd64) and pip will get the right one.

**Comment by aquynh** [comment]
But compile from source on Windows is a big issue. This is why our capstone-windows package was introduced with precompiled DLL inside.

**Comment by scudette** [comment]
Will you be uploading windows binary wheels for the main capstone package as well? This will help our dependency management because we can just ignore capstone-windows package and use capstone everywhere.

**Comment by aquynh** [comment]
the most important reason why we have `capstone-windows` package is that it includes precompiled DLLs, so those on Windows without compiler (MSVC) can still install Capstone.

meanwhile package `capstone` is for those who want to compile from source on any machine - including Windows with MSVC readily available.

now if we want to combine these 2 packages into 1 only, the question is: how can `setup.py` figures out when users want to compile from source, and when they just want to install precompiled binaries?

**Comment by scudette** [comment]
In case you are not familiar with wheels:

**Comment by scudette** [comment]
In case you are not familiar with wheels:
http://pythonwheels.com/

They are binary packages for specific OS versions.

If you publish wheels users will just get the binary package without needing to compile it. But if they want to they can always compile it too. It is the very same setup.py used in all cases.

**Comment by aquynh** [comment]
no i am not familiar with wheels.

with PR #589, can you please explain the steps users need to do compile from source, and the steps they need to do to install from binaries (without having to compile)?

**Comment by scudette** [comment]
Sure - users just need to do:

```
pip install capstone
```

If there are wheels available for their OS it will just install those - it takes a second or two. If there is no wheel available for their OS it will download the source package and try to build it. At this time, if they dont have compilers, it will fail but otherwise it should just go ahead and compile as normal.

As a packager, one needs to do this:
```
python setup.py bdist_wheel
```
to make wheels on the windows system with compilers etc. The produced wheel goes in `dist` you upload it with `twine upload dist/*whl`.

**Comment by aquynh** [comment]
does this limit the choice for users? for example, in the case there are wheels (Windows), "pip" just install the binaries. but what if users want to compile from source instead?

currently we dont have this problem because we purposely separate binary & source packages ("capstone-windows" & "capstone" PyPi). so users can decide what to do (either install from binaries, or compile from source), rather than let "pip" decides that for themselves. do i miss something here?

**Comment by scudette** [comment]
If you want to compiler from source:
```
pip install --no-use-wheel
```

Will force a recompile.

**Comment by aquynh** [comment]
great, this answers my concern. so depending on the environment of the install machine, the right wheels will be downloaded separately by "pip", and OSX will not download Windows DLLs, correct?

will look closer at your PR, thanks!

**Comment by scudette** [comment]
Yeah you can see this here for example:
https://pypi.python.org/pypi?:action=files&name=pytsk3&version=20160207.post1

This package has one OSX version and two windows versions (32 and 64 bits). All other OSs are built from source as normal. PyPi currently have a policy that no wheels are hosted for Linux - I guess there are just too many flavors of Linux to support and compiling on Linux is much easier.

**Comment by ksloven** [comment]
Good day,

I have just recently tried to install capstone on windows and I get the same error:

``` raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.```

I have downloaded https://pypi.python.org/pypi/capstone-windows and executed "setup.py install";
I have even tried installing it using pip (pip.exe install capstone // pip.exe install capstone-windows);
I have downloaded the binaries (windows core engine and Python module for Windows - Binaries ) from http://www.capstone-engine.org/download.html

But I still can't get it to work on my windows 7 (64 or 32 bit).

Did someone end up finding a solution for this?

Thank

**Comment by aquynh** [comment]
we have Python modules prebuilt at http://www.capstone-engine.org/download.html, you can install those .MSI files.

**Comment by ksloven** [comment]
Hi aquynh

Yes, I installed those .msi files (64 bit and tried 32 bit) but I still get the same error

**Comment by aquynh** [comment]
something is wrong with your Python path.

can you overwrite your `__init__.py` (that was installed from .MSI file) with https://github.com/aquynh/capstone/blob/master/bindings/python/capstone/__init__.py, then comment out a debug line https://github.com/aquynh/capstone/blob/master/bindings/python/capstone/__init__.py#L218, then try again & report the output here?

**Comment by ksloven** [comment]
I have done so, here is the output:

>>> import capstone
Trying to load C:\Python27\lib\site-packages\capstone\lib\capstone.dll
Trying to load C:\Python27\lib\site-packages\capstone\lib\capstone.dll
Trying to load capstone.dll
Trying to load C:\Python27\Lib\site-packages\capstone.dll
Trying to load /usr/lib64\capstone.dll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\capstone\__init__.py", line 249, in <modul
e>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
>>>

**Comment by aquynh** [comment]
you can see that it tries to load capstone.dll from those places, but failed.

now can you find exactly where capstone.dll is installed in your machine?

**Comment by ksloven** [comment]
Yes, it is installed in "C:\Python27\Lib\site-packages\capstone\lib" directory aswell as the C:\Python27\Lib\site-packages\capstone directory.

I just don't get why it can't load them.

**Comment by aquynh** [comment]
i compiled capstone.dll using VS2015. my best guess is that you dont have the right version of MSVCRT. 

you may try to download and install MSVCRT from
https://www.microsoft.com/en-sg/download/details.aspx?id=48145

**Comment by ksloven** [comment]
I had already installed MSVCRT from the link you mentioned. But I still had no luck.

I will try compile it with VS as per https://github.com/aquynh/capstone/blob/master/COMPILE_MSVC.TXT and see how it goes and let you know.

Thanks

**Comment by joseph-hannon** [comment]
I had the same issue and the MSVCRT Redistributable for VS2015 fixed it for me

**Comment by scudette** [comment]
Just FYI - I  made this pypi package which should build by itself on windows without anything special installed. Just install the usual VC for python compilers (if you dont have them pip will print the URL to get them from).

https://github.com/rekall-innovations/rekall-capstone

```
pip install rekall-capstone
```
