### ISSUE TITLE
Cannot disassemble mrs in Thumb

### ISSUE THREAD

**Issue by radare** [aquynh/capstone#596]
As reported here: https://github.com/radare/radare2/issues/4215

Looks like capstone can't disassemble those bytes in thumb mode: eff31080

**Comment by aquynh** [comment]
yes, it can with a proper mode.

```
$ cat t1.py

#!/usr/bin/python
from capstone import *

md = Cs(CS_ARCH_ARM, CS_MODE_THUMB | CS_MODE_MCLASS)

for i in md.disasm(b"\xef\xf3\x10\x80", 0x1000):
    print "0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str)
```

here is the output:

```
$ python t1.py 
0x1000:	mrs	r0, primask
```

**Comment by radare** [comment]
Is MCLASS conflicting with some non-cortex instructions?

**Comment by aquynh** [comment]
Yes it is.

**Comment by radare** [comment]
Ok, so maybe is better to add this as default and add an option to disable?

**Comment by aquynh** [comment]
Why do you favour this over the current default option?

**Comment by radare** [comment]
Because most users will be analyzing cortex-m code, but it's ok to be like this in capstone, i was just thinking loud about what to do in r2, or how to detect when it is loading such kind of code and enable that option.

Thanks!
