### ISSUE TITLE
Design Decisions and their impact on Haskell bindings

### ISSUE THREAD

**Issue by ibabushkin** [aquynh/capstone#603]
I am currently writing Haskell bindings for Capstone and I'd like to ask a few general questions on design-related decisions that imposed limitations I noticed so far, as well as maybe share some of my thoughts. 

So far, the intended use of Capstone's API is revolving around creating a handle with `cs_open`, passing necessary options and use said handle to perform actual work. This implies that the information passed to `cs_open` can't be accessed again. I noticed from `cs_priv.h` that handles are actually pointers to the `cs_struct` type holding that information, which is (obviously) an internal datastructure not meant to be exposed to the user of the library. Given the functional paradigm of Haskell, it might be of great use to be able to access said information, like the architecture used. This is because `cs_detail` uses an untagged union to store architecture-specific data, which is awkward to work around in Haskell. 

Given this situation, I'd like to know why an untagged union is used here. I suspect this is because that'd be a bit wasteful on memory, in which case I suggest adding an API to get back information from a handle, maybe like this, analogous to the implementation of `cs_errno`:
```C
cs_arch cs_get_arch(csh ud, cs_arch *ar) {
    struct cs_struct *handle = (struct cs_struct *)(uintptr_t) ud;
    if (!ud)
        return CS_ERR_CSH;
    *ar =  handle->arch;
    return CS_ERR_OK;
}
```

My motivation for this is simple: Whereas it is not a problem to port Capstone's API 1:1 to Haskell, creating idiomatic Haskell bindings on top of that requires a more through approach to API design, so I thought I'd communicate with the original authors before resorting to ugly hacks.

Thank you.

**Comment by aquynh** [comment]
this is great, thanks for working on this.

in principle, each language has different idiomatic to handle things, so yes it is fine to adjust the bindings accordingly. in fact, i can see different bindings take different ways to make it more "natural" to the language, but not necessarily follow the original API.

i suppose you know very well how a Haskell binding should be, so please go ahead with what you think is best. let me know if you need any helps, and keep us updated on your project.

thanks!

**Comment by ibabushkin** [comment]
No problem :) What my actual question was is whether the additions proposed can be added to the core, as reading from an internal datastructure isn't a very good idea compatibility-wise.

**Comment by aquynh** [comment]
can you post your proposal here?

**Comment by ibabushkin** [comment]
I suggested adding capabilities to get information from a handle, as described in my first post. What part should I elaborate on?

**Comment by aquynh** [comment]
the information inside cs_struct should be private. are you sure that Haskell cannot do without those information?

regarding your example on `handle->arch`, why dont you save that info when you initialize the engine? this is what Python/Ocaml/Java bindings did, and i guess everything other bindings do the same thing.

i believe that there is always workaround, without having to expose cs_struct internals.

thanks.

**Comment by ibabushkin** [comment]
You are certainly right about this, but as Haskell is a purely functional language, it doesn't have implicit stateful computation. This means that keeping state is explicit. It's much cleaner if I can thus deduct architecture information from a handle, as that's a piece of state the low-level bindings have anyway. That's not absolutely necessary, but I personally would regard it as a great improvement, because that way all I'd need to marshal a pointer to a `cs_insn` to my Haskell datatype would be said pointer with no additional information. This would make using low-level bindings for performance reasons more convenient I suppose. I could, however, look into a more clever way of handling handle state and maybe leverage that, which might be a better idea (and have less impact on the core). I'll let you know when I come to a conclusion.

So far, I have successfully ported the headers in `include/`. Some minor additions might be needed, but judging by my tests, they seem to be stable. A high level API is what I work on now.

If you are interested, the bindings are here: https://github.com/ibabushkin/hapstone

**Comment by aquynh** [comment]
yes, please find workaround, or i might get attacked if i expose cs_struct info out :-)

you are amazing, that looks like a great code! keep me updated, and please inform when it is ready, so i will add it to the list of bindings at https://github.com/aquynh/capstone/tree/master/bindings

thanks

**Comment by ibabushkin** [comment]
So, a little update on this:

I have developed a reasonable-enough solution for this, so I'll outline the concept here:

There is a special `Disassembler` datatype which is parametrized over some result type.
This datatype holds all information needed by capstone to disassemble a buffer, said buffer,
and a function that takes a handle and an instruction object and returns an object of the result
type (roughly how it works, but that result is obtained using side-effects, so it is wrapped in the IO monad).

There is an interpreter function of type
```Haskell
disasmIO :: Disassembler a -> IO (Either CsErr [(CsInsn, a)])
```
that incorporates possible failure and incorporates all necessary cleanup.
This isn't perfect, as it is a bit involved to use and kills off some versatility (you are forced to use
`cs_disasm` that way and if you want `cs_disasm_iter`, you *have* to use the low-level bindings), but I guess this is fine for now. In case someone involved in the project wants to get back to the discussion around exposing info from `cs_struct`, I'm still interested, so I'll keep the issue open.

Apart from that, only some tests and docs have to be written.

**Comment by aquynh** [comment]
thanks for the update, it seems you are making a very good progress!

regarding `cs_disasm_iter`, this is mostly for C level program. Python  binding is one of the most complete bindings we have, but it does not even wrap this API.

thanks.

**Comment by aquynh** [comment]
close, thanks!
