### ISSUE TITLE
FLDENV/FNSTENV reported as having dword arguments

### ISSUE THREAD

**Issue by 10110111** [aquynh/capstone#613]
The following instructions are reported wrongly

    D9 74 24 D8    fnstenv [rsp-0x28]
    D9 64 24 D8    fldenv [rsp-0x28]

Capstone disassembles them adding `dword ptr` before memory operand. Actual operand size is 14/18 bytes depending on operating mode.

**Comment by aquynh** [comment]
which mode has the size as 14, and which mode has the size as 18?

**Comment by 10110111** [comment]
Oh, not 18, it's 28. In 32- and 64-bit modes it's 28 bytes, and in 16-bit it's 14.

**Comment by aquynh** [comment]
fixed in the next branch now with commit https://github.com/aquynh/capstone/commit/75701e806a25714f762e2abc099fa5d55bf89295.

please confirm, thanks!

**Comment by 10110111** [comment]
Seems to look good now.
