### ISSUE TITLE
Announcing Haskell bindings and a small question on type choice

### ISSUE THREAD

**Issue by ibabushkin** [aquynh/capstone#619]
Haskell bindings over at https://github.com/ibabushkin/hapstone are officially ready and should be free of the big nasty bugs. I'd be glad if they would be referenced here.

A note on procedure:
1. documentation is still not completely clean, and people who want to read the source are invited to do so, contribution is always welcome.
2. I will upload the package to Hackage soon, so some notes on installation will be needed.

Now onto the second point:
In some structures in the architecture headers, registers are represented by (unsigned) integers.
On others, the corresponding enumeration is used. Is this inconsistency deliberate? If so, what are the reasons and is it safe to perform appropriate casting in the Haskell bindings?

Best regards.

**Comment by aquynh** [comment]
congrats for this amazing work!

i put Hapstone in the list of bindings at http://www.capstone-engine.org & http://www.capstone-engine.org/download.html, and also linked to it at https://github.com/aquynh/capstone/tree/master/bindings

keep it up, and thanks for doing this!

**Comment by aquynh** [comment]
on the question about registers type, they should be declared as enum. please sending a PR to fix that, thanks.

**Comment by ibabushkin** [comment]
alright, will do ASAP

**Comment by aquynh** [comment]
i fixed that typo, sorry about that!

**Comment by ibabushkin** [comment]
I think I can close this now, because both issues have been resolved.
