### ISSUE TITLE
Can't disassemble a certain instruction

### ISSUE THREAD

**Issue by kevinkoo001** [aquynh/capstone#632]
I am trying to disassemble the following buffer, but the capstone gives an empty string. Currently I am using the latest version 3.0.4.

```
from capstone import *
buffer = b'\x66\x0f\x3a\x63\x47\xf0\x40'
md = Cs(CS_ARCH_X86, CS_MODE_64)
for i in md.disasm(buffer, 0x1000):
    print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))
```
Expected result is as following:
`pcmpistri xmm0, xmmword ptr [edi-10h], 40h`

It seems like a bug, could you fix it? 
Thanks.

**Comment by aquynh** [comment]
you can consider using the "next" branch, which handles this instruction. thanks.

**Comment by kevinkoo001** [comment]
Alright, let me give it a try. Thanks.

**Comment by kevinkoo001** [comment]
After installing "next branch" of python binding, the version is 4.0.0. But I got the following message.
```
Traceback (most recent call last):
  File "test_all.py", line 3, in <module>
    import test_basic, test_arm, test_arm64, test_detail, test_lite, test_m68k, test_mips, \
  File "D:\Koo\Repo\Github-starred\capstone\bindings\python\test_basic.py", line 5, in <module>
    from capstone import *
  File "D:\Koo\Repo\Github-starred\capstone\bindings\python\capstone\__init__.py", line 363, in <module>
    _setup_prototype(_cs, "cs_regs_access", ctypes.c_int, ctypes.c_size_t, ctypes.POINTER(_cs_insn), ctypes.POINTER(ctypes.c_uint16*64), ctypes.POINTER(ctypes.c_uint8), ctypes.POINTER(ctypes.c_uint16*64), ctypes.POINTER(ctypes.c_uint8))
  File "D:\Koo\Repo\Github-starred\capstone\bindings\python\capstone\__init__.py", line 345, in _setup_prototype
    getattr(lib, fname).restype = restype
  File "C:\Python27\lib\ctypes\__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'cs_regs_access' not found
```

**Comment by aquynh** [comment]
Be sure to always reinstall the binding if you are in doubt:

    $ cd bindings/python
    $ sudo make install

**Comment by kevinkoo001** [comment]
I've reinstalled it but still I got the same error. Weird.

**Comment by aquynh** [comment]
can you get the latest Github code, and from branch "next" do this:

    $ ./make.sh
    $ sudo ./make.sh install
    $ cd bindings/python
    $ sudo make install

and see if the problem is solved?

**Comment by kevinkoo001** [comment]
Alright, I recompiled a 'capstone.dll' with Visual Studio and copied it into 
```C:\location_to_python\Lib\site-packages\capstone\```

Now everything works fine. Thanks!
