### ISSUE TITLE
disasm blx thumb

### ISSUE THREAD

**Issue by McLovi9** [aquynh/capstone#633]
I just notice that arm thumb disassembly is wrong, tested with code from next branch.
Thumb code:

IDA pro
```
0xF400048A FF F7 54 EE BLX 0xF4000134
```

Capstone  CS_MODE_THUMB
```
F400048A    FFF754EE    blx #0xf4000138
```

**Comment by aquynh** [comment]
are you sure this is "next" branch? i get your expected output here.

```
0xf400048a:	blx	#0xf4000134
	op_count: 1
		operands[0].type: IMM = 0xf4000134
	Registers read: pc
	Registers modified: lr
```

**Comment by McLovi9** [comment]
no, it's okay. Sorry for confusion, I have few VMs and apparently "next" branch was not up-to-date in this VM image.
