### ISSUE TITLE
Missing disassembly when ending with 0x00

### ISSUE THREAD

**Issue by kevinkoo001** [aquynh/capstone#637]
I am using the next capstone version (4.0). I found that capstone does not disassemble the binary when the last byte ends with 0x00. Maybe it is because the string has been terminated earlier. For example, the following missed the last 6-byte code.
```
buf=pe.get_data(0x82ED, 0x2D)
buf[-1]
\x00

for i in md.disasm(buf, 0x4082ED):
    print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))

0x4082ed:	mov	ecx, dword ptr [ebp - 4]
0x4082f0:	xor	ecx, ebp
0x4082f2:	call	0x40c19c
0x4082f7:	leave	
0x4082f8:	ret	
0x4082f9:	nop	
0x4082fa:	sbb	dword ptr [ebx + 0x40], edi
0x4082fd:	add	byte ptr [edi], cl
0x4082ff:	jns	0x408341
0x408301:	add	byte ptr [edi + 0x79], bl
0x408304:	inc	eax
0x408305:	add	byte ptr [eax + 0x4004079], ch
0x40830b:	jp	0x40834d
0x40830d:	add	byte ptr [ecx], dl
0x40830f:	jp	0x408351
0x408311:	add	byte ptr [ebx + 0x7a], ah
0x408314:	inc	eax
```

The missing one is 
```add	byte ptr [ecx + 0x5500407b], ah```

I can see it when I increase the buffer size by 1.
```
buf=pe.get_data(0x82ED, 0x2E)

for i in md.disasm(buf, 0x4082ED):
    print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))

0x4082ed:	mov	ecx, dword ptr [ebp - 4]
0x4082f0:	xor	ecx, ebp
0x4082f2:	call	0x40c19c
0x4082f7:	leave	
0x4082f8:	ret	
0x4082f9:	nop	
0x4082fa:	sbb	dword ptr [ebx + 0x40], edi
0x4082fd:	add	byte ptr [edi], cl
0x4082ff:	jns	0x408341
0x408301:	add	byte ptr [edi + 0x79], bl
0x408304:	inc	eax
0x408305:	add	byte ptr [eax + 0x4004079], ch
0x40830b:	jp	0x40834d
0x40830d:	add	byte ptr [ecx], dl
0x40830f:	jp	0x408351
0x408311:	add	byte ptr [ebx + 0x7a], ah
0x408314:	inc	eax
0x408315:	add	byte ptr [ecx + 0x5500407b], ah
```
I believe the last 0x00 byte should be considered when disassembly. Thanks!

**Comment by aquynh** [comment]
to keep it simple, can you base on http://www.capstone-engine.org/samples/test1.py to have a code triggering this issue?

you can paste your code here, thanks.

**Comment by kevinkoo001** [comment]
test1.py worked.

The buf above has the following value.
```buf = '\x8b\x4d\xfc\x33\xcd\xe8\xa5\x3e\x00\x00\xc9\xc3\x90\x19\x7b\x40\x00\x0f\x79\x40\x00\x5f\x79\x40\x00\xa8\x79\x40\x00\x04\x7a\x40\x00\x11\x7a\x40\x00\x63\x7a\x40\x00\xa1\x7b\x40\x00\'```

I think the last 5 bytes should be 6 to get an appropriate disassembly. This means the binary might have a problem when compiled, because the 6th byte must be starting another block. Very confusing.

**Comment by aquynh** [comment]
your input has a trailing `\` (in `'...\x40\x00\'`). is this a mistake?

what is your expected output?

**Comment by kevinkoo001** [comment]
The output was to be expected as:
```0x408315:   add byte ptr [ecx + some_value], ah```

Obviously, the next byte (followed by the last ```0x00```) should be part of the next function to be referenced in my binary. This makes me very confused because a compiler has generated the last 5 bytes ```x00\xa1\x7b\x40\x00```, which means a dead code. 

Okay, it looks like Capstone handles the case properly. Thanks.

**Comment by aquynh** [comment]
ok, so there is no more issues?

**Comment by kevinkoo001** [comment]
Yes, thanks for your quick response. 
If I found any issue dealing with Capstone, I will inquiry about it in the future.
