### ISSUE TITLE
When is cs_x86_op::fp used?

### ISSUE THREAD

**Issue by 10110111** [aquynh/capstone#648]
In `x86.h` in `struct cs_x86_op` Capstone has a union member `double fp`. AFAIK, there're no x86 instructions which take a floating-point immediate. All the floating-point operands are either in registers (thus `reg` would be used), or in memory (thus `mem` would be used). What is this member used for then?

**Comment by aquynh** [comment]
Yes, this should be removed. Can you send a PR doing that?

Thanks

**Comment by 10110111** [comment]
Will do ASAP.
