### ISSUE TITLE
X86 16-bit mode uninitialized displacement

### ISSUE THREAD

**Issue by davidcarne** [aquynh/capstone#656]
insn->eaDisplacement isn't correctly initialized in X86 16-bit mode when parsing modrm bytes for mod == 3. Verified on both master and next. This can lead to incorrect disassembly (an additional byte being consumed randomly).

I've only seen the actual issue show up on -O3 builds on gcc (not on unoptimized GCC builds, or any clang builds).

Patch: https://gist.github.com/davidcarne/3dc373b450072dd2bc37b73e8e947375

**Comment by aquynh** [comment]
thanks for this info!

- what is the input (hexcode) exposing this issue?

- can you send a pull request so i can merge it?

**Comment by davidcarne** [comment]
Where it may show up depends on whatever is on the stack when `X86_getInstruction` is called. For my test case, `0B D0 90 90` was enough to trigger the issue. (Of course, the issue is only visible if there happens to be a non-zero byte in that exact location on the stack).

I'll send a pull request

**Comment by aquynh** [comment]
thanks for the PR, and sorry to take so much time to look at this!
