### ISSUE TITLE
test_winkernel produces wrong results with MIPS-32 (Big-endian) related tests

### ISSUE THREAD

**Issue by tandasat** [aquynh/capstone#673]
### Summary
test_winkernel does not produce the identical test results from the other existing test cases for all 10 MIPS-32 (Big-endian) related tests. Some of them print out different results and some others print out the below error message:

> ERROR: Failed to disasm given code!

### Impact
I think it is a minor issue because disassembling MIPS-32 (Big-endian) code from Windows drivers is extremely rare. While a root cause is unknown, it seems to affect only MIPS-32 (Big-endian) handling and no issue is seen on other targets from regression tests. 

### Step to reproduce
1. Compile the test_winkernel project on VS2015 or VS2013. It does not matter Debug or Release, Win32 or x64.
2. Copy compiled test_winkernel.sys to a test system and run it with DebugView (Kernel Capture enabled)
3. Save output to a file.
4. Compile test, test_detail, test_iter, and test_mips project on VS2015 or VS2013.
5. Run them on the same test system, save output to file(s).
6. Compare results in files.
7. All 10 tests named "* (Big-endian)" have different results (those of test_winkernel should be wrong). Affected tests and associated files are:

- test_detail (3 hits)
 - Platform: MIPS-32 (Big-endian)
 - Platform: MIPS-32R6 | Micro (Big-endian)
 - Platform: MIPS-32R6 (Big-endian)
- test_iter (1 hit)
 - Platform: MIPS-32 (Big-endian) 
- test_mips (3 hits)
 - Patform: MIPS-32 (Big-endian)
 - Platform: MIPS-32R6 | Micro (Big-endian)
 - Platform: MIPS-32R6 (Big-endian) 
- text (3 hits)
 - Platform: MIPS-32 (Big-endian)
 - Platform: MIPS-32R6 | Micro (Big-endian)
 - Platform: MIPS-32R6 (Big-endian)

### Reproduced test environment
commit: f0e528b079f01636d8ee308d6b2b56457bb748ba
platforms: Win10x64, Win10x86, Win7x64 (seems any platform)

### Note
- [both_test_results.zip](https://github.com/aquynh/capstone/files/250525/both_test_results.zip) contains outputs from both win_kernel and existing tests on Windows 10 x64.
- Using neither a checked build (a debug version of Windows) nor a DriverVerifier (a runtime driver error detector) identified the issue.

**Comment by aquynh** [comment]
it is interesting that this cannot be reproduced with userland code, but only kernel code?

can you try to minimize the code triggering this issue to be as small as possible? (ideally just few bytes)

also, if you can somehow reproduce this on Linux or Mac, it will be much easier for me to debug the issue.

thanks.

**Comment by ionescu007** [comment]
I have a theory -- is it possible that there is usage of floating point
instructions in Capstone?

On Thursday, May 5, 2016, Nguyen Anh Quynh <notifications@github.com> wrote:

> it is interesting that this cannot be reproduced with userland code, but
> only kernel code?
>
> can you try to minimize the code triggering this issue to be as small as
> possible? (ideally just few bytes)
>
> also, if you can somehow reproduce this on Linux or Mac, it will be much
> easier for me to debug the issue.
>
> thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/aquynh/capstone/issues/673#issuecomment-217172366>
>


-- 
Best regards,
Alex Ionescu

**Comment by aquynh** [comment]
no we dont use FP anywhere in the Mips core, or anywhere inside Capstone.

**Comment by aquynh** [comment]
i am wondering if we have this same issue with the "next" branch.

**Comment by tandasat** [comment]
I will try to find out minimal bytes to reproduce the issue and get back to you.

I am wondering that it may potentially be caused due to a use of higher address space like 0xFFFFF801`EEE6291C compared with that of user-mode somehow, although none of other target platform seem to trigger the issue.

**Comment by aquynh** [comment]
then can you try to set that high offset address to those test_xxx in userland, and see the result?

**Comment by tandasat** [comment]
Just a quick note:
- Only using this code in test_mips.c is sufficient to reproduce the issue
`#define MIPS_CODE "\x0C\x10\x00\x97"`
- Setting the warning level 4 and addressing warnings in cs.c and Mips* does not help
- Using .c as opposed to *.cpp does not help

I will find some more time shortly.

**Comment by ionescu007** [comment]
Would be curious if you tried this in win10 user-mode with high-entropy
ASLR and forcing top-down allocations :). This will cause extremely high
addresses (but still not 0xFFFFF)...

Best regards,
Alex Ionescu

**Comment by tandasat** [comment]
Thanks for ideas of testing, but I was not able to reproduce the issue on user mode yet. I will trace code path to find out difference.

What I did
- Used Win10 with 64bit PE
- [HEASLR](https://msdn.microsoft.com/en-us/library/dn195771.aspx) and [system-wide MEM_TOP_DOWN](https://msdn.microsoft.com/en-us/library/bb613473(VS.85).aspx) enabled
 - malloc's return value was like 00007FF7`BED0FA50
- modified the `address` parameter to use this higher address

**Comment by tandasat** [comment]
I have found that changing code in cs_open() solved the issue.
```
// from 
ud->big_endian = mode & CS_MODE_BIG_ENDIAN;
// to
ud->big_endian = (mode & CS_MODE_BIG_ENDIAN) != 0;
```
Code is setting 0 because the big_endian field is unsigned char and not real bool causing truncation of a result of the AND operation. 
```
struct cs_struct {
	...
	bool big_endian;

```
Here is a definition of bool in capstone_static_winkernel
```
// from platform.h

#if (_MSC_VER < 1800) || defined(_KERNEL_MODE)
// this system does not have stdbool.h
#ifndef __cplusplus
typedef unsigned char bool;
#define false 0
#define true 1
#endif    
```

As for a scope of this issue, I do think there is other instances of the same bug in the project because the warning C4244, which is triggered by the code, is not seen anywhere else, so the above fix should be fine. I will send a PR with test logs shortly.

**Comment by aquynh** [comment]
oh interesting. yes this issue should be fixed no matter what. look forward to your PR, and thanks for your great effort on this bug!
