### ISSUE TITLE
winkernel: could fail formatting string when float point is used on the Windows kernel

### ISSUE THREAD

**Issue by tandasat** [aquynh/capstone#681]
### Description
The Windows kernel does not support formatting string for any of the floating point types. This limitation is not explicitly documented anywhere besides for [DbgPrintf()](https://msdn.microsoft.com/en-us/library/windows/hardware/ff543632(v=vs.85).aspx), but I confined that _vsnprintfw("%f", 0.0) did produces "f" instead of "0.00" etc on a Windows driver. This behavior results in a failure of creating proper strings from float points (ie, double and float) with printf-style functions used in Capstone when it is compiled for a Windows driver.

### Scope
As for a scope of this issue, those are code likely to be affected because of use of any of unsupported type specifiers, ie, %f, %e, %E, %g, %G, %a and %A, according to MSDN linked above: 

- \capstone_master\arch\AArch64\AArch64InstPrinter.c (1 hit)
 - 	Line 1040: 	SStream_concat(O, "#%.8f", FPImm);
- \capstone_master\arch\ARM\ARMInstPrinter.c (1 hit)
 - 	Line 2106: 	SStream_concat(O, "#%e", getFPImmFloat((unsigned int)MCOperand_getImm(MO)));
- \capstone_master\suite\arm\test_arm_regression.c (11 hits)
 - 	Line 83: 				_this_printf("\t\toperands[%u].type: FP = %f\n", i, op->fp);
- \capstone_master\suite\benchmark\test_iter_benchmark.c (1 hit)
 - 	Line 92: 	printf("time used:%f\n", timeUsed);
- \capstone_master\tests\test_arm.c (14 hits)
 - 	Line 59: 				printf("\t\toperands[%u].type: FP = %f\n", i, op->fp);
- \capstone_master\tests\test_arm64.c (15 hits)
 - 	Line 57: 				printf("\t\toperands[%u].type: FP = %f\n", i, op->fp);

(Search "%[^\s]*[feEgGaA]")

While exact paths that could be affected this limitation is not investigated yet, it is likely that code creating ASCII texts for cs_insn::op_str is impacted other than some test code.

### Impact
Minor. From what I can tell from the above list, this issue only affects code dealing with AArch64 and ARM (and M68K on the 'next' branch) code. Capstone does not support building a driver which runs on those architectures, and it is extremely rare that a driver in the x86_64 Windows kernel deals with those architectures' code. Given that, probability to face this issue is very low in reality.

### Proposed Fix
As for workaround, I can figure three options.

1.Compile error

we could trigger a compile error when capstone_static_winkernel is compiled with affected code. So we may add code like this in `capstone.h`
```
#if defined(_KERNEL_MODE) && !defined(CAPSTONE_DIET) && (CAPSTONE_HAS_x | CAPSTONE_HAS_y | ...)
#error Windows driver does not support full features for architecture(s) you specified. Use CAPSTONE_DIET to compile Capstone with only supported features. See issue #xyz for details.
#endif 
```
But this is a big limitation and prevents us from compiling even test code for Windows driver.

2.Warning + Runtime error

An alternative workaround is adding code to return error when string conversion from float points is going to be attempted with `_KERNEL_MODE`, and adding a compile time warning similar to the above in `capstone.h`
```
#if defined(_KERNEL_MODE) && !defined(CAPSTONE_DIET) && (CAPSTONE_HAS_x | CAPSTONE_HAS_y | ...)
#pragma message("Windows driver does .... See issue #xyz for details.")
#endif
```
A challenge of this approach is that functions formatting strings all do not have return value and not easy to indicate failure. 

3.Warning + Do not attempt to convert

Probably, the best way may be returning a string indicating error along side the above `#pragma message`. For example with AArch64InstPrinter.c, it would be some thing like this :
```
	// 8 decimal places are enough to perfectly represent permitted floats.
#if defined(_KERNEL_MODE) 
	SStream_concat(O, "#<unsupported>");
#else
	SStream_concat(O, "#%.8f", FPImm);
#endif
```

Let us discuss what we could do.

**Comment by aquynh** [comment]
solution (3) can be improved with a special "printf" made for Windows kernel?

@ionescu007, do you have any comments?

**Comment by tandasat** [comment]
I have found some discussion around this issue and found no perfect solution to convert floats to strings. The most acceptable solution may be manually converting to two integers. 

```
         double d;
         ...compute value in d
        int before = (int) d;
        int after = abs( (int)(d * 1000) % 1000);
        DebugPrint("%d.%03d, before, after);
```
http://osronline.com/showThread.CFM?link=236557 

But, we may need to know expected ranges of float points in order to do this with 'close enough' precision, and I do not have enough knowledge to assess the ranges for each architecture (or at least, for each affected architecture).

**Comment by aquynh** [comment]
i see. then i think we should go with option (3).
