### ISSUE TITLE
error: ‘all_insn’ was not declared in this scope

### ISSUE THREAD

**Issue by roj4s** [aquynh/capstone#685]
Testing the samples code on the website of Capstone, specifically the one providing more detailed output.  The first sample works.

cs_insn *i = &(all_insn[j]);
         cs_detail *detail = i->detail;

**Comment by aquynh** [comment]
yes but that excerpt is not even a complete code either. in case you still havent figured it out yet, `all_insn` should be declared as:

    cs_insn *all_insn;

for more example, see all C files in the directory `tests/` in source code.
