### ISSUE TITLE
document: docs/README should probably refer to contrib/cs_driver for Windows driver

### ISSUE THREAD

**Issue by tandasat** [aquynh/capstone#686]
This is open discussion.

docs/README currently refers to KernelProject for a sample on using Capstone from a Windows driver. 
> * Sample application on how to embed Capstone into Windows kernel driver.
> 
> 	https://github.com/aquynh/KernelProject

This project is, however, not too easy to use as a reference due to insufficient documents, a use of a two years old revision of Capstone, and unnecessarily large number of accompanying library files.   

Instead, the README could refer to a cs_driver sample project included in the Capstone repository.
- https://github.com/aquynh/capstone/tree/master/contrib/cs_driver

This project comes with a single one file with sufficient code and comments on how to use Capstone from a Windows kernel driver, and moreover, is supported and maintained as a part of Capstone repo.

This discussion should probably involve with @zer0mem, the original author of the KernelProject project, since he may have another idea to address the above downsides.

**Comment by aquynh** [comment]
yes, please update docs/README to link to cs_driver sample. 

at the same time, we can explain the current position, and how KernelProject can still be useful, like serving as an example on how to embed Capstone into Windows kernel from scratch, etc?

**Comment by tandasat** [comment]
To me, the project is more useful for using C++ libraries from drivers, but it does not quite relate to making use of Capstone. I pinged the author for his thoughts.

I will send PR after we conclude this discussion.
