### ISSUE TITLE
Can not open X86 with CS_MODE_BIG_ENDIAN

### ISSUE THREAD

**Issue by snsmac** [aquynh/capstone#698]
Example code:
#include<stdio.h>
#include<capstone/capstone.h>
int main(void)
{
    csh handle;
    int returnv = cs_open(CS_ARCH_X86, CS_MODE_64 + CS_MODE_BIG_ENDIAN, &handle);
    printf(cs_strerror(returnv));
    return 0;
}`
This fails with:

> Invalid mode (CS_ERR_MODE)

OS is Ubuntu 16.04,
compiler is gcc 5.3.1
im using the "next" branch

**Comment by hlide** [comment]
Lol! do you know x86 has always been a little endian processor in 
nature? Do you want to start a troll between x86-ists and motorola-ists? :p.
