### ISSUE TITLE
test eax, ecx

### ISSUE THREAD

**Issue by mrexodia** [aquynh/capstone#702]
See https://github.com/keystone-engine/keystone/issues/91

**Comment by bSr43** [comment]
If you want a cleaner fix, you can proceed to these modifications in the file **X86GenDisassemblerTables.inc**:
- line 18923, change 88 to 87 (instruction **TEST8rr**)
- line 18835, change 69 to 73 (instruction **TEST16rr**)
- line 18863, change 69 to 73 (instruction **TEST32rr**)
- line 18891, change 43 to 76 (instruction **TEST64rr**)

It will change the _operand specifier_ to the proper one, where the operands are inverted.

Sorry for not providing the DIFF, it is not possible for me right now 😊

**Comment by mrexodia** [comment]
Thanks, that is a good idea. I will send a pull request...

**Comment by mrexodia** [comment]
@aquynh what are those files generated from? Perhaps it's better to change the source since the `_reduce.inc` has different constants for those instructions...

**Comment by ant1** [comment]
It seems those files are generated by llvm-tblgen,  and the bug was fixed in llvm r233686

http://llvm.org/viewvc/llvm-project?view=revision&revision=233686
https://llvm.org/bugs/show_bug.cgi?id=22995

**Comment by aquynh** [comment]
fixed now, please confirm.

**Comment by mrexodia** [comment]
Works correctly now, thanks a lot!

![test eax, ecx](https://i.imgur.com/aSMEf8x.png)

**Comment by radare** [comment]
in r2 we had this issue opened for more than a year. now we can close it too. thanks, any will in releasing capstone during 2017 or should distros and users be forced to use the code from git one year more?

**Comment by aquynh** [comment]
yes, the plan is to merge https://github.com/aquynh/capstone/tree/encoding into "next", then we can go for v4.0. however, this would break all the bindings, that is my concern now.

**Comment by mrexodia** [comment]
Well, it is a new major version so breaking bindings isn't a big deal I
think.

**Comment by radare** [comment]
version numbers are used to solve this problem. all dependency managers from node, python, rust, etc… all them support to specify the version number, so i dont see any problem in breaking the API after 2 years
