### ISSUE TITLE
unexcepted op_access.

### ISSUE THREAD

**Issue by cherry-wb** [aquynh/capstone#711]
Hi!
I do some test for the op_access feature, but i catch some unexcepted?
can some explain, thank you!

code snippet:
    regs_read_name = []
    regs_write_name = []
    (regs_read, regs_write) = insn.regs_access()
   
    if len(regs_read) > 0:
        for r in regs_read:
            regs_read_name.append(insn.reg_name(r))
   
    if len(regs_write) > 0:
        for r in regs_write:
            regs_write_name.append(insn.reg_name(r))
        
    if len(insn.regs_read) > 0:
        for r in insn.regs_read:
            regs_read_name.append(insn.reg_name(r))
    
    if len(insn.regs_write) > 0:
        for r in insn.regs_write:
            regs_write_name.append(insn.reg_name(r))
    
    print("0x%x:\t%s\t%s" % (insn.address, insn.mnemonic, insn.op_str))#bytes(insn.bytes)
    
    print("Registers read:", end="")
    print(regs_read_name)
    
    print("Registers modified:", end="")
    print(regs_write_name)

the out put:

Platform: 0
Code: 0xf7 0xd0 0xa3 0x44 0xb0 0x00 0x10 
Disasm:
0x1000:	not	eax
Registers read:[u'eax']
Registers modified:[u'eax']

0x1002:	mov	dword ptr [0x1000b044], eax
Registers read:[] ### while we except eax detected,  none detected??
Registers modified:[]

**Comment by aquynh** [comment]
can you post the full script? if you dont know how to put the code here with Markdown format, paste it to gist.github.com, and put the link here. thanks.

**Comment by cherry-wb** [comment]
Ok,this is the scripts.
[capstone_issue.py.txt](https://github.com/aquynh/capstone/files/326061/capstone_issue.py.txt)

**Comment by aquynh** [comment]
fixed now, please confirm. thanks.

**Comment by cherry-wb** [comment]
nice work!
