### ISSUE TITLE
mov eax, dword ptr ds:[0x1000]

### ISSUE THREAD

**Issue by fvrmatteo** [aquynh/capstone#718]
Disassembling the instruction "mov eax, dword ptr ds:[0x1000]" with Capstone Next the destination register access is reported as "CS_AC_IGNORE", but it should be "CS_AC_WRITE".

I fixed that changing the access from CS_AC_IGNORE to CS_AC_WRITE on X86MappingInsnOp.ins & X86MappingInsnOp_reduce.inc and it seems to work. The only thing I don't understand is: what does "X86_MOV16ao16" means?

**Comment by aquynh** [comment]
"a" is for eax, "o16" is for offset of 16bit

**Comment by lucasg** [comment]
Some {reg|mem} to reg MOV instructions aren't correct in terms of access : 
```
diff --git a/arch/X86/X86MappingInsnOp.inc b/arch/X86/X86MappingInsnOp.inc
index a523a2c..a3cbd7e 100644
--- a/arch/X86/X86MappingInsnOp.inc
+++ b/arch/X86/X86MappingInsnOp.inc
@@ -5607,11 +5607,11 @@
 },
 {	/* X86_MOV16ao16, X86_INS_MOV: mov{w}	ax, $src */
 	0,
-	{ CS_AC_IGNORE, CS_AC_READ, 0 }
+	{ CS_AC_WRITE, CS_AC_READ, 0 }
 },
 {	/* X86_MOV16ao32, X86_INS_MOV: mov{w}	ax, $src */
 	0,
-	{ CS_AC_IGNORE, CS_AC_READ, 0 }
+	{ CS_AC_WRITE, CS_AC_READ, 0 }
 },
 {	/* X86_MOV16ao64, X86_INS_MOVABS: movabs{w}	ax, $src */
 	0,
@@ -5675,11 +5675,11 @@
 },
 {	/* X86_MOV32ao16, X86_INS_MOV: mov{l}	eax, $src */
 	0,
-	{ CS_AC_IGNORE, CS_AC_READ, 0 }
+	{ CS_AC_WRITE, CS_AC_READ, 0 }
 },
 {	/* X86_MOV32ao32, X86_INS_MOV: mov{l}	eax, $src */
 	0,
-	{ CS_AC_IGNORE, CS_AC_READ, 0 }
+	{ CS_AC_WRITE, CS_AC_READ, 0 }
 },
 {	/* X86_MOV32ao64, X86_INS_MOVABS: movabs{l}	eax, $src */
 	0,
@@ -5759,7 +5759,7 @@
 },
 {	/* X86_MOV64ao32, X86_INS_MOV: mov{q}	rax, $src */
 	0,
-	{ CS_AC_IGNORE, CS_AC_READ, 0 }
+	{ CS_AC_WRITE, CS_AC_READ, 0 }
 },
 {	/* X86_MOV64ao64, X86_INS_MOVABS: movabs{q}	rax, $src */
 	0,
```

Question : what's the convention for memory reference for access status ? 

`X86_MOV64mr` (move memory reference to register) return `CS_AC_READ` for source operand while `X86_MOV64mi32` (move immediate addr to register) return `CS_AC_IGNORE` : is that correct ?

**Comment by aquynh** [comment]
Can you please send a pull req to fix what you found?

**Comment by fvrmatteo** [comment]
I confirm the fixes, I forgot to make the pull request 2 weeks ago, sorry!

**Comment by lucasg** [comment]
Done.

**Comment by aquynh** [comment]
this was fixed, thanks.
