### ISSUE TITLE
X86_insn_reg_intel is incredibly slow

### ISSUE THREAD

**Issue by crowell** [aquynh/capstone#719]
in profiling radare2, i noticed a lot of time is spent in the function `X86_insn_reg_intel`, looping over a 115 item array when it could be replaced with a simple lut.

**Comment by aquynh** [comment]
yes, there are rooms for performance improvement here & there. can you fix this?

**Comment by crowell** [comment]
@aquynh check it

**Comment by crowell** [comment]
check #722

**Comment by aquynh** [comment]
close, thanks.
