### ISSUE TITLE
capstone tests on travis are failing but the badge is green

### ISSUE THREAD

**Issue by crowell** [aquynh/capstone#721]
see https://travis-ci.org/aquynh/capstone/jobs/140243891#L344 for example.

**Comment by danghvu** [comment]
Confirmed; Introduced from https://github.com/aquynh/capstone/commit/8375270e7805aedb1f7cc5c7a1f0330f35a3f8a5

cc @pranith I think you should `s/(echo FAILED; exit 1;)/{ echo FAILED; exit 1; }/` otherwise It will spawn a subshell and lost the exit code ?

**Comment by pranith** [comment]
@danghvu Yes. Looks like that needs to be changed. Do you want to submit the patch? If not I will do that.

**Comment by danghvu** [comment]
@pranith please if you can

**Comment by danghvu** [comment]
travis should fail now
