### ISSUE TITLE
using registers read and written by instructions

### ISSUE THREAD

**Issue by roj4s** [aquynh/capstone#731]
I've using this feature of capstone but i found something is not working as i expected.
Ex: arpl word ptr [eax], ax
According to capstone output for regs read and written on that instruction, that instruction don't use or modify any register, however when looking to the description of the mnemonic arpl modifies ZF flag and uses the first and second operand. Im getting the regs read and written like this: 

for reg in capstone_instruction.regs_read:
    self.uses.append(capstone_instruction.reg_name(reg))

for reg in capstone_instruction.regs_write:
     self.defs.append(capstone_instruction.reg_name(reg))

**Comment by aquynh** [comment]
please always provide the input, so we can verify the issue.

here is the output on the latest "next" branch, with input `63 00` for X86 32bit

```
0x0:	arpl	word ptr [eax], ax
	Prefix: 0x00 0x00 0x00 0x00
	Opcode: 0x63 0x00 0x00 0x00
	rex: 0x0
	addr_size: 4
	modrm: 0x0
	disp: 0x0
	sib: 0x0
	op_count: 2
		operands[0].type: MEM
			operands[0].mem.base: REG = eax
		operands[0].size: 2
		operands[0].access: READ

		operands[1].type: REG = ax
		operands[1].size: 2
		operands[1].access: READ

	Registers read: eax ax
```

do you mean we are missing the EFLAGS update?

**Comment by roj4s** [comment]
Should i provide the whole code? In my output this instruction neither use or modify any register.

**Comment by aquynh** [comment]
then your code is broken somehow. 

be sure to use the latest code from "next" branch. after install the core, make sure to also reinstall the Python binding coming with the new core.

**Comment by roj4s** [comment]
Ok, now it works, but still the output don't state that a flag is modified. Thanks, and sorry 'bout my english.

**Comment by aquynh** [comment]
pull req to add the missing flag is welcome.

you just need to add the missing info to https://github.com/aquynh/capstone/blob/next/arch/X86/X86MappingInsnOp.inc & https://github.com/aquynh/capstone/blob/next/arch/X86/X86MappingInsnOp_reduce.inc. format of these files are simple & self-contained.

**Comment by roj4s** [comment]
Seems like every thing is ok on those files since there is the description on the ARPL mnemonic stating that it modifies the ZF EFLASG. Im closing this issue since it should be working ok and the problem is most definitely on my code.
