### ISSUE TITLE
ARM64 BLR instruction has no group labels

### ISSUE THREAD

**Issue by xia0pin9** [aquynh/capstone#736]
When decompiling ARM64 ELF executables, I noticed that the _BLR_ instruction has empty group information, which I think it should belong to the _JUMP_ group, according to the [reference](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0802a/BLR.html).

**Comment by aquynh** [comment]
can you fix this and send a PR? what you need to modify is at https://github.com/aquynh/capstone/blob/next/arch/AArch64/AArch64MappingInsn.inc#L541

thanks.

**Comment by xia0pin9** [comment]
Just noticed that ARM32 assigns all branch instructions as [ARM_GRP_CALL](https://github.com/aquynh/capstone/blob/next/arch/ARM/ARMMappingInsn.inc), using ARM_GRP_JUMP maybe more appropriate.

**Comment by aquynh** [comment]
I thought that, too. Still need to have them as JUMP  insn though. So you can send another PR to change the group name back, thanks.

**Comment by xia0pin9** [comment]
Found the [following](https://github.com/aquynh/capstone/blob/next/arch/ARM/ARMMapping.c#L305) code trying to add ARM_GRP_JUMP group label, maybe we can just specifically add the corresponding labels in the mapping file and remove this part?

**Comment by aquynh** [comment]
yes, that is what i mean in my last comment.
