### ISSUE TITLE
ARM: Discrepancy in read registers between ARM and Thumb encoding of pop

### ISSUE THREAD

**Issue by rossng** [aquynh/capstone#744]
The instruction `pop {r1, pc}` can be represented in both Thumb and ARM encodings.

ARM: `E8BD8002` (see encoding A1, Architecture Reference Manual A8.8.132)
Thumb: `BD02` (see encoding T1, Architecture Reference Manual A8.8.131)

For the ARM-encoded instruction, Capstone correctly reports that the registers written are `sp`, `r1` and `pc`. It also reports that the registers read are `sp`, `r1` and `pc` - I'm not sure this is correct as I don't expect `pop` reads `r1` or `pc`.

For the Thumb-encoded instruction, Capstone incorrectly reports that the only register written is `sp` - `r1` and `pc` are missing. It also (I think correctly) reports that the only register read is `sp`.

I haven't tested the `push` instructions but I can well imagine that the same issue might occur there.

N.B. I'm using the `next` branch.

**Comment by aquynh** [comment]
fixed, please confirm.

**Comment by rossng** [comment]
Looks fixed to me. My output now:

ARM
```
0x1000:	pop		{r1, pc}	Shifter: 0 0	Groups: arm 
	Registers read: sp
	Registers modified: sp r1 pc
```

Thumb
```
0x1000:	pop		{r1, pc}	Shifter: 0 0	Groups: thumb thumb1only 
	Registers read: sp
	Registers modified: sp r1 pc
```

**Comment by aquynh** [comment]
thanks
