### ISSUE TITLE
ARM: Incorrect register access information for ldmia

### ISSUE THREAD

**Issue by rossng** [aquynh/capstone#747]
Both the ARM and Thumb encodings of `ldmia r0!, {r1-r3}` return incorrect register access information.

# ARM `E8B0000E`
See Architecture Reference Manual A8.8.58, A1

## Actual
Written: `r0` `r1` `r2` `r3`

## Expected
Written: `r0` `r1` `r2` `r3`
Read: `r0`

# Thumb `C80E`
See Architecture Reference Manual A8.8.57, T1

## Actual
Read: `r0` `r1` `r2` `r3`

## Expected:
Read: `r0`
Written: `r0` `r1` `r2` `r3`

The instruction `ldmia r0, {r1-r3}` (without writeback) is correct.

**Comment by aquynh** [comment]
fixed now, please confirm.

**Comment by rossng** [comment]
This appears to be fixed.
