### ISSUE TITLE
ARM: Incorrect register access information for stmdb

### ISSUE THREAD

**Issue by rossng** [aquynh/capstone#750]
`stmdb r0!, {r1-r3}` returns incorrect register access information.

# ARM `E920000E`
See Architecture Reference Manual A8.8.201

## Actual
Read: `r0`

## Expected
Written: `r0`
Read: `r0` `r1` `r2` `r3`

The instruction `stmdb r0, {r1-r3}` (without writeback) is correct.

**Comment by aquynh** [comment]
fixed now, please confirm.

**Comment by rossng** [comment]
This appears to be fixed.

Thanks!
