### ISSUE TITLE
PyPi Package Capstone-Engine is not registered

### ISSUE THREAD

**Issue by zachriggle** [aquynh/capstone#751]
Since Keystone uses the package name `keystone-engine`, it only makes sense for `capstone-engine` to be an alias for `capstone`.  Someone may take advantage of this for typo-squatting, but it's also nice for consistency.

```
https://pypi.python.org/pypi/capstone-engine
```

The easiest way to do this is to register a dummy package which depends on `capstone` as its only dependency.

**Comment by aquynh** [comment]
i did, thanks!
