### ISSUE TITLE
Patch for crash in X86_insn_reg_intel() in capstone-next

### ISSUE THREAD

**Issue by mokipcs** [aquynh/capstone#755]
The following code (trying to disassemble 0x37 to AAA) crashes libcapstone:

        #include <stdlib.h>
        #include <capstone/capstone.h>

        int
        main(void)
        {
                unsigned char code[] = { 0x37 };
                static csh h;
                cs_insn *insn;

                if (cs_open(CS_ARCH_X86, CS_MODE_32, &h) != CS_ERR_OK) {
                        return EXIT_FAILURE;
                }

                cs_disasm(h, code, sizeof(code), 0x1000, 0, &insn);

                return EXIT_SUCCESS;
        }

In X86_insn_reg_intel() the "mid" and "last" variables are invalid values:

        (gdb) bt
        #0  0x00000000004bbf48 in X86_insn_reg_intel (id=22, access=access@entry=0x7fffffffd618)
              at arch/X86/X86Mapping.c:2953
        #1  0x00000000004b36e4 in X86_Intel_printInst (MI=0x7fffffffd910, O=<optimized out>, Info=<optimized out>)
              at arch/X86/X86IntelInstPrinter.c:733
        #2  0x000000000040332b in cs_disasm (ud=11137040, buffer=0x0, size=2147483647, offset=0, count=4294967295, 
              insn=0x600a9e1f4) at cs.c:664
        #3  0x000000000040264b in main () at test.c:17

        (gdb) p first 
        $1 = 0
        
        (gdb) p mid
        $2 = 2147483647
        
        (gdb) p last
        $3 = 4294967295

The following patch should fix that:

        diff -ur _capstone-next-orig/arch/X86/X86Mapping.c capstone-next/arch/X86/X86Mapping.c
        --- _capstone-next-orig/arch/X86/X86Mapping.c   2016-08-25 14:24:16.067980694 +0200
        +++ capstone-next/arch/X86/X86Mapping.c 2016-08-25 14:27:16.695974281 +0200
        @@ -2936,9 +2936,9 @@
         // this is to handle instructions embedding accumulate registers into AsmStrs[]
         x86_reg X86_insn_reg_intel(unsigned int id, enum cs_ac_type *access)
         {
        -       unsigned int first = 0;
        -       unsigned int last = ARR_SIZE(insn_regs_intel) - 1;
        -       unsigned int mid = ARR_SIZE(insn_regs_intel) / 2;
        +       int first = 0;
        +       int last = ARR_SIZE(insn_regs_intel) - 1;
        +       int mid = ARR_SIZE(insn_regs_intel) / 2;
         
                if (!intel_regs_sorted) {
                        memcpy (insn_regs_intel_sorted, insn_regs_intel,

Kind regards,
Morten S. Kirkegaard

**Comment by aquynh** [comment]
this is a wrong patch. i just pushed a commit for this issue, can you confirm it works?

**Comment by mokipcs** [comment]
Sure, your way of testing if **mid** would underflow is valid as well, and fixes that bug in your library.
