### ISSUE TITLE
Very simple example run out of memory(Python)

### ISSUE THREAD

**Issue by roj4s** [aquynh/capstone#756]
In this repository https://github.com/roj4s/capstone_simple_example.git  there is a very simple code that extract the code from a PE32 executable (file included into the repository also) and pass it to capstone for disassembling. It crashes: Process finished with exit code 139, i don't know what to do, please help.
Thanks in advance.

**Comment by aquynh** [comment]
fixed in the "next" branch, please confirm.

**Comment by aquynh** [comment]
just to confirm: did you have this issue with "next", or "master" branch?

**Comment by roj4s** [comment]
Now it works with next branch, thanks.

**Comment by roj4s** [comment]
it was "master" branch, sorry bout delay

**Comment by aquynh** [comment]
do you mean your app crashes with "master" branch? i tried, but there is no crash at all.
