### ISSUE TITLE
ARM: Incorrect register access information for pop

### ISSUE THREAD

**Issue by rossng** [aquynh/capstone#760]
`pop {r1, pc}` returns incorrect register access information.

# ARM `E8BD8002`
See Architecture Reference Manual A8.8.132

## Actual
Read: `sp` `r1` `pc`
Written: `sp` `r1` `pc`

## Expected
Read: `sp`
Written: `sp` `r1` `pc`

The equivalent Thumb instruction `BD02` returns the expected result.

Error observed on tip of `next` branch.

**Comment by aquynh** [comment]
fixed, please confirm

**Comment by rossng** [comment]
Yes, looked fixed. Thanks!
