### ISSUE TITLE
ARM: Incorrect register access information for ldmia.w

### ISSUE THREAD

**Issue by rossng** [aquynh/capstone#767]
`ldm.w r1!, {r2-r10}` returns incorrect register access information.

# Thumb `E8B1 07FC`
See Architecture Reference Manual A8.8.57

## Actual
Read:
Written: `r1` `r2` `r3` `r4` `r5` `r6` `r7` `r8` `r9` (`sb`) `r10` (`sl`)

## Expected
Read: `r1`
Written: `r1` `r2` `r3` `r4` `r5` `r6` `r7` `r8` `r9` (`sb`) `r10` (`sl`)

The equivalent ARM instruction `E8B107FC` returns the expected result.

Error observed on tip of `next` branch.

**Comment by aquynh** [comment]
is this a Thumb, or Arm instruction??

**Comment by aquynh** [comment]
i asked because this code does not return any instruction for Thumb

**Comment by rossng** [comment]
It's a 32-bit Thumb2 instruction. If you go [here](http://svr-acjf3-armie.cl.cam.ac.uk/main.cgi) and change the 'Instruction set' to 'Thumb', tick the 'Machine code' radio button and then type in `e8b1` `07fc`, you should see the instruction decoded.

If you look at the [Architecture Reference Manual](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.subset.architecture.reference/index.html), section A8.8.57, you can see it listed as encoding `T2`.

To get Capstone to recognise it, I used `CS_MODE_THUMB` and

```
const uint8_t thumb_code[] = {0xb1, 0xe8, 0xfc, 0x07};
```

The mnemonic and op_str come back as:

```
ldm.w		r1!, {r2, r3, r4, r5, r6, r7, r8, sb, sl}
```

**Comment by aquynh** [comment]
fixed now, please confirm.

**Comment by rossng** [comment]
Looks fixed to me.
