### ISSUE TITLE
Empty list with regs_read and regs_write

### ISSUE THREAD

**Issue by frala19871987** [aquynh/capstone#772]
Hi,
I have installed the next branch but when i try to access to instruction.regs_read and instruction.regs_write I have always an empty list. Any idea?

Thanks

**Comment by aquynh** [comment]
there are many reasons, for example you did not to turn on Detail mode.

can you post your code?

**Comment by frala19871987** [comment]
The code is
```
from capstone import *
 
CODE = b"\x8d\x4c\x32\x08\x01\xd8"

md = Cs(CS_ARCH_X86, CS_MODE_32)
md.detail = True
 
for insn in md.disasm(CODE, 0x1000):
	print("%s\t%s" % (insn.mnemonic, insn.op_str))

	regs_read = insn.regs_read
	regs_write = insn.regs_write

	print(regs_read)
	print(regs_write)
	if len(regs_read) > 0:
		print("\n\tRegisters read:")
		for r in regs_read:
			print(insn.reg_name(r))
		print

	if len(regs_write) > 0:
		print("\n\tRegisters modified:")
		for r in regs_write:
			print(insn.reg_name(r))
		print
```

and the output

```
lea	ecx, dword ptr [edx + esi + 8]
[]
[]
add	eax, ebx
[]
[25]

	Registers modified:
eflags
```

Maybe I have done something wrong during the installation?

**Comment by aquynh** [comment]
the problem in your code is that you misunderstood the meaning of `regs_read` & `regs_write`: these fields only contain **implicit registers** read & written. example: `add eax, ebx` *implicitly* modifies EFLAGS, while `lea ecx, dword ptr [edx + esi + 8]` does not *implicitly* reads or writes any registers.

for the full list of accessed registers, see the sample at http://www.capstone-engine.org/op_access.html for what you really need.

**Comment by frala19871987** [comment]
Hi,
thanks for your answer. I tried the suggested code and now I have the following error:

```
lea	ecx, dword ptr [edx + esi + 8]
Traceback (most recent call last):
  File "a.py", line 11, in <module>
    (regs_read, regs_write) = insn.regs_access()
TypeError: 'NoneType' object is not callable
```

**Comment by aquynh** [comment]
can you post your code?

**Comment by frala19871987** [comment]
Hi,
yes of course:

```
from capstone import *
 
CODE = b"\x8d\x4c\x32\x08\x01\xd8"
 
md = Cs(CS_ARCH_X86, CS_MODE_32)
md.detail = True
 
for insn in md.disasm(CODE, 0x1000):
	print("%s\t%s" % (insn.mnemonic, insn.op_str))

	(regs_read, regs_write) = insn.regs_access()

	if len(regs_read) > 0:
		print("\n\tRegisters read:")
		for r in regs_read:
			print(" %s" %(insn.reg_name(r)))
		print()

	if len(regs_write) > 0:
		print("\n\tRegisters modified:")
		for r in regs_write:
			print(" %s" %(insn.reg_name(r)))
		print()
```

**Comment by aquynh** [comment]
i dont have any issues with your code. below is the output (with just a bit format to make it easier to read)

```
lea    	ecx, [edx + esi + 8]

       	Registers read:
       	edx
       	esi

       	Registers modified:
       	ecx
add    	eax, ebx

       	Registers read:
       	eax
       	ebx

       	Registers modified:
       	eflags
       	eax
```

perhaps you have a wrong library or Python binding installed.
if you are on Linux/Mac/Unix, do this:

```
$ git clone https://github.com/aquynh/capstone.git
$ cd capstone
$ ./make.sh
$ sudo ./make.sh
$ cd bindings/python
$ sudo make install
```

after that, you will be able to run https://github.com/aquynh/capstone/blob/next/bindings/python/test_x86.py (which extract all the accessed registers for you)

**Comment by aquynh** [comment]
dont forget the important step `git checkout next` to compile/install the "next" branch.

**Comment by frala19871987** [comment]
Thanks, obv it works. My fault...

Thanks again
