### ISSUE TITLE
x86 XSAVES instructions missing

### ISSUE THREAD

**Issue by el2ro** [aquynh/capstone#775]
apparently few x86 instructions seems to be missing:
XSAVES
XSAVES64
XSAVEC64
XRSTORS
XRSTORS64
seen while disassembling latest Linux 4.8 kernel for Ubuntu

**Comment by aquynh** [comment]
- can you provide the input? (hexa format)
- which version of Capstone are you using?

**Comment by el2ro** [comment]
I am using capstone master.

Objdump output looks like this:
0f c7 2f                xsaves (%rdi)
48 0f c7 2f             xsaves64 (%rdi)
0f c7 27                xsavec (%rdi)
48 0f c7 27             xsavec64 (%rdi)
0f c7 1f                xrstors (%rdi)
48 0f c7 1f             xrstors64 (%rdi)

**Comment by aquynh** [comment]
can you try again with the "next" branch?

**Comment by el2ro** [comment]
next branch seems to work, great!

How stable next branch is?

**Comment by aquynh** [comment]
Very stable.

**Comment by el2ro** [comment]
next branch seems to be working, that's enough for us.
