### ISSUE TITLE
[Aarch64] Cannot decode some instances of INS instruction

### ISSUE THREAD

**Issue by nathanhjay** [aquynh/capstone#786]
Decoding certain instances of the INS instruction seem to fail.

Bytes: 0x6e087ce0
Expected: ins v0.d[0], v7.d[1] 
Or, expected: mov v0.d[0], v7.d[1] 
Capstone produced an error.

**Comment by aquynh** [comment]
did you try this with the "next" branch?

**Comment by nathanhjay** [comment]
Issue does not appear on next branch.
