### ISSUE TITLE
[x86] ATT MOV size dressing does not match operand size for segment register

### ISSUE THREAD

**Issue by nathanhjay** [aquynh/capstone#789]
On capstone version 3.0.4, looking at x86, the result of decoding bytes `8E1E` is:
`movl (%rsi), %ds`

However, the segment register is 16 bits wide. The opcode should be `movw`

**Comment by aquynh** [comment]
Can you check with the next branch?

**Comment by nathanhjay** [comment]
Sure. I can look at that today and update my two previous reports as well.

**Comment by nathanhjay** [comment]
This issue remains in the next branch, though the output of Capstone changes slightly to `movl 0(%rsi), %ds`

**Comment by aquynh** [comment]
fixed, please confirm.

**Comment by nathanhjay** [comment]
This is fixed now.
