### ISSUE TITLE
X86_INS_RET bug

### ISSUE THREAD

**Issue by q1o1p** [aquynh/capstone#790]
this instruction must set RSP (esp, sp) reg as modified

**Comment by aquynh** [comment]
which version is this? can you try with the "next" branch?

**Comment by q1o1p** [comment]
right, bug in next branch.

**Comment by aquynh** [comment]
For C3 input?

**Comment by aquynh** [comment]
fixed in the "next" branch now, please confirm.

**Comment by q1o1p** [comment]
fixed
confirmed
