### ISSUE TITLE
[x86] Incorrect opcode suffix for ROL with data16 and REX.W

### ISSUE THREAD

**Issue by nathanhjay** [aquynh/capstone#804]
Capstone produces `roll $1, %ax` from `66 48f3 d1 c0`, but the `l` prefix is inconsistent with using `%ax`.

This error appears on the next branch as well as 3.0.4.

**Comment by aquynh** [comment]
fixed, please confirm.

**Comment by nathanhjay** [comment]
This is fixed now.
