### ISSUE TITLE
[x86] instructions moving 48 bit addresses should not use 'q' suffix

### ISSUE THREAD

**Issue by nathanhjay** [aquynh/capstone#805]
Here are two examples from both 3.0.4 and the next branch where Capstone uses the `q` suffix on instructions manipulating 48 bits. These instructions produce an error when assembled using gas.

Bytes: `48 ff a9 f1 80 16 76`
Output: `ljmpq *0x761680f1(%rcx)`

In the above case, the REX prefix seems to be resulting in the `q` suffix while the case below still uses the `q` suffix regardless of REX prefix.

Bytes: `48 4c f b5 80 16 76 8a fe`
Output: `lgsq -0x17589ea(%rax), %r8`

**Comment by aquynh** [comment]
fixed, pls confirm

**Comment by nathanhjay** [comment]
This is fixed now.
