### ISSUE TITLE
[x86] REX.WR prefix on SLDT instruction adds invalid 'q' suffix

### ISSUE THREAD

**Issue by nathanhjay** [aquynh/capstone#807]
Both Capstone 3.0.4 and the next branch produce `sldtq -0x17589ea(%rax)` from `4c 0f 00 80 16 76 8a fe` using AT&T syntax, but the SLDT instruction always operates on a 16-bit quantity, so the 'q' suffix is incorrect.

**Comment by aquynh** [comment]
fixed, pls confirm

**Comment by nathanhjay** [comment]
This is fixed now.
