### ISSUE TITLE
movaps        xmmword ptr [rbp - 0x210], xmm1 is not marked as access: WRITE

### ISSUE THREAD

**Issue by jrmuizel** [aquynh/capstone#809]
./cstool -d x64 "0f 29 8d f0 fd ff ff"
0  0f298df0fdffff                    movaps        xmmword ptr [rbp - 0x210], xmm1
        Prefix:0x00 0x00 0x00 0x00 
        Opcode:0x0f 0x29 0x00 0x00 
        rex: 0x0
        addr_size: 8
        modrm: 0x8d
        disp: 0xfffffdf0
        sib: 0x0
        op_count: 2
                operands[0].type: MEM
                        operands[0].mem.base: REG = rbp
                        operands[0].mem.disp: 0xfffffffffffffdf0
                operands[0].size: 16
                operands[0].access: READ
                operands[1].type: REG = xmm1
                operands[1].size: 16
                operands[1].access: READ
        Registers read: rbp xmm1
        Groups: sse1

**Comment by aquynh** [comment]
Which branch is this?

**Comment by jrmuizel** [comment]
next

**Comment by aquynh** [comment]
fixed now, and also for MOVAPD. please confirm

**Comment by jrmuizel** [comment]
Yes this appears fixed.
