### ISSUE TITLE
Capstone on ubuntu 16.04 with python binding

### ISSUE THREAD

**Issue by davidt99** [aquynh/capstone#818]
I'm using capstone with the python binding inside python's virtual environment.
Until recently, when I installed the python binding (using `pip`), capstone was installed automatically inside the venv (although the documentation specify that it wouldn't).

I created new python venv and install the binding. This time capstone wasn't installed automatically. I went to the documentation, and followed the instruction, but `libcapstone2` wasn't exist in the apt repository.
Eventually, I installed `libcapstone3` on the machine and it worked.

I think the documentation needs to be updated, and the fact that `libcapstone2` doesn't exist in the repository might relate to the capstone installation by `pip` issue (Again, I'm not sure how it worked previously)

**Comment by aquynh** [comment]
Nothing change with pip package recently, so something changed on your side. How to reproduce this issue?

**Comment by davidt99** [comment]
I investigated a bit.
It's seems that the difference is the installation type: egg vs wheel.
In the old venv, capstone was install with egg so `libcapstone.so` exists in capstone directory and the directory `capstone-3.0.4-py3.5.egg-info` in the site-package.
In the new venv, capstone was install with wheel and `libcapstone.so` doesn't exists in capstone directory and the directory `capstone-3.0.4.dist-info` in the site-package.
[23fe9f3](https://github.com/aquynh/capstone/commit/23fe9f36622573c747e2bab6119ff245437bf276) might fix this issue , I'll try to check it later.

**Comment by aquynh** [comment]
we expect to release v3.0.5 soon, but you can always install directly from Github, like:

    $ sudo pip install "https://github.com/aquynh/capstone/archive/master.zip#egg=capstone&subdirectory=bindings/python"

**Comment by davidt99** [comment]
Installing from git solves this, so I guess it'll be fixed when v3.0.5 released.
