### ISSUE TITLE
M68k signed displacement

### ISSUE THREAD

**Issue by BartmanAbyss** [aquynh/capstone#834]
It seems all M68k displacements are unsigned in capstone.
e.g. `jsr     $fe62(a6)`
where IDA shows `jsr     -$19E(a6)`
Just wanted to check in if this was intentional or not,
I'm pretty sure they need to be signed.
I can provide a patch if necessary.

**Comment by aquynh** [comment]
@emoon, do you have any comments?

**Comment by emoon** [comment]
Yeah this is correct. They should be signed. If you can provide a patch that would be great!

**Comment by BartmanAbyss** [comment]
I'm still new to github, can you work with this patch file?
I created it with TortoiseGit > Create Serial Patch > Save unified diff since HEAD.
It's based on branches/next commit b1b9f2c0

[m68k_signed_displacement.patch.txt](https://github.com/aquynh/capstone/files/677908/m68k_signed_displacement.patch.txt)

**Comment by emoon** [comment]
It would be much better if you created a pull request instead https://help.github.com/articles/creating-a-pull-request/

**Comment by BartmanAbyss** [comment]
see pull request #835

**Comment by BartmanAbyss** [comment]
see pull request #836
