### ISSUE TITLE
Incorrect version on the documentation.html page

### ISSUE THREAD

**Issue by amanjeev** [aquynh/capstone#837]
[The documentation page](http://www.capstone-engine.org/documentation.html) says `sudo apt-get install libcapstone2` where as the actual version available is `libcapstone3`. In fact,  [the download](http://www.capstone-engine.org/download.html) page says 3.0.4.

Sorry about reporting this if this is a false-alarm. I would have opened a PR with this minor change but I am not which repo has the web pages in.

Thanks.

**Comment by aquynh** [comment]
fixed, thanks!
