### ISSUE TITLE
Implement an eBPF decompiler/disassembler

### ISSUE THREAD

**Issue by mtnmts** [aquynh/capstone#838]
Hey,

Recently in a CTF Competition (33C3) there was a challenge which required analysis of a SECCOMP BPF - a mechanism that allows to filter syscalls using a BPF,  BPF disassembly is simple, as you probably know the opcode set is very small and backward branches are not available (BPF programs always terminate). 

I used this debug tool called bpf_dbg i found in the kernel tree (http://lxr.free-electrons.com/source/tools/net/bpf_dbg.c) in the competition, it was quite awkward and I had to convert the BPF to a list of struct's format the get it to work properly, here is the actual decompile function:
http://lxr.free-electrons.com/source/tools/net/bpf_dbg.c#L216
I am confident this will be useful to many people. I would be glad to contribute the code myself, can I get a green light to start working on this? (Haven't worked on this project before so didn't just want to throw up a pull request on you guys).

**Comment by aquynh** [comment]
yes, adding a new arch is very much welcome. but please keep in mind that we only accept BSD license code (as Capstone is under BSD license).

just in case you dont know, Capstone was forked from LLVM, which got BPF disassembler recently, see https://github.com/llvm-mirror/llvm/tree/master/lib/Target/BPF. perhaps you may find that porting code from there is easier?

thanks.

**Comment by mtnmts** [comment]
Very cool, I'll probably port from LLVM then, that looks good.

just making sure I got your other point, porting code from Linux is not license compatible with BSD License?.

I'll start working on a pull request soon.

**Comment by aquynh** [comment]
i am not very sure about license of BPF code in Linux kernel, you can check that yourself. be sure to clear the doubt, as lots of Linux kernel code is released under GPL license, which is incompatible with BSD.

**Comment by mtnmts** [comment]
Checked and it looks you are correct, the relevant code is indeed license incompatible.

I'm currently abroad so I'll starting rolling the ball on it next week.

Thanks for the quick reply.

**Comment by aquynh** [comment]
great, looking forwards to that! just one thing: please send pull req for the "next" branch, which picks up all the new stuff. (the "master" branch is only for stable version 3.x).

**Comment by Maijin** [comment]
@mtnmts @radare already implements bpf: disassembler, analyzer and emulator. 
You can install this using `r2pm -i bpf` after installing radare2 from git (`git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`.

**Comment by Maijin** [comment]
See here for more details/videos/code:  https://github.com/mrmacete/r2scripts/blob/master/bpf/README.md

**Comment by david942j** [comment]
I'm experienced in implementing classic BPF assembler/disassembler/emulator, [seccomp-tools](https://github.com/david942j/seccomp-tools), which is what @mtnmts needed.

@aquynh I can contribute eBPF to Capstone if you want, I think eBPF is easy enough to not refer to any existing projects, therefore there's no license issue.

**Comment by aquynh** [comment]
David, feel free to do pull req to the "next" branch.

I am working on a major update on all arches, and want to add few more new.
Do you want to do ebpf from scratch, or just port LLVM one over?

**Comment by david942j** [comment]
I haven't checked LLVM's code but currently I prefer to implement eBPF disassembler from scratch as a self challenge.

**Comment by david942j** [comment]
I have checked LLVM's BPF code and found it supports eBPF only, and I think it's a good idea to have Capstone support both classic and extended BPF.

BTW, I wanted to copy the test suite from llvm-mc to suite/ for regression testing, but llvm-mc's output is not in normal mnemonic form:
```
➔ llvm-mc -disassemble -triple=bpfel
0x30 0x00 0x00 0x00 0x00 0x00 0x00 0x00
        .text
        r0 = *(u8 *)skb[0]
```
(the expect output of Capstone will be `ldabsb 0`)
Therefore I have to modify the test into mnemonic form manually. In this case should I still put the test file (*.cs) under suites/MC/BPF, or create an independent directory for it (like suites/arm did)?

**Comment by aquynh** [comment]
Yes, i also had some good work to normalize those .cs files.

Please put them under suite/MC/

We have a regression tool named cstest now to test all .cs files now (in
master branch only, but will be merged to next branch soon)

**Comment by david942j** [comment]
@aquynh this issue can be closed

**Comment by aquynh** [comment]
thanks to @david942j, we now have BPF architecture in the next branch https://github.com/aquynh/capstone/tree/next. please report if you find any issues.
