### ISSUE TITLE
ARM: SETEND instruction group flags inconsistent

### ISSUE THREAD

**Issue by JustEnuff2BDangerous** [aquynh/capstone#842]
The `SETEND` instruction is a 16 bit Thumb instruction which was available in V6 T variants onward (see [here](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0489f/Cjacabbf.html) 

The current instruction group flags simply mark it as `{ARM_GRP_NOTMCLASS,0}`

To be consistent with other similar instructions it should marked as `{ARM_GRP_THUMB, ARM_GRP_V6, ARM_GRP_NOTMCLASS,0}`

**Comment by aquynh** [comment]
Can you send a pull req to fix this?

**Comment by JustEnuff2BDangerous** [comment]
Done.

**Comment by aquynh** [comment]
fixed, thanks.
