### ISSUE TITLE
[m68k] negative relative addressing disassembly is wrong

### ISSUE THREAD

**Issue by laanwj** [aquynh/capstone#844]
These instructions show as addressing with positive offsets, but what actually happens is that they use a negative offset (shown in comment):
```
1e3370f6       move.b 0xf6(a3, d7.w), d7   ; -0x0a
303370e2       move.w 0xe2(a3, d7.w), d0   ; -0x1e
303208fe       move.w 0xfe(a2, d0.l), d0   ; -0x02
```

This happens in radare (there reported as https://github.com/radare/radare2/issues/6554), and I saw #655 but I'm fairly sure this is a different issue as it's not a 64 versus 32 bit addressing conflict with post-analysis.

GNU objdump does have a similar issue. `m68k-linux-gnu-objdump -D -b binary -mm68k files/SYSTEM.INTERP ` gives me:
```
1e33 70f6       moveb %a3@(fffffffffffffff6,%d7:w),%d7
3033 70e2       movew %a3@(ffffffffffffffe2,%d7:w),%d0
3032 08fe       movew %a2@(fffffffffffffffe,%d0:l),%d0
```

Sign-extending the offset to 64 bit on a 32-bit architecture is weird. But at least it's clearly not a 8 bit positive offset.

**Comment by aquynh** [comment]
@emoon, do you have any comments?

**Comment by emoon** [comment]
I will look at it. Should be simple to fix.

**Comment by emoon** [comment]
I will start working on this now.

**Comment by emoon** [comment]
Should be fixed now. See the PR

**Comment by aquynh** [comment]
@laanwj, can you pull the latest code of the "next" branch, and confirm this is fixed?

**Comment by laanwj** [comment]
Thanks for the quick fix! Will test

**Comment by laanwj** [comment]
Works perfectly now:
```
303208fe       move.w -0x2(a2, d0.l), d0
```
