### ISSUE TITLE
 x64dbg run exe by openfile  breakpiont  for build capstone_dll of sourcescode

### ISSUE THREAD

**Issue by zyb225** [aquynh/capstone#851]
1. x64dbg run exe by openfile  breakpiont  for build capstone_dll of sourcescode
2.why?
3.where 👍 
const cs_x86_op & Capstone::operator[](int index) const
{
	int aa = OpCount();
    if(!Success() || index < 0 || index >= OpCount())
        DebugBreak();
    return x86().operands[index];
}
4.   index >= OpCount()
5.用自己编译的capstone_dll 会产生错误，当x64dbg调试通过openfile时老产生断点错误，用snapshot_2016-12-29_02-38.zip的capstone_dll，在调试时不会产生错误。为什么自己编译生成的capstone_dll 不行

**Comment by aquynh** [comment]
1. why dont you open this issue on x64dbg repo, but here?
2. can you write in English?

**Comment by zyb225** [comment]
capture picture?

**Comment by zyb225** [comment]
if(!Success() || index < 0 || index >= OpCount())
        DebugBreak();

**Comment by zyb225** [comment]
index >= OpCount() ===true

**Comment by aquynh** [comment]
seriously, if you cant post properly, i will have to close this issue.

**Comment by zyb225** [comment]
thank you! I can

**Comment by zyb225** [comment]
![breakpoint](https://cloud.githubusercontent.com/assets/25640924/22744518/877fb4f6-ee58-11e6-8e82-5f996f22bdb3.png)

**Comment by aquynh** [comment]
this is not related to Capstone, but x64dbg. please open your issue at https://github.com/x64dbg/x64dbg, thanks.

**Comment by zyb225** [comment]
capstone_dll by myself compile have a question of 80000003, but use your capstone_dll no question
