### ISSUE TITLE
x86: bug in decoding mov dword ptr fs:[0], eax

### ISSUE THREAD

**Issue by deroko** [aquynh/capstone#852]
When detailed information is requested, during decoding this instruction shows 3 operands instead of 2.

inst bytes: 64a300000000
operand[0].type == REG (eax)
operand[1].type == MEM (seg = FS/disp = 0)
operand[2].type == REG (eax)

Atm it happens only with eax as source reg, while others (ecx <-> edi) are decoded ok with 2 operands.

**Comment by aquynh** [comment]
fixed now, please confirm.

**Comment by deroko** [comment]
Yup, fixed now. Tested and working as it should. Tnx 👍
