### ISSUE TITLE
F7 / F8 keys not working in Ubuntu 16

### ISSUE THREAD

**Issue by ragnargraybeard87** [aquynh/capstone#862]
When Using the Visual Graph mode (VV) it won't stepi or stepo when pressing those keys. Tried on a fresh install of ubuntu as well.

Furthermore, it DOES seem to work in the other Visual modes, just not the graph mode (my favourite one)

**Comment by ibabushkin** [comment]
I guess this issue is something experiencing with radare2? In such a case,
please report the problem there.

**Comment by aquynh** [comment]
this is not related to Capstone.
