### ISSUE TITLE
AArch64 : stur gives unsigned offset.

### ISSUE THREAD

**Issue by roblabla** [aquynh/capstone#874]
Capstone gives an unsigned offset to stur instructions. for instance : `bf831fb8` turns into `stur	wzr, [x29, #0xfffffffffffffff8]`.

According to https://developer.arm.com/docs/dui0801/latest/a64-data-transfer-instructions/stur, the offset is signed.

Python code to reproduce : 

```
from capstone import *

CODE = b"\xbf\x83\x1f\xb8"

md = Cs(CS_ARCH_ARM64, 0)
for i in md.disasm(CODE, 0x1000):
     print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))
```

Expected : `0x1000:	stur	wzr, [x29, #-0x8]`
Got : `0x1000:	stur	wzr, [x29, #0xfffffffffffffff8]`

**Comment by aquynh** [comment]
Can you confirm with latest Github code, and also with the "next" branch?

**Comment by roblabla** [comment]
It's also the case on master. I can't get next to compile : 

```
[roblabla@ns352371 capstone]$ ./make.sh
make[1]: Entering directory '/home/roblabla/Dropbox/dev/src/c/capstone/cstool'
  LINK    cstool
cstool_arm64.o: In function `print_insn_detail_arm64':
cstool_arm64.c:(.text+0x487): undefined reference to `cs_regs_access'
cstool_arm.o: In function `print_insn_detail_arm':
cstool_arm.c:(.text+0x573): undefined reference to `cs_regs_access'
cstool_x86.o: In function `print_insn_detail_x86':
cstool_x86.c:(.text+0xae6): undefined reference to `cs_regs_access'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:21: cstool] Error 1
make[1]: Leaving directory '/home/roblabla/Dropbox/dev/src/c/capstone/cstool'
make: *** [Makefile:359: all] Error 2
```

**Comment by roblabla** [comment]
Nevermind, I had to rm the existing .so/.a/.o.

It seems to be fixed in the `next` branch.

**Comment by trufae** [comment]
r2 does that right already:

```
$ rasm2  -a arm -b 64 -d bf831fb8
stur wzr, [x29, -8]
```

so plz fix your system, r2 uses capstone-next and that issue should not be a problem if you are using r2 from git instead of the one from your distro

**Comment by roblabla** [comment]
Yup, I fixed it by getting capstone-git from the AUR on archlinux instead of the one in the packages.

**Comment by radare** [comment]
If u uninstall capstone from your distro r2 will build its own capstone which is grabbed from next. Stable one is so old and buggy
