### ISSUE TITLE
Getting registers read written

### ISSUE THREAD

**Issue by roj4s** [aquynh/capstone#875]
I have some assembly code in plain text and I'd like to get registers read and written from each instruction but since it's not coded in Capstone instructions I can't use the capstone_ins.regs_read/regs_write functionalities. However I know that a mapping exists here: https://raw.githubusercontent.com/aquynh/capstone/next/arch/X86/X86MappingInsnOp.inc and here https://github.com/aquynh/capstone/blob/next/arch/X86/X86MappingInsnOp_reduce.inc
How could I interpret these files to do what I want? Is there any way I can turn my plain text instructions into capstone instructions? Thanks in advance.

**Comment by aquynh** [comment]
one solution is that you can compile your assembly code with Keystone (www.keystone-engine.org) to get the binary. then you decode the binary with Capstone.

**Comment by roj4s** [comment]
Thanks
