### ISSUE TITLE
Could not disassemble avx instruction: vpermq  ymm0, ymm0, <imm8>

### ISSUE THREAD

**Issue by mebilly** [aquynh/capstone#880]
With python binding, the sequence: b"\xC4\xE3\xFD\x00\xC0\x00" could not be disassembled.

For verification, please copy and paste the following:

```
import capstone as cs

csd = cs.Cs(cs.CS_ARCH_X86, cs.CS_MODE_32)
csd.detail = True

insn = csd.disasm(b"\xC4\xE3\xFD\x00\xC0\x00", 0x00401000, 1)

for _insn in insn:
    print("Found!")

quit()
```

Have not tested on non-python bindings though, anyone who's insterested could try it out and let me know :)

**Comment by aquynh** [comment]
you can try with the "next" branch:

```
$ cstool x32 "\xC4\xE3\xFD\x00\xC0\x00"
0  c4e3fd00c000                      vpermq	ymm0, ymm0, 0
```

**Comment by mebilly** [comment]
Could you please elaborate on what you mean by "next"?
Am I understanding correctly if that means to do something like this:
`insn = csd.disasm(b"\xC4\xE3\xFD\x00\xC0\x00", 0x00401000, 1)
print(next(insn))`
but if that's the case, it still does not work. Any workarounds?

**Comment by aquynh** [comment]
I mean you should get the "next" branch of this Github repo, compile &
install that. "next" is more advanced than the default "master" branch.

**Comment by mebilly** [comment]
Wow, it's good to know for me as a repo noob. Thanks!
