### ISSUE TITLE
x86 AT&T syntax bug with zero offset segment register

### ISSUE THREAD

**Issue by dwks** [aquynh/capstone#884]
Instructions with a zero offset and an explicit segment register (prefix byte) are not turned into a string correctly. Here is an instruction as displayed by GDB,
```
64 48 03 04 25 00 00 00 00	add    %fs:0x0,%rax
```
and the same instruction as displayed by capstone (x86_64, AT&T syntax):
```
64 48 03 04 25 00 00 00 00	addq         %fs:, %rax                
```
This is not valid AT&T syntax.
```
$ as foo.s
foo.s: Assembler messages:
foo.s:1: Error: bad memory operand `'
```
Note that capstone does correctly generate Intel syntax in this case.
```
64 48 03 04 25 00 00 00 00	add          rax, qword ptr fs:[0]     
```

**Comment by aquynh** [comment]
fixed now, please confirm

**Comment by dwks** [comment]
Confirmed, fixed.
```
64 48 03 04 25 00 00 00 00    addq  %fs:0, %rax
```
I noticed that decimal is used to print displacements less than ten, then it switches to hexadecimal, so it does makes sense to print "0" in this case and not "0x0".
