### ISSUE TITLE
how to know operand size? 

### ISSUE THREAD

**Issue by ParkHanbum** [aquynh/capstone#886]
when I disassemble x86 instruction by using python binding capstone, all operands size is fixed by 4 even real size is 1byte. so, I can't calculate offset of operand. 

for example, 
00405CEF  |. C745 08 305F4000     MOV DWORD PTR SS:[EBP+8],PEview.00405F30

operands0.type:MEM	size=4
	operands0.mem.base: REG=ebp
	operands0.mem.disp: 0x-30
operands1.type:IMM=0x401068	size=4

how can I calcuate right offset?

**Comment by dwks** [comment]
I have the same issue: https://github.com/aquynh/capstone/issues/873

I'm currently working on a dedicated mod/rm byte decoder whose only task is to report the size of displacements and immediates. I'll post here once it's finished.

**Comment by ParkHanbum** [comment]
@dwks  sounds good. I'm same purpose to you. working on window PE format x86_32bit for support binary rewriting technique. I wish you well.

**Comment by aquynh** [comment]
you can try with the "next' branch, which fixes this issue in some instructions.

**Comment by smart-rabbit** [comment]
using capstone-next python bindings:
Erroneous operand size determination for all 2-byte Jcc instruction
****
Platform: X86 32 (Intel syntax)
Code:` 0x74 0x05`
Disasm:
0x1000:	`je	0x1007`
        Prefix: 0x00 0x00 0x00 0x00 
	Opcode: 0x74 0x00 0x00 0x00 
	rex: 0x0
	addr_size: 4
	modrm: 0x0
	disp: 0x0
	sib: 0x0
	imm_count: 1
		imms[1]: 0x1007
	op_count: 1
		operands[0].type: IMM = 0x1007
		`operands[0].size: 4` 
	Registers read: eflags

**Comment by smart-rabbit** [comment]
using capstone-next python bindings:
Erroneous operand size determination for all 2-byte Jcc instructions

Platform: X86 32 (Intel syntax)
Code:0x74 0x05
Disasm:
0x1000: je 0x1007
Prefix: 0x00 0x00 0x00 0x00
Opcode: 0x74 0x00 0x00 0x00
rex: 0x0
addr_size: 4
modrm: 0x0
disp: 0x0
sib: 0x0
imm_count: 1
imms[1]: 0x1007
op_count: 1
operands[0].type: IMM = 0x1007
operands[0].size: 4
Registers read: eflags

**Comment by aquynh** [comment]
this is because we consider the target address a 4bytes immediate. see the below output, decoding at offset 0x1000000 (ie we do a short jump from there)

```
$ cstool -d x32 7405 1000000
1000000  7405                              je	0x1000007
	Prefix:0x00 0x00 0x00 0x00 
	Opcode:0x74 0x00 0x00 0x00 
	rex: 0x0
	addr_size: 4
	modrm: 0x0
	disp: 0x0
	sib: 0x0
	imm_count: 1
		imms[1]: 0x1000007
	op_count: 1
		operands[0].type: IMM = 0x1000007
		operands[0].size: 4
	Registers read: eflags
	EFLAGS: TEST_ZF
	Groups: branch_relative jump 

```

**Comment by ParkHanbum** [comment]
@aquynh I know it. disasm3 also does the same parsing. However, disasm3 supports opcode size. This is because we can calculate the offset of the operand precisely.
