### ISSUE TITLE
Lack of VMX support for x86(_64)

### ISSUE THREAD

**Issue by moonheart08** [aquynh/capstone#887]
VMX, or the Virtual Machine eXtension, adds a few new instructions for interacting with hardware VMs. When i went to look at capstone, i was hoping for support, but saw the lack of it instead.

**Comment by aquynh** [comment]
Will sync with LLVM. For the record, can you put all the missing instructions here?

**Comment by aquynh** [comment]
i dont remember VMX added new instructions recently. are you talking about another extension?
