### ISSUE TITLE
Incorrect disassembly for 'mov eax, 0x61' in RelWithDebInfo

### ISSUE THREAD

**Issue by Querijn** [aquynh/capstone#888]
I'm iterating over instructions using `cs_disasm_iter` in Windows and VS2017, on a 32-bit build. I'm inspecting a 32-bit PE, on a 64-bit machine. Using `cs_open(CS_ARCH_X86, CS_MODE_32, &t_Capstone) != CS_ERR_OK)` for opening.

I have the current set of instructions, disassembled correctly in Debug

> 0xd13660: 'push' ebx ; oper size = 0x1
> 0xd13661: 'push' ebp ; oper size = 0x1
> 0xd13662: 'push' esi ; oper size = 0x1
> 0xd13663: 'push' edi ; oper size = 0x1
> 0xd13664: 'mov' edi, ecx ; oper size = 0x2
> 0xd13666: 'mov' eax, 0x61 ; oper size = 0x5
> 0xd1366b: 'lea' esi, dword ptr [edi + 0xa] ; oper size = 0x3

But in RelWithDebInfo, this becomes

> 0xd13660: 'push' ebx ; oper size = 0x1
> 0xd13661: 'push' ebp ; oper size = 0x1
> 0xd13662: 'push' esi ; oper size = 0x1
> 0xd13663: 'push' edi ; oper size = 0x1
> 0xd13664: 'mov' edi, ecx ; oper size = 0x2
> **0xd13666: '' edi, ecx ; oper size = 0x2**
> 0xd13668: 'add' byte ptr [eax], al ; oper size = 0x2
> 0xd1366a: 'add' byte ptr [ebp + 0x7c70a77], cl ; oper size = 0x6

Byteset at 0xd13660: `53 55 56 57 8B F9 B8 61 00 00 00 8D 77 0A C7 07 F0 43 3D 01 66 89 47 04 A1 90 ED A7 02 89 47 06`

**Comment by aquynh** [comment]
what is RelWithDebInfo?

is this from the master branch, or v3.0.5-rc2?

**Comment by Querijn** [comment]
Release with debug info, one of the solution configurations made by CMake for Visual Studio.

This is the master branch. Should I test with RC2?

**Comment by Querijn** [comment]
I see that the master branch might be ahead of 3.0.5-rc2, so I'll add that I've used a pretty old version previously. This problem was also present in version 3.0.4 ( July 15th, 2015, unknown if I got it from the master branch or from the website)

**Comment by aquynh** [comment]
I am pretty sure this was fixed in the "next" branch, you should try and
see.

**Comment by Querijn** [comment]
Heya,

After some changes, I come up with the same bug, now with 'next':

> 0xd13660: 'push' ebx ; oper size = 0x1
> 0xd13661: 'push' ebp ; oper size = 0x1
> 0xd13662: 'push' esi ; oper size = 0x1
> 0xd13663: 'push' edi ; oper size = 0x1
> 0xd13664: 'mov' edi, ecx ; oper size = 0x2
> 0xd13666: '' edi, ecx ; oper size = 0x2

I'm going to walk through the library and see I can spot the problem.

**Comment by aquynh** [comment]
please provide the all the input in hexcode format.

**Comment by Querijn** [comment]
Don't know which format you want specifically, so here's all of the ones I can think of. Starting at 0xd13660:
`53 55 56 57 8B F9 B8 61 00 00 00 8D 77 0A C7 07 F0 43 3D 01 66 89 47 04 A1 90 ED A7 02 89 47 06`
`0x53, 0x55, 0x56, 0x57, 0x8B, 0xF9, 0xB8, 0x61, 0x00, 0x00, 0x00, 0x8D, 0x77, 0x0A, 0xC7, 0x07, 0xF0, 0x43, 0x3D, 0x01, 0x66, 0x89, 0x47, 0x04, 0xA1, 0x90, 0xED, 0xA7, 0x02, 0x89, 0x47, 0x06`
`535556578BF9B8610000008D770AC707F0433D0166894704A190EDA702894706`

And the one instruction specifically, at 0xd13666:
`B8 61 00 00 00`
`0xB8, 0x61, 0x00, 0x00, 0x00`
`B861000000`

I've looked at it myself, going through the instructions. So far I found that the difference happens in `readOperands(insn)` in ```
int decodeInstruction(struct InternalInstruction *insn,
		byteReader_t reader,
		const void *readerArg,
		uint64_t startLoc,
		DisassemblerMode mode)
```

**Comment by aquynh** [comment]
can you just post the input having problem?

you can try with the built in tool "cstool", like below (i am using the "next" branch. you also have cstool.exe on Windows)

```
$ cstool -d x32 "B861000000"
$ 0  b861000000                        mov	eax, 0x61
	Prefix:0x00 0x00 0x00 0x00
	Opcode:0xb8 0x00 0x00 0x00
	rex: 0x0
	addr_size: 4
	modrm: 0x0
	disp: 0x0
	sib: 0x0
	imm_count: 1
		imms[1]: 0x61
	op_count: 2
		operands[0].type: REG = eax
		operands[0].size: 4
		operands[0].access: WRITE
		operands[1].type: IMM = 0x61
		operands[1].size: 4
	Registers modified: eax
```

i dont see any problem with the example above.

**Comment by Querijn** [comment]
After building cstool, and rebuilding again (using shared library this time), it seems to work both in cstool and in my application. Seems like Visual Studio didn't rebuild the first time (or I misclicked), I cannot repro it anymore.

It's working with the library from the next branch, in both static and shared now.

Thanks for your time. Sorry to have bothered you for longer than was necessary.
