### ISSUE TITLE
Opcode type and type_num

### ISSUE THREAD

**Issue by roj4s** [aquynh/capstone#897]
Hi you all ... I'd like to know what the opcode type and type_num fields in the outputs of capstone's disassembling stand  for or are based on. If that's a sort of categorization, grouping or classification where can I get a good explanation of its functioning.  Thanks in advance.

**Comment by aquynh** [comment]
see https://github.com/aquynh/capstone/blob/master/include/capstone.h for more information about what you want to know.

**Comment by roj4s** [comment]
Nice thanks
