### ISSUE TITLE
[x86] Missing REP prefix on string instruction

### ISSUE THREAD

**Issue by nathanhjay** [aquynh/capstone#907]
This instruction should should have a REP prefix, because it's encoded in the bytes and this is a string instruction, so rep may actually be used.

Bytes: f2 ac
Capstone Output: lodsb (%rsi), %al
Expected: repne lodsb (%rsi)

**Comment by aquynh** [comment]
how did you have this? on "master" branch, i have the correct result.

```
$ cstool x64att f2ac
0  f2ac                              repne lodsb	(%rsi), %al
```

**Comment by nathanhjay** [comment]
It seems like my master is out of date. I just confirmed that I definitely get the output without the rep. I'll close this issue, since it doesn't seem to be a problem anymore.

**Comment by aquynh** [comment]
Please confirm other issues, too.
