### ISSUE TITLE
win32 releases should include import library in addition to static library

### ISSUE THREAD

**Issue by lzybkr** [aquynh/capstone#910]
The current [3.0 release zip files](https://github.com/aquynh/capstone/releases/tag/3.0.5-rc2) have a dll and **static** lib.

If one wants to link to the dll, e.g. from rust, one needs the import library, not a static library.

**Comment by aquynh** [comment]
will update that tonight, thanks.

**Comment by aquynh** [comment]
updated. please report if you still have issues, thanks.
