### ISSUE TITLE
[x86] LOCK NOP not decoded (F0 0F 1F 00)

### ISSUE THREAD

**Issue by davidbrazdil** [aquynh/capstone#915]
The byte sequence "F0 0F 1F 00" disassembles to "lock nopl (%rax)" with GNU Binutils 2.26.1 and Online Disassembler [1] but is undecoded by Capstone "next" branch. It is emitted by LLVM for alignment.

[1] https://www.onlinedisassembler.com/odaweb/mkfPEHoP/0

**Comment by aquynh** [comment]
Any other disassembler can handle this code, besides Gas?

**Comment by davidbrazdil** [comment]
NASM: `F00F1F00          lock nop dword [rax]`
Zyan: `lock nop [rax]`

It's just the LOCK prefix. Capstone disassembles the NOP `0F 1F 00` just fine.

**Comment by aquynh** [comment]
fixed now, please confirm.

**Comment by davidbrazdil** [comment]
Yes, now decodes. Thank you

**Comment by gdbinit** [comment]
Zyan doesn't accept this anymore (there's a Jul 3 commit about illegal lock prefixes).

$ ./ZydisInfo -64 F0 0F 1F 00
Could not decode instruction: ILLEGAL_LOCK

**Comment by aquynh** [comment]
the only way to confirm this is to run it on real cpu, to see it really
works.
-- 
Thanks,
Quynh

http://www.keystone-engine.org
http://www.capstone-engine.org
http://www.unicorn-engine.org

**Comment by gdbinit** [comment]
Yes, it's an illegal instruction per Intel manuals and verified on a real cpu.
