### ISSUE TITLE
"Customize instruction mnemonic at run-time" docs typo

### ISSUE THREAD

**Issue by disconnect3d** [aquynh/capstone#919]
There is a typo on http://www.capstone-engine.org/mnemonic.html :

> This has been changed with a new option CSOPTMNEMONIC (available in the Github branch next now, and will be ready when version 4.0 is out). 

I believe the `CSOPTMNEMONIC` should be `CS_OPT_MNEMONIC`.

Similar formatting problem happens later on:

> Find the full samples on how to use CSOPTMNEMONIC in the source of test_x86.c or test_x86.py.

There are also similar issues on http://www.capstone-engine.org/lang_python.html

**Comment by aquynh** [comment]
fixed, thanks!

**Comment by disconnect3d** [comment]
On http://www.capstone-engine.org/lang_python.html : 
> Line 17 ~ 18: If this operand is register (reflected by type ARM64OPREG),
> Line 19 ~ 20: If this operand is immediate (reflected by type ARM64OPIMM),
> Line 21 ~ 22: If this operand is of type C-IMM (coprocessor register type, reflected by ARM64OPCIMM), 
> Line 23 ~ 24: If this operand is real number (reflected by type ARM64OPFP),
> Line 25 ~ 35: If this operand is memory reference (reflected by type ARM64OPMEM),

**Comment by aquynh** [comment]
fixed, thanks!
