### ISSUE TITLE
cmake complains about target "test"

### ISSUE THREAD

**Issue by nbriggs** [aquynh/capstone#922]
(As of git commit 7b4e870480be645f2e1cbb736ea1823545a76924, May 8th 2017)

> CMake Warning (dev) at CMakeLists.txt:348 (add_executable):
>   Policy CMP0037 is not set: Target names should not be reserved and should
>   match a validity pattern.  Run "cmake --help-policy CMP0037" for policy
>   details.  Use the cmake_policy command to set the policy and suppress this
>   warning.
> 
>   The target name "test" is reserved or not valid for certain CMake features,
>   such as generator expressions, and may result in undefined behavior.

Perhaps the test program should be changed to "test_all" instead of "test"?

**Comment by aquynh** [comment]
We can change it to test_basic. Can you send a pull req?

**Comment by nbriggs** [comment]
I've not created pull requests for github projects before -- give me a bit to read up on what's to be done.

It's trivial for me to change the CMakeLists.txt and rename the file, but I don't know that I can generate the right change to the xcode project and Visual Studio definitions.

-- Nick
