### ISSUE TITLE
Was M68K dropped in 3.0.5-rc2?

### ISSUE THREAD

**Issue by gwasser** [aquynh/capstone#924]
Just a quick question. I'm looking to update some bindings and don't see `m68k` in the tarball for 3.0.5-rc2. This (https://github.com/aquynh/capstone/commit/8853489ea99b5f47be6b9c8fe7aea4740ab6a987) commit suggests it was removed on purpose, but I'm surprised to not see it mentioned in the release notes. Also, `m68k` still seems to be on the `next` branch.

Was it removed for 3.0.5 but planned to be re-integrated in 4.0? Just looking for an official response. Thanks!

**Comment by aquynh** [comment]
M68k has never been in master branch, but only in next branch.

**Comment by gwasser** [comment]
Ah that would explain it, I was totally backwards. Sorry I'm new to it. Thanks!
