### ISSUE TITLE
MIPS32 Parser broken for R5900 (ps2) on sd

### ISSUE THREAD

**Issue by GovanifY** [aquynh/capstone#937]
```
govanify@Witcher ~ $ cat test.py 
from capstone import *

CODE= b"\x40\xff\xbd\x27\x70\x00\xb2\xff\x80\x00\xb4\xff\x90\x00\xb6\xff\x2d\x90\x80\x00\x98\x00\xb7\xff\x2d\xa0\x00\x00\xa0\x00\xbe\xff\x2d\xb0\xc0\x00\x60\x00\xb0\xff\x2d\xb8\xe0\x00\x68\x00\xb1\xff\x2d\xf0\xa0\x00"
md = Cs(CS_ARCH_MIPS, CS_MODE_32)
for i in md.disasm(CODE, 0x1000):
    print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))
govanify@Witcher ~ $ python test.py 
0x1000: addiu   $sp, $sp, -0xc0
```
it stops at invalid opcode, full result(using r2) is:

```
[0x001da558]> pd 20
/ (fcn) fcn.001da558 4
|   fcn.001da558 ();
|              ; CALL XREF from 0x0016caf4 (fcn.0016cab8 + 60)
|              ; CALL XREF from 0x0016cd94 (fcn.0016cd48 + 76)
|              ; CALL XREF from 0x0016ca24 (fcn.0016c8f8 + 300)
\           0x001da558      40ffbd27       addiu sp, sp, -0xc0
            0x001da55c      7000b2ff       invalid
            0x001da560      8000b4ff       invalid
            0x001da564      9000b6ff       invalid
            0x001da568      .dword 0x0080902d ; sym.0x0080902d
            0x001da56c      9800b7ff       invalid
            0x001da570      2da00000       invalid
            0x001da574      a000beff       invalid
            0x001da578      .dword 0x00c0b02d ; sym.0x00c0b02d
            0x001da57c      6000b0ff       invalid
            0x001da580      .dword 0x00e0b82d ; sym.0x00e0b82d
            0x001da584      6800b1ff       invalid
            0x001da588      .dword 0x00a0f02d ; sym.0x00a0f02d
            0x001da58c      7800b3ff       invalid
            0x001da590      8800b5ff       invalid
            0x001da594      a800bfff       invalid
            0x001da598      b000b4e7       swc1 f20, 0xb0(sp)
```
Result should be:

```

var_C0= -0xC0
var_BC= -0xBC
var_B0= -0xB0
var_70= -0x70
var_6C= -0x6C
var_60= -0x60
var_58= -0x58
var_50= -0x50
var_48= -0x48
var_40= -0x40
var_38= -0x38
var_30= -0x30
var_28= -0x28
var_20= -0x20
var_18= -0x18
var_10= -0x10

addiu   $sp, -0xC0
sd      $s2, 0xC0+var_50($sp)
sd      $s4, 0xC0+var_40($sp)
sd      $s6, 0xC0+var_30($sp)
move    $s2, $a0
sd      $s7, 0xC0+var_28($sp)
move    $s4, $zero
sd      $fp, 0xC0+var_20($sp)
move    $s6, $a2
sd      $s0, 0xC0+var_60($sp)
move    $s7, $a3
sd      $s1, 0xC0+var_58($sp)
move    $fp, $a1
sd      $s3, 0xC0+var_48($sp)
sd      $s5, 0xC0+var_38($sp)
sd      $ra, 0xC0+var_18($sp)
swc1    $f20, 0xC0+var_10($sp)
```

**Comment by hlide** [comment]
using CS_MODE_32 instead of CS_MODE_64 is probably the issue you have.

> The R5900 core was developed by Toshiba, exclusively for use in the Playstation 2 Emotion Engine (EE).  It is similar to the R5000, but adds several SIMD (multimedia) instructions.
_  It implements almost all MIPS3 instructions, though it supports MIPS4's movn/movz.
_ It has a lot of SIMD instructions which allow you to do 128 bits register manipulations (vector rotations, etc)
_ It doesn't support load linked and store conditional instruction (ll/lld/sc/scd, MIPS2).

> MIPS III was introduced 1992 in the R4000. It adds **64-bit registers and integer instructions** and a square root FP instruction.
MIPS IV adds conditional moves and an inverse square root FPU instruction. The R8000 was the first to implement the MIPS IV instruction set.
MIPS V was specified in 1994 by SGI but never actually implemented by any processor. MIPS64 is a superset of MIPS V
MIPS32 is the 32-bit subset of MIPS64.
MIPS64 is a superset of the MIPS V.

So it appears you need MIPS64 and so CS_MODE_64 to get **64-bit registers and integer instructions**.

**Comment by GovanifY** [comment]
This is wrong, it is indeed using a 32bits ISA
Here is a comparison picture on radare issues:

https://cloud.githubusercontent.com/assets/6375438/26532170/1f2d155e-43fa-11e7-9dd2-d08f64f901f1.png

Debugger is clearly 32bits(and is from pcsx2 so I doubt they fudged up a whole set of opcodes)

**Comment by hlide** [comment]
SD is a 64-bit instruction and it is clearly marked that R4K then R5K add 64-bit registers and integer instructions and your debugger screenshot shows it as well.

**Comment by GovanifY** [comment]
Well it seems capstone indeed fixed the issue upstream when trying mips64, although ida and other debuggers still load it as mips32 which is weird.
Sorry for the response and thanks

**Comment by hlide** [comment]
I didn't spot those sdc3 at first. But there is a chance that SDC3 is SD in 64-bit 

> MIPS III removed the Coprocessor 3 (CP3) support instructions, and reused its opcodes for the new doubleword instructions.

**Comment by GovanifY** [comment]
Yup but capstone seems to render those correctly in x64, although not radare and so this seems to be a radare issue
