### ISSUE TITLE
MIPS64 SD instruction swallowed by COP3_32

### ISSUE THREAD

**Issue by mrmacete** [aquynh/capstone#938]
In `next` branch, passing mode=(CS_MODE_MIPS64 | CS_MODE_LITTLE_ENDIAN), the bytes `7000b2ff` are disassembled like this:

```
7000b2ff       sdc3 18, 0x70(sp)
```

which is wrong and should be instead:

```
7000b2ff       sd $s2, 0x70($sp)
```

The reason is this code: https://github.com/aquynh/capstone/blob/next/arch/Mips/MipsDisassembler.c#L454-L461 triggers before the MIPS64 decoder, thus swallowing the instruction.

In `master` branch or current releases this doesn't happen because that code block is `#if 0`'ed out.

**Comment by aquynh** [comment]
could you send a pull req to fix this?

**Comment by mrmacete** [comment]
sure! just i don't know what's the right solution yet - i have to do some research and find suitable test cases to understand how those COP3_32 instructions interact with other modes, so the fix may be one of:

- just remove it like it is in master
- exclude it in 64 bit mode
- move the check at the end of the group, as a fallback for everything
- move the check before the 32-bit case

**Comment by mrmacete** [comment]
Those COP3 instructions (coprocessor 3) has been removed in MIPS III, but earlier versions of MIPS32/64 were based on MIPS II, then has been removed also from there and their usage has been "discouraged" on earlier versions too.

Probably the safest thing to do is disable that code or adding a specific mode to support COP3, in case someone has to deal with older architectures, at the cost of loosing support for the new doubleword instructions.
