### ISSUE TITLE
Capstone python binding Fails to disassemble large bytestreams for CS_ARCH_X86, CS_MODE_64 

### ISSUE THREAD

**Issue by n4x0r** [aquynh/capstone#947]
the follow test script works for CS_MODE_32 but no for CS_MODE_64 on CS_ARCH_X86

	fd = open(sys.argv[1], 'rb')
	data = fd.read()
	md = Cs(CS_ARCH_X86, CS_MODE_64)

	for i in md.disasm(data, 0x40000):
        	print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))

The output I get from previous script having passed as argument the name of an ELF64 binary of 8548 bytes in size is the following:

n4x0r@ubuntu:~/Desktop/Intezer/parser_lin$ python capstonetest.py a.out 
0x40000:	jg	0x40047
0x40002:	add	r8b, byte ptr [rcx]
0x40006:	add	dword ptr [rax], eax
0x40008:	add	byte ptr [rax], al
0x4000a:	add	byte ptr [rax], al
0x4000c:	add	byte ptr [rax], al
0x4000e:	add	byte ptr [rax], al
0x40010:	add	al, byte ptr [rax]
0x40012:	add	byte ptr ds:[rcx], al
0x40015:	add	byte ptr [rax], al
0x40017:	add	byte ptr [rax + 4], al
0x4001a:	add	byte ptr [rax], al
0x4001d:	add	byte ptr [rax], al
0x4001f:	add	byte ptr [rax], al
0x40022:	add	byte ptr [rax], al
0x40024:	add	byte ptr [rax], al
0x40026:	add	byte ptr [rax], al
0x40028:	js	0x4003b
0x4002a:	add	byte ptr [rax], al
0x4002c:	add	byte ptr [rax], al
0x4002e:	add	byte ptr [rax], al
0x40030:	add	byte ptr [rax], al
0x40032:	add	byte ptr [rax], al
0x40034:	add	byte ptr [rax], dil
0x40037:	add	byte ptr [rcx], cl
0x40039:	add	byte ptr [rax], al

for ELF32 binaries I get the entire file disassembled which is what I am expecting. I have also tried different things such as passing a bytestream of different sizes incrementally and always gives me the same disassembly of 0x39 bytes. Any idea what could be the reason of this?

Cheers

**Comment by aquynh** [comment]
Capstone stops when it finds invalid code. have you heard about the concept of "recursive disassembler", when you have to follow branch targets?

**Comment by n4x0r** [comment]
I haven't heard of it. could you please specify or point me to the right direction? Thank you

**Comment by aquynh** [comment]
you can google for it. what you want is a "recursive disassembler", which can use Capstone inside (Capstone is just doing basic "linear disassembler")

**Comment by n4x0r** [comment]
Is there any way to tell whether capstone has stop due to an invalid code?
