### ISSUE TITLE
Disassembly has wrong number of operands

### ISSUE THREAD

**Issue by japesinator** [aquynh/capstone#950]
I'm trying to disassemble some x86 assembly containing a `mov` from memory to eax, and capstone seems to think there are 3 operands, despite that not being reflected in `op_str` (which I believe is correct). Notably, this behavior only occurs with 3.0.5-rc2 and not 3.0.4.

```
>>> from capstone import *
>>> md = Cs(CS_ARCH_X86, CS_MODE_32)
>>> md.detail = True
>>> insn = md.disasm(b"\x66\xa3\x94\x90\x04\x08", 0x1000).next()
>>> print insn.op_str
word ptr [0x8049094], ax
>>> print len(insn.operands)
3
```

**Comment by aquynh** [comment]
fixed now, please confirm.
