### ISSUE TITLE
Critical coding bug in decodeInstruction function of arch/X86/X86DisassemblerDecoder.c file

### ISSUE THREAD

**Issue by mazhenke** [aquynh/capstone#954]
Hello,

I am using capstone to disassemble X86_CODE32 instruction stream, and I find that, the following instruction couldn't be disassembled success:

**0xC4, 0xE2, 0x89, 0xDB, 0x4C, 0x8E, 0xBD**

The decoding result is:

****************
Platform: X86 32 (Intel syntax)
Code:0xc4 0xe2 0x89 0xdb 0x4c 0x8e 0xbd 
Disasm:
0x0:	.byte	0xc4   ID: 0x0
0x1:	loop	0xffffff8c   ID: 0x14c
	Prefix:0x00 0x00 0x00 0x00 
	Opcode:0xe2 0x00 0x00 0x00 
	rex: 0x0
	addr_size: 4
	modrm: 0x0
	disp: 0x0
	sib: 0x0
	imm_count: 1
		imms[1]: 0xffffff8c
	op_count: 1
		operands[0].type: IMM = 0xffffff8c
		operands[0].size: 4

0x3:	fisttp	dword ptr [esi + ecx*4 - 0x43]   ID: 0xeb
	Prefix:0x00 0x00 0x00 0x00 
	Opcode:0xdb 0x00 0x00 0x00 
	rex: 0x0
	addr_size: 4
	modrm: 0x4c
	disp: 0xffffffbd
	sib: 0x8e
		sib_base: esi
		sib_index: ecx
		sib_scale: 4
	op_count: 1
		operands[0].type: MEM
			operands[0].mem.base: REG = esi
			operands[0].mem.index: REG = ecx
			operands[0].mem.scale: 4
			operands[0].mem.disp: 0xffffffffffffffbd
		operands[0].size: 4

Obviously, the decoding is wrong. This is a 3 bytes VEX prefixed VAESIMC instruction, and the correct decoding is:

vaesimc	xmm1, xmmword ptr [esi + ecx*4 - 0x43]

Please have a check, thanks!

**Comment by aquynh** [comment]
for now Capstone can handle this similar code:

```
$ cstool x32 "0xC4, 0xE2, 0x79, 0xDB, 0x4C, 0x8E, 0xBD"
0  c4e279db4c8ebd                    vaesimc	xmm1, xmmword ptr [esi + ecx*4 - 0x43]
```

the difference is the 3rd byte: 0x79 vs 0x89.

where did you find the details of this instruction? i dont see that in the manual, yet.

**Comment by mazhenke** [comment]
Hi aquynh,

The instruction stream 0xC4, 0xE2, 0x89, 0xDB, 0x4C, 0x8E, 0xBD is from windows system:
C:\Windows\SysWOW64\d2d1.dll.
And we use the windows tool **dumpbin** can disassemble them successfully:
![2017-07-04 09 42 13](https://user-images.githubusercontent.com/16829846/27811862-245fe7d0-609d-11e7-83de-0e6ef7cd7897.png)

So I tried the capstone, find the previous issue.

But Now we have conclusion: this is NOT a capstone bug. Because I found even the CPU couldn't execute the instruction: 0xC4, 0xE2, 0x89, 0xDB, 0x4C, 0x8E, 0xBD.

So please ignore this issue, and have a nice day!
Sorry for that and thanks a lot!

**Comment by aquynh** [comment]
interesting, this means Windows disassembler is buggy.

thanks for updating me.
