### ISSUE TITLE
X86 Java and Python bindings with AT&T syntax appear to incorrectly add suffixes to some mnemonics

### ISSUE THREAD

**Issue by Dmium** [aquynh/capstone#957]
This may be me incorrectly setting up capstone/using the wrong settings I'm new to disassembly etc.

I've found the mnemonics to be correct except for a few such as ret and call. When these get disassembled by capstone they return retl and calll instead of ret and call.
Sample Machine code: E828000000 should have a call mnemonic but returns calll

Sample from java X86 test (32 bit AT*T disassembling E828000000):
Disasm:
0x1000:	calll	0x102d
	Prefix: 0x00 0x00 0x00 0x00 
	Opcode: 0xe8 0x00 0x00 0x00 
	rex: 0x0
	addr_size: 4
	modrm: 0x0
	disp: 0x0
	sib: 0x0
	imm_count: 1
		imms[1]: 0x102d
	op_count: 1
		operands[0].type: IMM = 0x102d
		operands[0].size: 4

I'm running this on arch and I've tested on the master branch as well as the next branch with java bindings and tested on the master branch with python..

**Comment by aquynh** [comment]
that "l" indicates long RET & long CALL

**Comment by Dmium** [comment]
Am I just misunderstanding AT&T syntax? As far as I can tell ret doesn't usually have a suffix and I tested disassembling with other tools and they returned ret instead of retl.

**Comment by Dmium** [comment]
@aquynh Took a look around to try and find relevant documentation. https://cs.brown.edu/courses/cs033/docs/guides/x64_cheatsheet.pdf
Found this section 3.5, page 5. "Procedure call instructions do not have any suffixes." and gives examples including call and ret. Struggling to find a more reliable source that indicates either way

**Comment by Dmium** [comment]
hmm it seems I'm mistaken or some guides are conflicting
