### ISSUE TITLE
The number of operands is incorrect on x86

### ISSUE THREAD

**Issue by chq007** [aquynh/capstone#959]
Hi, 

When I use capstone to process an x86 instruction, I find the number of operands returned by capstone is incorrect. Here is the python code:

    from capstone import *
    code = b'\xa0\x28\x57\x88\x7c'  # mov al, byte ptr[0x7c885728]
    md = Cs(CS_ARCH_X86, CS_MODE_32)
    md.detail = True
    for inst in md.disasm(code, 0x1000):
        print ('0x%x: \t%s\t%s'%(inst.address, inst.mnemontic, inst.op_str))
        print ('Number of operands %d'%len(inst.operands))
        for op in inst.operands:
            print op

The following is the output:
    0x1000: 	None	al, byte ptr [0x7c885728]
    Number of operands 1
    <capstone.x86.X86Op object at 0x7f8cf89590e0>

I checked the instruction code using IDA and unicorn-engine and I'm pretty sure it is "mov al, byte ptr[0x7c885728] ". Obviously, capstone takes " al, byte ptr[0x7c885728]" as one operand. 

Can anybody help me to fix it?

**Comment by aquynh** [comment]
Which code are you using: 3.0.4, or "master" or "next" branch?

**Comment by aquynh** [comment]
fixed in the "master" branch now, please confirm.

**Comment by chq007** [comment]
The problem is fixed now. Thank you
