### ISSUE TITLE
undocumented instructions

### ISSUE THREAD

**Issue by Kalfan** [aquynh/capstone#962]
Hello people please look at this hypothetical scenario.

I am a malware analyst and I have a malware I am analyzing.

Besides the common tools of the trade I also have to use y own tool tool that logs single-step instructions and which uses the Capstone disasm dll for instructions translations into asm mnemonics.

Now let us suppose the malware is sing some of the open-secret Intel undocumented instructions some of which Dr Dobbs' website plenty wrote articles about.

In such scenario our disasm dll fails because it does not include the undocumented instructions in its dictionary.

I propose they should be included.

**Comment by Kalfan** [comment]
Apologies, my keyboard has stuck keys.

**Comment by aquynh** [comment]
i dont get it: what do you want to propose?

**Comment by Kalfan** [comment]
I propose that the undocumented instructions should be included in this project.
The following file I am attaching was obtained from Dr Dobb's website many years ago.
[opcodes.zip](https://github.com/aquynh/capstone/files/1148490/opcodes.zip)

**Comment by aquynh** [comment]
Cool, can you paste all the code here instead?

You can put them in the format "hexcode = assembly". For ex, "90 = nop".

**Comment by Kalfan** [comment]
I guess the contents of the opcode.zip have sufficient information. and as I have said this is a hypothetical scenario about the need for the Capstone disasm dll to include undocumented instructions.

**Comment by aquynh** [comment]
can you paste just one code that Capstone does not handle properly here? i looked thru, and havent found anything special yet.

**Comment by aquynh** [comment]
what i mean is that all these undocumented cases are already handled in Capstone long ago.

**Comment by Kalfan** [comment]
Ii WISH TO THANK YOU AGAIN FOR YOUR OUTSTANDING PROJECT SIR.                    .--------------------------------------------
On Tue, 7/18/17, Nguyen Anh Quynh <notifications@github.com> wrote:

 Subject: Re: [aquynh/capstone] undocumented instructions (#962)
 To: "aquynh/capstone" <capstone@noreply.github.com>
 Cc: "Kalfan" <khalfan1959aziz@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Tuesday, July 18, 2017, 7:56 AM
 
 what i mean is that all these
 undocumented cases are already handled in Capstone long
 ago.
 
Ii WISH TO THANK YOU AGAIN FOR YOUR OUTSTANDING PROJECT SIR
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by aquynh** [comment]
You are welcome! Give this repo a star if you haven't done so yet :-)

**Comment by Kalfan** [comment]
Of course a will, an entire galaxy if need be but how to do that please ? 
I am new at Git.
--------------------------------------------
On Sun, 7/23/17, Nguyen Anh Quynh <notifications@github.com> wrote:

 Subject: Re: [aquynh/capstone] undocumented instructions (#962)
 To: "aquynh/capstone" <capstone@noreply.github.com>
 Cc: "Kalfan" <khalfan1959aziz@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Sunday, July 23, 2017, 6:18 AM
 
 You are welcome! Give this repo a
 star if you haven't done so yet :-)
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by aquynh** [comment]
the star button is at the top right corner of this page. just click there once, and you will see the number increased by 1. (currently it is 2074)
