### ISSUE TITLE
arm64: Instructions added in ARMv8.1/2

### ISSUE THREAD

**Issue by semihalf-oleksy-michalina** [aquynh/capstone#967]
I've noticed that some instructions added in ARMv8.1/2 are not supported yet.
On this branch in my fork I made changes in the files that could be edited manually: https://github.com/semihalf-oleksy-michalina/capstone/tree/arm64v8.2_instr yet I've seen several posts indicate that you edit some table gen files by hand and there is no public info on how to perform such changes.

I can do it myself in case I missed appropriate info - otherwise above I've linked to the branch that has them listed so that it would be easier for you to add new instructions.

(all the changes were based on arm manuals)

**Comment by trufae** [comment]
Can you do a PR?

**Comment by semihalf-oleksy-michalina** [comment]
Sure. It's here: https://github.com/aquynh/capstone/pull/1011

**Comment by XVilka** [comment]
Are there any updates here?

**Comment by aquynh** [comment]
supported now in the next branch, thanks.
