### ISSUE TITLE
PowerPC: Bad operands in crset, crclr, crmove, crnot

### ISSUE THREAD

**Issue by PeterMatula** [aquynh/capstone#971]
Simplified mnemonics for condition register logical instructions (`crset, crclr, crmove, crnot`) take CR bit positions as operands. I think that these should be disassembled into `PPC_OP_CRX` operands, or simple `PPC_OP_IMM` operands, but `PPC_OP_REG` operands of general puspose registers `PPC_REG_R0 -- PPC_REG_R32` are currently used instead in the `next` branch.

E.g.:
- `crset 0` = `crset lt`, has operand `PPC_REG_R0`, should probably have operand `ppc_op_crx = {4, PPC_REG_CR0, PPC_BC_LT}`, or `PPC_OP_IMM` with value 0. 
- `crset 1` = `crset gt`, has operand `PPC_REG_R1`, should probably have operand `ppc_op_crx = {4, PPC_REG_CR0, PPC_BC_GT}`, or `PPC_OP_IMM` with value 1.
- `crset 2` = `crset eq`, has operand `PPC_REG_R2`, should probably have operand `ppc_op_crx = {4, PPC_REG_CR0, PPC_BC_EQ}`, or `PPC_OP_IMM` with value 2.
- `crset 3` = `crset so`, has operand `PPC_REG_R3`, should probably have operand `ppc_op_crx = {4, PPC_REG_CR0, PPC_BC_SO}`, or `PPC_OP_IMM` with value 3.
- `crset 4` = `crset 4*cr1+lt`, has operand `PPC_REG_R4`, should probably have operand `ppc_op_crx = {4, PPC_REG_CR1, PPC_BC_LT}`, or `PPC_OP_IMM` with value 4. 
- ... an so on to 31.

I would personally prefer using `PPC_OP_CRX` operand type, not `PPC_OP_IMM`, so that it is not needed to convert immediate values to corresponding pairs by Capstone users.

Two example outputs of my Capstone dumper utility program (dumps everything Capstone knows about an instruction):
```
$ capstone-dumper -a ppc -m 32 -e big -b 0x1000 -t "crset lt"

Keystone input : crset lt
Keystone output: 4c 00 02 42 

Capstone version: 1024 (major: 4, minor: 0)

#0
        General info:
                id     :  937 (crset)
                addr   :  1000
                size   :  4
                bytes  :  4c 00 02 42 
                mnem   :  crset
                op str :  0
        Detail info:
                R regs :  0
                W regs :  0
                groups :  0
        Architecture-dependent info:
                branch code :  PPC_BC_INVALID
                branch hint :  PPC_BH_INVALID
                update cr0  :  false
                op count    :  1

                        type   :  PPC_OP_REG
                        reg    :  44 (r0)
```

```
$ capstone-dumper -a ppc -m 32 -e big -b 0x1000 -t "crset 4*cr4+lt"

Keystone input : crset 4*cr4+lt
Keystone output: 4e 10 82 42 

Capstone version: 1024 (major: 4, minor: 0)

#0
        General info:
                id     :  937 (crset)
                addr   :  1000
                size   :  4
                bytes  :  4e 10 82 42 
                mnem   :  crset
                op str :  16
        Detail info:
                R regs :  0
                W regs :  0
                groups :  0
        Architecture-dependent info:
                branch code :  PPC_BC_INVALID
                branch hint :  PPC_BH_INVALID
                update cr0  :  false
                op count    :  1

                        type   :  PPC_OP_REG
                        reg    :  60 (r16)
```

**Comment by aquynh** [comment]
planning to have a major update to all architectures to catch up with latest LLVM changes. but please be patient, i need to find time for that.

meanwhile, if you want any changes, please send pull req.

**Comment by aquynh** [comment]
please confirm this is fixed now.

```
$ cstool -d ppc64be "4c000242 4e108242"

 0  4c 00 02 42  crset	cr0lt
	ID: 233 (crset)
	op_count: 1
		operands[0].type: REG = cr0lt

 4  4e 10 82 42  crset	cr4lt
	ID: 233 (crset)
	op_count: 1
		operands[0].type: REG = cr4lt
```

**Comment by PeterMatula** [comment]
Yes, it looks ok now - the newly added registers `PPC_REG_CR{0,1,2,3,4,5,6,7}{EQ,GT,LT,UN}` are used correctly.
