### ISSUE TITLE
something wrong occurred disassembling IA-64 program

### ISSUE THREAD

**Issue by Levimocun** [aquynh/capstone#973]
when i disassemble the IA-64 program, there are a lot of DEC instruction different from the result in IDA.
and the address after call instruction is not correct.
eg:
0x140001000:	**dec		eax**
0x140001001:	sub		esp, 0x38
0x140001004:	mov		dword ptr [esp + 0x20], 0
0x14000100c:	**dec		eax**
0x14000100d:	lea		edx, dword ptr [esp + 0x20]
0x140001011:	**dec		eax**
0x140001012:	lea		ecx, dword ptr [0x11f8]
0x140001018:	call		**0x40001230**
the result disasseble by IDA:
0000000140001000 48 83 EC 38                             sub     rsp, 38h
0000000140001004 C7 44 24 20 00 00 00 00                 mov     [rsp+38h+a], 0
000000014000100C 48 8D 54 24 20                          lea     rdx, [rsp+38h+a]
0000000140001011 48 8D 0D F8 11 00 00                    lea     rcx, _Format    ; "%d"
0000000140001018 E8 13 02 00 00                          call    **0x140001230**

**Comment by aquynh** [comment]
because you setup the engine in 32bit mode, not 64bit mode?
