### ISSUE TITLE
Segmentation fault due to csh->regsize_map is NULL

### ISSUE THREAD

**Issue by rrrfff** [aquynh/capstone#988]
![qq 20170805153550](https://user-images.githubusercontent.com/8240935/28993910-c1319dd2-79f3-11e7-9b98-534b30fb871a.png)

**Comment by aquynh** [comment]
In "master" or "next" branch? Can you provide input triggering this?

**Comment by rrrfff** [comment]
I use master branch, and after investigation I found the code which causes regsize_map to NULL.
![5555](https://user-images.githubusercontent.com/8240935/28994040-07818b0a-79f7-11e7-8fb9-dd096c94bc08.png)
