### ISSUE TITLE
Add ccapstone.a to cython

### ISSUE THREAD

**Issue by liuxuan30** [aquynh/capstone#989]
Hi there,

Great library! We want to run capstone on AWS lambda with Cython, but it seems that capstone only produce `ccapstone.so` file, but we want `ccapstone.a` file for capstone. Unfortunately AWS Lambda does not support `.so`, so we have to use `ccapstone.a`

It can gain huge performance improve if we can use `ccapstone.a` on lambda (lambda only allow up to 5 min job)

Can you add this support? Thank in advance!

**Comment by aquynh** [comment]
sure. please send a pull req for this, i will merge it.

**Comment by liuxuan30** [comment]
I mean can you help add it, because we don't know how to make a '.a' file 😂

**Comment by aquynh** [comment]
It is time to learn new things, and contribute back to community then :-)

**Comment by liuxuan30** [comment]
We found that
Turns out capstone + Cython just work on AWS lambda. The key is to compile and install them under the same runtime environment as AWS lambda, which is at the writing Amazon Linux AMI 2016.3.3 (amzn-ami-hvm-2016.03.3.x86_64-gp2)
 http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

**Comment by aquynh** [comment]
glad that it works for you ;-)

**Comment by liuxuan30** [comment]
closing :) Thanks for this wonderful project
