### ISSUE TITLE
OSS-Fuzz and libFuzzer

### ISSUE THREAD

**Issue by revskills** [aquynh/capstone#990]
Please consider creating a pull request to [OSS-Fuzz ](https://github.com/google/oss-fuzz)

[Accepting new projects](https://github.com/google/oss-fuzz#accepting-new-projects)

> To be accepted to OSS-Fuzz, an open-source project must have a significant user base and/or be critical to the global IT infrastructure

Minimum example:

```c++
#include <stdlib.h>
#include <unistd.h>
#include "include/capstone.h"


extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {

  csh handle;
  cs_insn *insn;
  size_t count;

  cs_open(CS_ARCH_X86, CS_MODE_64, &handle);
  count = cs_disasm(handle, data, size, 0x1000, 0, &insn);
  cs_free(insn, count);
  cs_close(&handle);

  return 0;
}


```

**Comment by aquynh** [comment]
Great idea! Do you mind sending a pull req to put this script under suite/,
so we can maintain it?

I will submit it for fuzzing afterwards. Thanks

**Comment by revskills** [comment]
it's faster for you to add the license header (Also 's/cs/ks/g' to your Keystone project), expand make.sh c&p debug $TARGET to asan-coverage (=memory or =undefined too) or similar to 'CFLAGS='-O0 -g -fsanitize=address -fsanitize-coverage=edge,indirect-calls,trace-cmp,trace-div,trace-gep,trace-pc-guard' LDFLAGS='-fsanitize=address'. And build using:

clang++ -g -fsanitize=address -fsanitize-coverage=edge,indirect-calls,trace-cmp,trace-div,trace-gep,trace-pc-guard -Iinclude/ -lcapstone   cs_fuzzer.cc -o cs_fuzzer ../libfuzzer/libFuzzer.a

Keep in mind that OSS-Fuzz has some PR requirements so better just added as docummented.
