### ISSUE TITLE
Running setup.py bdist_wheel for Capstone ... error in Termux.

### ISSUE THREAD

**Issue by Deathlive** [aquynh/capstone#991]
i want to install a capstone,

http://prntscr.com/g6wv66 → ERROR
http://prntscr.com/g6wvim → ERROR

WHAT IS THE PROBLEM?

**Comment by aquynh** [comment]
Is this on the latest Github code of "master" branch?

**Comment by Deathlive** [comment]
@aquynh 
Capstone to be in the pip repository?
I installed it through  `pip2 install Capstone`.
Is this the same thing?
