### ISSUE TITLE
Is there access(RWX) property in the operands of x86 architecture?

### ISSUE THREAD

**Issue by mudongliang** [aquynh/capstone#996]
Dear developers,
I have a question about operand access(RWX) in x86 architecture. I don't find this property in the x86 related data structure.
For example,
```
add eax, ebx
```
Result:
eax : Read, Write; ebx : Read

```
mov eax, [esp]
```
Result:
eax: Write; [esp]:Read

**Comment by aquynh** [comment]
1. You should use the "next" branch for this. Remember to "make clean", then rebuild & reinstall again.

2. Run "cstool -d x32 01d8", and find out what you need.

**Comment by mudongliang** [comment]
I have seen this property in cs_x86_op(
https://github.com/aquynh/capstone/blob/next/include/capstone/x86.h#L289)

Is this branch - next stable enough?

**Comment by aquynh** [comment]
Yes, i is even more stable than the "master" branch.

**Comment by mudongliang** [comment]
Thanks. I have compiled that branch and linked it in my project. It looks good.
